### ISSUE TITLE
Define contributor role vocabulary

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1001]
In the [metadata model update](https://github.com/CatalogueOfLife/backend/issues/989) we want to have a more flexible take on various contributors to a dataset, not just the authors & editors. For this we need a role vocabulary or decide to even use just free text.

Contributor roles will have to be mapped from and to [DataCite DOI metadata](http://schema.datacite.org/meta/kernel-4.3/doc/DataCite-MetadataKernel_v4.3.pdf) and [EML RoleType](https://eml.ecoinformatics.org/schema/eml-party_xsd.html#RoleType), so a controlled vocabulary would be very useful. EML allows free text and only recommends a few roles in comments, but DataCite and [GBIF](https://github.com/gbif/gbif-api/blob/dev/src/main/java/org/gbif/api/vocabulary/ContactType.java#L32) are strict and require controlled values.

See https://docs.google.com/spreadsheets/d/1-zO5zHqul6VBwcCcYh8egMI2N6q6LUB7uCU247o727c/edit#gid=491248187 for a quick and dirty mapping of these roles.

**Comment by mdoering** [comment]
First draft proposal for roles:

 - **contact**: Person with knowledge of how to access, troubleshoot, or otherwise file issues related to the dataset
 - **author**: The main researchers involved in producing the data, or the authors of the publication, in priority order. This property will be used to formulate the citation, so consider the prominence of the role. 
 - **editor**: A person who oversees the details related to the publication format of the dataset. This property will be used to formulate the citation, so consider the prominence of the role. 
 - **publisher**: The name of the entity that holds, archives, publishes prints, distributes, releases, issues, or produces the dataset. This property will be used to formulate the citation, so consider the prominence of the role. 
 - manager: Person (or organisation with a staff of data managers, such as a data centre) responsible for maintaining the finished dataset.
 - curator: Person tasked with reviewing, enhancing, cleaning, or standardizing data
 - contentProvider ? : Person/institution responsible for finding, gathering/collecting data under the guidelines of the author(s) or Principal Investigator (PI)
 - metadataAuthor ?
 - programmer
 - distributor: Institution tasked with responsibility to generate/disseminate copies of the dataset
 - rightsHolder: Person or institution owning or managing property rights, including intellectual property rights over the dataset
 - other

The bold roles are metadata fields on their own and can be supplied directly without a role under contributor.

**Comment by mdoering** [comment]
@dhobern @gdower @timrobertson100 anything that springs to your mind if we get started with aboves list? The 3 roles I feel most uneasy about are:
 - _manager_: data manager vs project manager. Do we need both, want them to be lumped or only care about data managers?
 - _curator_: maybe its worth splitting the role into _reviewer_ and _processor_? curator is also used by GBIF EML for specimen collection curators while DataCite calls this role a data-curator. 
 - _contentProvider_:  DataCite has DataCollector, but "collector" sounds rather passive. On the other hand what is the difference between a contentProvider and the authors? The real taxonomy work will be done by the authors. Is it therefore good to have a _collector_ role that is not having as much creative input as an author has? Thinking about it I start to prefer collector over contentProvider.

**Comment by dhobern** [comment]
Thanks @mdoering. I'm already struggling with thinking about how to apply so many role terms consistently in different cases. Some thoughts.

- Wouldn't the contact always be someone who occupies one of the other roles? If so, should it be a separate property that can be attached to any person record in the metadata (indicating that they can be contacted about the dataset)?
- Do we expect just to have a single block of contributors in the metadata, each with an associate role (or roles)? Or will there (also) be contributor records elsewhere in the metadata in contexts where some of the semantics are constrained by the context? For example, would we expect to have a section on the authorship of the metadata itself, with an embedded contributor record that is for the metadata author? If we are separately relying on or expecting some semantics to be based on structure, we may not need the role vocabulary to be so rich. Rights holder is a role that I would expect only to see in the context of the IPR and licensing section.
- I know we have the name author because of our history, but it still feels odd to me to use this word to refer to list compilation and curation tasks. 
- I can't understand why "curator" would be separate from "author".
- "Manager" seems cryptic - I would not split it further, but I'd think about what we mean. There is likely to be someone who leads the project (not necessarily a PM) and who can be seen as the lead author and primary contact. I would expect us to indicate this person through a combination of the author role and the contact role/flag. Then there may be a person who heads up the technical infrastructure that is hosting the dataset - if this is what we are highlighting, I'd call them something like "host" rather than manager. I'm not sure we need to think of "project managers" in the sense we would use the term for an IT project. See my next bullet.
- To be honest, I'm not sure I'd split the informatics roles so much. I would think that the boundary between data managers and programmers would be blurry in many relevant organisations. Other than because it seems so passive, I would be inclined just to have an "IT support" role and include them all that way.
- If "contributor" was not our umbrella term for all roles, I would tend to use "contributor" for "contentProvider". This captures the kind of relationship I think is intended.

**Comment by mdoering** [comment]
> * Wouldn't the contact always be someone who occupies one of the other roles? If so, should it be a separate property that can be attached to any person record in the metadata (indicating that they can be contacted about the dataset)?

Roles are not exclusive, the same person can be the contact, author and more.

> * Do we expect just to have a single block of contributors in the metadata, each with an associate role (or roles)? Or will there (also) be contributor records elsewhere in the metadata in contexts where some of the semantics are constrained by the context? For example, would we expect to have a section on the authorship of the metadata itself, with an embedded contributor record that is for the metadata author? If we are separately relying on or expecting some semantics to be based on structure, we may not need the role vocabulary to be so rich. Rights holder is a role that I would expect only to see in the context of the IPR and licensing section.

Yes, thats the current expectation. We have an _agent_ type merging person and organisation information that is used for  contact, author, editor, publisher & contributor lists. The first ones implicitly define their roles, for contributors we were thinking to provide finer roles. But reading your last comment about contentProvider being best described as contributor I tend to agree and wonder if we should rather just have contributor without any further roles. And instead add a few more properties for e.g. reviewer, manager, programmer (IT support is not a nice YAML key) or distributor.

Dublin Core has the following properties with range http://purl.org/dc/terms/AgentClass:
 - audience: A class of agents for whom the resource is intended or useful. Recommended practice is to use this property with non-literal values from a vocabulary of audience types.
 - contributor: An entity responsible for making contributions to the resource. The guidelines for using names of persons or organizations as creators apply to contributors.
 - creator: An entity responsible for making the resource. Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided.
 - mediator:  An entity that mediates access to the resource. In an educational context, a mediator might be a parent, teacher, teaching assistant, or care-giver.
 - publisher: An entity responsible for making the resource available.
 - rightsHolder : A person or organization owning or managing rights over the resource. Recommended practice is to refer to the rights holder with a URI. If this is not possible or feasible, a literal value that identifies the rights holder may be provided.


> * I know we have the name author because of our history, but it still feels odd to me to use this word to refer to list compilation and curation tasks.

DataCite & DublinCore both use `creator` - happy to adopt that term instead which indeed fits better to datasets.

> * I can't understand why "curator" would be separate from "author".

Apart from the reviewer role I agree. 

> * "Manager" seems cryptic - I would not split it further, but I'd think about what we mean. There is likely to be someone who leads the project (not necessarily a PM) and who can be seen as the lead author and primary contact. I would expect us to indicate this person through a combination of the author role and the contact role/flag. Then there may be a person who heads up the technical infrastructure that is hosting the dataset - if this is what we are highlighting, I'd call them something like "host" rather than manager. I'm not sure we need to think of "project managers" in the sense we would use the term for an IT project. See my next bullet.

I guess the use case was the [WoRMS Data Management Team](http://www.marinespecies.org/about.php#governance). That is probably best handled by the "IT support" below

> * To be honest, I'm not sure I'd split the informatics roles so much. I would think that the boundary between data managers and programmers would be blurry in many relevant organisations. Other than because it seems so passive, I would be inclined just to have an "IT support" role and include them all that way.

Agree. Can we think of a name for IT support that can easily be used as a key and starts with a lower case? 
_informatics_, _support_ (would also include helpdesks), _systemSupport_ or use _programmer_ and be very inclusive in its definition?


> * If "contributor" was not our umbrella term for all roles, I would tend to use "contributor" for "contentProvider". This captures the kind of relationship I think is intended.

Yes I like that. See above.


That would leave the following "roles", each existing as their own property and not nested under contributor:

 - contact
 - creator
 - editor
 - publisher
 - reviewer
 - contributor
 - programmer (aka IT support, name to be discussed)
 - distributor

Distributor might not be needed even. But might make sense for Plazi?
in GBIF there are 2 related organisations for a datasets, the hosting and the publishing organization. The later is the publisher, the first maps best to distributor. We could also consider to use "host", but with EML and DataCite both having a distributor role I would prefer distributor.

**Comment by dhobern** [comment]
Thanks @mdoering - that seems better. I forgot to mention that I don't understand the difference between creator and editor in real-world GSD cases, but I'm comfortable for it to be there.

**Comment by mdoering** [comment]
I wonder if we should not just collapse reviewer and programmer into contributor. Whats the benefit of having those roles separated out explicitly? We could habe a note field for contributors that allows people to specify their exact contribution if that is wanted. [FishBase](https://www.fishbase.de/Collaborators/CollaboratorsTopicList.php) does this for example Ali, Atheer _Provided references on fishes of Iraq_:
https://www.fishbase.de/collaborators/CollaboratorSummary.php?id=2574

**Comment by dhobern** [comment]
This makes sense to me @mdoering
-- 

*Donald Hobern* / ***@***.*** / +61 420511471
Araba Bioscan Project <https://stangeia.hobern.net/araba-bioscan-project/>
/ Pterophoroidea <https://pterophoroidea.hobern.net/> / Alucitoidea
<https://alucitoidea.hobern.net/> / BOLD Australia
<https://bold-au.hobern.net/>
ORCID: 0000-0001-6492-4016 <https://orcid.org/0000-0001-6492-4016> / Blog
<https://stangeia.hobern.net/> / iNaturalist
<https://inaturalist.ala.org.au/people/dhobern> / Flickr
<https://www.flickr.com/photos/dhobern/>/ GitHub
<https://github.com/dhobern> / Twitter <https://twitter.com/dhobern>

**Comment by dshorthouse** [comment]
"Role" tends to be an overloaded term, often conflating job title or responsibilities with the action executed in the context of producing a work. Likewise, there's a frequent requirement to capture multiple roles. This is why RDA/TDWG Interest Group has downplayed this term in favour of a vocabulary to express the actions as the edge between two nodes: edited, curated, reviewed, programmed, etc.

**Comment by mdoering** [comment]
Closing this as we converged on having no contributor role at all but instead a flexible note field and fixed "roles" as part of metadata fields based on Dublin Core or EML:

 - contact
 - creator
 - editor
 - publisher
 - distributor
 - contributor

Related discussion will continue on the [metadata model update](https://github.com/CatalogueOfLife/backend/issues/989).
