### ISSUE TITLE
Name matching gives integer IDs 

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1006]
Example: `Cortinarius caerulescens (Schaeff.) Fr.` gives id `2802316`:
http://api.catalogueoflife.org/name/matching?q=Cortinarius%20caerulescens%20(Schaeff.)%20Fr.&verbose=true

ID `2802316` gives no usages:
http://api.catalogueoflife.org/nameusage/search?NAME_ID=2802316

But it seems usages are here with id `8d6b424d-db82-4677-b92d-f23c0c7828fe`:
http://api.catalogueoflife.org/nameusage/search?NAME_ID=8d6b424d-db82-4677-b92d-f23c0c7828fe

**Comment by mdoering** [comment]
Thats correct. It returns the names index ids, not usage or name keys.
It currently needs several steps to find the matching usage.

Note also that /name/matching is deprecated over `/nidx/match` where there are also other methods to deal with the names index, e.g. list names in the same group or resolve the integer keys

**Comment by mdoering** [comment]
You can find usages of a certain dataset with the same names index id like that:

https://api.catalogueoflife.org/dataset/3LR/nameusage?nidx=2802316

But it might be several that match
