### ISSUE TITLE
CsL Date deserialization error

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1020]
Request failed with status code 400
Cannot deserialize instance of `[I` out of VALUE_NUMBER_INT token at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 113] (through reference chain: life.catalogue.api.model.CslData["issued"]->life.catalogue.api.model.CslDate["date-parts"]->java.lang.Object[][0])

HTTP method: POST

https://api.dev.catalogueoflife.org/dataset/2091/reference

Body:
{"type":"dataset","title":"TEST ref2","author":[{"family":"Jeppesen","given":"Thomas"}],"issued":{"date-parts":[2021,6,10]},"accessed":""}

**Comment by mdoering** [comment]
Arg, yes. I used ISO date strings as the serialisation.
Will have to make that proper CSL style dates I reckon

**Comment by thomasstjerne** [comment]
Another one:

Request failed with status code 400
Cannot deserialize instance of `java.util.ArrayList<life.catalogue.api.model.Citation>` out of START_OBJECT token at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 703] (through reference chain: life.catalogue.api.model.Dataset["source"])

HTTP method: PUT

https://api.dev.catalogueoflife.org/dataset/2091

Body:
`````

{
  "title": "TSJ Test DWCA",
  "description": "A list of taxa.",
  "contact": {
    "orcid": "0000-0003-1691-239X",
    "given": "Thomas",
    "family": "Jeppesen",
    "email": "tsjeppesen@gbif.org",
    "name": "Jeppesen T."
  },
  "creator": [
    {
      "orcid": "0000-0003-1691-239X",
      "given": "Thomas",
      "family": "Jeppesen",
      "email": "tsjeppesen@gbif.org",
      "name": "Jeppesen T."
    },
    {
      "given": "Markus",
      "family": "Döring",
      "department": "IT dept",
      "city": "Berlin",
      "country": "DE",
      "email": "markus@mailinator.org",
      "url": "https://www.catalogueoflife.org",
      "note": "A little note",
      "name": "Döring M.",
      "address": "Berlin, Germany"
    }
  ],
  "type": "nomenclatural",
  "identifier": {
    "col": "2091",
    "gbif": "4321",
    "plazi": "kvlkfvwjrvnr"
  },
  "license": "cc0",
  "confidence": null,
  "completeness": 0,
  "source": {
    "type": "dataset",
    "title": "Svampeatlas",
    "author": [
      {
        "family": "Jeppesen",
        "given": "Thomas"
      },
      {
        "family": "Guldberg Frøslev",
        "given": "Tobias"
      }
    ],
    "editor": [
      {
        "family": "Heillmann-Clausen",
        "given": "Jacob"
      }
    ],
    "publisher": "Danish Mycological Society",
    "publisher-place": "Copenhagen",
    "URL": "https://svampe.databasen.org",
    "issued": {
      "date-parts": [
        2021,
        6,
        10
      ]
    },
    "accessed": {
      "date-parts": [
        2021,
        6,
        12
      ]
    }
  },
  "private": false
}
`````

**Comment by mdoering** [comment]
is the darts parts serialisation correct? I thought its supposed to be a 2 dimensional array to support ranges.
https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#date-fields

```
"accessed": {
     "date-parts": [[ 2005, 4, 12 ]]
},
"issued": {
     "date-parts": [[ 2000, 3, 15 ], [2000, 3, 17]]
}

```

**Comment by thomasstjerne** [comment]
Indeed. Fixed now, but still getting:

Request failed with status code 400
Cannot deserialize instance of `java.util.ArrayList<life.catalogue.api.model.Citation>` out of START_OBJECT token at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 703] (through reference chain: life.catalogue.api.model.Dataset["source"])

HTTP method: PUT

https://api.dev.catalogueoflife.org/dataset/2091

Body:

`````
{
  "title": "TSJ Test DWCA",
  "description": "A list of taxa.",
  "contact": {
    "orcid": "0000-0003-1691-239X",
    "given": "Thomas",
    "family": "Jeppesen",
    "email": "tsjeppesen@gbif.org",
    "name": "Jeppesen T."
  },
  "creator": [
    {
      "orcid": "0000-0003-1691-239X",
      "given": "Thomas",
      "family": "Jeppesen",
      "email": "tsjeppesen@gbif.org",
      "name": "Jeppesen T."
    },
    {
      "given": "Markus",
      "family": "Döring",
      "department": "IT dept",
      "city": "Berlin",
      "country": "DE",
      "email": "markus@mailinator.org",
      "url": "https://www.catalogueoflife.org",
      "note": "A little note",
      "name": "Döring M.",
      "address": "Berlin, Germany"
    }
  ],
  "type": "nomenclatural",
  "identifier": {
    "col": "2091",
    "gbif": "4321",
    "plazi": "kvlkfvwjrvnr"
  },
  "license": "cc0",
  "confidence": null,
  "completeness": 0,
  "source": {
    "type": "dataset",
    "title": "Svampeatlas",
    "author": [
      {
        "family": "Jeppesen",
        "given": "Thomas"
      }
    ],
    "publisher": "Danish Mycological Society",
    "publisher-place": "Copenhagen",
    "URL": "https://svampe.databasen.org",
    "issued": {
      "date-parts": [
        [
          2021,
          6,
          1
        ]
      ]
    },
    "accessed": {
      "date-parts": [
        [
          2021,
          6,
          12
        ]
      ]
    }
  },
  "private": false
}

``````

**Comment by thomasstjerne** [comment]
Actually, I think the array should only be multidimensional when it is a range. At least in this demo the single date is in a regular array: https://citation.js.org/demo/

**Comment by mdoering** [comment]
That's the hell of CSL-JSON. There are various falvors out there. 
The official JSON schema does not allow one dimensional arrays, it seems to be a bug in Citation.js:
https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-data.json#L505

The reference implementation is citeproc-js:
https://github.com/Juris-M/citeproc-js

Crossref DOI resolution also returns 2d arrays:
```
curl -s -LH "Accept: application/vnd.citationstyles.csl+json" http://dx.doi.org/10.1093/database/baw125 | jq . | grep -A 10 issued
  "issued": {
    "date-parts": [
      [
        2016
      ]
    ]
  },
```

**Comment by thomasstjerne** [comment]
Just pick the one you like, it is easy to adapt the UI. We can even go for the raw data format (ISO data strings)

**Comment by mdoering** [comment]
Use the 2d array. I have support for raw as well, but I reckon for external users the 2d array is the way to do it.
Citation.js also reports 2d arrays in: https://github.com/larsgw/citation.js/issues/53
