### ISSUE TITLE
I was not able to attach subfamily Entiminae as a child of family Curculionidae in assembly tree 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1031]
Frontend version: 78b36a3 June 30, 2021 7:28 AMBackend version: 0173dc6 June 28, 2021 12:45 PM
https://data.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=97102c94-251b-4cf1-badf-a6ddfebd34ac&datasetKey=1166

I need to establish a new sector for subfamily Entiminae (3i Curculio) as a child of the family Curculionidae. 

I have drug&dropped subfamily Entiminae (3i Curculio) into family Curculionidae. The system has no any reaction - there is no pop-up menu offering options "Replace", "Union" etc. The same situation 30 later.

![image](https://user-images.githubusercontent.com/28574252/123970190-870fd300-d97e-11eb-8076-a7f3f1b7d9d5.png)

See also, https://github.com/CatalogueOfLife/backend/issues/1030#issuecomment-871389860

**Comment by yroskov** [comment]
Now it's working as expected

**Comment by mdoering** [comment]
Good. The fix was not deployed to prod before

**Comment by yroskov** [comment]
Woops. It might be too premature to say "it's working". Cannot see results, Entiminae is not in the tree (yet). Perhaps, slow respond from the software.

**Comment by yroskov** [comment]
Confirmed: it's work & Entiminae  is in right place now
