### ISSUE TITLE
Potential importer download cache problem

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1036]
There might be a problem with the importer using a cached version of dataset archives instead of downloading the latest copy of an external zip archive. [30 of the WoRMS checklists did not update to the new 2021-07-01 version](https://github.com/CatalogueOfLife/testing/issues/145#issuecomment-881479928), despite the [logs showing the importer downloading the archives on 2021-07-01](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/6ZJrYnoBBVmQ6cT2MK_w?_g=(filters:!())&_a=(columns:!(level,logger_name,message),filters:!())). After the zip archives were "downloaded" by the importer, the [last modified dates were still 2021-06-01 not 2021-07-01](https://download.catalogueoflife.org/archives/) (**not presently, because I did succeed in finally getting the 30 datasets to update**). I suspect that this is a caching problem because I tried to re-import some of these archives yesterday on prod and the importer still "downloaded" the 2021-06-01 version but if I setup a completely new test dataset on the dev server it was downloading the latest 2021-07-01 version.

**Comment by gdower** [comment]
I can confirm that this is an issue. I imported all WoRMS checklists today and the issued dates are `2021-08-01` for 35 of the 65 datasets, but if you look directly at the zip archive from WoRMS the issued date in the metadata.yaml is `2021-09-01` so it seems like the zip archive is either cached or the metadata is not updating. I can probably fix it by re-importing WoRMS again like last month, but I'll leave it like this for now so that you can look at it.

title | issued | version | imported
-- | -- | -- | --
World Porifera Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:27:28
World List of Bryozoa | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:23:29
World Nemertea Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:05:57
World List of Bochusacea | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:10:51
World List of Mystacocarida | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:10:26
World Polychaeta Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:10:23
World List of Tantulocarida | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:10:53
World List of Thermosbaenacea | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:05:43
World Asteroidea Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:03:30
World List of Xenoturbellida | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:02:12
World Echinoidea Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:02:07
World List of Holothuroidea | 2021-08-01 | ver. (08/2021) | 2021-09-01T19:10:49
World List of marine Brachyura | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:39:29
World List of Polycystina (Radiolaria) | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:37:28
World Hydrozoa Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:37:06
World Gastrotricha Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:36:08
World Placozoa Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:36:00
World List of Priapulida | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:35:58
World List of Monogenea | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:35:55
MolluscaBase | 2021-08-01 | ver. (08/2021) | 2021-08-19T02:58:46
World List of Octocorallia | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:32:51
World List of Chaetognatha | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:32:00
World List of Rhombozoa | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:31:53
World List of Merostomata | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:31:50
World List of Cephalochordata | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:31:41
World Foraminifera Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:56:14
World List of Ceriantharia | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:30:30
World List of Loricifera | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:30:18
Ascidiacea World Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:29:53
World List of Scyphozoa | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:29:18
World List of Antipatharia | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:27:36
World List of Gnathostomulida | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:25:00
World List of Crinoidea | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:23:46
World Euphausiacea Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:23:33
World Strepsiptera Database | 2021-08-01 | ver. (08/2021) | 2021-09-01T18:21:57
World Cumacea Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:21:32
World Ophiuroidea Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:21:47
World List of Brachypoda | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:01:14
World Remipedia Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:05:59
World Marine, Freshwater and Terrestrial Isopod Crustaceans database | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:05:40
World List of Marine Oligochaeta | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:02:57
World List of Leptostraca | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:02:10
World List of Tanaidacea | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:37:21
World List of Cestoda | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:35:12
World List of Trematoda | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:34:52
World List of Myxozoa | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:33:10
World List of Orthonectida | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:56
World Kinorhyncha Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:48
World Ostracoda Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:33:03
World List of Actiniaria | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:56
World List of Appendicularia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:35
Phylum Ctenophora: list of all valid species names. Electronic internet document | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:25
World List of Cubozoa | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:21
Pycnobase: World Pycnogonida Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:15
World List of Staurozoa | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:01
World List of Thaliacea | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:29:58
World of Copepods Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:39
World List of Corallimorpharia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:27:31
World List of Scleractinia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:29:13
World List of Zoantharia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:27:22
MilliBase | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:05
World Amphipoda Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:27:18
World List of turbellarian worms: Acoelomorpha, Catenulida, Rhabditophora | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:25:17
World Brachiopoda Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:23:54
Nemys: World Database of Nematodes | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:24:57

**Comment by mdoering** [comment]
so you notice this only by looking at the metadata? maybe the metadata was invalid and not changed?
I will take a look

**Comment by bart-v** [comment]
Hi all,

This is an issue at our side: we have a sync between multiple web servers.
In some cases that sync gets stuck and one of the webservers still has the old version.
I forced a sync now.
If you re-import, all of them should have 2021-09-01 as issued data

Can you confirm?

**Comment by gdower** [comment]
Thank you, @bart-v, this is resolved now:

id | alias | title | issued | version | imported
-- | -- | -- | -- | -- | --
1044 | WoRMS Porifera | World Porifera Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:30:21
1058 | WoRMS Cumacea | World Cumacea Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:21:32
1059 | WoRMS Ophiuroidea | World Ophiuroidea Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:21:47
1081 | WoRMS Bryozoa | World List of Bryozoa | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:26
1085 | WoRMS Nemertea | World Nemertea Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:23:44
1086 | WoRMS Bochusacea | World List of Bochusacea | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:23:46
1087 | WoRMS Brachypoda | World List of Brachypoda | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:01:14
1088 | WoRMS Mystacocarida | World List of Mystacocarida | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:31:53
1090 | WoRMS Polychaeta | World Polychaeta Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:36:22
1091 | WoRMS Remipedia | World Remipedia Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:05:59
1092 | WoRMS Tantulocarida | World List of Tantulocarida | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:31:50
1093 | WoRMS Thermosbaenacea | World List of Thermosbaenacea | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:31:47
1094 | WoRMS Isopoda | World Marine, Freshwater and Terrestrial Isopod Crustaceans database | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:05:40
1095 | WoRMS Asteroidea | World Asteroidea Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:31:44
1099 | WoRMS Oligochaeta | World List of Marine Oligochaeta | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:02:57
1100 | WoRMS Xenoturbellida | World List of Xenoturbellida | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:31:05
1105 | WoRMS Leptostraca | World List of Leptostraca | 2021-09-01 | ver. (09/2021) | 2021-09-01T19:02:10
1106 | WoRMS Echinoidea | World Echinoidea Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:31:50
1107 | WoRMS Holothuroidea | World List of Holothuroidea | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:30:48
1108 | WoRMS Brachyura | World List of marine Brachyura | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:31:03
1109 | WoRMS Polycystina | World List of Polycystina (Radiolaria) | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:28:44
1110 | WoRMS Tanaidacea | World List of Tanaidacea | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:37:21
1112 | WoRMS Hydrozoa | World Hydrozoa Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:28:39
1122 | WoRMS Gastrotricha | World Gastrotricha Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:27:37
1123 | WoRMS Placozoa | World Placozoa Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:27:29
1124 | WoRMS Priapulida | World List of Priapulida | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:27:27
1126 | WoRMS Monogenea | World List of Monogenea | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:27:24
1127 | WoRMS Cestoda | World List of Cestoda | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:35:12
1128 | WoRMS Trematoda | World List of Trematoda | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:34:52
1129 | WoRMS Myxozoa | World List of Myxozoa | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:33:10
1130 | WoRMS Mollusca | MolluscaBase | 2021-09-01 | ver. (09/2021) | 2021-09-02T07:26:59
1131 | WoRMS Octocorallia | World List of Octocorallia | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:26:37
1132 | WoRMS Chaetognatha | World List of Chaetognatha | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:38
1149 | WoRMS Orthonectida | World List of Orthonectida | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:56
1150 | WoRMS Rhombozoa | World List of Rhombozoa | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:34
1152 | WoRMS Merostomata | World List of Merostomata | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:31
1153 | WoRMS Kinorhyncha | World Kinorhyncha Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:48
1154 | WoRMS Cephalochordata | World List of Cephalochordata | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:29
1157 | WoRMS Foraminifera | World Foraminifera Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:51:30
1175 | WoRMS Ostracoda | World Ostracoda Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:33:03
1176 | WoRMS Actiniaria | World List of Actiniaria | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:56
1178 | WoRMS Appendicularia | World List of Appendicularia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:35
1179 | WoRMS Ceriantharia | World List of Ceriantharia | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:07
1180 | WoRMS Ctenophora | Phylum Ctenophora: list of all valid species names. Electronic internet document | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:25
1181 | WoRMS Cubozoa | World List of Cubozoa | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:21
1182 | WoRMS Loricifera | World List of Loricifera | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:02
1183 | WoRMS Pycnogonida | Pycnobase: World Pycnogonida Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:15
1184 | WoRMS Staurozoa | World List of Staurozoa | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:30:01
1185 | WoRMS Thaliacea | World List of Thaliacea | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:29:58
1186 | WoRMS Ascidiacea | Ascidiacea World Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:25:00
1188 | WoRMS Scyphozoa | World List of Scyphozoa | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:24:23
1191 | WoRMS Copepoda | World of Copepods Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:39
1194 | WoRMS Antipatharia | World List of Antipatharia | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:24:18
1195 | WoRMS Corallimorpharia | World List of Corallimorpharia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:27:31
1196 | WoRMS Scleractinia | World List of Scleractinia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:29:13
1197 | WoRMS Zoantharia | World List of Zoantharia | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:27:22
1200 | WoRMS MilliBase | MilliBase | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:31:05
1202 | WoRMS Amphipoda | World Amphipoda Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:27:18
1125 | WoRMS Gnathostomulida | World List of Gnathostomulida | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:24:13
1193 | WoRMS Turbellarians | World List of turbellarian worms: Acoelomorpha, Catenulida, Rhabditophora | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:25:17
2299 | WoRMS Brachiopoda | World Brachiopoda Database | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:23:54
2300 | WoRMS Crinoidea | World List of Crinoidea | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:24:10
2301 | WoRMS Euphausiacea | World Euphausiacea Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:23:56
2302 | WoRMS Nemys | Nemys: World Database of Nematodes | 2021-09-01 | ver. (09/2021) | 2021-09-01T18:24:57
1103 | WoRMS Strepsiptera | World Strepsiptera Database | 2021-09-01 | ver. (09/2021) | 2021-09-02T16:23:53
