### ISSUE TITLE
Interpret html entites into their values when importing metadata.yaml?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1038]
The frontend does not render html entities in the metadata, and we are [getting html entities in some of the metadata yaml files](https://github.com/CatalogueOfLife/testing/issues/144#issuecomment-885906444). It might be good if the backend interprets html entities to their values so that exported datasets have human readable yaml? If you disagree, we could transfer this to the frontend and render the html entities.

**Comment by bart-v** [comment]
The HTML entities encoding were basically a bug/legacy issue in our metadata export, so not sure if this is still needed.

**Comment by mdoering** [comment]
This should be done in the backend so it's correct in the API response.
We need to deal with html tags anyways already: https://github.com/CatalogueOfLife/backend/issues/1021
