### ISSUE TITLE
Error after attempt to save edited metadata

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1041]
https://data.catalogueoflife.org/dataset/1146/about

I have edited metadata for CrabCat, id 1146. After I pushed Save button, I have got following error message (422):

![image](https://user-images.githubusercontent.com/28574252/130117700-1d1e2d8e-baa2-4dca-aea0-89b4f0962882.png)

**Comment by mdoering** [comment]
duplicate of #1040
