### ISSUE TITLE
I cannot establish sector

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1042]
Frontend version: de391f9 August 17, 2021 7:49 AMBackend version: af406c2 August 16, 2021 9:03 AM

Seems, I am not able to establish sector in the tree.

https://data.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=684c9337-ff83-4272-a94f-603cee940923&datasetKey=1146&sourceTaxonKey=xJ 

I need to re-establish the sector - subfamily Caraboidea - for a new version of CarabCat (id 1146). I have deleted old sector in the CoL Tree. After that I have tried to drug&drop subfamily Caraboidea and chosen REPLACE button. However, the system did not perform any action. Pop-up menu stays as it is forever:
![image](https://user-images.githubusercontent.com/28574252/130130568-7e339b7f-7b7d-4fe2-b811-d82e67e5f8e0.png)

There is no result after window refresh.

https://data.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=684c9337-ff83-4272-a94f-603cee940923&datasetKey=1146&sourceTaxonKey=xJ

**Comment by mdoering** [comment]
@yroskov does this work again now?
