### ISSUE TITLE
Export w species count: Counts seems off in some cases

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1050]
I would expect the childrens species counts to sum up to the parents species count.
https://api.catalogueoflife.org/dataset/2332/export.json?rank=phylum&rank=class&countBy=species&taxonID=B

`````
{
   "id":"622BK",
   "name":"Actinobacteria",
   "authorship":"Cavalier-Smith, 2002",
   "rank":"phylum",
   "code":"bacterial",
   "status":"accepted",
   "label":"Actinobacteria Cavalier-Smith, 2002",
   "labelHtml":"Actinobacteria Cavalier-Smith, 2002",
   "species":2419,
   "children":[
      {
         "id":"622BJ",
         "name":"Actinobacteria",
         "authorship":"Cavalier-Smith, 2002",
         "rank":"class",
         "code":"bacterial",
         "status":"accepted",
         "label":"Actinobacteria Cavalier-Smith, 2002",
         "labelHtml":"Actinobacteria Cavalier-Smith, 2002",
         "species":6,
         "children":[
            
         ]
      }
   ]
}
`````

**Comment by thomasstjerne** [comment]
Also it looks like both the Phylum and Class are named `Actinobacteria Cavalier-Smith, 2002`

**Comment by mdoering** [comment]
You explicitly only include phylum and class, so all other children are dropped.
You can see that there are a few sublcasses directly linked to the phylum:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/327505/132335343-3650971c-4297-4e88-a5e1-3cb247fb13c3.png">

**Comment by thomasstjerne** [comment]
Hmm - any easy way to get all unique child ranks of a taxon?

**Comment by mdoering** [comment]
I could change the API to return all children regardless of their rank and a cutoff rank to avoid e.g. tons of species linked to a family? Virtually grouping them is probably too complex to implement here also. Maybe actually the tree API is better to be used if it contained species counts?

**Comment by thomasstjerne** [comment]
That sounds useful - but yes the tree api with species counts would be really useful for this

**Comment by mdoering** [comment]
Let me add counts to the tree API then - thats not gonna be hard and seems more adequate. It will also pave the way for showing species counts in the tree as the original design by Yuri was (I would probably want to precalc them if we really put this into the COL homepage though)

**Comment by mdoering** [comment]
deployed to dev: http://api.dev.catalogueoflife.org/dataset/3/tree/7a77dbd5-bcff-42c9-b9fc-b05d5678302f/children?countBy=species
