### ISSUE TITLE
Species with subgenus "homonyms" getting misplaced during sync?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1052]
It seems that ["homonym" subgenera are being misplaced in the taxonomic classification](https://github.com/gbif/checklistbank/issues/187) with all of Culex (Culex) placed incorrectly in Trigonometopus (Culex), and most likely it is happening during sync in assembly. In some cases it is caused by bad data in which the "homonym" subgenus was incorrectly applied but the expected behavior during sync is to copy the data as it was in the source and not attach it to an unexpected subgenus homonym.

The reasons I think it is happening during sync are:

1) The data are [correct in the source dataset](https://data.catalogueoflife.org/dataset/1101/taxon/Culicidae-Culicinae-Culicini-Culex-Culex-tarsalis-d434e7ec4), but were not correct in assembly
2) @yroskov and I determined that it is not [caused by union sectors](https://github.com/gbif/checklistbank/issues/187#issuecomment-914456446) by switching all sectors in Diptera to attach mode, which did not solve the problem.
3) When @yroskov applied a decision to remove the incorrect subgenus Culex from Trigonometopus ("Culex") canus, and synced it fixed the issue

The [logs](https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:'2021-09-07T20:58:00.428Z'))&_a=(columns:!(level,logger_name,message),filters:!(),index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',interval:auto,query:(language:kuery,query:Culex),sort:!())) say that the subgenus Culex is ignored by TreeCopyHandler, but not much other info is present on Culex in the logs.

**Comment by mdoering** [comment]
Puzzling. I cannot reproduce this problem in integration tests. Still figuring out whats going on...

**Comment by gdower** [comment]
I reproduced the issue in a [debug assembly](https://data.dev.catalogueoflife.org/catalogue/2179/assembly?assemblyTaxonKey=1bdd96fa-7627-47fe-a48d-1b36df1d628f&datasetKey=2178&sourceTaxonKey=x4) with a smaller dataset of just Culex, which I hope will help.

**Comment by mdoering** [comment]
THanks @gdower that's useful! I can reproduce it now in tests and should be able to locate the problem!

**Comment by mdoering** [comment]
@gdower btw, while trimming the data down to a tiny dataset that we can keep in tests I spotted that some name ids are not unique:

```
Culicidae-Culicinae-Culicini-Culex-Culex-abnormalis-7ccf8431f		Culex (Culex) abnormalis	Lane, 1936	species	Culex	Culex	abnormalis					189	1936	zoological	http://purl.obolibrary.org/obo/NOMEN_0000285		
Culicidae-Culicinae-Culicini-Culex-Culex-abnormalis-7ccf8431f		Culex (Culex) abnormalis	Lane, 1936	species	Culex	Culex	abnormalis					189	1936	zoological	http://purl.obolibrary.org/obo/NOMEN_0000224		
```
