### ISSUE TITLE
NotAssigned taxa without children

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1054]
https://data.catalogueoflife.org/dataset/3/classification?taxonKey=06ec82f1-dd3d-43e1-a75f-b5cd4198e804
Frontend version: 82de357 September 10, 2021 10:42 AMBackend version: 5179b8d September 10, 2021 1:46 PM

I have spot NotAssigned taxa without children in different parts of the tree. 

For example:

Phylum Arthropoda - class NotAssigned (empty)
Class Insecta - order NotAssigned (empty)
Family Zorotypidae - subfamily NotAssigned (empty)

![image](https://user-images.githubusercontent.com/28574252/133270585-e1a76f5e-4856-4ab2-9606-14a9cb61b620.png)

**Comment by mdoering** [comment]
There are indeed species dangling lose. But the API returns the "Not assigned" placeholder with childCount=0 why the UI does not allow you to open it and show them.
