### ISSUE TITLE
TASK reports have changed their behaviour

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1056]
Frontend version: 82de357 September 10, 2021 10:42 AMBackend version: 5179b8d September 10, 2021 1:46 PM

@mdoering, @thomasstjerne, working with TASKS, as I can see, some reports changed their results. For example, report ACC-SYN **species**  (diff acc, same auth) now contains trinomials such as Anisolabis felix felix, Forcipula quelchi quelchi, Forficula davidi davidi, etc. 

https://data.catalogueoflife.org/catalogue/3/dataset/1158/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym&withDecision=false

Expected behaviour: only duplicated binomials present in all reports for **species**, and only duplicated trinomials are in all reports for **infraspecies**.

@gdower, I think, I should stop making decisions in the checklistbank until this bug will be fixed. Correct?

**Comment by mdoering** [comment]
@yroskov can you point out an example what is wrong please? I only see binomials in the link above.

**Comment by yroskov** [comment]
Woops, you are right. My alarm is false
