### ISSUE TITLE
Taxonomic references not getting imported?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1058]
We're missing taxonomic references in ChecklistBank and the Portal, but they also seem to be missing in the API:

![image](https://user-images.githubusercontent.com/8573609/135169995-a693b056-1e28-4c73-94af-6a9de87cd16b.png)

`referenceIds` in verbatim:
https://api.dev.catalogueoflife.org/dataset/1189/verbatim/108906

`referenceIds` not included in the API:
https://api.catalogueoflife.org/dataset/3LR/taxon/6GB7G
https://api.dev.catalogueoflife.org/dataset/1189/taxon/44300

clb:
https://data.dev.catalogueoflife.org/dataset/1189/taxon/44300

portal: 
https://www.catalogueoflife.org/data/taxon/6GB7G

Re: https://github.com/CatalogueOfLife/testing/issues/135#issuecomment-917139615

**Comment by mdoering** [comment]
Hm, that looks indeed like a bad bug

**Comment by mdoering** [comment]
indeed missing in the implementations. Only singular referenceID fields were set.
I have implemented it now and on its way to dev for testing.

**Comment by gdower** [comment]
Thanks!

**Comment by mdoering** [comment]
Works: https://api.dev.catalogueoflife.org/dataset/1189/taxon/44300
