### ISSUE TITLE
Comment [sic] in scientific names

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1059]
There are thousands of scientific names in CoL with comment **[sic]**. 

For example:
Acyrthosiphon beiqueti [sic] Hille Ris Lambers, 1960	
Amphorophora rubifolii [sic] Theobald, 1926	
Phylloxera vastabrix [sic] Planchon, 1868
Phylloxera vestatrix [sic] Planchon, 1868

The comment **[sic]** (=so!) is used in the nomenclature to highlight a misspelled version of the name. (In botany, I met similar comment **est!**).

For attention of @dhobern (Taxonomy Group) & @mdoering:  
At this moment, checklistbank software allows such names to go in the CoL without editorial modifications. Shall we continue the same practice, or do adjustments in the software for (1) removing portion [sic] from the name and (2) giving these names a status "orthographic variant"?

Such names usually included in the ISSUES reports _Multi Word Epithet_ or _Parsed Name Differs_.

Example of the report for _SF Aphid_:
https://data.catalogueoflife.org/catalogue/3/dataset/1061/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=multi%20word%20epithet&limit=1000&offset=0&reverse=false

**Comment by mdoering** [comment]
Yes, that was on our todo list a while ago but we forgot about it. Good you raise this again as its problem we should address. I think the software should try to figure out the known common cases you have pointed out above and change the name and nom status like you say. `Phylloxera vastabrix [sic] Planchon, 1868` would then become
`Phylloxera vastabrix Planchon, 1868` with nom status _orthographic variant_. 

Do we know what the correct orthography is in all cases? Is this used in synonyms when the accepted name has the correct orthography?

**Comment by yroskov** [comment]
In majority cases, accepted name represents correct spelling. However, in some cases, another name among "semantic synonyms" may represent correct spelling.

**Comment by camiplata** [comment]
@mdoering I believe that sic has been removed even from places where its a valid part of the name, for example on the Fleas dataset I'm getting wrong authorships, for example `Rosicky, 1955` has become `Roky, 1955`, 


<img width="1160" alt="Captura de pantalla 2024-03-02 a la(s) 4 06 17 p m" src="https://github.com/CatalogueOfLife/backend/assets/5700527/4315c28c-a721-4613-9242-7859a8ac1108">

**Comment by mdoering** [comment]
Ha, that looks like a serious bug ;)

**Comment by mdoering** [comment]
@yroskov you might want to wait with any syncs until this is solved!

**Comment by mdoering** [comment]
Fix is deployed!
