### ISSUE TITLE
Author rendering problem for author strings with non

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1067]
Names with non in the author string on rendering like this in the backend:

`Xiphipops fisheri () non Snyder, 1904`

http://api.catalogueoflife.org/dataset/3LR/nameusage/search?q=Xiphipops%20fisheri

It should be rendered like `Xiphipops fisheri (non Snyder, 1904)` according to the original source:

http://api.catalogueoflife.org/dataset/3LR/nameusage/search?q=Xiphipops%20fisheri
http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/587afe9531d12b58997646929867a0be/synonym/038a4d358f0f5f44515d76459be2ed93

That's how it is provided in the verbatim data:

https://data.catalogueoflife.org/dataset/1010/verbatim?q=Xiphipops%20fisheri

**Comment by yroskov** [comment]
As presented on FishBase website:
![image](https://user-images.githubusercontent.com/28574252/142913008-879f2f53-0446-421f-be51-f0967ea7f431.png)

https://fishbase.mnhn.fr/Nomenclature/SynonymsList.php?ID=9222&SynCode=27342&GenusName=Centropyge&SpeciesName=acanthops

As presented in AC19:
http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/587afe9531d12b58997646929867a0be/synonym/038a4d358f0f5f44515d76459be2ed93

**Comment by mdoering** [comment]
what meaning do the brackets have? Would it be fine to remove them with the standardization so it becomes `Xiphipops fisheri non Snyder, 1904` ?

**Comment by yroskov** [comment]
To avoid confusion of CoL users, the authorstring presentation in CoL should match its presentation in the original website - i.e. in brackets in this case.

(However, I'll forward your question to Nicolas)

**Comment by yroskov** [comment]
Dear Nicolas,

FishBase: Could you please let us know, whether brackets in authorstrings with misapplied names essential, or can be dropped? Please reply via GitHub.

Example of names:
https://fishbase.mnhn.fr/Nomenclature/SynonymsList.php?ID=9222&SynCode=27342&GenusName=Centropyge&SpeciesName=acanthops

Yours, Yury

**Comment by mdoering** [comment]
> To avoid confusion of CoL users, the authorstring presentation in CoL should match its presentation in the original website - i.e. in brackets in this case.

We mostly try to do that - with the exception of splitting the name authorship and the misapplied "accordingTo" into 2 parts. I reckon we can keep the brackets if we need to - but it I wonder if it's not better to remove them like everywhere else with "non"?

**Comment by NicBailly** [comment]
These names recover two situations:
- Misidentifications
- Wrong name having been applied for a long time to a valid species (e.g., Epinephelus guaza for Epinephelus marginatus). The latter case is much less frequent than the former.

Parentheses have no meaning although we are progressively filling up if the name used in a misidentification represent an original vs a new combination, when we have finished, parentheses could =have meanings. We will also differentiate between the 2 cases above by using non for misidentification, and not of for misapplied name, but it is only plans for now.

**Comment by yroskov** [comment]
Done. Nicolas.

 

From: Roskov, Yury ***@***.***> 
Sent: Monday, 22 November, 2021 12:44
To: CatalogueOfLife/backend ***@***.***>; CatalogueOfLife/backend ***@***.***>; Nicolas Bailly (Qq) ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [CatalogueOfLife/backend] Author rendering problem for author strings with non (Issue #1067)

 

Dear Nicolas,

 

FishBase: Could you please let us know, whether brackets in authorstrings with misapplied names essential, or can be dropped? Please reply via GitHub.

 

Example of names:

https://fishbase.mnhn.fr/Nomenclature/SynonymsList.php?ID=9222&SynCode=27342&GenusName=Centropyge&SpeciesName=acanthops

 

Yours, Yury

**Comment by mdoering** [comment]
@NicBailly I am only catching up on this now. I still find the use of brackets in your misapplications odd. Looking at the [example](https://fishbase.mnhn.fr/Nomenclature/SynonymsList.php?ID=9222&SynCode=27342&GenusName=Centropyge&SpeciesName=acanthops) from above:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/327505/160368707-f4e79fbb-90d2-433e-bd4e-e334f74e3aa2.png">

[Centropyge fisheri (non Snyder, 1904)](https://fishbase.mnhn.fr/Summary/SpeciesSummary.php?ID=7813) is a misapplication of the recombination `Centropyge fisheri (Snyder, 1904)`. `non Snyder, 1904` states this is the usage by someone (or rather anyone), but Snyder in 1904. As Snyder was the original author and likely never used that combination it makes little sense to me. The non would have to be the _combination_ author. That obviously is not tracked in zoology, so you end up placing the non into the brackets, correct? Did you consider to use `Centropyge fisheri non (Snyder, 1904)` instead? This seems a bit better to me. Much better would be to know which author did misapply the name, sth like `Centropyge fisheri (Snyder, 1904) sensu F. Schneidewind, 2004`.

Another thing I find odd is that you list the [misapplied name as an accepted name](https://fishbase.mnhn.fr/Nomenclature/SynonymSummary.php?ID=13335&GSID=&Status=misapplied%20name&Synonymy=misapplied%20name&Combination=new%20combination&GenusName=Centropyge&SpeciesName=fisheri&SpecCode=9222&SynonymsRef=4858&Author=%28non+Snyder%2C+1904%29&Misspelling=0) in your website. There is also a Status ref [Schindler, I. and F. Schneidewind,2004](https://fishbase.mnhn.fr/References/FBRefSummary.php?ID=53274) given, would that be the reference the misapplication is found in? Then this would be an important concept reference to know, sth DwC and ColDP track as  `accordingTo`.

**Comment by mdoering** [comment]
@dhobern @chantalhuijbers this might be an interesting topic for the Taxonomy Group to discuss.
