### ISSUE TITLE
nameusage search gives usages with datasetKey that is not found in taxon info

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1068]
This search gives two usages
https://api.catalogueoflife.org/nameusage/search?datasetKey=2083&facet=datasetKey&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Cortinarius&rank=genus&sortBy=taxonomic

Trying to get taxon info for a usage says `"Dataset 2083 does not exist"`
https://api.catalogueoflife.org/dataset/2083/taxon/5f1b8978-f0d5-4443-92d3-3b9ffc715e37/info

**Comment by mdoering** [comment]
Weitd. The usage returns, its driven by the db. 

https://api.catalogueoflife.org/dataset/2083/taxon/5f1b8978-f0d5-4443-92d3-3b9ffc715e37
