### ISSUE TITLE
Media extension not imported for DWC?

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1070]
It looks like the simple multimedia extension is not making it into CLB: https://data.catalogueoflife.org/dataset/2047/taxon/10000
Here are the [verbatim records pointing the taxon](https://data.catalogueoflife.org/dataset/2047/verbatim?type=dwc%3ATaxon&type=dwc%3AVernacularName&type=dwc%3ADescription&type=dwc%3ADistribution&type=dwc%3AMultimedia&type=dwc%3AReference&type=coldwc%3ANameRelations&dwc:parentNameUsageID=10000&dwc:acceptedNameUsageID=10000&dwc:originalNameUsageID=10000&dwca:id=10000&dwca:id=10000&dwca:id=10000&dwca:id=10000&dwca:id=10000&dwca:id=10000&coldwc:relatedNameUsageID=10000&termOp=OR)

The media is present on the GBIF equivalent taxon page:
https://www.gbif.org/species/132619745

**Comment by mdoering** [comment]
http://rs.gbif.org/terms/1.0/Multimedia as in http://rs.gbif.org/extension/gbif/1.0/multimedia.xml should be interpreted already

**Comment by mdoering** [comment]
The dwca linked in [CLB](https://data.catalogueoflife.org/dataset/2047/imports): https://svampe.databasen.org/dwc/DMS_Fun_taxa.zip
does not contain that extension. Here is the meta.xml:

```
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="UTF-8" fieldsTerminatedBy="\t" linesTerminatedBy="\n" fieldsEnclosedBy='' ignoreHeaderLines="0" rowType="http://rs.tdwg.org/dwc/terms/Taxon">
    <files>
      <location>taxon.txt</location>
    </files>
    <id index="0" />
    <field index="1" term="http://rs.tdwg.org/dwc/terms/taxonID"/>
    <field index="2" term="http://rs.tdwg.org/dwc/terms/scientificNameID"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/specificEpithet"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/infraspecificEpithet"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/parentNameUsageID"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/acceptedNameUsageID"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/taxonomicStatus"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/taxonRank"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/vernacularName"/>
        <field index="11" term="http://rs.tdwg.org/dwc/terms/scientificNameAuthorship"/>
        <field index="12" term="http://purl.org/dc/terms/references"/>


  </core>

</archive>
```

Is this the wrong DwC-A?

**Comment by mdoering** [comment]
in GBIF this is Checklist of Danish Fungi with a DwC-A from https://svampe.databasen.org/dwc/dwcchecklistarchive.zip
https://www.gbif.org/dataset/2b94a042-fe01-4d9f-8995-d996c21d33cd

@thomasstjerne Shall we use that instead?

**Comment by thomasstjerne** [comment]
You are right I confused the two. The one in COL is containing taxa recorded outside of Denmark, whereas the other has only taxa recorded as danish.
