### ISSUE TITLE
Broken syncs?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1079]
For attention of @mdoering (@gdower) 

I have kicked off syncs for World Plants & Ferns yesterday (2021-12-01). Today, I don't see that any processes running. However, about 158 sectors from these GSDs marked with a status "waiting". Is something wrong there?

https://data.catalogueoflife.org/catalogue/3/sector/sync?limit=25&offset=0

![image](https://user-images.githubusercontent.com/28574252/144497839-95e4e340-d52a-4ff5-a2d7-942e5e4ec679.png)

**Comment by yroskov** [comment]
Well... there are related interface issues (@thomasstjerne):

Sectors labelled as "waiting" have no option to be re-synced. Button "stop sync" gives error message 404:

![image](https://user-images.githubusercontent.com/28574252/144627112-318ba252-d4ad-4bc2-bd11-8e6da70dd92d.png)

**Comment by gdower** [comment]
I don't know if it is related or not, but the importer hit the [database deadlock issue](https://github.com/CatalogueOfLife/backend/issues/1002) yesterday probably while those syncs were running, so they may have failed and the sync status was not updated from waiting to failed. So this is really [issue #793](https://github.com/CatalogueOfLife/backend/issues/793) with dead jobs not leaving the sync queue.

**Comment by mdoering** [comment]
This happened when I had to redeploy/restart the backend some days ago. There was a bug that these syncs did not get marked as canceled, but instead linger on as ghosts. I have changed them to canceled now, please resubmit them if you need to.
