### ISSUE TITLE
How to handle stable IDs being deleted in monthly releases

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1083]
When a public, monthly release is deleted this might remove the only record for a given stable ID.
If we ever want to be able to resolve it again we need to preserve it or at least link it to a subsequent version from an annual LTS release

**Comment by mdoering** [comment]
Options to consider:

1.  - accept the fact that we will lose some identifiers that only existed between annual releases
2.  - maintain a new project wide id table that tracks all identifiers ever issued and that can be rematched to a new names index. This would require keeping basic names data in that table incl the name, authorship, rank, release attempt created/deleted or first/latest. It adds some overhead to the release process, but should not be dramatic. It would also allow for better [project wide resolution](https://github.com/CatalogueOfLife/backend/issues/1082) of identifiers.
3. same as 2, but only store the deleted identifiers. We already report deleted and resurrected ids which can be used to manage such a lost ids table

 -

**Comment by mdoering** [comment]
@yroskov @gdower @olafbanki Until this is solved we should not be deleting any old releases - which we planned to do after 1y, i.e. we would now remove the first monthly releases with stable ids.

**Comment by timrobertson100** [comment]
My gut feeling is that a version along the lines of option 3. is the better solution.  Perhaps implement a simple "key/value" table that drives a tombstone page documenting the state before the entry was deleted.

I anticipate option 2., which aims to maintain all discovery services for "legacy" data will become a hindrance over time and may limit the ability to bring new features that need e.g. schema changes. I assume you don't really want people to discover deleted data, other than if they hold a direct link to it - in many cases it may be mistakes such as unwittingly publishing duplicates etc.

Option 1. will reduce any trust in COL IDs so I feel should be discounted.

**Comment by mdoering** [comment]
Thanks Tim, I think I fully agree and would also lean towards option 3. Or can anyone think of some other option not mentioned yet? @dhobern maybe?

**Comment by dhobern** [comment]
Option 3 makes sense to me too - thanks for addressing this.

**Comment by mdoering** [comment]
I have implemented 2 layers so we can gracely cope with private, preview releases which often will be deleted. IDs issued on those deleted releases should not be preserved.

1. Every release starts out as a private release and generates an id report which lists newly created, deleted or resurrected ids. Deleted ids work against the last public release and resurrected list ids that have been created & used before the previous release, but not in the previous one. Those text reports are now stored in the database. 
2. When a preview release is deleted, the id reports will be removed too. If it is published, name usages that have been deleted will be stored as a new ArchivedNameUsage instance in postgres with a primary key on projectKey & id.
3. ArchivedNameUsages is exposed under the existing resource /dataset/{projectKey}/nameusage/{id} which already returns different subclasses of NameUsageBase (Taxon, Synonym, BareName)
