### ISSUE TITLE
Name search not working through FME anymore

### ISSUE THREAD

**Issue by javiermerino-tracasa** [CatalogueOfLife/backend#1088]
Hello this is Javier Merino working on EUNIS database.

I have been using the name search API through FME processes for quite a while but today it is not working.
I see the website and search is actually working but not through FME.

Has there been a change in security measures or a proxy?
The error can also be from the FME side. I am not sure if there has been an update.
Below is the error message I get in case you can help. Thank you!

HTTPCaller_CoL_API (HTTPFactory): [1]: HTTP transfer error: SSL connect error
HTTPCaller_CoL_API (HTTPFactory): [1]: Please ensure that your network connection is properly set up
HTTPCaller_CoL_API (HTTPFactory): [1]: No proxy settings have been entered.  If you require a proxy to access external URLs, please ensure the appropriate information has been entered
HTTPCaller_CoL_API (HTTPFactory): An error occurred while accessing the URL 'https://api.catalogue.life/dataset/3LR/nameusage/search?q=Vulpes%20vulpes%20indutus&limit=10'

**Comment by mdoering** [comment]
Hi Javier. I dont know FME, but it looks like a general ssl connection problem. Me and our sysadmin are out this week, but we'll look into this next week. Can you get some more logs of why its failing to connect?

**Comment by javiermerino-tracasa** [comment]
Hello Markus,
Thanks for the quick response.
Here is the log file from FME. I believe those lines pertaining to the issue are those I shared already but maybe there is more here that can help. We have not changed anything in the FME and it has always worked until today.

[Test-Search-CoL.log](https://github.com/CatalogueOfLife/backend/files/7780719/Test-Search-CoL.log)

**Comment by javiermerino-tracasa** [comment]
I figured out the issue. It seems to be related to the certificate. It has either changed or has expired.
If I turn the "Verify SSL-certificates" parameter in the HTTP Caller to "No", the call works
![image](https://user-images.githubusercontent.com/96727598/147566352-c0a81d86-316d-46c4-a1ce-b78f42a69d89.png)

**Comment by mdoering** [comment]
@MattBlissett the SSL certificates for production COL have expired on 27th december.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/327505/147922687-5bc2476e-27df-4469-a6aa-9515f30dd33e.png">

DEV seems to have 40 more days before that expires, but seems to have a bad domain name associated:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/327505/147922847-5058fcd1-36dc-4cdb-a9ff-566ca80d6b92.png">

**Comment by mdoering** [comment]
Oh, I just realized now this is the old, deprecated domain!

Please use api.catalogueoflife.org instead!

**Comment by javiermerino-tracasa** [comment]
Thank you!
