### ISSUE TITLE
Parasitic space in epithet with dash

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1090]
CoL have received a comment:
28DEC2021

Secretariat:

"Hieracium brevifolium subsp. malyi -caroli"

should be

"Hieracium brevifolium subsp. malyi-caroli"

Ernie Spencer

Ernest Newell Spencer
Austin, Texas, USA
sites.google.com/site/piecesebook
sites.google.com/site/piecesebook2
sites.google.com/site/piecesebook3

**It looks like backend incorrectly parsing names (or the name) with dash inside an epithet, or frontend incorrectly displaying them** 

Portal view:
![image](https://user-images.githubusercontent.com/28574252/148846544-edd76025-29f4-4829-8b2c-468585e18a4f.png)

and API:
https://api.catalogueoflife.org/dataset/3LR/taxon/5HQLS

**Comment by mdoering** [comment]
Indeed the html label inserts a space. The parsing is just fine, but apparently the name is wrongly marked up
