### ISSUE TITLE
PUT user roles does not seem to work

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1094]
PUT /user/{userKey}/role ['ADMIN', 'EDITOR']

gives status 204, but changes are not applied.

Can be tested from here: https://data.dev.catalogueoflife.org/admin/users

**Comment by mdoering** [comment]
This seems to be a dev only problem, as that is a different partitioning branch.
Once Yuri agreed to the release I will merge branches, test it on dev so its available
