### ISSUE TITLE
query param for user access on dataset search 

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1100]
For the UI we need an easy way to list any dataset the user can access.

we have separate `editor` and `reviewer` params but a compound would be good,
maybe something like https://api.dev.catalogueoflife.org/dataset?origin=managed&limit=1000&editorOrReviewer=117

**Comment by mdoering** [comment]
do we then even need the individual editor / reviewer params at all or can they be replaced?

**Comment by mdoering** [comment]
I will add a new parameter `accessibleBy` that allows us to add more roles in the future without renaming the parameter.
Or maybe call it `visibleTo`? All public datasets should be visible by anyone.

**Comment by mdoering** [comment]
If it is only for the logged in user you can just use the dataset search without any further parameter.
it will only return those dataset a user has access to already, i.e. all public ones and the private ones with access based on the roles.

**Comment by mdoering** [comment]
Only if you need to list datasets for any user, not the authenticated one, we need an additional parameter.

**Comment by thomasstjerne** [comment]
Ahh, OK. So a query for `origin=managed` will only give the ones you can see as editor or reviewer?

**Comment by mdoering** [comment]
yes!
