### ISSUE TITLE
Not interpreted distribution records causing bare names?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1107]
The importer might be failing to import records from the CoLDP taxon table if it cannot interpret a related distribution record. Between these 2 import attempts, I only deleted 1 row in the distribution.tsv for Scarabs and re-imported with no other changes made to the .zip archive and there is a difference in names, which seems odd:

https://data.catalogueoflife.org/dataset/1027/diff?attempts=78..79

In import attempt 78 there were 5 `not interpreted` records in the distribution table. There were several synonym records with `missing accepted ID`'s. Deleting that 1 row in distribution fixed those issues and changed bare names to accepted taxa.

For example _Trox (Trox) unistriatus_ was a bare name and now it's an accepted name: 

https://data.catalogueoflife.org/dataset/1027/taxon/15-.01-.00-.00-.001-.001-.087-.-

I deleted this row from distribution.tsv:

```
15-.01-.00-.00-.001-.001-.115-.-	Neotropical(Mexico:Colima, Durango, Hidalgo, Michoacán, Nuevo León, Veracruz), Nearctic(USA:Texas, Florida, Kansas, South Carolina, Nebraska, Oklahoma, Iowa, Pennsylvania, Kentucky, Indiana, Vermont, Canada:Ontario, Quebec, New Brunswick, Nova Scotia, Prince Edward Island)	text				     
```

This was probably also a bare name in import attempt 78 but I don't know for sure:

https://data.catalogueoflife.org/dataset/1027/taxon/15-.01-.00-.00-.001-.001-.115-.-

I reproduced it:

https://data.catalogueoflife.org/dataset/1027/diff?attempts=80..81

**Comment by mdoering** [comment]
That is odd. I cannot explain how that one distribution row should have such an effect. Will try to reproduce and debug this locally. All I see in import attempt 80 are the following log lines:

> Normalizer: 6 orphan synonyms removed

> NeoCsvInserter: The inserted dataset contains 4 bad taxon foreign keys in col:Distribution
> NeoCsvInserter: The inserted dataset contains 1 bad taxon foreign keys in col:VernacularName
> NeoCsvInserter: Non existing taxonID 15-.01-.00-.00-.001-.001-.086-.- found in VernacularName record line 505, VernacularName.tsv
> NeoCsvInserter: Non existing taxonID 15-.01-.00-.00-.001-.001-.155-.- found in Distribution record line 16273, Distribution.tsv
> NeoCsvInserter: Non existing taxonID 15-.01-.00-.00-.001-.001-.115-.- found in Distribution record line 13575, Distribution.tsv 
> NeoCsvInserter: Non existing taxonID 15-.01-.00-.00-.001-.001-.087-.- found in Distribution record line 5067, Distribution.tsv
> NeoCsvInserter | Non existing taxonID 15-.01-.00-.00-.001-.001-.086-.- found in Distribution record line 5066, Distribution.tsv

**Comment by mdoering** [comment]
@gdower do you have the bad archive at hand? I cannot reproduce this with the above line added to the current version

**Comment by gdower** [comment]
Here they are:

[original](https://github.com/CatalogueOfLife/backend/files/8083481/coldp.zip)
[patched](https://github.com/CatalogueOfLife/backend/files/8083484/patch.zip)

**Comment by mdoering** [comment]
There are a lot of differences between those 2 archives, not just one deleted Distribution record.
[1027.diff.zip](https://github.com/CatalogueOfLife/backend/files/8087636/1027.diff.zip)

 - Distribution -1, +44
 - Name +21
 - NameRel +26
 - Reference +15
 - Synonym +49
 - Taxon +4
 - TypeMaterial +23
 - VernacularName +31
 
 This includes a new Taxon [15-.01-.00-.00-.001-.001-.087-.-](https://data.catalogueoflife.org/dataset/1027/taxon/15-.01-.00-.00-.001-.001-.087-.-) which you say was a bare name before and which would be perfectly correct. It was in the Name file, but not in the Taxon one so it ends up as a bare name.

To avoid bare names altogether I nearly always use the combined NameUsage entity in ColDP. Thats a lot simpler to use.

**Comment by mdoering** [comment]
I dont see any issue with the importer

**Comment by gdower** [comment]
@mdoering, thanks for spotting that. I was diffing the unzipped tsv files, not the zipped tsv files and there was a bug with the zipping process that's now fixed.
