### ISSUE TITLE
CLB: search for names containig square bracket (or other non-standard characters)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1112]
[Frontend version: 1bb80f5 February 11, 2022 1:19 PM](https://github.com/CatalogueOfLife/checklistbank/tree/1bb80f5)[Backend version: c94dbef February 15, 2022 12:00 AM](https://github.com/CatalogueOfLife/backend/tree/c94dbef)

Present release of CLB does not allow me to do a search in Workbench for names which contain square bracket or other non-standard characters.

I need this option in the Workbench, for example, to get a list of names similar to  **[Culex] stercoreus** and mark them as Provisionally Accepted (case of Systema Dipterorum, https://github.com/CatalogueOfLife/testing/issues/127#issuecomment-1045199243)

**Comment by mdoering** [comment]
There is no interpreted version of `[Culex] stercoreus`:
https://data.catalogueoflife.org/dataset/1101/names?q=stercoreus

The genus has been removed, probably due to the unexpected curly brackets, don't know.
