### ISSUE TITLE
CLB is down

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1114]
2022-02-23, 10.25 Champaign: CLB is down

https://data.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=0dc55baa-e9d6-496c-b4aa-10db2e55ca96&datasetKey=1141&sourceTaxonKey=Oxalidales-Achariaceae

error 403

![image](https://user-images.githubusercontent.com/28574252/155362376-bb967bbe-38d8-4ae7-b414-1344bcab62bf.png)

**Comment by mdoering** [comment]
Please first see Slack in such cases: https://catalogue-of-life.slack.com

**Comment by yroskov** [comment]
If the system stops working in the middle of my tasks, whether you put in a Slack, is helpless.

**Comment by mdoering** [comment]
Sorry for that. But there is always a chance of unexpected things happening in larger changes. I had hoped it to work out more smoothly, but we have not been down for more than 10 minutes. And that was only for the UI, the API continued to work all the time. If you follow Slack you are at least aware that there might be unexpected disturbances ahead.
