### ISSUE TITLE
Add version to dataset facet label for managed datasets

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1116]
To avoid seemingly identical rows representing each version:
https://www.checklistbank.org/nameusage/search?facet=datasetKey&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Cortinarius%20prodigiosus&sortBy=taxonomic&type=EXACT

**Comment by mdoering** [comment]
How should we best present the label, concatenated with space, comma or sth else?

1.   Catalogue of Life Checklist 2020-12-01
2.   Catalogue of Life Checklist, 2020-12-01
3.   Catalogue of Life Checklist - 2020-12-01
4.   Catalogue of Life Checklist (2020-12-01)
5.   Catalogue of Life Checklist [2020-12-01]

I think I like number 4 with brackets best.
