### ISSUE TITLE
generated citation looks odd

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1117]
~~Wonder if it is related to danish chars in author list?~~
Looks more like the institutions have become part of the author names.
https://api.checklistbank.org/dataset/2047.json

**Comment by mdoering** [comment]
indeed 2 things wrong here. The first name should not contain the institution.
Will see how that got there.

b) the abbreviation of the first name with brackets goes wrong.

**Comment by mdoering** [comment]
EML looks fine:

```
<creator>
  <individualName>
      <givenName>Jacob</givenName>
    <surName>Heilmann-Clausen</surName>
  </individualName>
  <organizationName>Center for Macroecology, Evolution and Climate</organizationName>
  <positionName>Associate Professor</positionName>
  <address>
      <deliveryPoint>Natural History Museum of Denmark, Universitetsparken 15</deliveryPoint>
      <city>Copenhagen</city>
      <postalCode>2100</postalCode>
      <country>DK</country>
  </address>
  <phone>+45 51330991</phone>
  <electronicMailAddress>jheilmann-clausen@snm.ku.dk</electronicMailAddress>
    </creator>
```

**Comment by mdoering** [comment]
I have reuploaded the EML and it now looks much better!
https://www.checklistbank.org/dataset/2047/about

maybe that was from past times...
