### ISSUE TITLE
Problem with the checklistbank

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1124]
Frontend version: 5160964 March 15, 2022 5:32 AMBackend version: 6a9c69c March 4, 2022 12:00 AM

Yesterday's CoL conversion is running 27 hours, and still is in progress:

https://www.checklistbank.org/imports/running?limit=10&offset=0&state=waiting&state=preparing&state=downloading&state=processing&state=deleting&state=inserting&state=matching&state=indexing&state=analyzing&state=archiving&state=exporting 

Last time, in February, a conversion took ~16h

**Comment by mdoering** [comment]
the search index rebuilt in parallel interferred. We should avoid that in the future, there are some table locks I need to avoid

**Comment by mdoering** [comment]
killed the indexing and now its fine
