### ISSUE TITLE
Source Dataset ID's to Dataset Name

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/backend#1135]
Monthly COLDP exports do not contain any means to programmatically find the name of a source dataset by its ID. Manually this is very tedious.
Please include a simple file to ease this task.
Ideally for me, it could be a tsv format file with three columns: sourceID, shortName and fullName. Any other format and/or contents, for example xml, would do.

**Comment by mdoering** [comment]
All DwC-A and ColDP archives should also have metadata files for each source bundled in a subfolder:
 - DwC-A as `dataset/{key}.xml`
 - ColDP as `source/{key}.yaml` (in addition to the source section in the main metadata.yaml above)

**Comment by mdoering** [comment]
@aoern finally I had time to update all monthly COL downloads to include the source metadata.
Please let me know if still sth is missing.

**Comment by aoern** [comment]
Thanks Markus. Ok now. 

Ari Örn
