### ISSUE TITLE
Import failures: update or delete on table "name_mod4" violates foreign key constraint "name_match_dataset_key_name_id_fkey27

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1144]
Most of the WoRMS imports failed with:

`PersistenceException: ### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_mod4" violates foreign key constraint "name_match_dataset_key_name_id_fkey27" on table "name_match" Detail: Key (dataset_key, id)=(1095, urn:lsid:marinespecies.org:taxname:204031) is still referenced from table "name_match". ### The error may exist in life/catalogue/db/mapper/DatasetPartitionMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: DELETE FROM name WHERE dataset_key=?; ### Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_mod4" violates foreign key constraint "name_match_dataset_key_name_id_fkey27" on table "name_match" Detail: Key (dataset_key, id)=(1095, urn:lsid:marinespecies.org:taxname:204031) is still referenced from table "name_match".`

**Comment by mdoering** [comment]
that was due to the bad partitioning I discovered and fixed last week
