### ISSUE TITLE
col:publishedInPageLink missing in API responses

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1146]
[This verbatim record](https://api.dev.checklistbank.org/dataset/131219/verbatim/190167) has a `col:publishedInPageLink` attribute, but it is not present in [Taxon](https://api.dev.checklistbank.org/dataset/131219/taxon/4116), [TaxonInfo](https://api.dev.checklistbank.org/dataset/131219/taxon/4116/info) or [Name](https://api.dev.checklistbank.org/dataset/131219/name/4116) responses

**Comment by mdoering** [comment]
Indeed missing the the data model and database :(
