### ISSUE TITLE
CLB: generation of TASKS reports failed, error code 503

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1157]
Working with TASKS for World Ferns: long wait to open task-report page, and error code 503 at the end of wait.

Tasks report: ACC-SYN species, diif acc, diff auct:

![image](https://user-images.githubusercontent.com/28574252/180842857-66a61df2-15d8-4384-a349-26739f826af8.png)

**Comment by mdoering** [comment]
It indeed takes ages, but I dont get the error...

**Comment by yroskov** [comment]
>But I also dont get any results for the green tasks with just few record counts. Not right.

I tested this report: 
![image](https://user-images.githubusercontent.com/28574252/182419695-b09aff21-9141-4ce7-a834-5863d8a01aab.png)

indeed, it took a long time to generate (it says 7 of 7 names). Finally, I got report (Advanced setting: With decision - Ignore):
https://www.checklistbank.org/catalogue/3/dataset/1140/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0
![image](https://user-images.githubusercontent.com/28574252/182420391-e7e43f06-0722-4b3b-b825-2a3f288a5ba0.png)

**Comment by mdoering** [comment]
@thomasstjerne I am not sure how the UI populates the task bars/numbers.
For SYN-SYN species (different accepted, same authors) [here](https://www.checklistbank.org/catalogue/3/dataset/1140/tasks) I see 30 pairs. But the [API call](https://api.checklistbank.org/dataset/1140/duplicate.json?acceptedDifferent=true&authorshipDifferent=false&catalogueKey=3&category=binomial&limit=51&minSize=2&mode=STRICT&status=synonym&withDecision=false) used by the UI returns an empty array. Where does the 30 come from?
