### ISSUE TITLE
Recommended citation in the Annual Checklist

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1161]
_For attention of @mdoering & @olafbanki_ 
  
As for me, the Recommended Citation looks odd:

DeWalt, R. E., Hopkins, H., Maehr, M. D., Neu-Becker, U., & Stueber, G. (**2021**). Plecoptera Species File. In O. Bánki, Y. Roskov, M. Döring, G. Ower, L. Vandepitte, D. Hobern, D. Remsen, P. Schalk, R. E. DeWalt, M. Keping, J. Miller, T. Orrell, R. Aalbu, R. Adlard, E. M. Adriaenssens, C. Aedo, E. Aescht, N. Akkari, S. Alexander, et al., **Catalogue of Life Checklist** (**Aug 2021**). https://doi.org/10.48580/dfq8-39r

1) it does not mention "Annual Checklist 2022" (it says "Catalogue of Life Checklist")

2) incorrectly applies year of GSD update as a year of AC publication (I would expect **2022** after GSD authors names, instead of "2021", a year of GSD update in the CoL) 

3) incorrectly placed a GSD version **Aug 2021** after "Catalogue of Life Checklist" (I would expect this version attached to the GSD name: "Plecoptera Species File (ver. Aug 2021)"

4) missing short name of GSD in its title (as result, all GSDs from WoRMS have no indication of WoRMS)

As for me, a recommended citation should look like a bibliographic citation of a chapter in the book:
DeWalt, R. E., Hopkins, H., Maehr, M. D., Neu-Becker, U., & Stueber, G. (**2022**). **SF Plecoptera:** Plecoptera Species File (**ver. Aug 2021**). In O. Bánki, Y. Roskov, M. Döring, G. Ower, L. Vandepitte, D. Hobern, D. Remsen, P. Schalk, R. E. DeWalt, M. Keping, J. Miller, T. Orrell, R. Aalbu, R. Adlard, E. M. Adriaenssens, C. Aedo, E. Aescht, N. Akkari, S. Alexander, et al., **Catalogue of Life Checklist (Annual Checklist 2022)**. **Catalogue of Life**. https://doi.org/????

Citations appear in the portal:

https://www.catalogueoflife.org/data/dataset/1065
and the list at
https://www.catalogueoflife.org/about/colusage

**Comment by yroskov** [comment]
Please also pay attention to the publisher in the citation:

ITIS, Alexander, S., Hodson, A., Mitchell, D., Nicolson, D., Orrell, T., & Perez-Gelabert, D. (2022). The Integrated Taxonomic Information System. In O. Bánki, Y. Roskov, M. Döring, G. Ower, L. Vandepitte, D. Hobern, D. Remsen, P. Schalk, R. E. DeWalt, M. Keping, J. Miller, T. Orrell, R. Aalbu, R. Adlard, E. M. Adriaenssens, C. Aedo, E. Aescht, N. Akkari, S. Alexander, et al., Catalogue of Life Checklist (Version 2022-08-01). **ITIS**. https://doi.org/10.48580/dfq8-4ky

https://www.catalogueoflife.org/data/dataset/2144

Somehow, "ITIS" appears in this citation as a publisher of the CoL compilation. I would expect there "Catalogue of Life" as a publisher as indicated in the general citation:
Bánki, O., Roskov, Y., Döring, M., Ower, G., Vandepitte, L., Hobern, D., Remsen, D., Schalk, P., DeWalt, R. E., Keping, M., Miller, J., Orrell, T., Aalbu, R., Adlard, R., Adriaenssens, E. M., Aedo, C., Aescht, E., Akkari, N., Alexander, S., et al. (2022). Catalogue of Life Checklist (Annual Checklist 2022). **Catalogue of Life**. https://doi.org/10.48580/dfq8

**Comment by mdoering** [comment]
You can see the actual details that make up the citation here:
https://api.checklistbank.org/dataset/3LR/source/2144.json

The only attributes that refer to the annual checklist are the `containerTitle` and `containerCreator`. All the rest is the ITIS publication. And that uses the version which was last synced.

I agree it makes sense to use the issues date and maybe even version of the AC22 "serial" if you regard the source as a part of the bigger AC22 publication. But we decided to have new DOIs for sources only when they actually change. So their metadata will still refer to the version when the last change happened.

Both makes sense to me. What do we want???

**Comment by mdoering** [comment]
Plecoptera in AC21:
https://api.checklistbank.org/dataset/9837/source/1065.json

Plecoptera in latest release (Sept 2022 as of today):
https://api.checklistbank.org/dataset/3LR/source/1065.json

The problem to discuss is largely if we want to treat sources as a part of a release and therefore have different metadata (which then means citation) for every release even if they do not change or if we only want to change the metadata if data has changed - which we mostly did because it felt wrong to issue a new DOI when nothing has changed. We cannot have the same DOI but different metadata.

**Comment by mdoering** [comment]
@olafbanki anything that needs to happen on the backend which is not content?
