### ISSUE TITLE
<TAB> delimiter handling

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1166]
For Species File datasets the prod importer is finishing jobs instantly and [not importing any interpreted data](https://www.checklistbank.org/dataset/1061/imports). I saw the recent delimiter change, but the [same exact dataset config](https://www.dev.checklistbank.org/dataset/269254/options) and [zip archive](https://github.com/CatalogueOfLife/backend/files/9813755/aphid_species_file.2022-09-05_233432_%2B0000._coldp_otu_id_97680_2022-10-18t113837-0500.zip) works on [dev](https://www.dev.checklistbank.org/dataset/269254/options) and [actually on prod too with a newly registered dataset](https://www.checklistbank.org/dataset/168310/options) so I don't think the delimiter change is causing the issue and suspect it's an issue with the gbifkey change.

**Comment by yroskov** [comment]
As a result, we are not able to complete re-import of SFs checklists with fixed issue of missing extinct flag.

**Comment by gdower** [comment]
I also just tried enabling `gbif sync lock`, which didn't fix it, so I disabled it. Disabling it in clb sets the `gbif sync lock` key to false instead of empty, which might be okay.

**Comment by gdower** [comment]
The settings actually are not the same settings in the backend, but the settings render looking the same in the frontend. 

https://api.checklistbank.org/dataset/1061/settings
```
{
  "csv quote escape": "\\",
  "csv quote": "\"",
  "csv delimiter": "<TAB>",
  "gbif sync lock": false,
  "nomenclatural code": "zoological",
  "data format": "coldp",
  "distribution gazetteer": "text",
  "import frequency": "never"
}
```

https://api.dev.checklistbank.org/dataset/269254/settings
```
{
  "csv quote escape": "\\",
  "nomenclatural code": "zoological",
  "distribution gazetteer": "text",
  "import frequency": "never",
  "csv quote": "\"",
  "data format": "coldp",
  "csv delimiter": "\t"
}
```

**Comment by gdower** [comment]
Switching the `csv delimiter` from <TAB> to \t does indeed fix the issue. Did the backend used to convert <TAB> to \t or is the frontend wrongly saving the settings with <TAB> instead of \t?

**Comment by mdoering** [comment]
`<TAB>` was never used by the backend, I think it is just a UI thing to simplify the rendering.
Good it is working now. Did the logs not reveals this?

**Comment by mdoering** [comment]
Found these WARNings in logs:

> Setting CSV_DELIMITER must be a single character but got >><TAB><< instead. Ignore setting

I will make sure the settings validate a single character for the delimiter and quote char!

**Comment by mdoering** [comment]
A db query shows there are still some troublesome settings:

```
col=> select key, settings ->> 'csv delimiter', title, deleted from dataset where length((settings ->> 'csv delimiter')::text)>1;
 key  | ?column? |                               title                                | deleted 
------+----------+--------------------------------------------------------------------+---------
 1206 | \t       | World catalogue of the tribe Sepidiini (Tenebrionidae, Coleoptera) | 
 2317 | <TAB>    | 3i World Auchenorrhyncha Database                                  | 
 1198 | <TAB>    | Isoptera Species File                                              | 
(3 rows)
```

I will change the problematic ones to `\t` manually

**Comment by gdower** [comment]
Yeah, I found it in the logs.

Thanks! I was wondering how many datasets were set to <TAB>. Maybe there was a brief frontend bug several weeks back that put it in there. I'll fix those other three.

**Comment by mdoering** [comment]
Are the csv settings really needed for those archives? The reader usually does a good job finding them itself.
And having a `csv quote` setting for tab delimited files is not recommended in ColDP. We had issues before with WoRMS because of values starting with a double quote (a bad reference citation) which then caused several lines to be read as a single value until another double quote is found.
