### ISSUE TITLE
Diacritics issue in TDWG distributions

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1172]
There might be a diacritics corruption issue with TDWG distribution data in the backend, for example:

São Paulo is in the [backend](https://api.checklistbank.org/dataset/3LR/taxon/9H2WR/info) with a replacement character: [S�o Paulo](https://api.checklistbank.org/dataset/3LR/taxon/9H2WR/info)

The distribution data is provided in the TDWG standard from TaxonWorks:
```
10403	BZL-SP	BZL-SP	tdwg		60813	
10403	BZL-MG	BZL-MG	tdwg		60813	
```

It seems to be correct here:

https://github.com/CatalogueOfLife/backend/blob/77cb4e41466ec31164b8416d35b811d02bdc7b13/api/src/main/resources/vocab/area/tdwg/tblLevel4.txt#L98

But maybe it's getting imported into incorrectly?

**Comment by mdoering** [comment]
indeed wrongly read files, fixing...
