### ISSUE TITLE
Subgenera and combinations including subgenera should be italicised

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/backend#1176]
See example here of Arion (Arion) ater:

https://www.catalogueoflife.org/data/taxon/5W2WT

Example from StaphBase:

https://www.checklistbank.org/dataset/1204/taxon/706896

The subgenus and its parentheses should be italicised:

_Arion (Arion) ater_
_Acritus (Acritus)_
_Acritus (Acritus) fidjiensis_

**Comment by mdoering** [comment]
The html representation is generated by the backend
