### ISSUE TITLE
rank marker included in epithet

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1191]
The [Fulgoroidea](https://www.checklistbank.org/dataset/1011/about) synonym [Cerynia albata var. triscipta](http://api.checklistbank.org/dataset/3LR/nameusage/5GCP8) is included in COL releases with a rank marker in the epithet:

```
"name":{
"created":"2022-07-26T16:22:53.158638",
"createdBy":102,
"modified":"2022-07-26T16:22:53.158638",
"modifiedBy":102,
"datasetKey":9859,
"id":"6db4b2d9-265b-4a24-9e15-05b0d0b1ca39",
"sectorKey":589,
"namesIndexId":10535378,
"namesIndexType":"exact",
"scientificName":"Cerynia albata var. triscipta",
"authorship":"(Walker, 1858)",
"rank":"subspecies",
"genus":"Cerynia",
"specificEpithet":"albata",
"infraspecificEpithet":"var. triscipta",
"basionymAuthorship":{
"authors":[
"Walker",
],
"year":"1858",
},
"code":"zoological",
"origin":"source",
"type":"scientific",
"parsed":true,
}
``` 

How did the marker enter? The source contains [303 names with unusual character](https://www.checklistbank.org/dataset/1011/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=50&offset=0) issues that sometimes flag the dot from the markers. [C.albata var. triscipta](https://www.checklistbank.org/dataset/1011/name/27105) is also [one of them](https://www.checklistbank.org/dataset/1011/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=50&offset=0&q=Cerynia%20albata).

**Comment by mdoering** [comment]
This is an ACEF data issue with ["acef:InfraSpeciesEpithet":"var. triscipta"](https://api.checklistbank.org/dataset/1011/verbatim/49622) being 
[interpreted](https://api.checklistbank.org/dataset/1011/name/27105) wrongly.

Is this a correct usage of ACEF or should the rank not be given via acef:InfraSpeciesMarker="var." ?

**Comment by yroskov** [comment]
Just a comment: we are not able to get data from DBTNT databases (including FLOW) after switch to the CLB. FLOW update in June 2020 was experimental and unsuccessful. Ideally, it should not appear in production CoL.
