### ISSUE TITLE
Memory leak in indexing job

### ISSUE THREAD

**Issue by timrobertson100** [CatalogueOfLife/backend#1196]
Releasing the COL 23.1 failed, and investigation found a memory leak on the indexing stage.

Adjusting from `-Xmx 32G` to `-Xmx 31G` allowed the job to run (reduced the memory addressing length) but the memory graph shows as (see 08:40 to 09:20):

![image](https://user-images.githubusercontent.com/237221/216011423-f3991796-c42d-4309-87d6-6cdab143d1c5.png)

Note we're right at the limit of 31G so in a precarious state.

While this proceeds for now it needs to be addressed. I suggest we copy the DB and app and run the step with a profiler attached.

**Comment by timrobertson100** [comment]
I haven't got to the bottom of this, but suspect [this line in this commit](https://github.com/CatalogueOfLife/backend/commit/139f6ac0ddfaddeb2c2875c92700b25b4aa47716#diff-0252072973c72fa5f998059a686ba58e4b6de65a71ef6832db7c4b96aa8577e0R80) may have something to do with it - or something in this commit anyway.

Memory grows with this Hashmap cache as you would anticipate (note we're close to blowing memory though) but for some reason, it is not freed. The objects in this cache are themselves embedded in objects that extend MyBatis stuff and are handed over to the worker pool. I don't know MyBatis internals but perhaps something relating to them holding an internal reference (?) to a JDBC connection pool causes them to be overlooked for GC.

The version running was deployed on the 25th and I notice this whole area has subsequently changed on master to use MapDB anyway.

**Comment by timrobertson100** [comment]
I have captured a memory snapshot following an ITIS indexing run. I haven't had time to analyze it yet: 

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/237221/216342713-0536cd91-2dc0-40b7-82ad-c62cff488e26.png">

**Comment by timrobertson100** [comment]
Recording here so it's not lost - the commits above were deployed Tuesday afternoon:

![image](https://user-images.githubusercontent.com/237221/217459316-0aeb8e2c-3061-4084-a6eb-a18935e8dc00.png)

**Comment by mdoering** [comment]
I indexed 3 medium sized datasets up to 150k names and finally ITIS while profiling the app.
Memory was constantly low, so the fix did work:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/327505/217547261-c1ea24fa-947e-4a09-93a3-a7881b3e91f5.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/327505/217547037-48b6e050-07a7-43a0-a070-c3a6273716e1.png">

But it seems there is another issue maybe with syncs that leads to the memory increase seen before?
