### ISSUE TITLE
Filtering /dataset by nom code returns incomplete list

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1200]
There seems to be too few datasets returned when filtering by nom code:

https://api.checklistbank.org/dataset?code=botanical

For example, 1140 is not in the list and nom code is set:

https://api.checklistbank.org/dataset/1140/settings

**Comment by mdoering** [comment]
Unexpected indeed. But the code does look fine, investigating...

**Comment by mdoering** [comment]
https://api.checklistbank.org/dataset?code=botanical returns 41 datasets now!
