### ISSUE TITLE
Verbatim term and termOp

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1201]
The API documentation has term and termOp on the verbatim endpoint, but just FYI it doesn't look like it works and I don't see an open/closed issue for implementing it. It might indeed be useful to filter by term, but it seems low priority.

http://api.checklistbank.org/dataset/1141/verbatim?term=col:ReferenceID
http://api.checklistbank.org/dataset/1141/verbatim?term=col:ReferenceID&term=acef:ReferenceID&termOp=or

**Comment by mdoering** [comment]
It is a code bug. I will get this fixed soon
