### ISSUE TITLE
issue parameter not working on /dataset/{key}/reference

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1202]
It seems that the issue parameter may not work on the reference endpoint:

https://api.checklistbank.org/dataset/1140/reference?issue=unmatched%20reference%20brackets
https://api.checklistbank.org/dataset/1140/reference?issue=UNMATCHED_REFERENCE_BRACKETS

The above query returns 45602 records when the dataset should have 117 unmatched reference brackets according to the issues page:

https://www.checklistbank.org/dataset/1140/issues

**Comment by mdoering** [comment]
issues are linked to verbatim records and that seems to also return 117 recs:
https://api.checklistbank.org/dataset/1140/verbatim?issue=UNMATCHED_REFERENCE_BRACKETS

Clearly a bug
