### ISSUE TITLE
Java 8 date/time type `java.time.LocalDateTime` not supported by default

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1203]
If you don't set the accept header to application/json, you get a LocalDateTime error on /dataset/{key}/editor endpoint. I think this the only endpoint that requires setting the accept header, so it's probably a bug. 

For example, try these 2 queries replacing {TOKEN} with your token:

1) Doesn't work:

```
curl --request GET \
  --url https://api.checklistbank.org/dataset/3/editor \
  --header 'Authorization: Bearer {TOKEN}'
```

```
{
	"code": 400,
	"message": "Bad JSON argument",
	"details": "Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module \"com.fasterxml.jackson.datatype:jackson-datatype-jsr310\" to enable handling (through reference chain: java.util.ArrayList[0]->life.catalogue.api.model.User[\"lastLogin\"])"
}
```
  
2) Works:

```
curl --request GET \
  --url https://api.checklistbank.org/dataset/3/editor \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer {TOKEN}'
```

**Comment by mdoering** [comment]
when no explicit accept header was present the backend tried to return XML (maybe the default for curl?) which failed in this case.
