### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/backend#1204]
There was an error processing your request. It has been logged (ID 53cdf111dc1d9cea).

**Comment by DianRHR** [comment]
![image](https://user-images.githubusercontent.com/124217901/221282080-869bef86-b89b-483b-a906-45837ef973f6.png)

**Comment by mdoering** [comment]
found the reason, but still surprised you hit this. It just works for me.
@DianRHR can you please try again to create a project?

**Comment by DianRHR** [comment]
Ok ... I didn't want to find it though! 
Now it's working .. will try to continue . Thanks for fixing it.

**Comment by DianRHR** [comment]
Error didn't appear anymore
