### ISSUE TITLE
Filtering on broken=false

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1207]
Is setting broken=false supposed to filter out broken decisions/estimates?

https://api.checklistbank.org/dataset/9837/estimate?broken=false&offset=7&limit=2
https://api.checklistbank.org/dataset/3/decision?broken=false&limit=10&offset=1580

Both decision and estimate endpoints include broken records when broken is set to false. 

I'd assume not setting the broken parameter would give you both broken and unbroken.

**Comment by mdoering** [comment]
I think we only used it for filtering out broken ones with broken=true. The default is broken=false, there is no null. So it is either only broken or all. Guess it would have been better called `brokenOnly`
