### ISSUE TITLE
CLB: project options disappeared from the menu

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1209]
2023-03-17: there is no project options in my menu. I cannot access Assembly tools and others.

[Frontend version: fb5152b March 17, 2023 8:04 AM](https://github.com/CatalogueOfLife/checklistbank/tree/fb5152b)[Backend version: 53da770 March 15, 2023 12:00 AM](https://github.com/CatalogueOfLife/backend/tree/53da770)

![image](https://user-images.githubusercontent.com/28574252/225943381-c25a541a-d4b6-4d3f-8d26-035c6fb17317.png)

**Comment by mdoering** [comment]
please just search for the project and follow the link to the project

**Comment by mdoering** [comment]
See https://github.com/CatalogueOfLife/checklistbank/issues/1161

**Comment by yroskov** [comment]
Do you mean "search dataset"?

I do not see an option "search for the project"

**Comment by mdoering** [comment]
Give it a try for some time. We all find this way more convenient as it was with redundant and hidden menu items.

**Comment by yroskov** [comment]
I agree interface menu was redundant. 

Simple improvement should solve the current problem (not intuitive mix of datasets & projects under "Search datasets" item): menu should have two items: "**Search projects**" (incl. drop down a list of available projects in CLB) and "**Search datasets**".

"Dataset" and "Project" are two different entities.  CoL-draft as  a Project has many tools which are absent in the menu for "Dataset". As soon as CoL released as a fixed dataset, it moves to the category "Dataset".

**Comment by mdoering** [comment]
There are actually 3 entities called dataset origins: `external`, `project` and `release` datasets. 
You can filter them in the search as you need.

**Comment by yroskov** [comment]
Yes, 3 entities.

Could you pls give me a screenshot, showing where I can choose between project, external & release?

**Comment by mdoering** [comment]
<img width="1845" alt="image" src="https://user-images.githubusercontent.com/327505/225962875-3debb995-efc6-4f5a-a97d-bf7125a62ce8.png">

**Comment by mdoering** [comment]
And this is what the collapsed release list looks like: 
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/327505/225963092-65c48014-2e50-456f-936c-5458a4f52b78.png">

**Comment by yroskov** [comment]
Thanks! 

Such an unobvious implementation...
