### ISSUE TITLE
Merge, duplicate species is added due to a slight typo

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/backend#1222]
Hi @mdoering! I'm testing how merging regional lists will work, I also want to have a general idea of the number of species these lists can add to COL checklist.

I did a project merging ITIS Mammalia with the [Colombian Mammalian list ](https://www.checklistbank.org/dataset/31908/about) and I found a species that was added as an accepted species but it is due to a typo.

It is a one-letter typo  plus a difference on a space on the authorship:  S`i`lvilagus fulvescens J.A. Allen, 1912 vs  S`y`lvilagus fulvescens J.` `A. Allen, 1912. Interestingly the species name was placed under the correct genus.

See: Silvilagus fulvescens J.A. Allen, 1912 (project 9999)
<img width="484" alt="Captura de pantalla 2023-04-27 a la(s) 2 26 33 p m" src="https://user-images.githubusercontent.com/5700527/234970672-aae7294f-9de7-443b-a1b4-9a63df93810b.png">

There is a way for the Merge algorithm to detect these kinds of issues and avoid adding this "wrong" species? Maybe using the parent information plus slight variations of the authorship?

**Comment by mdoering** [comment]
Another option might be to have some settings for the merge sector that allows more lenient comparisons. That way we can use different strategies to merge sources of different quality. But that might lead to lots of curatorial work?

**Comment by mdoering** [comment]
Having an overview of the kind of typos to deal with would be good. Can we curate a simple list on this [wiki page](https://github.com/CatalogueOfLife/backend/wiki/Orthographic-Variants) please?

**Comment by mdoering** [comment]
Will be handled by a generic orthograühoc variation detection feature: https://github.com/CatalogueOfLife/backend/issues/1363
