### ISSUE TITLE
Problems with changing of name statuses for uninomials via decisions

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1224]
Seems, **we have a problem with application of decisions to uninomials.** 

(Ref. to 215 redundant families and above in the COL checklist https://github.com/CatalogueOfLife/data/issues/463#issuecomment-1540350635)

_Example:_

Subfamily **Acridinae Mivart, 1869** flagged as _provisionally accepted_ in ITIS@CLB:
![image](https://github.com/CatalogueOfLife/backend/assets/28574252/61a69313-37c9-4cdf-be56-1e01d5339648)

However, it appear as _accepted_ subfamily in CLB & in the final product:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/3d2a101a-3055-45bc-9713-f748b81e1b6f)

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/26c9f3e1-4478-48aa-a6e9-2b98b28bb34c)

and in Markus list:
![image](https://github.com/CatalogueOfLife/backend/assets/28574252/d79bd009-2b11-4b21-acc6-d438520d6fc9)

**Comment by mdoering** [comment]
It seems you did not sync the sector after you created the decision? Last sync of ITIS Amphibia is from 1st of May
https://www.checklistbank.org/catalogue/3/sector/sync?sectorKey=1506

The decision is from yesterday: https://www.checklistbank.org/catalogue/3/decision?limit=100&name=Acridinae&offset=0

PS: If you could keep links to the problem in checklistbank that would help a lot to more quickly figure out what is going on.
