### ISSUE TITLE
Source (GSD) field is missing in CSV export

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1225]
(...working with 215 redundant families and above in the COL checklist https://github.com/CatalogueOfLife/data/issues/463#issuecomment-1540350635)

Field with **Source** (GSD) name is  missing in CSV export.

GSD name is present in the CLB interface:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/fe493599-8bfc-421b-8c32-ef8ab6b21a5b)

But it is missing in CSV export:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/dea064a9-cc7c-4655-bae8-b89db7dcb9ce)

**Comment by yroskov** [comment]
This "small" loss makes export file useless for bug fixes.

**Comment by mdoering** [comment]
what is the CLB link please?

**Comment by mdoering** [comment]
There will be a new sourceDatasetKey column shortly
