### ISSUE TITLE
Unnecessary spaces in formatted authors in tree view downloads

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/backend#1229]
When I download a tree view for a zoological dataset, an extra space is inserted before the closing parenthesis around authorship if the year is enclosed in square brackets. See three cases in this example:

![image](https://github.com/CatalogueOfLife/backend/assets/26148454/205d7efa-0a78-4af2-ba65-5c94b43271d6)

**Comment by dhobern** [comment]
Sorry - it's also in browse views, etc.

![image](https://github.com/CatalogueOfLife/backend/assets/26148454/3439f011-ce50-48ed-9878-dce5cf69e61a)

**Comment by mdoering** [comment]
It was a bug that happened when you had 2 closing brackets, here ]), and whitespace is normalised in authorships to have a space after that. Should be fixed now in code and deployed soon
