### ISSUE TITLE
Subgenera are not merging in a project

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/backend#1230]
Hi @mdoering 
To let yoou kno that in the project [DHR_Chrysomelidae](https://www.dev.checklistbank.org/catalogue/10001/assembly)  I merged the dataset [24881 ](https://www.dev.checklistbank.org/dataset/24881/about), which includes subgenera, but they were not included in the project: 
![image](https://github.com/CatalogueOfLife/backend/assets/124217901/6770b174-130b-408c-834f-b5e8f0870064)

Even that I established to consider them in the characteristics of the sector: 
![image](https://github.com/CatalogueOfLife/backend/assets/124217901/cd25d745-c162-40da-b762-29d88174f1f0)

**Comment by mdoering** [comment]
Thanks, thats interesting. The syncs should also honour implicit subgenera in species names just as we create missing genera.

**Comment by mdoering** [comment]
The subgenus sync works fine if it is not called like the genus. Will try to make that work too...

**Comment by DianRHR** [comment]
I made the sync again and it's now working ... however .. another odditie came out, my project ow has two Chaetocnema subgenera: one with author and another without author, and the species nested under the one without author
![image](https://github.com/CatalogueOfLife/backend/assets/124217901/8369a8dd-9871-49d5-9e9e-018d93a67a27)

Weird thing because the original dataset doesn't have a subgenus without author. 
this happened once again after I told you at slack.

**Comment by mdoering** [comment]
I am not exactly sure whats going on. In my tests it is all fine.
I *think* this is because of an odd names index, so I am going to rebuild the index tonight.

**Comment by mdoering** [comment]
Looks like it works this time:

<img width="705" alt="image" src="https://github.com/CatalogueOfLife/backend/assets/327505/90f8d5c2-512c-4d8f-a02c-4aeadc5607a6">
