### ISSUE TITLE
Should GBIF datasets be removed from CLB if they are removed from GBIF?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1231]
GBIF checklist datasets are synced to ChecklistBank. Currently we do not remove them if they get deleted in GBIF.
Should we do this as part of a sync?

**Comment by mdoering** [comment]
@timrobertson100 @olafbanki I would think we should automatically remove them. A tombstone will still remain with the deletion date indicated. Any reasons not to?

**Comment by timrobertson100** [comment]
> I would think we should automatically remove them. Any reasons not to?

None I can think of. 
Keeping them could be problematic (e.g. misunderstood permission, sensitive data etc)

**Comment by mdoering** [comment]
k, Ill deploy the next version with deletion enabled then

**Comment by mdoering** [comment]
Fixed in https://github.com/CatalogueOfLife/backend/commit/55d60296389a17e8e7729bfd57b1e2241074d1da & https://github.com/CatalogueOfLife/backend/commit/c61e8aa129f7fd0978a27356c5aaa4fac4a5f89d

**Comment by olafbanki** [comment]
You already closed this issue. Just to let you know that I do agree. If a dataset has no place in GBIF, I do not see why it should remain in ChecklistBank. Do you however keep a log of what is being removed? It would be good that such a list if it occurs is managed somewhere, so someone can see the history of a data source.
