### ISSUE TITLE
Add ability to generate the RCC-5 DIFF report

### ISSUE THREAD

**Issue by timrobertson100** [CatalogueOfLife/backend#1234]
The [listtools](https://github.com/jar398/listtools) scripts are now able to generate RCC-5 reports that summarise the difference between two checklists, or subsets of checklists. 

We'd like to introduce this as an additional DIFF tool allowing users to run a report by selecting the two source datasets, root taxa and then downloading the CSV output (i.e. similar to other diff tools).

This will require an API to take the configuration from the front end, run the linux process, and present the output file. It would be nice to be able to access previous runs, so perhaps the directory structure might store the input and output configurations within a directory per user, or similar.

**Comment by mdoering** [comment]
I would probably integrate the request submission into the DatasetDiffResource similar to how a MatchingJob is submitted in NameUsageMatchingResource. And a new BackgroundJob subclass that does all the work.

**Comment by timrobertson100** [comment]
@beckettws and I are together and had a call with Nico and Jonathan @jar398, who has a new output report.
We (I) believe this would be useful for the comparison of changes within chosen sectors between monthly releases.

@mdoering and I should find time to get this API and UI integrated in 2023 and separately, we propose to find time to present the report to the xcol data managers.

CC @sternerlab

**Comment by jar398** [comment]
Just merged my 'gbif' branch to main at https://github.com/jar398/listtools , as this is the code that produced the spreadsheet Beckett showed this morning.  Up next for me: make it easy for you to run it on some CoL example.

**Comment by mjy** [comment]
On a related note this may be of interest if it's not on people's radar https://github.com/gnames/gndiff.

**Comment by jar398** [comment]
I fixed a few bugs and updated the documentation.  It could certainly bear some more testing (have only done COL mammals) but what's in the listtools repo is a "release candidate" in the sense that I am not aware of any reasons not to have others try it.

My test is Mammalia in COL 2019 (COL19) vs. COL 2023 (COL23.1). Output for this comparison is in the doc/ directory of the repo.

Let me know what you think.

**Comment by mdoering** [comment]
[integrated into the UI](https://www.checklistbank.org/tools/taxonomic-alignment) for some time
