### ISSUE TITLE
Name merge creates duplicates

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1235]
Both canonical & non canonical names duplicated by 2 merge sectors in a project (not release):

https://www.dev.checklistbank.org/catalogue/10018/assembly?assemblyTaxonKey=771718a0-96f1-40c8-bd3c-055a62f175e2

<img width="1403" alt="image" src="https://github.com/CatalogueOfLife/backend/assets/327505/a8ead6a4-5189-4e2f-a39a-03e6158dbc57">

**Comment by cristian-flavius** [comment]
I want to work on this issue

**Comment by mdoering** [comment]
fixed in latest release: https://www.checklistbank.org/dataset/304443/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Orthiopteris%20campylura&sortBy=taxonomic
