### ISSUE TITLE
Browse view does not respect sequenceIndex values

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/backend#1241]
The COLDP model allows for child taxa to be sequenced using natural integer order for values specified in the sequenceIndex property of the Taxon or NameUsage records.

ChecklistBank currently does not respect these values and continued to display children in alphabetical order.

An example - children of Amniota here have been given sequenceIndex values that should sort them as [ Sphenodontia, Testudines, Crocodylia, Squamata, Mammalia, Aves ] but they still appear in alphabetical order.

https://www.checklistbank.org/dataset/58312/classification?taxonKey=e07b1ca0-7f74-4423-a9e1-b388312843e2

Ability to sequence child taxa has been requested by members of the Taxonomy Group for this and similar cases.

**Comment by mdoering** [comment]
I have finally taken the time to work on the implementation (as well as other ColDP 1.1 related tasks, e.g. remarks all over and a TaxonProperty table). Here are the bird orders in a custom ordering:

https://www.dev.checklistbank.org/dataset/270357/classification

Not that I also adapted importing of TextTrees to preserve the ordering they come in, so this [aves.txtree](https://github.com/CatalogueOfLife/backend/files/13053284/aves.txt) file defines all ordinals implicitly for the birds.

**Comment by mdoering** [comment]
<img width="854" alt="image" src="https://github.com/CatalogueOfLife/backend/assets/327505/52339ef7-e932-49b1-9cfb-76eef15fdbcf">

will be deployed to prod on monday or tuesday
