### ISSUE TITLE
CLB: problem with login

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1257]
Every page which I open in a new tab, now requires login again.

If I refresh page in the browser (Firefox), CLB says "403 Sorry, you don't have access to this page" and asks for a login again.  

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/56f44fa8-12ed-4892-9951-eb542e6304bb)

Login button does not respond from the first attempt; two-three pushes needed. ...Actually, a single click is enough, but a button respond is very slow, takes ~8 seconds to process.

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/c199bcec-b13a-40be-a40d-970b16105aed)

**Comment by yroskov** [comment]
@mdoering, I am not sure whether it is a backend or frontend issue...

**Comment by yroskov** [comment]
The problem appeared today, 2023-09-08

**Comment by mdoering** [comment]
@yroskov I have apparently introduces this problem when I tried to assist @thomasstjerne in solving the problem of permissions to releases: https://github.com/CatalogueOfLife/checklistbank/issues/1268

Me and Thomas will try to find a solution quickly!

**Comment by yroskov** [comment]
@mdoering, the same problem exists for me today:

Been in CoL - SF Isoptera - Imports, trying to open Sectors in a new tab:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/2f51f739-e310-447b-874a-5ebaa2f31eec)

**Comment by mdoering** [comment]
And you cannot log in? Can you take a screenshot of the network resources in your browser while doing this?

**Comment by yroskov** [comment]
Cannot. Geoff directed me to make this screenshot:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/d36666f0-9a88-4db7-b893-198329832544)

**Comment by yroskov** [comment]
and this one:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/0ac3e5f7-24de-49f3-b3e4-d682d2efe1c4)

**Comment by mdoering** [comment]
sth with the loading of release keys to address https://github.com/CatalogueOfLife/checklistbank/issues/1268 wasnt working. I have reverted the change and login works now as usual again

**Comment by yroskov** [comment]
Yes, it works now. Thanks!
