### ISSUE TITLE
Add createdBy as a filter parameter to /importer

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1258]
Would it be possible to add a filter to the import queue for jobs createdBy a userID? If you are trying to check the status of an import, with all the automated imports in the queue, it's hard to find jobs that I actually created. Even trying to page through it is impossible because the queue pagination shifts with new jobs added faster than I can page through it. A filter for contributesTo=3 could also be potentially be useful, too, but maybe a userID filter would be easier to implement with it already being on the DatasetImport object.

https://api.checklistbank.org/importer?createdBy=103

https://api.checklistbank.org/importer?contributesTo=3

**Comment by mdoering** [comment]
contributesTo would be difficult, but user key should be doable and useful.
Also a search by datasetKey, but that is shown o the dataset import page already

**Comment by gdower** [comment]
I think createdBy would help a lot and contributesTo probably isn't necessary. I didn't realize you could do this:

https://api.checklistbank.org/importer?limit=10&offset=0&datasetKey=2144

But the frontend doesn't seem to take advantage of it yet:

https://www.checklistbank.org/imports?datasetKey=2144

**Comment by mdoering** [comment]
`createdBy` is implemented in the dataset search now: https://www.dev.checklistbank.org/dataset?createdBy=103
and also in the importer API: https://api.dev.checklistbank.org/importer?createdBy=103

to be deployed to prod on Monday

**Comment by gdower** [comment]
Awesome, thanks!
