### ISSUE TITLE
The exported file in coldp format has missing references for all names in synonym status

### ISSUE THREAD

**Issue by sergbolshakov** [CatalogueOfLife/backend#1270]
When working with the NameUsage file in the latest version of COL, I found that for all names in the synonym status there are no links to nomenclatural databases-sources of these names. At the same time, online, links are available at least for Bryonames (Tropicos) and Species Fungorum (on Index Fungorum) — https://www.checklistbank.org/dataset/272972/name/4a2f4d14-e255-4c55-a8a4-b5df5608bf6c or https://www.checklistbank.org/dataset/272972/name/fd3df3e9-bac4-4808-9907-f9333545f8e7. It looks as if there is a separate list of exported fields for synonyms, where the link field was omitted.

**Comment by mdoering** [comment]
In [my exports of genus Acacia](https://www.checklistbank.org/download/2b2095f4-5d1e-4039-ad83-dc973b13a1be) generated today I have values for nameReferenceID for synonyms like [Acacia accola](https://www.checklistbank.org/dataset/272972/name/827702b5-db4a-4dbe-9a4d-a955a274274b). But the reference id c2904010-2f85-46f1-a40b-a1a832ddbd84 is not present in the Reference.tsv nor Reference.json file (which btw wrongly has very little content, different from Reference.tsv). This seems to be an exporter bug I am hunting now.

**Comment by sergbolshakov** [comment]
What I meant was somewhat different, that for names in synonym status in the exported file the Link field is empty, even where it is present, as seen in ChecklistBank (examples above).
For World Wide Wattle, as you can see from the original archive, the link field for synonyms is not filled in (similar situation for many other sources - I wonder why?...) - for this particular name, the link could be like this http://worldwidewattle.com/speciesgallery/species-intro.php?id=-1034, but since it was empty in the source, everything is fine for this case.

**Comment by mdoering** [comment]
Also fixed the missing reference records for publishedIn with synonyms: https://github.com/CatalogueOfLife/backend/commit/44deb54afbc1015ce4cc9fd4cbaaf6f32f815361
