### ISSUE TITLE
Lepidoptera won't download

### ISSUE THREAD

**Issue by jlegind** [CatalogueOfLife/backend#1274]
I tried downloading Lepidoptera from the GBIF backbone twice last week (06-10 November 2023) and the attempt failed. Download key for the last attempt is: 8650dc59-7301-4508-87dc-1324a754be1b 

I did manage to get the service to download GBIF Plantae, but Lepidoptera ... no luck.

Best,
Jan Kristoffer Legind
Data manager, DaSSCo project NHMD

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/backend/commit/f7b095f0bf1572d99e019621fce1ec555a48e76b

will be deployed in a few hours
