### ISSUE TITLE
Can't set simple: false on exports

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1278]
@mdoering, I don't think [setting "simple":false works](https://github.com/CatalogueOfLife/checklistbank/issues/1321)? I tried:

POST https://api.checklistbank.org/dataset/168310/export
```JSON
{"format":"dwca","simple":false,"synonyms":true,"bareNames":false,"excel":false,"root":{"id":"891436"}}
```

And got a response of "[afa237de-331d-480d-9bb9-69296551e193](https://www.checklistbank.org/download/afa237de-331d-480d-9bb9-69296551e193)" which is still the SimpleDwcaExport.

The [logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/shy58osBOejCygyAhpZX?_g=(filters:!())&_a=(columns:!(level,logger_name,message),filters:!())) say this:

>Existing DWCA export afa237de-331d-480d-9bb9-69296551e193 found for request DWCA export of 168310 [excel=false, simple=false, synonyms=true, extinct=null, bareNames=false, root=891436]

Maybe that explains why I was able to get the full DWCA export for the GBIF Backbone but not other datasets if it's incorrectly matching to previous downloads possibly without taking the simple boolean into account?

**Comment by gdower** [comment]
I tried again sending simple: false as the first download request and then it works so it probably is incorrectly matching to previous downloads without taking the simple boolean into account:

https://www.checklistbank.org/download/f52c524d-4617-42d6-806b-651e7bccfc0c

**Comment by mdoering** [comment]
There was indeed a comparison missing which I have fixed now, while also changing simple to `extended` which is nicer to default to `false` now.

**Comment by mdoering** [comment]
@gdower can you try now again please with this?

>{"format":"dwca","extended":true,"synonyms":true,"bareNames":false,"root":{"id":"891436"}}

**Comment by gdower** [comment]
It works!
