### ISSUE TITLE
CLB: editorial decisions do not work

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1290]
I am assessing and resolving Issues for a new version of World Plants. 

Today, 2024-02-06, **I was not able to apply Complex decision** here:
https://www.checklistbank.org/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=multi%20word%20epithet&limit=100&offset=0
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c52e5094-a53c-4b1d-b416-de4d47d0c464)

Parsing of the name Gamanthera van der Werff was corrected ("van der Werff" is the author). 
However, applied decision was not shown in the interface. 

**Blocking decisions do not work here**:  
https://www.checklistbank.org/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=inconsistent%20name&limit=100&offset=0

All following names were blocked, but decisions are not shown in the interface:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/be788d2e-147f-465e-9aee-6974efd04fb9)
and
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/05b9c8fd-d446-42df-b140-e7ab8b877314)

**Comment by yroskov** [comment]
Another example from WWW:

**Attempt to block these names failed (code 400):**
https://www.checklistbank.org/catalogue/3/dataset/1162/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&nomstatus=manuscript&offset=0

**Comment by mdoering** [comment]
Case [Gamanthera van der Werff](https://www.checklistbank.org/dataset/1141/taxon/Laurales-Lauraceae-Licaria-Laurales-Lauraceae-Licaria-Gamanthera%20van%20der%20Werff):
 - a genus synonym which is wrongly parsed as a species and stored with rank=species

Your links above all have a filter with `nomstatus=manuscript` in the URL. Any idea where that is coming from?

With the status filter it obviously doesnt yield anything:
https://www.checklistbank.org/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=500&nomstatus=manuscript&offset=0&q=Gamanthera

But without it does:
https://www.checklistbank.org/catalogue/3/dataset/1141/workbench?q=Gamanthera
... but still without a decision, an API problem.

And @thomasstjerne I am unable to add any decision in the workbench as described here before: https://github.com/CatalogueOfLife/checklistbank/issues/1313#issuecomment-1829432583

The decision does exist though: https://www.checklistbank.org/catalogue/3/decision?limit=100&name=Gamanthera%20van%20der&offset=0&subjectDatasetKey=1141

**Comment by mdoering** [comment]
The workbench interface is driven by the ES search, not from the database like the duplicate search.
That means there can be data inconsistencies if sth fails and I suspect this is what we see here. The World Plants decision was stored in the database, but the ES search index was not updated properly.

I am reindexing WP as I type, lets see if that solves it.

**Comment by mdoering** [comment]
@gdower I have posted your parser config json to the API and it worked. It requires an ADMIN role to be able to modify the configs. As this doesnt happen often, could you just send me those configs to be added?

**Comment by mdoering** [comment]
reindexing solved it, decisions are now shown: https://www.checklistbank.org/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Gamanthera

**Comment by yroskov** [comment]
Thank you, @mdoering! 

That's all for now

**Comment by mdoering** [comment]
@yroskov @gdower I have reindexed the dataset.
In case you see this more often you should be able to `re-index` datasets yourself in the Options page of a dataset:
https://www.checklistbank.org/dataset/1166/options

**Comment by yroskov** [comment]
Thank you, @mdoering!

Working with SF Orthoptera, I met the same problem (all names here should get decision "Ignore" https://www.checklistbank.org/catalogue/3/dataset/1021/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=900&offset=0&q=supersp).

When I tried to re-index dataset, I got message **Request failed with status code 403 User not authorized.**

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/067d0c2b-4ac8-4d2d-adad-44b9bece7604)

**Comment by mdoering** [comment]
reindexed
