### ISSUE TITLE
CLB: broken TASKS?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1300]
Working with TASKS reports https://www.checklistbank.org/catalogue/3/dataset/1101/tasks for Systema Dipterorum (id 1101) today, I met problem with application and displaying decisions.

_For attention of @thomasstjerne & @mdoering_ 

_Case 1._ Applied decisions "ignore" were not shown in the interface (see screenshot below) after successful(?) application of these decisions in the reports _Identical tribe 0 of 37_. https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?catalogueKey=3&category=uninomial&limit=50&minSize=2&mode=STRICT&offset=0&rank=tribe&status=accepted&withDecision=false)
and in _Identical genus 0 of 62_ https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?catalogueKey=3&category=uninomial&limit=50&minSize=2&mode=STRICT&offset=0&rank=genus&status=accepted&withDecision=false 

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bebfea22-8f18-4f56-aa7c-74cdd1ffdd55)

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/878081e2-c402-42fc-ab40-3ce74cb1ac9d)

**Comment by yroskov** [comment]
_Case 2_ I have resolved all issues in [ACC-ACC species (different authors) 2 of 512](https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?_colCheck=c1), but TSKS panel didn't reflect this (still red, says "2 of 512")

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9953f537-3556-4f8e-a87f-0e13f631223b)

**Comment by yroskov** [comment]
@thomasstjerne, unfortunately, I have the same problem in TASKS: applied decisions are not shown in the report and in the TASKS panel. 

Today,I worked with [ACC-ACC species (same authors) 0 of 342](https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?_colCheck=c2) in Systema Dipterorum.

I applied decisions for at least 50 pairs, but they are not shown in the report: 

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3461618c-8638-4f76-acff-c5c6f86a2f39)

_ACC-ACC species (same authors) 0 of 342_ bar in TASKS panel does not show progress:
  
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b13f71eb-01c2-4886-a7cc-c8f0d3d88520)

This is a serious blockage of my work now - I don't know which names are already resolved, and which need further work.

**Comment by yroskov** [comment]
_Case 3_

I am applying decision "Ambiguous Synonym" in [ACC-SYN species (different accepted, different authors) 8 of 869](https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?_colCheck=c5)

...and getting back a list of errors. No progress in the bar:  

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/7886dd43-6e5a-40ed-9d89-bc2baef81d44)

I am applying decision "Ambiguous Synonym" in  [ACC-SYN species (different accepted, same authors) 0 of 77](https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?_colCheck=c6)

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/4447be89-f711-49d8-ab2d-478a58fc8e1c)

**Comment by yroskov** [comment]
_Case 3 B_

I am applying decision "Ambiguous Synonym" in [SYN-SYN species (different accepted, same authors) 0 of 53](https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?_colCheck=c12)
![image](https://github.com/CatalogueOfLife/backend/assets/28574252/f7e04828-6e69-4e14-9a77-63fe1099457b)

...all decisions successfully applied, report shown decisions:
![image](https://github.com/CatalogueOfLife/backend/assets/28574252/ebb10dc7-7f5d-4fb8-b9e6-aaed94957f80)

But, after window re-load in a browser, all decisions vanished in the interface:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/257b5f04-4d79-413a-8c24-8e524d47760d)

The bar in TASKS panel does not show a progress:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/d4d1e49a-fe05-4771-8b5e-c000841f49d8)

**Comment by mdoering** [comment]
If you want to know if decisions were actually created use the decision page to be sure.
There are a few ignore decisions on tribes including Aedini: 
https://www.checklistbank.org/catalogue/3/decision?limit=100&mode=ignore&offset=0&rank=tribe

It looks like another search index problem at first glance

**Comment by mdoering** [comment]
Well, the ignore tribe task seems perfectly fine now for me. 37/37 and green:
<img width="1435" alt="image" src="https://github.com/CatalogueOfLife/backend/assets/327505/1227f60c-606e-4004-8550-e5ec124762fc">

@yroskov is there still sth wrong? It might take some seconds to update the search index after a decision was applied

**Comment by mdoering** [comment]
Is this correct now?
[SYN-SYN species (different accepted, same authors) 44 of 53](https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?_colCheck=c12)

@thomasstjerne any idea why things might not show up quickly?

**Comment by thomasstjerne** [comment]
Not really. I don´t think the results are cached

**Comment by mdoering** [comment]
The genus duplicates report 61/62 and there is one genus [Tauroconopa](https://www.checklistbank.org/catalogue/3/dataset/1101/duplicates?catalogueKey=3&category=uninomial&limit=50&minSize=2&mode=STRICT&offset=0&rank=genus&status=accepted&withDecision=false) missing. Looking at decisions there is a broken one created 12th February:

https://www.checklistbank.org/catalogue/3/decision?limit=100&name=Tauroconopa&offset=0

Rematching fails as we have 2 identical genera and the original ID 1790251 is not used by these 2 any longer.
@gdower do all TW exports change identifiers or is this a unique Systema Dipterorum problem?

@thomasstjerne there is no option to manually relink a broken decision like we do for sectors. Could we port the same lookup maybe?

**Comment by mdoering** [comment]
Looking at the stored and broken block decisions I see there is no `parent` property given.
That would probably be the only way to disambiguate duplicates in these cases. @thomasstjerne can we store that for all duplicate decisions? It would allow the automatic rematching to find many more names.

And @yroskov, is block the right decision or would you not want the species underneath to be placed

this has 2 species:
https://www.checklistbank.org/dataset/1101/taxon/2697344

this has 5:
https://www.checklistbank.org/dataset/1101/taxon/2697360

Ignoring might be better, but then the species would end up under the family.
We might want a new decision to ignore the name and merge/union all descendants with another target taxon given. Well I suppose that is exactly what a sector does already. Do you block and create new sectors for all these blocked genera?

**Comment by gdower** [comment]
> @gdower do all TW exports change identifiers or is this a unique Systema Dipterorum problem?

This is unique to SD because it's not permanently imported into the production server yet, so it's IDs will still change until the final TW import.

**Comment by yroskov** [comment]
_Case 4_

I believe that I resolved Tasks for **Alucitoidea** (id 2207) 2024-03-17, but TASKS panel does not show results (3 bars are still yellow):
https://www.checklistbank.org/catalogue/3/dataset/2207/tasks

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/2d5f6d89-2ec2-4e79-8082-0a0fe8731dbb)

**Comment by mdoering** [comment]
All green here :)
<img width="1203" alt="image" src="https://github.com/CatalogueOfLife/backend/assets/327505/0ef7908c-6e5d-420d-84bd-c42e51a094c1">

Looks like unexpected caching somewhere

**Comment by mdoering** [comment]
@yroskov can you clear your browser cache or turn off the use of the browser cache?
Do you use Chrome?

**Comment by mdoering** [comment]
I think I know whats going on. 
@thomasstjerne the task count calls are not within the project but scoped around the source dataset - which we treat as not changing too quickly and cache for an hour at least in varnish. I might have to reroute the call through the project!

**Comment by mdoering** [comment]
@thomasstjerne I am setting up a new resource that exposes duplicates for sources in a project.
Instead of 
https://api.checklistbank.org/dataset/2207/duplicate/count?catalogueKey=3&category=uninomial&minSize=2&mode=STRICT&rank=order&status=accepted&withDecision=false

you can then use the following without the need to set the catalogueKey:
https://api.checklistbank.org/dataset/3/source/2207/duplicate/count?category=uninomial&minSize=2&mode=STRICT&rank=order&status=accepted&withDecision=false

**Comment by mdoering** [comment]
In fact I think we can remove the catalogueKey query parameter alltogether with that project source specific routing.

**Comment by mdoering** [comment]
@yroskov can you try again please? improved caching has been deployed

**Comment by yroskov** [comment]
Bingo! It works now: the panel shows me results of resolutions. (Checked with WCO (id2256) https://www.checklistbank.org/catalogue/3/dataset/2256/tasks).

Many thanks!
