### ISSUE TITLE
Logo endpoints not working?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1304]
When deleting a dataset logo, the backend gives a 200 status code, but doing a hard refresh of the metadata page still loads the deleted logo so it seems like the backend doesn't delete it. Uploading a new logo also returns a 201, but it doesn't seem to replace the image. Specifically we were trying on this page:

https://www.checklistbank.org/dataset/2130/about

**Comment by mdoering** [comment]
smells again like caching

**Comment by mdoering** [comment]
not deployed yet, will do that tomorrow

**Comment by gdower** [comment]
Thanks!
