### ISSUE TITLE
CLB: Unable to apply Complex Decisions

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1309]
_For @mdoering attention:_

Working with Unparsable Authorship (42 names) in SF Lygaeoidea (id 1173), I was no able to edit authorstrings (i.e. delete star symbol). All decisions which I applied are not shown in the report/interface here: 

https://www.checklistbank.org/catalogue/3/dataset/1173/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20authorship&limit=100&offset=0

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/677bc6c2-0f56-4873-b31a-b7c74f802f9b)

**Comment by yroskov** [comment]
FireFox console, if it may help:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/ce6327cb-4c2e-4723-9590-8faddd4e974d)

**Comment by mdoering** [comment]
The cached API call is URL: https://api.checklistbank.org/dataset/1173/nameusage/search?catalogueKey=3&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20authorship&limit=100&offset=0

the catalogueKey is the problem. When set I will make sure caching is off

**Comment by mdoering** [comment]
gonna be deployed in ~1h

**Comment by mdoering** [comment]
@yroskov sorry, its getting to late for today. The build still takes an hour. Doing this early tomorrow instead

**Comment by mdoering** [comment]
deployed and works for me

**Comment by yroskov** [comment]
Thank you, @mdoering ! It works for me too. But the fix caused another problem: **all 3 buttons "With decision", "Without decision" & "All" show now a list "Without decision"**

**Comment by mdoering** [comment]
Can you give me an example link where the same results are shown? The link above returns no results at all for me in all 3 cases. And if I remove the issue filter I get 3 different results for with/without/all decisions as expected:

https://www.checklistbank.org/catalogue/3/dataset/1173/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=100&offset=0

**Comment by yroskov** [comment]
"the same results are shown" means that all names now have got decisions. During my work, I have seen that list become shorter and shorter after application of decisions and window refresh - up to the 0 results. I would expect that list "With decision" will show all names with applied decisions, but today it was not happened - the same 0 results.

I'll put here a link to the same problem, as soon as I meet it again.
