### ISSUE TITLE
Add a metadata service for matching-ws

### ISSUE THREAD

**Issue by djtfmartin** [CatalogueOfLife/backend#1318]
It would be useful to provide a metadata service for the `matching-ws`. This service could report:
* The dataset in checklistbank that has been index, and the version
* git version info
* basic statistics on the service (number of taxa at different ranks etc)
* When the index was generated
* Index size on disk

**Comment by mdoering** [comment]
we should consider to extend the CLB model to hold that information. We do already track stats for specific versions, so these could be reused:

https://api.checklistbank.org/dataset/1010/import?limit=10

See compound `datasetKey` & `attempt` key
