### ISSUE TITLE
Problems with DOIs in the Citation

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1319]
[adrik29](https://github.com/adrik29) commented [May 10, 2024](https://github.com/CatalogueOfLife/testing/issues/13#issuecomment-2105214458): _I guess the DOI for the last version is broken._

**Comment by yroskov** [comment]
I have checked DOIs in few checklist metadata:
   
WCO https://doi.org/10.48580/dg4lg-4pt
WTaxa https://doi.org/10.48580/dfrdl-38v
3i Auchenorrhyncha https://doi.org/10.48580/dg4lg-4rx
GLI https://doi.org/10.48580/dg4lg-49xk

All shown "DOI Not Found" message:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c67a192c-fa04-4d28-a416-57ea61019c03)

**Comment by mdoering** [comment]
DOIs only work on published releases, but this seems to be the April release?
https://doi.org/10.48580/dg4lg

There indeed seems to be sth going wrong with those source DOIs

**Comment by yroskov** [comment]
Yes, I took them from https://www.catalogueoflife.org
