### ISSUE TITLE
Support generation of single index for multiple checklistbank datasets

### ISSUE THREAD

**Issue by djtfmartin** [CatalogueOfLife/backend#1323]
As an example, WoRMS is registered as multiple datasets in checklistbank.
We need to produce a single index/docker container combining these datasets.

**Comment by mdoering** [comment]
WoRMS does exist as a single dataset in CLB. The other ones are parts of WoRMS used by COL and we are trying to get away from that model and use the single dataset instead. I am not aware of any split datasets that we would need to combine. Without a single dataset key (int or UUID) it would be difficult to identify what the service is matching against.

**Comment by djtfmartin** [comment]
thanks @mdoering . Possibly nothing to do here then.
