### ISSUE TITLE
Portal (preview): Incorrect GSD version in the Source Datasets page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1333]
Preview release of 2024-06-21 (id [298708](https://www.checklistbank.org/dataset/298708/about)): 
**incorrect GSD version appears in the Source Datasets page** https://preview.catalogueoflife.org/data/source-datasets

The software now applied "Annual Checklist 2024" for all GSDs instead of individual versions of GSDs:
![image](https://github.com/CatalogueOfLife/portal/assets/28574252/30dbf9fe-7a56-4f5b-864a-3d4702c1804b)

Expected presentation:

![image](https://github.com/CatalogueOfLife/portal/assets/28574252/58bc0164-0208-48cd-9b5c-af974ba8585f)

**Comment by mdoering** [comment]
This is fixed in code and deployed, but the source metadata of a release is created at release time, so it still shows the same.
I have just started a new release to fix it

**Comment by mdoering** [comment]
looks fine again
<img width="1280" alt="image" src="https://github.com/CatalogueOfLife/backend/assets/327505/9b562169-2f67-4ac0-ac3f-34c50b387063">
