### ISSUE TITLE
subgenus atomised wrongly

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/backend#1335]
Subgenus are flagged as inconsistent names, can we unflag them allowing to have a non- monomial for the subgenus rank?

for example: https://www.checklistbank.org/dataset/298754/taxon/DF5YR

<img width="1088" alt="Captura de pantalla 2024-06-25 a la(s) 3 41 49 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/8df051de-33a3-4145-8393-e15e690ebc24">

**Comment by mdoering** [comment]
[This subgenus](https://api.checklistbank.org/dataset/298754/name/~30J4) at least is wrongly atomized:

```
"rank":"subgenus",
"scientificName":"Aglaostigma (Aglaostigma)",
"uninomial":"Aglaostigma (Aglaostigma)"
```

It should be like this:
```
"rank":"subgenus",
"scientificName":"Aglaostigma (Aglaostigma)",
"genus":"Aglaostigma"
"infragenericEpithet":"Aglaostigma"
```
See https://github.com/CatalogueOfLife/coldp/blob/master/docs/publishing-guide.md#infrageneric-names

So the flagging is correct. Let's find out how we got there

**Comment by mdoering** [comment]
It comes from here: https://www.checklistbank.org/dataset/290762/taxon/xP9L

which already has it wrong:
https://api.checklistbank.org/dataset/290762/taxon/xP9L

And that is programmatically created as its a denormalised origin. An importer bug then.

**Comment by mdoering** [comment]
fixed in https://github.com/CatalogueOfLife/backend/commit/ce1778df1ba04f6a85c810daea0fc916121463bb
