### ISSUE TITLE
Portal: missing CoL portion in GSD citations on the page Recommended Citations

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1339]
Recommended citations for GSDs on this page of the portal https://www.catalogueoflife.org/about/colusage#recommended-citations **do not include Catalogue of Life portion**. 

It would be better if the citation style on this page matches the citation style on the GSD page (e.g. https://www.catalogueoflife.org/data/dataset/1161)

Brinda, J. C., & Atwood, J. J. (2024). Bryophyte Nomenclator (14 May 2024). https://doi.org/10.48580/dg6lk-8zmp

vs

Brinda, J. C., & Atwood, J. J. (2024). Bryophyte Nomenclator (version 14 May 2024). _In O. Bánki, Y. Roskov, M. Döring, G. Ower, D. R. Hernández Robles, C. A. Plata Corredor, T. Stjernegaard Jeppesen, A. Örn, L. Vandepitte, D. Hobern, P. Schalk, R. E. DeWalt, K. Ma, J. Miller, T. Orrell, R. Aalbu, J. Abbott, R. Adlard, C. Aedo, et al., Catalogue of Life (Annual Checklist 2024). Catalogue of Life, Amsterdam, Netherlands._ https://doi.org/10.48580/dg6lk-8zmp

![image](https://github.com/CatalogueOfLife/portal/assets/28574252/e6f6e0a0-b694-49d8-a618-9e891b34dd21)

**Comment by mdoering** [comment]
fixed now on prod
