### ISSUE TITLE
xrelase failed or cancel email notification

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/backend#1352]
### Description

I suggest to create an email notification when the xrelease fails o get cancels, similar to the one is sent when the xrelease is ready.

<img width="889" alt="Captura de pantalla 2024-09-09 a la(s) 7 37 19 a m" src="https://github.com/user-attachments/assets/39cf91b8-5e96-4769-b89d-741427fcb47f">

**Comment by mdoering** [comment]
Indeed we were missing email templates. I have added them now, so success, cancel or failed (x)releases should be announced via email now.
That is once deployed to prod.
