### ISSUE TITLE
All results in /nidx/match with rank unranked?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1362]
It seems like all names in /nidx/match have rank unranked and they were ranked the last time I ran API tests:

https://api.checklistbank.org/nidx/match?q=Animalia
https://api.checklistbank.org/nidx/match?q=Orthoptera
https://api.checklistbank.org/nidx/match?q=Alces%20alces
https://api.checklistbank.org/nidx/match?q=Pericycos%20philippinensis
https://api.checklistbank.org/nidx/match?q=Pericycos%20philippinensis
https://api.checklistbank.org/nidx/match?q=Pongo%20pygmaeus

If we don't use /nidx/match rank field anywhere then it might not matter all that much. I'm removing it from my tests.

**Comment by mdoering** [comment]
That must have been some time ago, but it is correct.
The canonical nidx entries all have no authorship nor rank.
Just the qualified ones come with both.

https://api.checklistbank.org/nidx/match?q=Animalia&rank=kingdom
