### ISSUE TITLE
merge Dataset search fails for some checklists

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/backend#1364]
### Description

The dataset [Lista taxonómica de las especies de equinodermos de México](https://www.checklistbank.org/catalogue/3/dataset/5552/metadata) contributes [ 163 names](https://www.checklistbank.org/dataset/304443/source/5552) to the xrelease, but is not possible to reach these names vía the dateset search, only by directly editing the url.

This issues comes and goes, in every release there are  different datasets that present this problem

<img width="681" alt="Captura de pantalla 2024-10-17 a la(s) 1 35 07 p m" src="https://github.com/user-attachments/assets/e1313c42-5668-435a-aeda-eb6517d8c9a2">

**Comment by mdoering** [comment]
Looks like there is an issue with non ascii characters in the search:

https://api.checklistbank.org/dataset/3/source/suggest?merge=true&q=Lista%20taxonomica%20de%20las%20especies%20de%20equinodermos%20de

https://api.checklistbank.org/dataset/3/source/suggest?merge=true&q=Lista%20taxonómica%20de%20las%20especies%20de%20equinodermos%20de
