### ISSUE TITLE
Unite dataset imported in CLB lacks Higher taxonomy

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/backend#1373]
Unite dataset imported in CLB lacks Higher taxonomy, this issue appeared on the latest version of the dataset on CLB, the GBIF source doesn't have this problem 

Example Sh0887892.09fu

On CLB lost classification: https://www.checklistbank.org/dataset/30477/taxon/SH0887892.09FU
On UNITE with classification: https://unite.ut.ee/bl_forw_sh.php?sh_name=SH0887892.09FU#fndtn-panel2
On GBIF with classification: https://www.gbif.org/species/201763784

**Comment by mdoering** [comment]
Fix deployed and new import running, let's see

**Comment by mdoering** [comment]
All the issues are gone and the classification is back again:
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/2a4f10cf-1a77-4ad2-ba4f-5a495064431e">
