### ISSUE TITLE
Exclude vernacular names from search response?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#200]
Should we exclude the vernaculars if the search was not targetting vernacular names? They can be quite big and I doubt they are used in the UI unless the match was a vernacular name. @thomasstjerne ?

**Comment by ayco-at-naturalis** [comment]
We could include an "includeFields" or "excludeFields" field in the search request

**Comment by mdoering** [comment]
there is already a content field which I wonder we could use as is:
https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/org/col/api/search/NameSearchRequest.java#L22

**Comment by ayco-at-naturalis** [comment]
But is this not to direct the q search? Is it not imaginable that you want to search for name usages matching whatever type of name, but you're not interested in having the vernacular names returned?

**Comment by mdoering** [comment]
imaginable yes, but not sure if @thomasstjerne needs that. I don't have a strong opinion really on this

**Comment by ayco-at-naturalis** [comment]
I will leave this one for now

**Comment by mdoering** [comment]
I have removed all vernacular names from the search results for now as we dont seem to use them. Can make that configureable later again once needed. Searching for them still makes sense and is used!
