### ISSUE TITLE
Allow download of taxon groups

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#219]
The current CoL interface provides a dwca download service for higher taxa and their entire descendants subtree, optionally including synonyms, common names, distributions and linked references: http://www.catalogueoflife.org/DCA_Export/

The Clearinghouse should provide sth very similar, but integrated into the main UI. On every taxon page it should be possible to download the taxon and all its descendants, optionally restricted down to a certain rank (e.g. all Animalia but only down to family). Options to include synonyms, linked references, distributions, descriptions, media and vernacular names should be provided.

[ColDP](https://github.com/Sp2000/coldp) is most suited as the download format.
Consider a [recursive CTE query](http://gbif.blogspot.com/2012/06/taxonomic-trees-in-postgresql.html) for the taxa, remembering all visited taxon ids and ref ids (publishedIn) which then later can be used to populate the optional synonyms, common names, etc

**Comment by Australis86** [comment]
Has any progress been made on this? I note that the DCA Export previously provided has been removed and I can't see an option for this in the public API documentation.

**Comment by mdoering** [comment]
Yes we have made quite some progress, but not completed this.
The idea is that there is an asynchronous export of an entire dataset or a part of it by defining optional filters with
 - a root taxon to only consider the subtree
 - rank filter to exclude any taxa of ranks below that (so you can get kingdom-family only, or just genera in families)
 - exclude synonyms

This is available now for DwC-A and some simple JSON & [TextTree](https://github.com/gbif/text-tree/blob/master/README.md) formats

The DwC-A exports is waiting for our next deploy to prod in the next days

**Comment by Australis86** [comment]
Great, thanks for the update.

Would you be able to point me in the right direction as to where in the API the DwC-A exports will become available?

**Comment by mdoering** [comment]
Sure. I'll use 3LR (latest release of COL) as the dataset key in my examples here:

**Asynchronous API methods**

There is a single export resource to trigger the build of an asynchronous export by POSTing an export request:

```
curl -s -X POST --data-binary '{"format":"DWCA", "taxonID":"6224G", "exclusions": ["VS"], "minRank":"GENUS"}' "https://api.catalogueoflife.org/dataset/3LR/export"
```

This will return the UUID key for the export to be generated.

The request object has these props right now:
 - `format`: DWCA, ACEF (COLDP, TEXT_TREE shortly)
 - `taxonID`: root taxon id
 - `exclusions`: array of taxon ids and its descendants to exclude from the export, i.e. above call excludes order Carnivora from the Mammalia export
 - synonyms: true/false, defaults to true i.e. they are included
 - minRank: a lowest rank to still include. In above request only genera and above are included, but no species or below


You will then be able to download the export at:
`GET   /export/{exportKey}`


For non project datasets that have been imported (not COL, but all its sources) you can also download the original archive:
```
curl -s -H "Accept: application/zip" https://api.catalogueoflife.org/dataset/1010/export
```

**Synchronous API methods**
There is also a synchronous "export" method that returns simple results directly either in JSON, HTML or TextTree.
That requires to request a single root taxon as the idea is to just use it for smaller subtrees:

```
curl -s -H "Accept: application/json" https://api.catalogueoflife.org/dataset/3LR/export/6224G
curl -s -H "Accept: text/html" https://api.catalogueoflife.org/dataset/3LR/export/6224G
curl -s -H "Accept: text/plain" https://api.catalogueoflife.org/dataset/3LR/export/6224G
```

I just realise we have an [issue with our varnish cache and Accept headers](https://github.com/CatalogueOfLife/deploy/issues/14), so you'll probably only see JSON for above requests. You can also force the Accept header using the `accept ` parameter, which works fine with caching already now:

```
curl -s "https://api.catalogueoflife.org/dataset/3LR/export/6224G?accept=json"
curl -s "https://api.catalogueoflife.org/dataset/3LR/export/6224G?accept=html"
curl -s "https://api.catalogueoflife.org/dataset/3LR/export/6224G?accept=plain"
```


See also https://github.com/CatalogueOfLife/portal/issues/77 for integration into the portal UI

**Comment by Australis86** [comment]
Thanks for taking the time to explain that, Markus - I think that's exactly what I'll need for my project.

**Comment by Australis86** [comment]
Sorry, I need a bit more help, please.

How do I find the taxon ID? It doesn't appear to be one the fields returned when I do a search using `/dataset/{key}/nameuseage/search`. Also somewhat confusing is that the API documentation says that the taxon ID is a 32-bit integer (under `/dataset/{key}/taxon/`), but many of them appear to be hex strings.

**Comment by mdoering** [comment]
The taxonID is the content of the `id` field in a Taxon record - which is a NameUsage record with status=accepted or doubtfully accepted.

You can find it in the search `http://api.catalogueoflife.org/dataset/3LR/nameusage/search` under `result[].id` which in turn is a copy of `result[].usage.id`

**Comment by mdoering** [comment]
The `{key}` parameter is the datasetKey, which is an integer indeed.
With the undocumented exception of the magic `LR` suffix that replaces a project datasetKey to the datasetKey of its latest release. So `datasetKey=3` refers to the COL project (the COL draft that is actively edited and can be in an inconsistent state); `3LR` then refers to its latest release, currently datasetKey=2242:

http://api.catalogueoflife.org/dataset/3LR

**Comment by Australis86** [comment]
Thanks for the explanations, Markus. I misread the API documentation mixed up the dataset key and taxon ID datatypes - my apologies.

Regarding the taxon ID field, I wondered one of the IDs in the JSON response from nameusage might be the right one, but none matched up with what I saw on the web interface. For example, looking at the genus entry for [i]Paphiopedilum[/i] on the COL website suggests a taxon ID of 6DFD:

https://www.catalogueoflife.org/data/taxon/6DFD

Whereas the API returns:

```
curl -X GET "https://api.catalogueoflife.org/dataset/3LR/nameusage/search?q=Paphiopedilum&minRank=GENUS&maxRank=GENUS&offset=0&limit=10" -H  "accept: application/json"

200830f2-e5ed-4171-b66c-a85b1399b250
```

If I then use this ID in the synchronous request, though, it returns an empty array:

```
curl -s -H "Accept: application/json" https://api.catalogueoflife.org/dataset/3LR/export/200830f2-e5ed-4171-b66c-a85b1399b250
[]
```

Have I missed something here? From the API documentation it looks like I need to send a POST query instead with a user key.

I haven't yet tested the asychronous export.

**Comment by mdoering** [comment]
We indeed change identifiers during the release of a project to ensure we have stable ids that do not change.
The project uses temporary UUIDs whereas all COL releases use short keys like 6DFD.

The UUID in the search results is for the _name_ though, the usage.id is 6DFD. We might change the name ids in the future to, but in general a _Name.ID_ is not the same as a _NameUsage.ID_ (which is the union of all _Taxon.ID_ and _Synonym.ID_s)

**Comment by Australis86** [comment]
Thanks for the clarification. I am making progress but have run into an issue with the asynchronous export.

I can successfully obtain the export key, but when I try to `GET` the archive from `https://api.catalogueoflife.org/export/{key}` using curl or Python requests, I receive a HTTP 406 error. However, pasting the URL into my browser (Firefox) works fine. I'm guessing there's a header I'm missing somewhere?

```
curl -X GET "https://api.catalogueoflife.org/export/{key}"
{"code":406,"message":"HTTP 406 Not Acceptable"}
```

and

```
r = session.get(export_retrieve_url, auth=HTTPBasicAuth(username, password), headers={"Accept": "application/zip"}, stream=True)
print(r.status_code)
406
```

As an aside, the POST query to `/dataset/{key}/export` doesn't work for the magic value 3LR. I found I had to extract the datasetKey from the `usage` data returned in the `namesearch` results.

**Comment by mdoering** [comment]
Several things to note:

 - the `/export/{key}` route is basically a redirect to https://download.catalogueoflife.org/exports/ which you can also access directly. Keys are grouped into folders by their first characters.
 - A 406 error means you are requesting the wrong content type via an "Accept" header. In case its missing the API defaults to application/json, which in this case is wrong as you want a zipped, binary archive. I will try to change the API to not default to json in this case and also allow for `application/zip`. Currently should need to add this header: "Accept: application/octet-stream"

**Comment by Australis86** [comment]
Thanks Markus! Just tested it with the application/octet-stream header and it works (somehow I missed that that was on the API documentation). If you can change the default, that would be great.

**Comment by Australis86** [comment]
Hi again,

I've noticed that even if I set synonyms=True when requesting a DwC-A export, there aren't any listed in the exported data.

```
data = {"format":"DWCA", "taxonID":taxonID, "synonyms": True}
r = session.post(export_request_url, auth=HTTPBasicAuth(username, password), data=json.dumps(data), headers={"Content-Type": "application/json"})
```

In this case I tried with the genus [i]Cymbidium[/i] and no synonyms were returned, only the accepted names.

**Comment by mdoering** [comment]
No Cymbidium species seems to have any synonym in COL, that might be the simple reason.
Have you tried others where they are known to exist, e.g. genus [Aganisia](https://www.catalogueoflife.org/data/taxon/QHV)

**Comment by Australis86** [comment]
Thanks Markus; you're right, the synonyms are displaying correctly for _Aganisia_.

That is exceptionally odd that there are no synonyms for _Cymbidium_ in the COL; there used to be (they are still listed at the source dataset - KEW WSCP) and there are certainly still some in common use! I'll have to contact COL support about it and see if that was intentional.

**Comment by mdoering** [comment]
Yes, lets file an issue for COL. You can best do this by creating an issue in the data repository:
https://github.com/CatalogueOfLife/data/issues/new/choose

**Comment by mdoering** [comment]
I just created an issue: https://github.com/CatalogueOfLife/data/issues/229
add to it if you have more insight

**Comment by Australis86** [comment]
Thanks Markus. I'll do that instead.
