### ISSUE TITLE
Create stable ids during CoL release

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#222]
We use temporary UUIDs as identifiers for newly created name, taxon and references in the draft CoL.
These should be converted to [proper stable ids](https://github.com/CatalogueOfLife/backend/issues/491) and the draft subsequently updated when the CoL is released. This allows drastic changes in the draft to happen without the need to maintain all the identifiers that were only ephemeral.

**Comment by mdoering** [comment]
temporary name ids should be replaced by their names index id and if duplicates exist by appending a sequence suffix `-x`.

Stability of the names should be via the names index id, i.e name matching. In case of duplicates, e.g. orthographic name variations caught by the name matching, the exact canonical name should be compared.

**Comment by mdoering** [comment]
We should immediately try to make use of the [protonym or set of protonyms as the base for the stable id](https://github.com/CatalogueOfLife/general/issues/6#issuecomment-679913548). Otherwise ids will change again rather soon.

Synonyms do not need to have stable ids, so they can continue to use unstable UUIDs that change whenever their sector is synced again. That should free us from most legitimate duplicate names, as the same name should never be properly accepted twice in the CoL. In case of provisionally accepted names we can treat them similar to synonyms and keep their unstable UUID.

Due to manual editing there still might be duplicates though. We could check for duplicates in the very beginning and fail such a release very early, requiring accepted duplicates to be fixed first. @yroskov does that make sense?

**Comment by mdoering** [comment]
We decided to implement name based identifiers for now, no taxon ids.
As long as the name string is unique this is straight forward.

For homonyms or names very much alike we must provide a deterministic rule that selects a stable id based on all previous releases. This can happen due to real homonyms, erroneous duplicates in the data or potentially extensive pro parte synonyms as we have now for some genera like `Achorutini Börner, C, 1901`.

 - we should avoid a major status change from accepted/synonym. Propose to require an ID change if the status changes even if the name is the same
 - for synonyms we should tie the ID also to the accepted names ID. Propose to change the synonym ID in case the accepted parent changes. This helps to deal with ids for pro parte synonyms. But we could also restrict this to ambiguous synonyms only.

**Comment by yroskov** [comment]
> But we could also restrict this to ambiguous synonyms only.

Not all "duplicated synonyms" might be identified in CoL and flagged as Ambiguous Synonyms.

**Comment by mdoering** [comment]
Yes, thats why I tend to prefer to always take the accepted name into account for all synonyms. If the accepted name changes all its synonyms would also get a new ID even if the name is still the same. Is this reasonable? @dhobern @thomasstjerne any strong opinion?

Alternatively we could ignore the accepted names of synonyms that only exist once and only look at the accepted name in case we have at least 2 synonym usages of the name - regardless the reason (true pro parte synonyms, erroneous duplicates, etc).

**Comment by dhobern** [comment]
Thanks @mdoering I think this is very reasonable.

For accepted names, it makes sense for us to treat them as "the same name" and for them to maintain the same id no matter how they are moved around the classification. 

For names treated as synonyms, there is a real and significant change if they get moved to become the synonym of a different name from previously. The same is true if a previously accepted name comes to be seen as a synonym and vice versa.

So different identifiers for each seems a fair reflection of their roles in this system.

In reality, we probably need three tiers of identifiers:

1. Names in the nomenclatural sense (but we have difficulty recognising them when homonyms are in play.
2. Names in their placement within a classification - as synonyms of X or children of Y, etc.
3. Concepts as delineated sets of 2.

**Comment by mdoering** [comment]
@dhobern @yroskov @olafbanki @timrobertson100 I'd like to review the design decisions above which we put into production a year ago. Looking at the stable ids report we create for every release, e.g. january 2022, the vast majority of names that have changed identifiers are synonyms with a different parent. This causes dead links for people storing the COL ID with every release. We can provide better ways for them to keep up to date, but I do wonder if we make it harder than necessary.

The current system is a hybrid of name & taxon identifiers really. I wonder if it would be better if we sticked to just name ids, keeping the id stable as long as we deal with the same name. The parent would matter for "duplicates" like true or false homonyms and pro parte synonyms only.

We only show the latest version of the COL checklist in the main portal. Keeping those ids as stable as possible seems wise to me. If people want an immutable response to their identifiers, they can simply keep the datasetKey of the release they accessed the checklist. The combination of datasetKey and COL ID is immutable and will return exactly what was there (we still need to [handle deleted monthly releases](https://github.com/CatalogueOfLife/backend/issues/1083) though).

So with that in place there is the option to have immutable data as well as more stable name ids. With at some point coming [taxon concept ids](https://github.com/CatalogueOfLife/general/issues/6) we could have another set of ids that provide even more stability even if names change. The user then has various choices for their needs.

**Comment by dhobern** [comment]
Quick thoughts. 

Ensuring stability of name identifiers is a clear and well defined priority. It should be possible at any to ask "Where is this name now treated in COL?" This should be true even if the treatment has changed radically. Pro parte synonyms and edge cases around name identity make this harder but it should be clear in most cases. 

However, if these names then serve as indestructible atoms, there is no easy way to tell when they have changed (new parent/synonymy). I can see two routes to address this, these being different representations of the same information.

You could manage identifiers for the graph edges that represent is-child-of and is-synonym-of. Our "taxon concepts" are really just bundles of these. This would mean that almost all names in COL would be associated with two identifiers, the identifier for the name itself and an identifier that gives its position in the COL classification. The identifiers would separately track name-details and name-placement. Different users could see benefit in using either or both according to their needs.

Alternatively, you could conceive the same information as a log of changing placements associated with each name. In essence, these become child records that record the placement history. The most recent record indicates current placement and all former configurations can be calculated from selecting the placements from a particular timepoint.

I think the latter may be conceptually simpler and very powerful.

**Comment by yroskov** [comment]
@mdoering, as I can see, your proposal is close to the idea of taxon LSIDs in CoL and **LSID Resolver** proposed by the Cardiff team (White & Jones). They tried to set up a name resolution inside a line of consequent editions of the CoL. You may ask them which barriers they met.

**Comment by mdoering** [comment]
At had hoped to get some feedback to the concrete proposal at hand to simply remove the two sources of changing ids currently:

> 1. we should avoid a major status change from accepted/synonym. Propose to require an ID change if the status changes even if the name is the same
> 2. for synonyms we should tie the ID also to the accepted names ID. Propose to change the synonym ID in case the accepted parent changes. This helps to deal with ids for pro parte synonyms. But we could also restrict this to ambiguous synonyms only.

... seen in the light of:
 - this being the nameID, for now also being used as the taxonID
 - having a proper basionym/type based taxonID in the future similar to an AvibaseID
 - keeping immutable versions in discrete releases that can be referenced if needed
 - being able to resolve any taxonID issued to the latest use even if they are now deleted

I guess my main question is, who or which use cases benefit from having number 1+2 above?

**Comment by dhobern** [comment]
Sorry @mdoering, I think my response was an attempt to answer this, but maybe it was really just a completely separate suggestion.

I don't completely understand how to respond to your question.

Are you proposing that a change only in the accepted/synonym status for a name (all name-specific metadata is unchanged) **should** or **should not** result in a different name id?

Stable name identifiers (regardless of placement) make sense to me as one necessary component.

Identifiers that change when a name is moved to a new parent or new/deleted synonymy also make sense - for a different set of use cases. These are probably as much as I think we need to model of species concepts in COL at this time. 

The first is necessary to locate where a name is now handled.

The second is necessary to determine whether and when the classification/synonymy changes.

Neither is a replacement for the other. One may be easier to implement and promote at this stage.

**Comment by mdoering** [comment]
We have in production now for one year stable ids based on the name BUT
 - enforce a change when the status changes
 - the accepted name of a synonym changes

See [this post describes](https://www.catalogueoflife.org/2021/04/14/stable-ids).

I am proposing to remove the above reasons for triggering ID changes and just keep ids stable if the name is the same. This leads to more stable ids and is much simpler to explain to users. Btw, how we manage COL IDs is a number one helpdesk question and people don't find that blog post. @chantalhuijbers we should explain identifiers in a separate section in https://www.catalogueoflife.org/about/colusage.

The API returns separate ids for the name and taxon/synonym (name usage), but we really only expose the taxonID to users. This probably needs to change so both are available, but I would have thought we do that once we have proper taxonIDs based on concepts looking at the _synonymy and children_, not the classification (aka [Thierry](https://github.com/CatalogueOfLife/general/issues/6#issuecomment-300236121)). These taxonIDs would stay the same if the accepted name or classification changes, as long as they still include the same organisms largely defined by the set of type specimens included. This is what we intended to do `[early on](https://github.com/CatalogueOfLife/general/issues/6#issuecomment-421997604)`, what @deepreef and @dremsen are designing for some time and is close to [AvibaseID](https://github.com/Sp2000/colplus/files/987182/Avibase.pdf)s. It fullfills the use cases of anything that needs identifications, e.g. specimens as it can deal with name changes and evolving taxonomies.

Question for now is: do we continue with this hybrid taxonID that is neither a name nor a good taxonID or should we replace it with a pure nameID that we'll need in any case?

**Comment by timrobertson100** [comment]
Since you tagged me above, I don't anticipate those changes causing an issue with GBIF occurrence record processing. We reprocess all data when a new taxonomy is released to bring consistency. That process uses names and not IDs so won't be affected.

**Comment by dhobern** [comment]
Thanks - on the given description, I would agree the priority should be to stabilise the name identifier (independently of changes in how the name is interpreted). We can adding mechanisms later for capturing other aspects. So I would agree that we can drop the hybrid taxonID.
