### ISSUE TITLE
Offer alphabetical index to search results

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#236]
An alphabetical index to name search results is very useful for larger resultsets. It is rather difficult to implement though without knowing the entire resultset in advance. If the sorting strictly is alphabetical we should be able to use a new search index field with just the first scientificName char and facet counts on it as the index for the paging offset.

**Comment by mdoering** [comment]
This should allow us to provide an alphabetical index to name search paging like you can see at the top here:

![screenshot-1](https://user-images.githubusercontent.com/327505/57534661-d5962980-7340-11e9-8671-c2fd544d511f.png)

**Comment by mdoering** [comment]
For the backend this means a new field `alphaindex` in ES that gets populated with the first upper cases char from the scientificName. We then add a new NameSearchParameter.ALPHAINDEX and expose this field as facet counts (to calculate the offset clientside) and for search filters.

**Comment by ayco-at-naturalis** [comment]
Implemented but now with extra unit tests

**Comment by mdoering** [comment]
Great! @thomasstjerne if you are bored this is a nice alternative to visualize searches

**Comment by mdoering** [comment]
Example prod query: https://api.checklistbank.org/dataset/3LR/nameusage/search?rank=GENUS&sortBy=NAME&alphaindex=d
