### ISSUE TITLE
Search index: Duplicate rows in search result

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#360]
https://dev.col.plus/dataset/1008/workbench?facet=rank&facet=issue&facet=status&issue=unparsable%20authorship&limit=50&offset=0

**Comment by mdoering** [comment]
Indeed the same usage `Rep-S-20350` multiple times in the search results:
https://api-dev.col.plus/dataset/1008/name/search?facet=rank&facet=issue&facet=status&issue=unparsable%20authorship&limit=50&offset=0

**Comment by ayco-at-naturalis** [comment]
Is this issue still actual? The duplication of Rep-S-20350 is now absent in https://api-dev.col.plus/dataset/1008/name/search?facet=rank&facet=issue&facet=status&issue=unparsable%20authorship&limit=50&offset=0
