### ISSUE TITLE
New Search Specifications

### ISSUE THREAD

**Issue by ayco-at-naturalis** [CatalogueOfLife/backend#374]
# Introduction
This document proposes search functionality enhancements based on a discussion thread in #333 and a document written by Geoff Dower: [Search for Scientific Names v7.docx](https://github.com/Sp2000/colplus/blob/master/docs/design/Search%20for%20Scientific%20Names%20v7.docx).

As far as free text search is concerned, the current search functionality is mainly focused on auto-completing what the user is typing in the GUI's search box. This turns out to be too restricted for what is actually required. See #333.

At the same time, the way it currently works is that for each new letter the user types in the search box, a query is carried out involving not just the search phrase (the "q" query parameter), but all other search parameters (like "rank") as well. This can become very heavy if the user has also specified facets.

# Redesign
First of all, the search functionality should be split into (at least) two services:

## Auto-complete (sec)
The first service remains focused on auto-completion. However we should restrict it to do just that. The auto-complete service takes just two parameters: the search phrase (the "q" parameter) and the search target (the "content" parameter). The search target can be any or all of SCIENTIFIC NAME, VERNACULAR NAME and AUTHORSHIP (e.g. the user could specify that the search be limited to just vernacular names). Other search parameters and facets are excluded from the auto-complete service.

That means that the response can also be a lot simpler: possibly just a list of strings matching the search phrase. However, to make it more obvious to the user (via tool tips or a drop down box) what those strings represent, the following should probably also be provided (T.B.D.):

* Whether it's a scientific name, vernacular name or author
* If it is a scientific name, the rank and possibly the author
* If it is a vernacular name, the language and possibly the scientific name

However, it does not make sense to return full-blown name usage objects, as we currently do. The auto-complete service only provides input for the actual search; it should **not** be confused with the actual search itself. The actual search happens when the user presses the search button.

We could also return the key of the scientific name c.q. vernacular name. This allows for fast retrieval once the user hits the search button. Note, however, that if the user chooses to ignore the suggestions and issue a search with a partial string, that must be allowed. In this case the frontend cannot send an ID back to the backend. The "q" and "content" parameters must _again_ be used for the actual search.

#### Fuzzy Search
Geoff's document also mentions _fuzzy search_ as an extra search option. This should then be an extra options besides the search target option (passed on via the "content" parameter). The document states that it should be disabled by default. However, what the document describes as fuzzy search is not exactly what search engines mean by fuzzy search: using algorithms to calculate a "distance" between two words and then specifying how far they are allowed to be apart. What the document describes as fuzzy search is the application of some basic normalizations on _both_ the search phrase _and_ the scientific names in the search index, and this is precisely what is currently already being done by default! In fact it is baked into the current name search service, so we need to discuss this further. _True_ fuzzy search might still be a powerful feature.

## Name search
This is the proper name search service. It is called when the user presses the search button. This service does not only use the text in the search box to get to a result, but all other search parameters and facets specified by the user as well.

This service can follow two paths:

#### The user has selected a name suggested by the auto-complete service
If the frontend determines that the user has selected one of the suggested name strings, an exact search can and must be issued. In addition, as per Geoff's document, if a user puts quotes around the search phrase, that must trigger an exact search as well. Note, however, that if auto-completion works properly, it's hard to see how searching with a search phrase that was _not_ suggested by the auto-complete service can have any exact match.

If the user selected a scientific name or a vernacular name from the drop down box populated from the auto-complete service,  the frontend does in fact not have to re-send the "q" and content parameters. Instead it can just send the applicable key, plus the nature of the key (name id or vernacular name key). If the user selected an author, this is unfortunately not possible because authors are not a separate entity within the data model, so there are no keys for them. However we can still issue an _exact_ search on the authorship string, so all in all this path will be very fast - even with facets.

#### The user wishes to issue a search on a partial name
In this case one the more advanced query mechanisms will kick in. The default query mechanism in Elasticsearch is full-text search. This, however, does not make sense for CoLPlus. Full-text search is good for searching through news paper articles, but not for searching through strings that usually contain just two ("Larus fuscus") or three ("Larus fuscus fuscus") words. 

We currently use a combination of Elasticsearch's [n-gram search](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-ngram-tokenizer.html) and some domain-specific normalization rules, provided by CoLPlus itself (e.g. such that "sylvestris" and "silvestris" map to the same normalized version). By and large this is probably still a good choice, but, as remarked, we might want to facilitate "true" fuzzy search as well. Not all examples in Geoff's document are covered by the covered by the normalization applied by the CoLPlus normalizer, and they would probably be covered when using Elasticsearch's fuzzy search mechanism.

_(As an aside, we currently distinguish between weakly normalized names and strongly normalized names. We store a weakly normalized version of the scientific name in the search index and a strongly normalized version. We then try to match the weakly normalized version of the user-provided search phrase with the weakly normalized name and the strongly normalized search phrase with the strongly normalized name. This distinction has to go in favour of **just** the strongly normalized version. Using both caused the #333 bug whereby trinomials are returned, but binomials not - which brought about this whole discussion.)_

#### Extra search parameters
As remarked by @mdoering  (below) limiting search to accepted names and synonyms (as requested in Geoff's document) is already supported through the "status" parameter. We do, however, need two new search parameters that allow the user to specify that he/she want to search for fossil species and/or for extant species. Proposed parameter names: FOSSIL and RECENT (case-insensitive as with al the other search parameters)

**Comment by mdoering** [comment]
> As per (link to Geoff's document) the following extra options should be added: accepted names, synonyms, extinct taxa, fuzzy search. Except for fuzzy search, the other search options are in fact refinements c.q. additions to the already exististing "content" query parameter.

**Comment by mdoering** [comment]
It makes sense to provide **2 services**, i.e. API resources for the *name usage* search.
The autocomplete should return the `scientificName`, `authorship`, `rank`, `status` and `ID` I would suggest. As we have 3 different entities in the search index (Taxon, Synonm, BareName) we need a way to identify them - which we can do with the status property (BareName have status=NULL). For BareNames the ID should be the name.ID, for all others the usage.ID

If a use finds sth in the autocomplete we can take him directly to the taxon page.
Or use the ID in forms when we need to lookup taxa (e.g. the assembly tree, sector forms, etc)
The autocomplete should work with the same NameSearchParameter filters as the main search.

**Comment by mdoering** [comment]
A good proposal Ayco. Some remarks and proposed changes from my side:

**auto-complete**
 - This should be a new API method `/name/suggest`
 - I think the auto complete should not be limited to provide input to the true search, but allow users to quickly select a NameUsage (i.e. Taxon or Synonym) which is very valuable in forms when managing/entering data. Thus is must include the Taxon/Synonym.id property, even for a vernacular name. In that case I would probably include a new vernacularNameKey property which is also of type int rather then a string.
 - I cannot see auto completion on authorship to be useful. Do it just on scientificName and vernacularName instead.
 - the autocomplete MUST also accept the datasetKey filter. In fact I would REQUIRE it as its rather useless to auto-complete across any dataset
 - the status, rank, sectorKey, PUBLISHER_KEY & TAXON_ID filters should also be left as an option as we need them in various places to restrict the corpus
 - returned properties should be `ID`, `scientificName`, `authorship`, `rank`, `status` and `code`. The later is the best way to disambiguate intraregnal homonyms. We might also want to add code to the supported filters / NameSearchParameter
 - fuzzy search makes not much sense for auto-completion as you get values as you type. It rather needs to as fast as possible, so I would strongly suggest to exclude generic fuzziness. Even the normalization we do now for the real search is not needed here I believe (it also mostly works on epithets, thus requires a user to already specify the full genus name until it kicks in)


**search**
 - this should remain on the current API method,  return the current format and largely be the same as have so far

**Comment by gdower** [comment]
I agree with Markus that autocomplete on author strings probably would not be all that useful and might just get in the way of searching for scientific names. 

Yuri and I think autocomplete would still be useful at the full catalogue level without dataset keys.

Having fuzzy match enabled by default could work if the exact search phrase matches are ranked as higher quality matches than the fuzzy matches. Otherwise, a less common spelling variant of a popular name might be difficult to find among all the noise from fuzzy match. Exact match (e.g., "Aus bus" with quotes) could also help eliminate fuzzy match noise but not all users will know about that search feature.

Development of the basic search functionality should be prioritized but eventually it would be very useful to have a way to specify which fields to search within (e.g. author:Lineaus, vernacular:firefly, genus:Quercus) with an advanced search form that will generate those more specific search queries for users. Twitter's [advanced search](https://twitter.com/search-advanced) is a good example. Even being able to search within supplemental verbatim fields not included in the standard submission formats would likely be extremely useful to some users, and could extend CoL+ to cover a lot of other use cases that we aren't even aware of yet. Advanced search could possibly be a separate search service that would get parsed out of the ?q= parameter and redirected to the advanced search service.

**Comment by mdoering** [comment]
@gdower when you say its useful to search the full catalogue without a datasetKey filter do you mean the entire clearinghouse? Search the entire catalogue sounds more like searching all of CoL which is a single dataset

Can we park the advanced search in a separate issue and deal with that later? @gdower mind writing such a new issue?

**Comment by mdoering** [comment]
Ah, I also have a use case for suggestions across datasets: Plazi or WoRMS. It would be nice to search by "publisher" and across all their datasets. So agree, datasetKey should be optional

**Comment by gdower** [comment]
@mdoering, yes, I meant across the full catalogue when searching for scientific names or common names within CoL+, and not across all datasets in the clearinghouse. You're right though that it might be useful to have meta-data and data search with autocomplete in the clearinghouse (e.g., so that you can search for datasets by a publisher, or datasets that contain a certain species). I moved advanced search to #403.

**Comment by mdoering** [comment]
ok. Just wanted to clarify that the `datasetKey` filter here and anywhere else is delimiting an entire dataset which the draft CoL is one of. Within the CoL we have sectors to split further

**Comment by ayco-at-naturalis** [comment]
@gdower Good point about ranking exact matches vs fuzzy matches, will take that into account

**Comment by ayco-at-naturalis** [comment]
Should users be allowed to use a search phrase like "fish" or "aves" (or rather should we be able to handle it)?

**Comment by mdoering** [comment]
@ayco-at-naturalis are you asking if a user should be allowed to search for the vernacular name with `q=fish` or for `"fish" or "aves"`? The later I dont think so

**Comment by ayco-at-naturalis** [comment]
OK - yes, q being the text the user is typing into the search box

**Comment by ayco-at-naturalis** [comment]
To be sure, regarding the suggest service:

- It takes a search phrase (q). Required
- It takes a dataset key. Required
- It does **not** take a search target ("content") parameter. It only suggests scientific names and vernacular names.

The consequence is that, when the user issues the actual search, which _does_ take take a search target, he/she may get fewer results (if, for example, content was limited to vernacular names only) or more (if content also included AUTHORSHIP). In fact it could be that the suggest service suggests something that will not actually produce a result, e.g. because it only suggested a scientific name while the content parameter was VERNACULAR_NAME only.

**Comment by mdoering** [comment]
Yes thats right. I would even propose to restrict the suggest to scientific names alone and ignore vernaculars.

Additional to your list it also takes a couple of optional filters (see my comments above)

**Comment by ayco-at-naturalis** [comment]
Do you not think that a lot of lay people will want to search the CoL using vernacular names? Or do you guess they'll anyhow only get to the CoL via Google?

**Comment by mdoering** [comment]
sure they do. but thats what the search is for rather than autocomple as vernaculars are anyhow rather inprecise. search is by no means dependant on auto completion

**Comment by ayco-at-naturalis** [comment]
OK - will exclude vernaculars then

**Comment by mdoering** [comment]
@ayco-at-naturalis can this be closed?

**Comment by ayco-at-naturalis** [comment]
I don't think so, because I'm not sure that @gdower and @yroskov  have had a change ti assess if the search in now saffy enough as regards "fuzzy matching"

**Comment by ayco-at-naturalis** [comment]
@gdower and @yroskov When you have chance, could you check if the search now works (at least as well) as specified in Geoff's document?

**Comment by yroskov** [comment]
Ayco, thanks! We'll do checks, seems, on the next week. 
To do search checks, I have started import of World Plants at data.dev.catalogue.life (November 27th, 8:43 pm). Taking in account that Scarabs import started on November 26th, 1:08 pm are still running, the dataset will not be ready soon.

**Comment by mdoering** [comment]
@ayco-at-naturalis @yroskov @gdower can we close this issue?

**Comment by ayco-at-naturalis** [comment]
I assume this is closed now (bar the NPE)

**Comment by yroskov** [comment]
I have completed Search for Scientific Names – test report #126 https://github.com/CatalogueOfLife/data/issues/126
