### ISSUE TITLE
/sector/{key}/treediff gives empty response

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#384]
/sector/{key}/treediff?attempts=1..2

**Comment by mdoering** [comment]
URL has changed, see https://github.com/CatalogueOfLife/clearinghouse-ui/issues/186

**Comment by mdoering** [comment]
there was a bug in the generation of sector metrics so that all sector trees and name sets were empty. Unfortunately we cannot rebuild the older attempts, but for future syncs this should be fixed now

**Comment by mdoering** [comment]
I am rebuilding all current metrics, so they all have tree, name index ids and name string metrics which can be diffed to future imports/syncs.

Name matching against the names index also doesnt work nicely anymore, many names have no match. Thats the reason why many id files are empty. I'll address that when I switch to the stable ids business.
