### ISSUE TITLE
Add an advanced search service

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#403]
It would be very useful to have a way to specify which fields to search within (e.g. author:Linnaeus, vernacular:firefly, genus:Quercus) with an advanced search form that will generate those more specific search queries for users. Twitter's [advanced search](https://twitter.com/search-advanced) is a good example. Even being able to search within supplemental verbatim fields not included in the standard submission formats would likely be extremely useful to some users, and could extend CoL+ to cover a lot of other use cases that we aren't even aware of yet. Advanced search could possibly be a separate search service that would get parsed out of the ?q= parameter and redirected to the advanced search service.

**Comment by mdoering** [comment]
I think thats better handled in the [UI as a advanced search component](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/567) - the UI can then decide which parts to render
