### ISSUE TITLE
Importing editorial decisions

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#419]
On the stand-up call this morning, @thomasstjerne and I discussed the potential idea of being able to dump large datasets out of CoL+ into tsv format, apply decisions or complete more complex workflows in a desktop application, re-import the tsv, and batch apply the decisions.

In the long-term this might simplify the task of developing taxonomic editing tools, because the frontend would not have to re-implement spreadsheet-like functionality in a RESTful environment which can become really complex. Also, some users may prefer to do the bulk of their work in desktop applications (Excel, Access, LibreOffice, etc) that they already know how to use.

@thomasstjerne made a good point that it would likely have to be a special type of import because the importer would have to interpret the decisions provided by the user, and inform the user when they provide invalid decisions.

I imagine this might take quite a lot of effort to develop and do not think it should be a priority right now, but we thought it might be worthwhile opening an issue ticket to discuss it as a potential long-term enhancement.

**Comment by mdoering** [comment]
Working offline locally on a subset of the data would surely be very useful.
How do you imagine that decisions are tracked in such a TSV? Should the (re)importer just compare the previous with the updated data and create a decision for that change? This might be quite challenging if any change can occurr in a spreadsheet.
