### ISSUE TITLE
Delete sector sync not working

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#469]
When clicking the [stop sync button](https://github.com/Sp2000/colplus-frontend/issues/342), the frontend sends the below request and gets a 204 No Content response from the backend, and the sector sync isn't deleted:

```
https://api.col.plus/assembly/3/sync/2729
Host: api.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer [redacted]
Origin: https://www.col.plus
DNT: 1
Connection: keep-alive
Referer: https://www.col.plus/
DELETE: HTTP/1.1 204 No Content
Date: Tue, 10 Sep 2019 15:41:17 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Keep-Alive: timeout=5, max=72
Connection: Keep-Alive
```

The deleted sector syncs [still show in the API](https://api.col.plus/assembly/3/sync?limit=25&offset=0):

```
{"attempt":2,"state":"preparing","started":"2019-09-09T22:09:42.133","finished":"2019-09-09T22:09:42.14","error":"IllegalArgumentException: Sector 2729 does have a non existing subject CLASS Polypodiopsida for dataset 1140","type":"SectorSync","sectorKey":2729,"usagesCount":0},
{"attempt":2,"state":"preparing","started":"2019-09-09T22:09:42.071","finished":"2019-09-09T22:09:42.128","error":"IllegalArgumentException: Sector 2728 does have a non existing subject CLASS Lycopodiopsida for dataset 1140","type":"SectorSync","sectorKey":2728,"usagesCount":0},
```

The bug can be reproduced from the steps described in #468.

Frontend version: 5e066ea September 10, 2019 8:46 AM
Backend version: 530045e September 9, 2019 11:45 AM

**Comment by gdower** [comment]
Actually delete sector sync does seem to work because I got an InterruptedException, it just doesn't remove the sector from the [sector sync list](https://api.col.plus/assembly/3/sync?limit=25&offset=0) so the frontend still displays it.

**Comment by mdoering** [comment]
the sector sync should still be in the list, but it should have a state=CANCELED. That does not seem to happen if I read this right?

**Comment by gdower** [comment]
The clearinghouse-ui sends the following API call when clicking any of the stop sync buttons on [this page](https://data.catalogue.life/catalogue/3/sector/sync?limit=25&offset=0):

```
DEL https://api.catalogue.life/assembly/3/sync/1

204 No content
```

I thought it was a clearinghouse-ui bug but the sector ID that we want to delete is actually sectorKey 1:
 
https://api.catalogue.life/assembly/3/sync?limit=25&offset=0

It doesn't end up as state=CANCELED and stays at state=preparing.
