### ISSUE TITLE
Dedicated vernacular search

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#531]
searching on vernaculars can only return accepted taxa. mixing search with sciname might just lead to confusion and were better off to offer a dedicated common name search?

**Comment by ayco-at-naturalis** [comment]
Is that not the same as specifying **only** VERNACULAR_NAMES for SearchContent? Or do you mean allowing for more common name search options like language?

**Comment by mdoering** [comment]
in todays call we decided to remove the vernacular search from the current ES name usage search and reimplement it as a dedicated vernacular search directly on postgres.

**Comment by mdoering** [comment]
simple postgres driven vernacular search added
