### ISSUE TITLE
Add ability to lock metadata?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#553]
Dataset metadata is taken from the imported data archives and will overwrite any potential manual changes. Do we need an option to lock the metadata for a dataset so that no changes are applied during imports?

**Comment by mdoering** [comment]
ping @yroskov

**Comment by yroskov** [comment]
Yes, we need an option to lock GSD metadata. 
Quite often, GSDs messed up their own metadata. Even GSD name might be unstable from one update to another.

**Comment by mdoering** [comment]
so you suggest to lock certain fields only? Possible, but sounds like a management nightmare.
Also it is a question of how providers feel about their data not being visible if they chose to change the title, description or whatever else. I find it a difficult question

**Comment by yroskov** [comment]
This is about metadata related to "chapters" of the entire publication. The editor is responsible for integrity of the publication. There is a standard procedure in the CoL: author and editor come to agreement over GSD name, versioning system, authorship, associated organisation, IPR, website address, point of attachment in the classification, abstract, frequency of updates, LTS, etc. at the stage of GSD first entry in the CoL. After that, changes in GSD name and in other key metadata should be discussed between author and GSD editor. This is an important condition of each product with added editorial value.
For example, a change of GSD name may cause significant chaos in data credits and citation. Seaweeds database changed its name to AlgaeBase, Hexacorals database to WoRMS Hexacoral, TIGR Reptile to EMBL Reptile finally to The Reptile Database - all these changes were suggested by authors and adopted by CoL editor. Even more, 65% of short names and 25% of full GSD names were worked out in collaboration between CoL and GSD authors. Another example, we agreed to have two separate GSDs as World Plants and World Ferns in CoL, whereas this is a single dataset outside CoL. 
So, full editor's control over metadata in CoL is important.

**Comment by mdoering** [comment]
Understood. So what's the features required for locking metadata? Without explicit locks you currently have the option to turn off automatic imports by setting import frequency to none. And once released metadata does not change ever, it is archived.

Metadata locking is relevant when you either have automatic imports (e.g. WoRMS, Paris DBs) and want to prevent automatic metadata updates. Not sure if that is relevant as you already trust that these source can deliver proper exports. For other manually triggered imports you will immediately see the new metadata. So maybe locking isn't that much of a need?

As far as I understand you though you would like to see locking on individual field level of the metadata which seems fine. Shall we do that?

**Comment by yroskov** [comment]
In the past, I had problems with unwanted change of metadata in both automated and manual updates. So, it would be nice to implement the same locking options through all GSDs. 
Yes, locking on individual field level of the metadata is useful.

**Comment by mdoering** [comment]
superceeded by https://github.com/CatalogueOfLife/clearinghouse-ui/issues/573
