### ISSUE TITLE
Dataset name comparison API

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#554]
Create an API to compare 2 or more datasets. There are many aspects that can be compared:
 - names
 - name usages / taxa / classifications
 - references
 - distributions, etc

Initially we should focus on plain names to understand the difference and overlap of datasets.
For this the name matching derived names index ids are key as they flag what is regarded as the same name between and within datasets.

The service should allow to generate [Venn diagrams](https://en.wikipedia.org/wiki/Venn_diagram#Overview) visualising the dataset overlaps:

![257px-3-set_Venn_diagram svg](https://user-images.githubusercontent.com/327505/68660598-bf5c6680-0539-11ea-9ed7-10681de84acc.png)

![289px-Venn's_four_ellipse_construction svg](https://user-images.githubusercontent.com/327505/68660621-cc795580-0539-11ea-876c-f2535ae151ff.png)

![240px-Symmetrical_5-set_Venn_diagram svg](https://user-images.githubusercontent.com/327505/68660588-bb304900-0539-11ea-860e-6806fc683774.png)

For this we need to first generate the unique set of names index ids for each dataset and then do a generic set comparison to find the intersections between each dataset which can then power a Venn diagram.

The API then also needs to be able to list all names that belong to a specific area in the diagram, ie the overlapping or unique names.

**Comment by mdoering** [comment]
see also https://github.com/Sp2000/colplus-backend/issues/138

**Comment by dhobern** [comment]
Thanks @mdoering 

To apply this to CoL-WFO-IPNI, I was thinking of a really simple four-part comparison:

* Is the same binomial found in each dataset? If so,
   * Is the author string identical?
   * Is the name consistently treated as accepted or as a synonym of the same binomial?
   * Is the family placement the same?

That gives 10 possible pairwise states between two databases (Found in A only, Found in B only, 8 possible states for those found in both A and B). I was thinking that repeating this three times for each database pair would be interesting. 

It would certainly be possible to carry out a three-way mapping with (I think) 152 possible states for any binomial: 

- A only 
- B only
- C only
- A+B 8 possible states as above
- B+C 8 possible states as above
- C+A 8 possible states as above
- A+B+C 125 possible states, where 125 is 5^3 representing five states [all different, A+B, A+C, C+A, A+B+C] for each of the three subquestions

From those data, it would then be easy to generate a range of three-ring Venn diagrams representing different aspects or degrees of match between the three datasets.

**Comment by mdoering** [comment]
we mostly have this in place now (name comparison, author, parent, status as additional options).
We do not work with names index numbers yet - that might be a good improvement to spot only major differences.
