### ISSUE TITLE
nameusage/search gives no results if catalogueKey param is given

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#575]
Doesn´t matter if it is with `decisionMode=_NULL`
https://api.dev.catalogue.life/dataset/1027/nameusage/search?catalogueKey=3&decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0

`decisionMode=_NOT_NULL`
https://api.dev.catalogue.life/dataset/1027/nameusage/search?catalogueKey=3&decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0

or without `decisionMode` param
https://api.dev.catalogue.life/dataset/1027/nameusage/search?catalogueKey=3&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0

**Comment by mdoering** [comment]
search is not updated yet to the new request format, see https://github.com/Sp2000/colplus-backend/issues/569#issuecomment-559609149

**Comment by thomasstjerne** [comment]
This is still not working after the deployment

**Comment by mdoering** [comment]
@ayco-at-naturalis maybe you did filter usages by the catalogueKey instead of filtering just the decisions? With or without a catalougeKey should yield exactly the same search result counts. Just the decisions list should be different.

**Comment by mdoering** [comment]
>    This takes the datasetKey of the managed catalogue to filter decisions by, not usages.
>     It will prune the list of decisions to just the ones matching the datasetKey.
>     I.e. the list only contains a single decision at max if one catalogue is given
>     so the UI can quickly determine if a decision exists at all for a given usage
>     and does not have to ignore decisions from other catalogues.
>

**Comment by mdoering** [comment]
decision mode on the other hand should filter usages (if catalogueKey was also given filter only based on the presence of that one decision matching the catalogueKey:

>   /**
>    * Allows to filter usages based on the existence of a decision with the matching MODE.
>    * NOT_NULL or NULL can be used here to filter usages to just the ones
>    * with or without any decision (from the requested DECISION_DATASET_KEY if given)
>    */
>   DECISION_MODE(EditorialDecision.Mode.class),
>

**Comment by mdoering** [comment]
based on #548 and #569

**Comment by ayco-at-naturalis** [comment]
OK, I understand this (and the javadoc comment for CATALOGUE_KEY)  now. I had totally not reckoned with post-processing step (not that it is complicated). This is something Elasticsearch definitely cannot do.

**Comment by mdoering** [comment]
@ayco-at-naturalis now that catalogueKey is used in postprocessing results, is it ignored when using the DECISION_MODE filter?

A search for `DECISION_MODE=_NOT_NULL&CATALOGUE_KEY=3` should only return usages that have a decision (mode!=null) which has SimpleDecision.datasetKey=3.

A search for `DECISION_MODE=_NULL&CATALOGUE_KEY=3` should only return usages that have no decision with SimpleDecision.datasetKey=3. But they might have decisions from a different catalogue!!!

**Comment by mdoering** [comment]
@ayco-at-naturalis is this still open? Can you verify it is working before closing please?

**Comment by thomasstjerne** [comment]
`decisionMode=_NOT_NULL` [works](https://data.dev.catalogue.life/catalogue/31450/dataset/31451/workbench?decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&rank=species)
but 
`decisionMode=_NULL` [doesn´t](https://data.dev.catalogue.life/catalogue/31450/dataset/31451/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&rank=species)

**Comment by ayco-at-naturalis** [comment]
Interesting ... I had discovered this myself and fixed this while fixing something else

This issue is the same as  #711
