### ISSUE TITLE
Add authorization scopes to roles

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#580]
Shouldn't the role `user` be able to [create new datasets](https://github.com/Sp2000/colplus-frontend/issues/96#issuecomment-453050629)? According to [this line](https://github.com/Sp2000/colplus-frontend/blob/master/src/components/LayoutNew/BasicMenu.js#L192) only editors and admins get the menu new dataset option.

Also, it seems like the `user` role can't edit dataset meta data or upload updates. The user role should probably only be able to edit datasets they created or were [granted permission to edit](https://github.com/Sp2000/colplus-frontend/issues/439).

**Comment by mdoering** [comment]
Yes. But that is not done. The user role as it is is meant for commenting and downloading though, not data management. We still need to define the fine grained roles and associated scopes.

Suggested ROLES and authorization scopes:

 - admin: can do anything
 - editor: can do data management and is allowed to create new datasets. Various scopes possible:
     - catalogue: can do anything in an entire catalogue, place decisions, sync, change hierarchy, etc
     - sector: anything within a sector, including syncs
 - user: non anonymous user that can comment on anything and download data. Not scoped

**Comment by mdoering** [comment]
Additional services that needs to be exposed:
 - list of authorized users by datasetKey

Implementation wise we could keep an array of dataset keys on the user object / table. In order to efficiently filter users by datasetKey a new authorization table might be a better option

**Comment by thomasstjerne** [comment]
I would like users with an EDITOR role to have an array of catalogueKeys.
Also a user with a dataset curator/owner role should have an array of datasetKeys.

**Comment by mdoering** [comment]
whats the difference between catalogue & dataset key? The idea is to have a list of dataset keys for editors. If its a managed one or external dataset it doesnt matter. With rights for an external dataset one can change metadata incl the data access link and manage imports. For managed datasets one can modify data, sync, manage decisions etc. 

In the first stage there is no fine grained control on parts within a managed dataset. It will be the entire CoL for example. But at a later stage we could consider sectors or maybe higher taxon names/ids to limit access to some parts of the tree in a managed dataset.

There is no authorisation planned on individual source datasets within a catalogue.

**Comment by thomasstjerne** [comment]
Ok, then the frontend will have to pull all datasets for the user to see if they are managed one by one. 
Could we then have a list of datasets by user?
sth like `/user/me/datasets` rather than pulling them one by one

**Comment by mdoering** [comment]
sure. And vice versa a list of users for a given dataset

**Comment by mdoering** [comment]
The implementation plan is the following:

 - [ ] scope all entities by a dataset, see #680. That includes sectors, decisions and estimates.This way all resource URIs contain the datasetKey
 - [ ] extend AuthFilter to make sure the user is authorized to edit a requested dataset by looking at the request URI path which then always includes the datasetKey. Only propagate the role if the dataset key is listed
 - [ ] add a new user_authorization table with user_key and dataset_key only
 - [ ] add IntSet ColUser.datasets so the (cached) user instance can offer a new isAuthorized(int datasetKey) method
 - [ ] extend AuthFilter to also check for a new private flag on datasets and refuse any access incl GET and OPTION to private datasets regardless of roles
 - [ ] extend AuthFilter to require https for authentication to avoid unsecure password transmission
 - [ ] expose new /user/me/datasets API method to list datasets the user has rights on

Initially we will keep the global sector, decision and estimate resources so the UI continues to work until it has adapted.

**Comment by mdoering** [comment]
`USER` role is superfluous and should be removed.
A user free text search is needed to find collaborators

**Comment by mdoering** [comment]
deployed to dev
