### ISSUE TITLE
Newly posted estimates doesn´t show up in tree API

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#615]
For example this one
https://api.dev.catalogue.life/estimate/2536

Should be in this response:
https://api.dev.catalogue.life/dataset/2055/tree/8f344f5d-d1eb-48b6-ae87-4a67570a2e83/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=2055

**Comment by mdoering** [comment]
duplicate of #707
