### ISSUE TITLE
Searching for exact matches only

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#636]
As we discussed on the call this morning, fuzzy match has already proven to be very useful in detecting classification conflicts by removing the scientific name suffixes and using fuzzy match to search for groups with the same name that have been promoted or demoted to a different rank and given a different suffix. However, we often do need to search for exact matches only, so it would be really useful if a boolean parameter could be added to enable or disable fuzzy match.

**Comment by ayco-at-naturalis** [comment]
@gdower @mdoering @thomasstjerne There are now two new query parameters

- **wholeWords** (boolean, default true).  This enables matching by whole words only. Partial matching must now be actively enabled by specifying wholeWords=false.
- **fuzzy** (boolean, default true)

The _fuzzy_ parameter can be used both for the suggest service and for the search service.

The _wholeWords_ can only be used for the search service

**Comment by mdoering** [comment]
does this need a rebuild of the index?

**Comment by mdoering** [comment]
@thomasstjerne can we please add these options to the search form?

**Comment by ayco-at-naturalis** [comment]
@mdoering I'm afraid yes, because there's now a full-text index on scientific name, but I would wait a bit until I have tested everything thoroughly (in case I might conclude the indexes should be specified a bit differently)

**Comment by mdoering** [comment]
ok. Now that its in master we must update the index soon as we need to regularly deploy.
In fact it's been already deployed to dev this morning.

**Comment by ayco-at-naturalis** [comment]
OK - just index ... not everything is exhaustively tested, but small chance that the index definitions themselves would change

**Comment by thomasstjerne** [comment]
I guess #649 is related to this

**Comment by mdoering** [comment]
@ayco-at-naturalis can we close this?
