### ISSUE TITLE
Export dataset as DwC-A and ColDP

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#650]
If feasable also for any root node of a subtree in a given dataset

**Comment by mdoering** [comment]
Exporting should be part of any release

**Comment by mdoering** [comment]
For ColDP export that only export a given subtree we need to decide how to deal with related data outside this subtree.
Should we always, never or on custom demand include:
 - related names, e.g. basionys
 - accepted taxa in case of pro parte synonyms
 - related taxa for species interactions or concept relations

The initial implementation will include all relations, but exclude all related names or taxa that are not covered by the requested subtree

**Comment by thomasstjerne** [comment]
Definitely the first two points. But not related taxa for species interactions.

**Comment by mdoering** [comment]
> Definitely the first two points. But not related taxa for species interactions.
means you would expect them to always be included?

**Comment by mdoering** [comment]
duplicate of #219
