### ISSUE TITLE
Provide new searchable sector API

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#652]
The resource should return a sector together with its latest sector import object (or at least the main parts, most stats are not important and might blow up the data returned).

For filtering parameters please see https://github.com/Sp2000/colplus-frontend/issues/134

**Comment by thomasstjerne** [comment]
The API exists and is pageable (https://data.dev.catalogue.life/catalogue/3/sector?limit=100&offset=200), but is not fully searchable. I Did a major rewrite yesterday, adapting broken sectors section (now renamed to just sectors) under catalogue, and sectors section under dataset to this paged API.
It used to pull all sectors for all datasets contributing to the current catalogue and then do client side paging, filtering & sorting. But this caused some issues (e.g. https://github.com/Sp2000/colplus-frontend/issues/491).

With the serverside paging, the fronted now decorates with dataset using Dataloader, so maybe no need to include that. It will only decorate sectors of the current page of the data.

But adding filters for `lastSyncDate`, `subjectTaxonName` , `targetTaxonName` and `higherTaxonKey` would be really useful.
I guess `higherTaxonKey` would point to the taxon in the catalogue/assembly and return any sector contributing with data below that taxon (even if the sector was sitting above the taxon)

**Comment by mdoering** [comment]
ok, if you pull the imports from the client then indeed the basic exists already and we can just add more filter params - thats quite simple apart from the higherTaxonKey

**Comment by mdoering** [comment]
Filters to be added for the UI:

 - rank (searches on both subject & target)
 - name (searches on both subject & target TaxonName)
 - syncdate (shows only sectors that have been synced BEFORE the given date or never at all)

**Comment by thomasstjerne** [comment]
But if we should be able to do a lastSyncDate query, then it is not sufficient to pull them from the client because I can only filter on the current page of data.

Actually the higherTaxonKey query could be solved by by simply being able to get sectors by multiple keys :
https://api.dev.catalogue.life/sector?datasetKey=3&key=1028&key=1033&key=1053&key=1148

I would then get the higher taxon from the tree API, decorated with datasetSectors:
`datasetSectors: {1028: 2, 1033: 2, 1053: 1, 1148: 1}
`

**Comment by mdoering** [comment]
the lastSyncDate would be part of the sector API filters (see syncdate above), so the client would not have to do filtering?

**Comment by thomasstjerne** [comment]
> the lastSyncDate would be part of the sector API filters (see syncdate above), so the client would not have to do filtering?

Ahh, then I understand. No problem to decorate with syncs in the frontend

**Comment by mdoering** [comment]
current the following search request parameters exist:

```
  @QueryParam("id")
  private String id;

  @QueryParam("datasetKey")
  private Integer datasetKey;
  
  @QueryParam("subjectDatasetKey")
  private Integer subjectDatasetKey;
  
  @QueryParam("rank")
  private Rank rank;
  
  @QueryParam("mode")
  private Sector.Mode mode;

  @QueryParam("userKey")
  private Integer userKey;
  
  @QueryParam("broken")
  private boolean broken = false;
  
  @QueryParam("target")
  private boolean target = false;
```

`name` and `syncdate` being added

**Comment by mdoering** [comment]
@thomasstjerne is it worth exposing more filters in the UI like sector mode and userKey?
I could see value in at least limiting the sectors to the ones the currently logged in user created?

**Comment by thomasstjerne** [comment]
Sure. 
But I don´t think I understand the target boolean in this context

**Comment by mdoering** [comment]
for datasets we store the latest successful import attempt. The search for date last modified then uses the last successful import date, even if we had later imports that failed.

We could do the same for sector syncs, only using the last successful attempt as the timestamp to compare with `lastSync`.

**Comment by mdoering** [comment]
the target boolean in this context is only applied to the `broken` flag.
Is it useful to have that target flag at all? Should we not just list all broken ones no matter which side is broken?

**Comment by thomasstjerne** [comment]
Yes, I think we should just list all broken.

**Comment by mdoering** [comment]
Propose to remove `target` and let `lastSync` only work against the last successful sync.
Would be useful to list all sectors that have failed in their last attempt then, hu? Would be easy to return all sectors that have a non successful `FINISHED` state as their last one. @thomasstjerne How about adding a new `lastSyncFailed` param then?

**Comment by thomasstjerne** [comment]
Sounds good.
Maybe the "sector sync" menu item becomes superfluous then?
But on the other hand "sector sync"  lists the sync attempts chronologically, so it would require an orderBy param as well ....

**Comment by mdoering** [comment]
If the sectors would be sorted chronologically indeed the sector sync section would become superflous. Right now the sectors are sorted by id to have a stable order. But that really doesnt mean anything. We could switch to last sync date as the standard sorting?

But that would not allow to see all syncs, just the latest. Maybe we can get a history like we have for datasets somewhere?

**Comment by mdoering** [comment]
all but higher taxon keys are done and deployed to dev already

**Comment by thomasstjerne** [comment]
Dev UI has been updated as well, but can you please check that `lastSync` works as expected: https://data.dev.catalogue.life/catalogue/31450/sector?lastSync=2020-01-12&limit=100&offset=0

Should it return sectors synced before or after the given date?

**Comment by mdoering** [comment]
It should be sectors that had last synced before that date - or never did.
The sector list in the UI should also indicate the last sync date. I will expose the last successfull sync attempt with a sector. That way its trivial to lookup that exact sync
