### ISSUE TITLE
Replicate clearinghouse db in Champaign?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#654]
@mdoering, the monthly and annual dwca's in the downloads directory is nice. :+1: We used to also have a colplus.sql.gz dump of the database back in the API downloads directory. Could we bring that back again? It might help with figuring out how to [port AC2019 into the Clearinghouse](https://github.com/CatalogueOfLife/data/issues/112). I also often get custom database export requests and a lot of the time it's much faster to just write SQL queries to quickly respond to those requests.

**Comment by mdoering** [comment]
what was the colplus.sql.gz content again? The CoL release as a sql dump?

We should definitely dump all mysql dbs for the various legacy AC releases and place them next to the dwcas

**Comment by gdower** [comment]
It was a full dump of the colplus postgres database. Hmm, I guess that might get kind of large.

**Comment by gdower** [comment]
We could limit it to just what's in CoL.

**Comment by mdoering** [comment]
It will get huge, it's the entire clearinghouse db. I dont think thats a good option, it will have quite some impact on the dbs performance if we do that regularly. We only did that cause we did not yet have a streaming replication backup then.

As for custom queries I agree that we are in a bad situation here. You should have access to the prod db to do queries. But it does not seem likely we can get access for you at GBIF. @MattBlissett maybe we can setup a readonly replica just for such queries in Champaign?

**Comment by gdower** [comment]
@mdoering, I think that's a good idea and probably I should run a local deployment for testing anyway. I could try to get the colplus-dockers working again, or use your deployment system. We have a kubernetes cluster though, so probably the docker route would be best for us.

**Comment by mdoering** [comment]
setting up the colplus docker again is a good idea, but that would be for testing, not replicating the prod db. We could try to replicate to a postgres instance in your kubernetes cluster. Do you wanna setup a postgres 12 instance for tests?

**Comment by gdower** [comment]
Sounds good. I'm getting ready to upgrade the hard drive and reinstall the OS on my laptop which will give me the space to get the dockers working again.

**Comment by gdower** [comment]
@mdoering, can we at least add a tool to create a SQL dump of a project instead of the entire clearinghouse database? In particular, having on demand dumps of /dataset/3 is pretty essential for testing.

**Comment by mdoering** [comment]
If a project just includes the data it has synced and its decisions, sectors etc that should be doable. Just like the ac export we export in native SQL. I would need to run the command line though for this. Can we make it a jenkins job that you trigger to create a SQL dump which gets copied into the downloads?

**Comment by mdoering** [comment]
manually one time dump at http://api.catalogue.life/download/dump/ds3.sql.gz
I will setup a jenkins job for you to trigger new dumps

**Comment by mdoering** [comment]
new job available: https://builds.gbif.org/job/col-dump-draft/
