### ISSUE TITLE
Allow for private datasets

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#659]
It should be possible to have private, hidden datasets.

These should not show up in the Clearinghouse UI, but probably also not in the API unless requested by an authorised user. All data related to a private dataset needs to be hidden.

As nearly all requests are dataset scoped this should be feasable without a major refactoring.

**Comment by mdoering** [comment]
@thomasstjerne do you have concerns/input from the UI perspective on this, especially if the API would behave differently depending on the logged in user? E.g. dataset searches would return different results?

**Comment by thomasstjerne** [comment]
I guess this could be transparent for the client. 
The UI already do authorised requests to all endpoints, so I guess only the amount of data returned would differ.
But a flag `private: true` would be useful for the UI to show it is private with a small icon or some  coloring.
