### ISSUE TITLE
Streamline ES code

### ISSUE THREAD

**Issue by ayco-at-naturalis** [CatalogueOfLife/backend#662]
Re-distribute classes, reduce number of packages packages & makecode more readable. Two new tag interfaces, UpwardConverter and DownwardConverter, to make it more clear which way the conversion is going

**Comment by ayco-at-naturalis** [comment]
@mdoering Help! I'm not allowed to push to the new repo (this one). Will go out now. Think it's important to push asap

**Comment by mdoering** [comment]
You might have an invitation, but let me check now again. gimme 5 minutes

**Comment by ayco-at-naturalis** [comment]
ok will wait a bit ... didn't see the invitation in my email backlog

**Comment by mdoering** [comment]
should be there again now

**Comment by ayco-at-naturalis** [comment]
Yes got it
