### ISSUE TITLE
Dataset registration 422 error with empty data access field

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#667]
When registering a new dataset, I'm getting a 422 error. It's fixable by filling in the data access field, but the data access field should be optional for uploaded datasets.

```
POST https://api.catalogue.life/dataset
{
  "title": "Test",
  "origin": "external",
  "type": "taxonomic",
  "code": "",
  "license": "unspecified",
  "settings": {
    "rematch decisions": "",
    "csv delimiter": "\\t",
    "csv quote": "\"",
    "csv quote escape": "\\\"",
    "distribution gazetteer": "",
    "nomenclatural code": ""
  },
  "dataFormat": "coldp",
  "dataAccess": "",
  "importFrequency": "once"
}
```

![image](https://user-images.githubusercontent.com/8573609/77669779-4c391700-6f53-11ea-9743-d66722917273.png)

**Comment by mdoering** [comment]
its on purpose to make sure external datasets have a URI.
But with uploads I guess this is wrong behavior. I will losen it
