### ISSUE TITLE
Incomplete decision data in search index

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#675]
This request gives one record with a decision:
https://api.catalogue.life/dataset/1068/nameusage/search?catalogueKey=3&decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0

````
{
 key: 17029, 
 datasetKey: 3, 
 mode: "update"
}
````
However fetching the decision directly from the [API](https://api.catalogue.life/decision/17029) gives this decision:

````
{
"created": "2020-04-02T13:52:36.874433",
"createdBy": 101,
"modified": "2020-04-02T13:52:36.874433",
"modifiedBy": 101,
"key": 17029,
"datasetKey": 3,
"subject": {
"id": "90242014",
"name": "Aspilota vector Belokobylskij, 2007",
"rank": "species",
"code": "zoological",
"status": "accepted",
"parent": "Aspilota"
},
"subjectDatasetKey": 1068,
"mode": "update",
"name": {
"rank": "unranked",
"candidatus": false,
"type": "scientific",
"parsed": false,
"formattedName": "null"
}
}
````

**Comment by mdoering** [comment]
I'm not sure if this is expected or a bug and the search is supposed to return the entire decision.

**Comment by mdoering** [comment]
It behaves as expected and is supposed to return only a `SimpleDecision` with the fields you listed above.
