### ISSUE TITLE
Cannot retrieve classification for a placeholders 

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#677]
When a link from somewhere (e.g sector table) goes to a tree, the classification from the root to the linked taxon id is retrieved like this:
https://api.dev.catalogue.life/dataset/31496/tree/3?catalogueKey=3&type=SOURCE

But this doesn´t seem to work for placeholders:
https://api.dev.catalogue.life/dataset/31496/tree/2--incertae-sedis--order?catalogueKey=3&type=SOURCE

**Comment by thomasstjerne** [comment]
Hmm, the other one works: https://api.dev.catalogue.life/dataset/31496/tree/1--incertae-sedis--CLASS?catalogueKey=3&type=SOURCE

**Comment by thomasstjerne** [comment]
The ranks given in placerHolderRank attr are lowerCase whereas the tree API expects uppercase.

**Comment by mdoering** [comment]
I will make the tree API case insensitive like we do anywhere else.
In general all vocabularies are lower cased as the canonical representation, but should be handled case insensitive in arguments.
