### ISSUE TITLE
Scope decision resource URLs under project dataset

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#680]
Sector, Decision and Estimates are global entities identified by a global integer key across all projects. They do clearly belong to a single (project) dataset though.

In order to simplify the implementation of [dataset wide authorization](https://github.com/CatalogueOfLife/backend/issues/580) we propose to also make these 3 entities dataset scoped CRUD resources, i.e. :

```
/dataset/{datasetKey}/sector/{key}
/dataset/{datasetKey}/decision/{key}
/dataset/{datasetKey}/estimate/{key}
```

The integer key would still be globally unique and we could even keep a single GET read resource to resolve a key without the dataset context if needed for the UI.

**Comment by mdoering** [comment]
@thomasstjerne do you forsee problems in the UI? Especially retrieving sectors/decisions or estimates without a known dataset (project) context?

**Comment by thomasstjerne** [comment]
Yes, in many places entities are decorated with their sectors based in their sectorKey. So the datasetKey is not known to the UI before the sector is fetched.
This is for example the case in assembly trees

**Comment by mdoering** [comment]
The decorating code of the tree is not aware of the catalogueKey it is showing? The datasetKey for the both trees, source and target, is the same. It is the project.

**Comment by thomasstjerne** [comment]
Ah, I thought it was the datasetKey (source)

**Comment by mdoering** [comment]
confusing as usual. But I tend to use datasetKey only for the actual dataset the data primarily belongs to. Decisions, sectors and estimates belong primarily to one project=dataset.

Would that be a problem then?

**Comment by thomasstjerne** [comment]
I would still need to GET like this for a source: https://api.dev.catalogue.life/sector?limit=500&offset=0&subjectDatasetKey=1113
In order to show sectors in any project/catalogue for a dataset in the plain dataset clearinghouse, where it is not project/catalogue scoped. 
But otherwise, I think it would be fine for CRUD on single entities

**Comment by mdoering** [comment]
Thats fine, thanks. It simplifies authorization a lot if we scope all objects behind a dataset.

**Comment by mdoering** [comment]
@thomasstjerne do you need to list all sectors for a given subjectDatasetKey? This can get really large in case we have lots of releases. Would it not be better to first get a list of all projects (maybe with count of sectors) and then list the sectors for a given project only?

We could expose this via `/dataset/{subjectDatasetKey}/projects` returning full dataset objects.

And/or we could expose `/dataset/{subjectDatasetKey}/sector?subject=true` to list only sectors where the subjectDatasetKey equals the path parameter. Then we could get rid of the global resource, right?

**Comment by mdoering** [comment]
Instead of adding a new resource `/dataset/{subjectDatasetKey}/projects` listing all projects by a given source dataset should be integrated into the dataset search:

`/dataset?sourceDatasetKey={subjectDatasetKey}`

We could also return the number of sectors for managed datasets if thats useful?
