### ISSUE TITLE
Proxy datasets not importing correctly

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#681]
Some recent changes seem to have broken the proxy dataset importer. For example, see [this dataset](https://data.dev.catalogue.life/dataset/1052/classification?sourceTaxonKey=78). It looks like it might be a delimiter issue, although I tried setting the delimiter configuration on the metadata page, which didn't fix the issue.

I'm in the middle of working on something else but will try to dig into this more later.

Frontend version: a663ae3 April 8, 2020 4:27 AM
Backend version: e997b02 April 8, 2020 10:36 AM

**Comment by gdower** [comment]
It looks like the importer is [trying to import the proxy yaml file as data](https://data.dev.catalogue.life/dataset/1052/verbatim).

**Comment by mdoering** [comment]
indeed the import job didnt check the format properly. Fixed in https://github.com/CatalogueOfLife/backend/commit/3f5ddd261dc2d36f87dd116c408a42af0c5813bb#diff-994b43388ee52f85ae886490ffa20d9cR175
