### ISSUE TITLE
Endpoints on /dataset route fail on dev

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#683]
e.g.:
https://api.dev.catalogue.life/dataset?contributesTo=31450&limit=1000
https://api.dev.catalogue.life/dataset/31450/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic
https://api.dev.catalogue.life/dataset/11235

**Comment by mdoering** [comment]
missing column in dev db. fixed
