### ISSUE TITLE
Ghost database: CoL Management Classification 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#686]
@mdoering @thomasstjerne @gdower 
Please bring database "CoL Management Classification" id500 in the Clearinghouse.

I cannot find this database in the Clearinghouse, however, it appears in final product:
http://workbench.catalogueoflife.org/col_plus/details/database/id/500

Metadata for this database are incorrect. Original source from AC19 has been badly misinterpreted in CoL+.

Just in case, similar databases with 0 species, Animal Biodiversity and IRMNG are present in the Clearinghouse:
https://data.catalogue.life/dataset/1502/meta
https://data.catalogue.life/dataset/2007/meta

**Comment by mdoering** [comment]
Yes, the management classification does not exist as a separate dataset. The idea was it simply is the CoL so there is no need for additional metadata just for that part.

As the legacy portal does require dataset 500 to exist we create that [metadata on the fly with hardcoded values in the export](https://github.com/CatalogueOfLife/backend/blob/master/webservice/src/main/resources/exporter/ac-export.sql#L69).

We can easily change these to your liking, just propose here what exact content you would like to see and we update the exporter. We could also put that metadata into its own file so you can modify it yourself much more easily.

Using a dedicated dataset for the management classification was considered initially, but we turned that down and it now does not work with how we planned out the editing tools. This has to do with the modify assembly tools that allow you edit the classification directly in the draft tree. These changes do not come from any external synced source/sector so we also do not link metadata from any other dataset. 

An alternative would be to create a new managed dataset just for the classification that we then sync back into the CoL draft each time it changes. Quite a bit of overhead I would think, but if you prefer that this is already possible. Reiterating - this would mean no manual changes are to be done directly in the assembly tree. The modify tab should not be used. You would have to change the 500 dataset using the modify tab and sync back any changes to the draft.

**Comment by yroskov** [comment]
Thank you Markus! It is clear that id500 is now default credit to any node in the classification which has no data provider. I have changed metadata follow your above link "metadata on the fly with hardcoded values in the export".

**Comment by yroskov** [comment]
Just in case, repeating metadata here:
SELECT
 500 AS record_id,
 'CoL Management Classification' AS database_name_displayed,
 'CoL Management Classification' AS database_name,
 'CoL Management Classification' AS database_full_name,
 NULL AS web_site,
 'Species 2000' AS organization,
 NULL AS contact_person,
 'Biota' AS taxa,
 'Taxa of various ranks' AS taxonomic_coverage,
 --'abs' AS abstract,
 'The management classification brings all contributed taxonomic checklists across all kingdoms into a coherent master view, and where possible enforces consistent nomenclature. To place a global species database within the Catalog of Life, a specific set of adjustments was be decided by the editors on where and how to insert it, to make it as consistent as possible, while not losing the essential taxonomic information.' AS abstract,
 '2020' AS version,
 '2020-01-10' AS release_date,
 NULL AS SpeciesCount,
 NULL AS SpeciesEst,
 'CoL editorial team' AS authors_editors,
 NULL AS accepted_species_names,
 NULL AS accepted_infraspecies_names,
 NULL AS species_synonyms,
 NULL AS infraspecies_synonyms,
 NULL AS common_names,
 NULL AS total_names,
 0 AS is_new,
 'Global' AS coverage,
 NULL AS completeness,
 NULL AS confidence

**Comment by mdoering** [comment]
@yroskov @olafbanki Should we really still use _Species 2000_ as the organisation?
When is the official change to _Catalogue of Life_ gonna happen?

**Comment by yroskov** [comment]
Release date 2020-01-10. Sp2000 is a legal custodian organisation for that date.
OK, today is 16th April. Do you have a legal document about closure of Sp2000 in UK and establishment of Catalogue of Life in Netherlands?
