### ISSUE TITLE
Prevent users to be locked out from datasets

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#687]
I changed dataset [31450](https://data.dev.catalogue.life/catalogue/31450/assembly) to private, and now I cant access it.
The backend should ensure that at least one user has access to a dataset after it is made private.

I guess that if a user is allowed to update (PUT) on the dataset, then the user should also be able to see it after the update, even if it has been made private.

**Comment by mdoering** [comment]
;) yes, also the creator of the dataset should probably not be allowed to be removed from the editors list. How did you change it to private without having rights though is sth I dont understand. Need to test this further

**Comment by mdoering** [comment]
@thomasstjerne should the dataset creator be removable? And do we need to make sure we always have one editor left? Admins can always change a dataset and add back editors

**Comment by thomasstjerne** [comment]
I dont think the dataset creator should be removable (this would probably be done by mistake in 99% of the cases)
I think there should be at least one editor left, otherwise it should give some kind of error. But the latter could never happen if the creator was not removable

**Comment by mdoering** [comment]
Yes, that was my thinking. If the creator remains there's always one left.
Ill do it that way for now at least
