### ISSUE TITLE
Release source dataset metadata

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#689]
When releasing a managed dataset like the CoL different sectors have been synced at different times. They might be years apart. The source datasets existing in the Clearinghouse could have been updated considerably since and contain different metadata than then one used at the time the source was synced.

The metadata for each source dataset bundled with a release should be the one that represents the exact import attempt that the sync was based on. This becomes a bit of a problem in cases where there are many sectors from the same dataset that have been synced at different times against different import attempts. We should use the latest attempt for all syncs per dataset in these cases.

In order to be able to access the metadata for a specific import attempt we should:

 - [ ] archive all metadata for all attempts, similar to how we store the import metrics
 - [ ] keep the import attempt with every sync so we know against which version we have synced
 - [ ] for each source dataset in releases use the metadata from the exact attempt of a sector sync - or the latest one in case there are multiple attempts existing for all sectors of a single source dataset

**Comment by mdoering** [comment]
Storing all versions of metadata is more complex than anticipated. To understand it better I ahve drawn a diagram that uses rectangular boxes for dataset metadata records:

![Dataset versioning](https://user-images.githubusercontent.com/327505/79993528-23099900-84b5-11ea-83b0-7a4f726f343c.png)

The one thing I am unsure about is whether a (released) project would maybe want to deviate from the source dataset owners metadata. I would bet that is true, especially if we deal with more projects over time. Is it necessary to have yet another copy of a dataset metadata for each source in a released project? Or maybe point to the official version (using the combined key of datasetKey & import attempt) and allow to specify changes stored the project dataset that modify the original metadata? A bit like decisions but simpler? Then we dont need to store dataset copies in their full glory over and over again.

**Comment by mdoering** [comment]
Alternatively we could 
 - keep a datasets current metadata 
 - store a projects source metadata as a separate file. Each time a sector is synced the metadata would also be checked if it has been updated and an editor be forced to merge the 2 versions if they are different. That manual merging would not work though if many sectors were to be synced at the same time

**Comment by yroskov** [comment]
I can explain approach to dates in metadata in CoL production 2010-19. 
We use an **analog to Sync attempt/date** (i.e. synced all sectors together): date stamp in LSID. It was a technical date, which was useful only for me, Luisa and systems manager in our management process. (It was not possible to "sync" different sectors in different dates. Independence of syncs in CoL+ is a positive feature).
**GSD Release Date**, a date when GSD export was generated for CoL. It is analog to **Import attempt/date**. That date was used by our data management team and GSD author. One editorial version of GSD may have different release dates.
**GSD version** (it included month and year), as defined by the GSD author. The version/date was used by our data management team, GSD author and CoL users.


Different projects may have different approaches and needs.
In CoL+, our data management team need to have consolidated log for sector syncs + {GSD import + GSD release} + GSD version, as well as separate logs for each parameter. Metadata with non-recently-synced GSDs in the assembled checklist should not be changed. For example, metadata for IRMNG should remain unchanged in the project despite of how newer version of IRMNG we have in the clearinghouse, UNTIL we do a sync for a new IRMNG. (In the case of automated updates, sync should be kicked off automatically).

**Comment by mdoering** [comment]
Thanks Yuri. This is not just dates though but any of the metadata like authors, description, citation you name it. Or don't you ever change that?

**Comment by yroskov** [comment]
Metadata should stay unchanged unless GSD version remain unchanged. 
There were different procedures for automated and manually updated GSDs. 
**Manually updated GSD**: I am checking metadata for each version of GSD. (GSD authors do not necessarily keep metadata consistent from one release to another. Before assembly, I am checking, that (1) GSD names remain stable (as names which we agreed with first entry of GSD), (2) style of versioning is consistent through editions, (3) style of authors, organizations, English name of the group comply with CoL standards.  
**Automated GSDs**: I was not able to check manually metadata in all automated GSDs. Thus, we frozen such fields as GSD names (for all GSDs), authors & organizations (for WoRMS; because these data do not comply with CoL standards). This approach had negative impact: if list of authors was changed in WoRMS, it may stay unchanged in CoL until our editors or GSD authors report a problem.

**Comment by mdoering** [comment]
I think we should not modify the original sources metadata. If multiple projects make use of the same source different styles are likely and not everyone will be happy. Modifying the authors and title is exactly what I was thinking of above - we need to find a way to apply these changes only in the project scope and not outside. How we do that so it is efficient but always up to date is the main question.

**Comment by yroskov** [comment]
Well, in this case, each project should have an option to create own view for metadata of the source.

**Comment by gdower** [comment]
The problem is that the metadata is [often not well maintained by authors](https://github.com/CatalogueOfLife/data/issues/110#issue-570179335), so I like the idea of projects being able to edit a copy of the metadata.

**Comment by mdoering** [comment]
We figured in our call that a metadata update decision on each source of a project would be address the problem. That decision gets applied during a release before copying the metadata into the archive.
