### ISSUE TITLE
/dataset endpoints fail with Bearer Auth

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#692]
https://api.dev.catalogue.life/dataset/31502/import
https://api.dev.catalogue.life/dataset/31502

**Comment by mdoering** [comment]
it works with Basic Auth and curl

**Comment by mdoering** [comment]
also with Bearer. What user are you using and what response headers do you get?

**Comment by mdoering** [comment]
maybe this was a problem of preflight requests not passing through? I think the old version didnt treat OPTIONS special and applied authorization filters. I have changed the CORS filter to not execute an of them in case of preflight requests
