### ISSUE TITLE
Remove bare names from CoL draft and releases?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#693]
there are lots of bare names in the CoL draft and its releases up to now:
https://data.catalogue.life/dataset/2123/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic

This should not happen anymore with the new recursive delete that also removes names.
But we should remove them once the monthly April release is out.

@gdower please ping me if its ok if I clear all orphan names - there is a routine to do so

**Comment by gdower** [comment]
To clarify, what do you mean by "bare names?" I've been using that term to refer to names in the names index that are not attached to the taxonomic classification. I think I've seen you use the term that way before, too. Under my definition, orphaned names would be caused by a relational data bug which is different from bare names.

**Comment by mdoering** [comment]
We call names that do not have a corresponding usage (taxon or synonym) a [BareName](https://github.com/CatalogueOfLife/backend/blob/master/api/src/main/java/life/catalogue/api/model/BareName.java#L11) in the backend code. Also in the UI if you set status=_NULL:
https://data.catalogue.life/catalogue/3/names?status=_NULL&limit=50

There are more than 293.000 bare names in the draft. They should mostly stem from deleted subtrees in the assembly, which used to only delete the usages, but not the name records. That is changed now on dev, but we did not deploy to prod yet. It was not a true bug, but a known lets say odd behavior ;)

**Comment by mdoering** [comment]
Oh, the issue should have been in CatalogueOfLife/data, but I cannot trasnfer the issue somehow. Can you @gdower?

**Comment by gdower** [comment]
Good to know.

It won't let me transfer the issue either, possibly because of either permissions or the data repo doesn't come up in the transfer search list because of all the other repos with the data- prefix.

**Comment by gdower** [comment]
On today's call, I think we decided to remove them automatically during a release which will give us a chance to review them before releasing.

**Comment by mdoering** [comment]
I dont think its a good idea to do that automatically. Some projects might not want that.
It should be a manual process. I thought we agree to do it once we deployed to prod, so the recursive tree deletion fix gets used avoiding the bare names creep.
