### ISSUE TITLE
NameUsage suggest doesn´t find higher taxa

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#697]
Trying to find Crocodylidae here:
https://data.dev.catalogue.life/catalogue/3/dataset/1008/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&rank=family

https://api.dev.catalogue.life/dataset/1008/nameusage/suggest?vernaculars=false&fuzzy=false&limit=25&q=Crocodylidae

**Comment by mdoering** [comment]
Hm, looks indeed like a search but to me.
It also happens on prod where you can search for it, but not use the suggest:

https://api.catalogue.life/dataset/1008/nameusage/search?q=Crocodylidae

https://api.catalogue.life/dataset/1008/nameusage/suggest?q=Crocodylidae

**Comment by ayco-at-naturalis** [comment]
Hm, odd b/c they share almost 90% of the code or so. Should be simple to fix

**Comment by mdoering** [comment]
Every higher taxon I tried is not found in suggest.
I assume it has to do with genus, specificEpithet fields not being set for higher taxon which use "uninomial" instead.

Quite essential bug to be fixed.
The suggest is not being used in all form fields, e.g. the "search by higher taxon" form on the names search
