### ISSUE TITLE
Cannot parse prefix into a known NameUsageSearchParameter

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#706]
https://api.dev.catalogue.life/dataset/1008/nameusage/search?catalogueKey=3&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&prefix=true&q=chryso

**Comment by mdoering** [comment]
see https://github.com/CatalogueOfLife/backend/issues/811
