### ISSUE TITLE
Setting `incertae sedis` names to `Not assigned` with decisions

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#708]
In one of the Paris proxy datasets, @yroskov was trying to use decisions set several names like `Fulgoroidea incertae sedis` to `Not assigned` and got the below [error on sync](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:4485),query:(match:(sector:(query:4485,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:7),query:(match:(attempt:(query:7,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))).

We do frequently encounter data with rank names set to or containing `incertae sedis` and it would be useful if we can use vocab or decisions to set them as `Not assigned`.

```
Sector Sync 4485 failed: life.catalogue.db.mapper.NameMapper.create (batch index #155) failed. 154 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    id,
    dataset_key,
    sector_key,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   , created, modified)
    VALUES ( 
    '4cab8e95-6bb0-440a-ac94-04d03bee2bf8',
    3,
    4485,
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (4cab8e95-6bb0-440a-ac94-04d03bee2bf8, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-04 20:24:33.34002, 2020-05-04 20:24:33.34002, 4cab8e95-6bb0-440a-ac94-04d03bee2bf8, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
```

**Comment by mdoering** [comment]
I'd be interested to see the actual example. But there are several issues involved here:

 1) the error should not happen and the sync should prevent inserting names without a scientificName - I will take this issue as the bug report for that to no happen
 2) all names that include`incertae sedis` and other keywords cause the name parser to mark these names as Name.type=`PLACEHOLDER`. Placeholders never sync and are always ignored no matter what their name is
 3) marking names as placeholders manually can be done by a decision to change the name type to `PLACEHOLDER`. No change in name needed

**Comment by mdoering** [comment]
@thomasstjerne @gdower I think we need to show [more name details on the taxon page](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/85) including the name type. But maybe even also in the workbench columns? As we only have a few name types we could maybe use a single letter to visualize them and safe space?

http://api.catalogue.life/vocab/nametype
S=scientific
V=virus
H=hybrid formula
I=informal
O=otu
P=placeholder
N=no name
