### ISSUE TITLE
Not possible to create a new reference through API / UI without an ID

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#709]
As part of frontend update/refactoring all forms are revisited and a test trying to add a new reference failed because no `id` is given.
Shouldn´t the backend create an  `id` if none is given  by the client? I guess this is because UUIDs are used for references rather than INTs.
![ID_NOT_NULL_REFERENCE](https://user-images.githubusercontent.com/1666484/81155389-2d339900-8f85-11ea-8314-84ad08a54a78.png)

**Comment by mdoering** [comment]
that should be sth the backend does indeed
