### ISSUE TITLE
Old bug: exclude According To person name from scientific name authorstring

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#713]
@mdoering or @thomasstjerne 

Person name from According To field appears in authorstring of scientific name. Example:

![image](https://user-images.githubusercontent.com/28574252/81603172-850e3d80-9393-11ea-8f38-932fcdde118d.png)

Please exclude According To person name from scientific name authorstring.

**Comment by mdoering** [comment]
yes. its next on my major todo list. It is a bit more complex than just removing though, the model with accordingTo and scrutinizer needs to be changed. 

@yroskov do you still want to continue with a LTS per taxon or rather refer to last modified by and cite the entire source?

**Comment by mdoering** [comment]
superceeded by #714
