### ISSUE TITLE
Interpret NOMEN status

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#716]
We want to allow and potentially recommend NOMEN status values to be used for the coldp:Name.status field. 

In the first stage these then end up as verbatim data and the Normalizer will interpret the simplified Name.status using the NomStatParser which needs to be extended to cover all NOMEN values.

In a second phase we could consider to use the NOMEN values also in the interpreted view if there is enough take up.

**Comment by mdoering** [comment]
@gdower @mjy could you provide me with a table of all [nomen statuses](https://github.com/SpeciesFileGroup/nomen) and if you can already map them to the [Clearinghouse values](http://api.catalogue.life/vocab/nomstatus)? 

Would we expect full URIs or also just a simple name?

**Comment by mjy** [comment]
NOMEN is here: https://github.com/SpeciesFileGroup/nomen, in nomen.owl.

There are two things there: object properties, i.e. relationships between
names (technically between monomials), and classes, i.e. status on names
with no further explanation.

I can see about using the new ROBOT tool to dump TSV for you.

I believe @proceps did this mapping exercise?

**Comment by mdoering** [comment]
I would expect only NOMEN classes as a name status, correct?

**Comment by mjy** [comment]
Yes.  You are not asserting a relationship between two names in this case, only one.  I spammed some quick and dirty explanation on the README.md here.

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/backend/commit/9c2297f58c0baf39f23837eb8b65fd3feab91c31

**Comment by mdoering** [comment]
The Clearinghouse should now accept NOMEN class values for any name status given in ColDP, ACEF or DwC in the corresponding fields.

The parser accepts the full URI `http://purl.obolibrary.org/obo/NOMEN_0000228` as well as the simple, local name `NOMEN_0000228` and even `NOMEN_228`

**Comment by mdoering** [comment]
Mapping is basically here:
https://github.com/CatalogueOfLife/backend/blob/master/parser/src/main/java/life/catalogue/parser/NomenOntology.java#L67

apply does apply to all subclasses too

**Comment by mjy** [comment]
Very cool @mdoering thanks for taking the time to try this out.

**Comment by mdoering** [comment]
I even managed to read it straight from owl. So we can update it easily when Nomen changes

**Comment by mjy** [comment]
Nice. Did you use this?  https://github.com/owlcs/owlapi

**Comment by mdoering** [comment]
I was thinking about it, but then I realized I need only very little from the ontology and as its serialized to xml/rdf I just wrote a simple xml parser for that which was simple and does not pull in more dependencies.
