### ISSUE TITLE
Error 403 when I tried to save edited metadata

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#720]
Frontend version: d2d0a59 May 13, 2020 8:46 AMBackend version: b38b74b May 12, 2020 10:11 AM

I have got Error 403 message when I tried to save edited metadata:
https://data.catalogue.life/dataset/2130/meta

![image](https://user-images.githubusercontent.com/28574252/82089634-9750ea00-96b9-11ea-8ae5-6e0b9ba00472.png)

**Comment by mdoering** [comment]
again this is user rights. You do not own dataset 2130:

> Created
May 14th 2020, 7:13:18 pm by gdower

Until #439 is implemented please send me a list of dataset keys that you need access to and I enter them through the API. 

@gdower you can add yuri (user=102) as an editor to any dataset by calling:

```
curl --user geoff:password -X POST -H "Content-Type: application/json" --data "102" "https://api.catalogue.life/dataset/{KEY}/editor"
```

**Comment by mdoering** [comment]
I've added you to 2130 now

**Comment by gdower** [comment]
I tried adding @yroskov to 2132 with your command above and it [added 2132 to his datasets array in the API](https://api.catalogue.life/user/102), but he still gets a 403 error when editing the metadata. Also, if I have the private flag set, he can't view or edit even when added to the dataset.

Frontend version: d2d0a59 May 13, 2020 8:05 AM
Backend version: 8c4b64f May 16, 2020 5:12 AM

**Comment by mdoering** [comment]
The user instance is cached by the token and not updated it seems. I'll fix this, workaround for now is to log out and back in again!
