### ISSUE TITLE
Error message in Issues

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#722]
Frontend version: d2d0a59 May 13, 2020 8:46 AMBackend version: 8c4b64f May 16, 2020 5:12 AM
at https://data.catalogue.life

When I click on count figure for the issue, I got an error message:

Request failed with status code **500**
There was an error processing your request. It has been logged (ID 60cfa9b36f0cab66).
HTTP method: GET
https://api.catalogue.life/dataset/2130/nameusage/search?catalogueKey=3&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=unmatched%20name%20brackets&limit=100

Verbatim reports work well.

**Comment by mdoering** [comment]
Urf, we need to update the search index. That takes 3-6 hours, I'll start it right now

**Comment by mdoering** [comment]
Ive reindexed the Collembola dataset which now works.
Ill reindex all other datasets too, but now you can at least continue working ;)

**Comment by yroskov** [comment]
Thank you @mdoering!
Error message gone now. But report lists are empty for all issues, like that:
![image](https://user-images.githubusercontent.com/28574252/82240898-d02ed000-9900-11ea-9c63-ac8698db80d1.png)

**Comment by mdoering** [comment]
Sth is still wrong. Some issues do yield results, many dont, others yield too little.
Maybe the reindexing did not fully work.

@thomasstjerne there is also an oddity that the UI does not show any results for issues when you follow the link from the issues page for dataset 2130, e.g. for [inconsistent name](https://data.catalogue.life/catalogue/3/dataset/2130/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=inconsistent%20name&limit=100)

But when you go to the workbench manually and select the respective issue filter you do get one result. There should be more, probably an ES index bug, but what puzzles me is that you get different results then the one linked from the Issue page

**Comment by thomasstjerne** [comment]
> Sth is still wrong. There are only 29 documents indexed, Ill debug the indexing.
> 
> @thomasstjerne there is also an oddity that the UI does not show any results for issues when you follow the link from the issues page for dataset 2130, e.g. for [inconsistent name](https://data.catalogue.life/catalogue/3/dataset/2130/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=inconsistent%20name&limit=100)
> 
> But when you go to the workbench manually and select the respective issue filter you do get one result. There should be more, probably an ES index bug, but what puzzles me is that you get different results then the one linked from the Issue page

This should work now
