### ISSUE TITLE
Mismatch between metrics and name usage search statistics

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#724]
A lot of the metrics aren't matching up with name usage search. For example, there should be [286 forms](https://data.dev.catalogue.life/dataset/31555/imports), but [name usage search only finds 5](https://data.dev.catalogue.life/dataset/31555/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&rank=form):

![image](https://user-images.githubusercontent.com/8573609/82371444-d3e55400-99df-11ea-8776-7064fb50321f.png)

![image](https://user-images.githubusercontent.com/8573609/82371917-9c2adc00-99e0-11ea-9659-1782c0f113f6.png)

The same thing is happening with issues. For example, issues shows [71 doubtful names](https://data.dev.catalogue.life/dataset/31555/issues), but name usage search only [returns 1](https://data.dev.catalogue.life/catalogue/3/dataset/31555/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=doubtful%20name&limit=50&offset=0):

![image](https://user-images.githubusercontent.com/8573609/82371869-874e4880-99e0-11ea-90f3-1a9e5db3b4a7.png)

![image](https://user-images.githubusercontent.com/8573609/82371819-730a4b80-99e0-11ea-91ae-580745d62cfb.png)

Possibly related to #668  #721.

Frontend version: 0e742b8 May 19, 2020 6:19 AM
Backend version: a51ee40 May 18, 2020 12:45 PM

**Comment by mdoering** [comment]
related to rebuilding the search index. We first need to swap in the new index and see if the problems still exist.

**Comment by gdower** [comment]
Ah, I didn't realize dev was getting reindexed, too.

**Comment by mdoering** [comment]
Actually, would you mind if we wipe dev completely? That would simplify things and make sure we are resetted

**Comment by gdower** [comment]
@mdoering, yeah, go ahead.
