### ISSUE TITLE
Rank is disregarded by the importer for uncapitalized uninomials

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#727]
@yroskov pointed out to me that when the following line is imported, the rank is ignored and it gets interpreted as a species epithet because it is not capitalized:

Name.tsv
```
7947780-58e1-0962-49af-3d9b850558a28    pseudoviolaceus Scott, 1964     subfamily
```
This [results](https://data.catalogue.life/dataset/2130/name/7947780-58e1-0962-49af-3d9b850558a28) in the name being flagged with the `Missing Genus` issue and `?` being added as a genus:

![image](https://user-images.githubusercontent.com/8573609/82477035-77903c00-9a94-11ea-9c9a-2bf62e2632c7.png)

When I'm converting data to CoLDP format, I could also capitalize subgenus and higher ranks, but this will likely be a fairly common data problem and ideally the backend should respect the provided rank instead of assuming it's a species just because it's not capitalized.

**Comment by mdoering** [comment]
I agree, rank should be honored. But parsing names unfortunately relies a great deal on character cases, which is the root of the problem. So please try always to include well formatted names in the archives.
