### ISSUE TITLE
Relative release LR links not working for nameusage export

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#733]
@mdoering, the command you sent to Johanna doesn't work because of the `LR` on the nameusage export service results in a 404: Dataset not released error.

```
curl -s -H "Accept: text/csv" "https://api.catalogue.life/dataset/3LR/nameusage?min=family" > col-families.csv
```

The name usage export works for the draft and April edition:

```
curl -s -H "Accept: text/csv" "https://api.catalogue.life/dataset/3/nameusage?min=family" > col-families.csv
```
I could email Johanna back and tell her to temporarily use the April release, unless you think this might be a quick and easy fix?

```
curl -s -H "Accept: text/csv" "https://api.catalogue.life/dataset/2123/nameusage?min=family"
```

On a side note, the API is also saying that dataset 3 was never released at the `latest` endpoint, which seems potentially incorrect:

https://api.catalogue.life/dataset/3/latest

**Comment by mdoering** [comment]
Weird, I did use the exact same command yesterday.
The backend cannot find the latest release, which you can always also access explicitly via curl -v https://api.catalogue.life/dataset/3/latest but which gives the same 404

**Comment by mdoering** [comment]
somehow the source_key column in the database table was empty. I cannot explain why, but its back again

**Comment by mdoering** [comment]
Ah, I updated the aliases and titles of the releases via the UI. That must have reset the sourceKey which is a bad thing that should never be possible.
