### ISSUE TITLE
ac-export attributing all names to CoL management classification

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#737]
All scientific names and families are set to database_id = 500 in the [ac-export](http://api.catalogue.life/download/export-2135.zip).

**Comment by mdoering** [comment]
This is a serious issue indeed. All taxa are missing a sector_key.
I think this is because at some stage I switched exports to work on releases, while we did create exports on the draft in the beginning.

So the problem is the release, not the export.
It also means all our previous releases are missing all sectors. 
I hope that is not too bad and we can remove them in 2021 anyways?

**Comment by gdower** [comment]
@mdoering, yeah I just noticed that the credits worked on the export. If you are able to easily move the export process back to exporting from draft 3 before copying draft 3 to an immutable release, that would be preferable because indexing takes a really long time, which makes creating a release take even longer because indexing + conversion is probably 2 work days. If we have to do multiple revision cycles that will mean that doing a release could take more than a week. If it's not a quick and easy to change, then I can make do with it until we eliminate conversion.

I guess the other workaround for now would be to do an export, and then do a release right after. They should match, and that will allow me to start conversion sooner.

**Comment by mdoering** [comment]
I can probably let the indexing run after the export so you can access it quicker. Inexing indeed takes a long time.
I would not want to move it back to the draft as that draft contains different keys and data as we just saw in this issue which helped to fix the release code.

**Comment by mdoering** [comment]
indexing runs now after exporting. Stable ids will also only be present in the release, so its important we use the release
