### ISSUE TITLE
Export endpoint moved to //dataset/{key}/export/export?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#738]
Did you mean to move the dataset export endpoint to [export/export](https://api.catalogue.life/#/default/export)?

https://api.catalogue.life/#/default/export

![image](https://user-images.githubusercontent.com/8573609/83200528-240f9500-a109-11ea-9885-10c5bc31ed79.png)

If so, please transfer this issue to the clearinghouse-ui to so that the endpoint is updated.

**Comment by mdoering** [comment]
No, not at all. Changed
