### ISSUE TITLE
Rematching broken estimates

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#741]
I tried to rematch broken estimates with:

```
POST //dataset/3/rematch
{"estimateKey": 844}
```
And got:

```JSON
201
{
  "sectors": {
    "broken": 0,
    "updated": 0,
    "unchanged": 0,
    "total": 0
  },
  "decisions": {
    "broken": 0,
    "updated": 0,
    "unchanged": 0,
    "total": 0
  },
  "estimates": {
    "broken": 1,
    "updated": 0,
    "unchanged": 0,
    "total": 1
  },
  "datasets": 0
}
```

The estimate did not rematch, so I'm not sure if estimates rematch is working?

http://api.catalogue.life/dataset/3/estimate?broken=true&rank=kingdom

If that's not the right way to rematch estimates, how do I do it? There's a [bunch of broken estimates, that I'll have to fix for next release](https://github.com/CatalogueOfLife/data/issues/131):

http://api.catalogue.life/dataset/3/estimate?broken=true

**Comment by mdoering** [comment]
looks like there are reasons why the matching does not succeed. From logs:

> SpeciesEstimate Estimate{844: 382000 species in KINGDOM Plantae} cannot be rematched to dataset 3 - lost KINGDOM Plantae

**Comment by mdoering** [comment]
I have filed this problem somewhere in frontend already, but we need a way to manually curate and fix broken estimates, decisions and sectors. There will always be cases when the automatic matching fails cause there are true duplicates or other genuine reasons

**Comment by mdoering** [comment]
the kingdom problems seem odd though. They do exist exactly once. Ill investigate tomorrow more closely

**Comment by mdoering** [comment]
Seems to work on prod now
