### ISSUE TITLE
Extinct species missing is_extinct status in ac-export

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#742]
In the [latest release candidate](http://api.catalogue.life/download/ac-export.zip), extinct species are missing the is_extinct=1 flag.

> This release of the Catalogue of Life contains contributions from 171 taxonomic databases with information on 1,867,814 living and **0 extinct species**, 160,092 living and **0 extinct infraspecific taxa** which belong to 184,526 genera, 12,267 families, 1,643 orders, 387 classes, 104 phyla and 7 kingdoms plus viruses, it also includes 1,710,622 synonyms and 423,691 common names.

![image](https://user-images.githubusercontent.com/8573609/83531566-c4234080-a4b2-11ea-908d-058f9f71a996.png)

![image](https://user-images.githubusercontent.com/8573609/83533436-33019900-a4b5-11ea-804b-bbfbdb19403b.png)

**Comment by gdower** [comment]
The extinct status is correct in the [draft](https://api.catalogue.life/dataset/3/taxon/faa12edd-42aa-42ae-81de-efc96e9aec37) but is missing in the [latest release](https://api.catalogue.life/dataset/3LR/taxon/faa12edd-42aa-42ae-81de-efc96e9aec37) for the extinct species, *Ankitokazoa bezanozanoi*.

**Comment by mdoering** [comment]
thanks, that pin it down nicely. I will have to fix the release code then and we'll need a new release
