### ISSUE TITLE
reoccuring broken decisions

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#748]
We see broken decisions in the draft CoL reoccurring even after several attempts to fix all tasks and [issues](https://data.catalogue.life/catalogue/3/dataset/2073/issues) for various GSDs, for example the [Species Fungorum Plus dataset](https://data.catalogue.life/catalogue/3/dataset/2073/tasks).

**Comment by mdoering** [comment]
some findings of my investigations.
Total number of decisions for the draft is [10870](https://data.catalogue.life/catalogue/3/decision?limit=100&offset=0&subjectDatasetKey=2073).
From these [1162 are broken](https://data.catalogue.life/catalogue/3/decision?broken=true&limit=100&offset=0&subjectDatasetKey=2073):

```
 subject_dataset_key | count 
---------------------+-------
                1011 |   351
                1015 |     7
                1021 |     5
                1027 |    55
                1189 |    84
                1206 |    21
                2073 |   286
                2130 |   353
```


Decisions about the Species Fungorum Plus dataset fall into:

```
    date    | broken     | count 
------------+------------+-------
 2020-03-18 | false      |  4119
 2020-03-18 | true       |   174
 2020-04-02 | false      |     2
 2020-04-02 | true       |   108
 2020-04-14 | false      |    32
 2020-04-14 | true       |     4
 2020-06-02 | false      |   122
```

so there are both broken and good decision from various times.

When I look into actual broken decisions ordered by date created I see:

```
17286 | BLOCK  | xQJ6                |            | GENUS              | Leptospora                               | 2020-04-14
 17283 | BLOCK  | xB8Q                |            | GENUS              | Hyphoscypha                              | 2020-04-14
 17277 | UPDATE | 160620              |            | SPECIES            | Ceriosporella gallica                    | 2020-04-14
 17276 | UPDATE | 160791              |            | SPECIES            | Ceriosporella acuta                      | 2020-04-14
 17161 | BLOCK  | 164970-548217       |            | INFRASPECIFIC_NAME | Hygrophorus erubescens capreolarius      | 2020-04-02
 17160 | BLOCK  | 260266-621926       |            | VARIETY            | Dacrymyces ceraceoides var. viridiflavus | 2020-04-02
 17159 | BLOCK  | 461067-634044       |            | VARIETY            | Clonostachys araucaria var. compacta     | 2020-04-02
 17158 | BLOCK  | 461067-138820       |            | VARIETY            | Clonostachys araucaria var. rosea        | 2020-04-02
 17157 | UPDATE | 105942-632912       |            | FORM               | Raphiospora flavovirescens f. alpina     | 2020-04-02
 17156 | UPDATE | 252517-117107       |            | VARIETY            | Inocybe vulpinella var. fuscolamellata   | 2020-04-02
 17155 | UPDATE | 113731-623337       |            | FORM               | Raphiospora flavovirescens f. alpina     | 2020-04-02
 17154 | UPDATE | 315893-116816       |            | VARIETY            | Inocybe vulpinella var. fuscolamellata   | 2020-04-02
 17153 | BLOCK  | 377077-630930       |            | SPECIES            | Verrucaria fallacior                     | 2020-04-02
 17152 | BLOCK  | 412430-409055       |            | SPECIES            | Verrucaria excellens                     | 2020-04-02
```

One issue I can see already is that there are decisions against "implicit" names such as genera, "Leptospora". Implicit names are created by the importer and get an id assigned automatically that might change to the next import. These ids usually start with "x" so you can identify them. The import metrics shows them under the origin slice:
https://data.catalogue.life/dataset/2073/imports

<img width="645" alt="Screenshot 2020-06-04 at 17 47 09" src="https://user-images.githubusercontent.com/327505/83786394-ec699580-a692-11ea-8f39-5bc77dddc43b.png">

Mostly these are denormalized classifications. For example a family name given in the classification of a species, but which does not exist as an individual record.

Looking at all genus decisions there are no duplicates and the broken decisions do not exist again, so there does not seem to be an issue:
```
  id   | mode  | original_subject_id | subject_id | subject_rank |  subject_name  |    date    
-------+-------+---------------------+------------+--------------+----------------+------------
 17273 | BLOCK | xFBY                | xFBY       | GENUS        | Cenangiopsis   | 2020-04-14
 17272 | BLOCK | xSVA                | xSVA       | GENUS        | Cephalotrichum | 2020-04-14
 17279 | BLOCK | xDSY                | xDSY       | GENUS        | Dermatina      | 2020-04-14
 17296 | BLOCK | xR68                | xR68       | GENUS        | Frankbaronia   | 2020-04-14
 17280 | BLOCK | x8UQ                | x8UQ       | GENUS        | Hawksworthiana | 2020-04-14
 17283 | BLOCK | xB8Q                |            | GENUS        | Hyphoscypha    | 2020-04-14
 17284 | BLOCK | xUGL                | xUGL       | GENUS        | Lepra          | 2020-04-14
 17286 | BLOCK | xQJ6                |            | GENUS        | Leptospora     | 2020-04-14
 17274 | BLOCK | xLEQ                | xLEQ       | GENUS        | Palaeoclavaria | 2020-04-14
 17291 | BLOCK | xC2L                | xC2L       | GENUS        | Patouillardina | 2020-04-14
 17293 | BLOCK | xJSN                | xJSN       | GENUS        | Schizostoma    | 2020-04-14
```

Investigating into the [SYN-SYN duplicates](https://data.catalogue.life/catalogue/3/dataset/2073/duplicates?acceptedDifferent=false&authorshipDifferent=true&category=trinomial&limit=50&minSize=2&mode=STRICT&offset=0&status=synonym&withDecision=false), there is species `Russula adusta` for example. But there are NO decisions at all in the backend about this species, not even broken ones. So this duplicate task can either never have been green or data has changed since, e.g. in the 2 imports that happened on June 1st.

All Russula decisions existing are the following, none of them being broken (subject_id=NULL):
```
  id   |  mode  | original_subject_id |  subject_id   | subject_rank |     subject_name     |    date    
-------+--------+---------------------+---------------+--------------+----------------------+------------
 15189 | UPDATE | 186063-169085       | 186063-169085 | SPECIES      | Russula aeruginosa   | 2020-03-18
 15188 | UPDATE | 305410-150470       | 305410-150470 | SPECIES      | Russula aeruginosa   | 2020-03-18
 13462 | UPDATE | 207265-174580       | 207265-174580 | SPECIES      | Russula atropurpurea | 2020-03-18
 13463 | UPDATE | 127270-322898       | 127270-322898 | SPECIES      | Russula atrovirens   | 2020-03-18
 13464 | UPDATE | 272416-129615       | 272416-129615 | SPECIES      | Russula fagetorum    | 2020-03-18
 13465 | UPDATE | 129585-305372       | 129585-305372 | SPECIES      | Russula formosa      | 2020-03-18
 13466 | UPDATE | 136438-110380       | 136438-110380 | SPECIES      | Russula heterochroa  | 2020-03-18
 13467 | UPDATE | 324430-327209       | 324430-327209 | SPECIES      | Russula insignis     | 2020-03-18
 13468 | UPDATE | 488021-477567       | 488021-477567 | SPECIES      | Russula littoralis   | 2020-03-18
 13469 | UPDATE | 203547-271416       | 203547-271416 | SPECIES      | Russula mitis        | 2020-03-18
 13471 | UPDATE | 209327-482003       | 209327-482003 | SPECIES      | Russula pulcherrima  | 2020-03-18
 13470 | UPDATE | 488020-290679       | 488020-290679 | SPECIES      | Russula rimosa       | 2020-03-18
 13472 | UPDATE | 507889-276745       | 507889-276745 | SPECIES      | Russula rosea        | 2020-03-18
 15190 | UPDATE | 305404-482004       | 305404-482004 | SPECIES      | Russula subfragilis  | 2020-03-18
 15192 | UPDATE | 187529-503631       | 187529-503631 | SPECIES      | Russula subfragilis  | 2020-03-18
 15193 | UPDATE | 207576-443223       | 207576-443223 | SPECIES      | Russula subintegra   | 2020-03-18
 15191 | UPDATE | 443220-129596       | 443220-129596 | SPECIES      | Russula subintegra   | 2020-03-18
 15195 | UPDATE | 186063-305415       | 186063-305415 | SPECIES      | Russula subtomentosa | 2020-03-18
 15194 | UPDATE | 459349-450653       | 459349-450653 | SPECIES      | Russula subtomentosa | 2020-03-18
 13473 | UPDATE | 488755-489092       | 488755-489092 | SPECIES      | Russula venusta      | 2020-03-18
```

**Comment by mdoering** [comment]
Here you can find all name metrics stored for every import attempt:
http://api.catalogue.life/download/metrics/dataset/073/2073/name

Unfortunately all of these are empty, a bug I need to investigate in. They are supposed to keep track of all names that were found with their names index key so we can monitor changes over time.

We also store the md5 hash for all archives, so we can check if the entire archive has changed in the imports:

```
 attempt |    date    |  state   |               md5                
---------+------------+----------+----------------------------------
       1 | 2020-02-12 | FINISHED | 5DB2722068D2A8579462CFBC800EE8EA
       2 | 2020-03-16 | FAILED   | 14FF9570BCE2C677DB7E3413CF8F8D09
       3 | 2020-03-16 | FINISHED | 14FF9570BCE2C677DB7E3413CF8F8D09
       4 | 2020-03-19 | FINISHED | 14FF9570BCE2C677DB7E3413CF8F8D09
       5 | 2020-05-04 | FINISHED | C7E1AF9CAEC76D43768EC6BC14A13EC9
       6 | 2020-06-01 | FINISHED | 6B08D9AD104F907422DBB9632ACCD02B
       7 | 2020-06-01 | FINISHED | BF5F58366AC5302D4013606CC1CE77E3
```

That seems to be the case. Only the march imports 2, 3 and 4 share the exact same archive file.
But what has changed in those files?

We can at least look into the text tree files which were generated just fine:
http://api.catalogue.life/download/metrics/dataset/073/2073/tree/

If you diff 7 vs 6 and vs 5 these are identical. But they do not show ids, just the names themselves. Archive number 4 from march is different and contains other species.

**Comment by mdoering** [comment]
It is a genuine decision matching bug. I will revert the decision subject ids to the ones from the stored original id and fix the matching bug tomorrow.

**Comment by mdoering** [comment]
I have reapplied all original ids where they existed. Older decisions did not yet have an original id.
344 decisions remain without a subject_id, i.e. are still broken:

```
 subject_dataset_key |    date    | count 
---------------------+------------+-------
                1015 | 2020-01-06 |     7
                1021 | 2020-01-07 |     1
                1021 | 2020-03-02 |     4
                1027 | 2020-01-06 |    54
                1027 | 2020-02-18 |     1
                1189 | 2020-01-14 |    84
                1206 | 2020-02-18 |     7
                1206 | 2020-02-19 |    10
                1206 | 2020-02-24 |     4
                2073 | 2020-03-18 |   169
                2130 | 2020-05-20 |     3
```

@yroskov can we simply remove those?

**Comment by mdoering** [comment]
@yroskov There are still red and orange tasks for SF+, is this expected?

<img width="1292" alt="Screenshot 2020-06-05 at 10 19 44" src="https://user-images.githubusercontent.com/327505/83853846-28920a00-a716-11ea-9c70-d6c08f32a244.png">

**Comment by yroskov** [comment]
ACC-ACC species (different authors) orange task was resolved before. Not sure about Identical Genus.
Other pink and orange task are "vaild".

**Comment by mdoering** [comment]
fixed rematching deployed to prod. Rematched draft via API cause 36 updates, but still left 1578 decisions as broken. We should look into them or maybe even delete them.
