### ISSUE TITLE
Search for taxon name in Project - Assembly does not work

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#749]
Frontend version: 45351db May 28, 2020 3:01 AMBackend version: 7cdfbaf June 4, 2020 6:59 AM

Taxon name search in Project - Assembly does not work. (Page reload and re-logging did not fix a problem).

**Comment by mdoering** [comment]
@yroskov can you please leave a link, if possible even from the API call if it is a backend problem?
