### ISSUE TITLE
Name status is replacing author strings

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#760]
There might be a new bug where the name status is replacing the author strings in newly imported datasets. Here's an example:

https://data.catalogue.life/dataset/2144/name/846548
https://api.catalogue.life/dataset/2144/nameusage/search?NAME_ID=846548

The verbatim info is correct and here's the data line from Name.tsv:

ID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspeciesEpithet | code | status | link
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
846548 | Rosanae | NULL | superorder | Rosanae | NULL | NULL | NULL | NULL | botanical | http://purl.obolibrary.org/obo/NOMEN_0000383 | https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=846548

**Comment by mdoering** [comment]
That's the current behavior that I am addressing in the scrutiny branch. Nomenclatural remarks and the scrutinizer are added to the name. By using the verbatim authorship in the future this will not happen anymore, so please ignore this silly "artifact" for now
