### ISSUE TITLE
Missing vernacular names for Dutch Species Register

### ISSUE THREAD

**Issue by ayco-at-naturalis** [CatalogueOfLife/backend#761]
I can see the archive has been harvested (2019-12-04) and that it contains a lot of vernacular names, but searching for them never returns any result.

For example I verified "pimpelmees" (blue tit) is there, but http://api.catalogue.life/nameusage/search?q=pimpelmees&datasetKey=2014 did not yield results.

**Comment by mdoering** [comment]
Looks like the dataset is not indexed into ES at all.
A relict from the pain of reindexing...

You can find the record in the db driven verbatim search:
https://data.catalogue.life/dataset/2014/verbatim?q=pimpelmees

**Comment by mdoering** [comment]
I have started a reindexing of the dataset

**Comment by mdoering** [comment]
> Successfully indexed dataset 2014 into index prod-nu. Usages: 84391. Bare names: 0. Total: 84391.

works now

**Comment by mdoering** [comment]
see also https://github.com/CatalogueOfLife/clearinghouse-ui/issues/452 for monitoring this problem
