### ISSUE TITLE
Use BibJSON instead of CSL-JSON

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#765]
CSL-JSON is very flexible and has lots of alternative fields (e.g. small, large, medium, verbatim, ...) and is implemented differently at the major players. It has proven very difficult to work with during implementation. The official biggest benefit to use differetn CSL formats to render different kind of citations also does not work as expected. The Java library is running the javascript reference implementation under the hood and is very slow. It takes a second to generate a single citation string. The JS library itself carries lots of dependencies and is rather large for the frontend. Rendering single citations is not what the library is made for (it builds bibliographies, i.e. list of citations). To do so you need to hack it.

Suggest to use the battle proven [BibTex](https://en.wikipedia.org/wiki/BibTeX) standard or its slightly more modern [BibJSON](http://okfnlabs.org/bibjson/) friend, which breaks down authorships to individual authors but otherwise is very close to BibTex ported to JSON.

**Comment by thomasstjerne** [comment]
The CSL library was only used for rendering and has already been removed from the UI.
However, effort has been put in development of a rather extensive set of forms supporting the CSL standard.
Consider consequences of switching format. Can this be done transparently for the UI with reuse of the existing form set?

**Comment by mdoering** [comment]
I doubt its exactly the same, but the basics with properties tied to a reference `type` is the same.

**Comment by mdoering** [comment]
[EML 2.2 now allows supports BibTex](https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html).

**Comment by sommer-gei** [comment]
FYI: here is [a comment from one of the developers, from 2020](https://github.com/okfn/bibjson/issues/3#issuecomment-595522890) (and the rest of the discussion may also be interesing)

> We developed BibJSON 10 years ago . We tried to get update then but with limited success. I don't think anyone uses it now. So I suspect that none of us would be too worried to see CSL js used.

**Comment by mdoering** [comment]
Thanks. Yes, I have seen that before. And after using CSL-JSON for some years now I dont think we should make a switch. CSL-JSON does lack some standardisation and isn't exactly the simplest format to work with. But as we sailed most of the rough waters already I dont think we need to swim through yet another sea.
