### ISSUE TITLE
Decisions do not work in prod

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#766]
Frontend version: c99dba2 June 17, 2020 9:47 AMBackend version: 507800e June 17, 2020 8:53 AM
@mdoering @thomasstjerne 

Step 1. Selected name, chosen decision:
![image](https://user-images.githubusercontent.com/28574252/85430492-caeb2380-b545-11ea-9855-5c30e9283429.png)

Step 2. Pushed button Apply Selected Decision (nothing happened)
![image](https://user-images.githubusercontent.com/28574252/85430741-287f7000-b546-11ea-8483-42cf9eb56624.png)

Step 3. Decision field is empty, even after refreshing a page in a browser
![image](https://user-images.githubusercontent.com/28574252/85430882-595fa500-b546-11ea-8eae-368bcd90e18b.png)

**Comment by yroskov** [comment]
In a case of Complex Decision: error code 403

![image](https://user-images.githubusercontent.com/28574252/85431323-fe7a7d80-b546-11ea-8462-fe801dee790e.png)

**Comment by gdower** [comment]
I think was just a permissions issue with the dataset. I added you as editor. Please try again and re-open this if it still doesn't work.

**Comment by yroskov** [comment]
All are the same. Neither decision is working. (After re-log in as well)

**Comment by yroskov** [comment]
Works now. Both. Thanks!
