### ISSUE TITLE
Illegal value for parameter DATASET_KEY: 3LR

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#767]
nameUsage search doesn´t support the latest release shorthand parameter:
https://api.catalogue.life/nameusage/search?USAGE_ID=845cc5f9-f5f5-4757-9bd2-f7e5a1863a09&DATASET_KEY=3LR

**Comment by mdoering** [comment]
Ha, the filter currently is case sensitive and expects `datasetKey`. I will make that insensitive
