### ISSUE TITLE
Name usage search for name type hybrid formula is missing a lot of names

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#768]
World Plants has lots of hybrids, but name usage search only finds 2 names for hybrid formula name types:

https://data.catalogue.life/dataset/2147/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic&type=hybrid%20formula
https://api.catalogue.life/dataset/2147/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic&type=hybrid%20formula

Here's one that's missing which has notho=specific:

https://data.catalogue.life/dataset/2147/name/4b91c49a-a3a7-5a91-90ed-bb07e7503170

We added the remark "Hybrid taxon" to hybrids so it's possible to search verbatim for hybrid formulas:

https://data.catalogue.life/dataset/2147/verbatim?q=Hybrid%20taxon&type=col%3AName

**Comment by mdoering** [comment]
We distinguish between hybrid formulas and named hybrids in the API.
Hybrid Formulas cannot be parsed and therefore have their own NameType.hybrid_formula which you can search on as you did.

Named hybrids follow the standard linnean name structure, but have a hybrid sign somewhere to indicate at which level the hybridization has happened. This is what we capture by the notho property, these names are parsable and have a NameType=SCIENTIFIC.

If you want to search for them you can look for NameField=NOTHO which gets you just over 4500 names:
https://data.catalogue.life/dataset/2147/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&field=notho&limit=50&offset=0&sortBy=taxonomic

**Comment by mdoering** [comment]
I cant see sth wrong with that, but if you still spot sth please reopen
