### ISSUE TITLE
POSTing a new child taxon gives 404 dataset does not exist

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#770]
But the child taxon is there after a reload, so probably just wrong response in the webservice?
<img width="719" alt="Screenshot at Jun 26 14-33-19" src="https://user-images.githubusercontent.com/1666484/85857497-46eda180-b7ba-11ea-9a54-c492b9cf2eed.png">

**After reload:**

<img width="482" alt="Screenshot at Jun 26 14-33-51" src="https://user-images.githubusercontent.com/1666484/85857506-4a812880-b7ba-11ea-8f81-e9fabf88967c.png">

**Comment by mdoering** [comment]
hm, does the parent exist?
I get a 404 with   
> "message": "Taxon 2067:b377666d-b560-462b-ae14-ef3113e5bd80 does not exist"

**Comment by mdoering** [comment]
also that test child does not exist now. Did you remove it? Or was it maybe a UI artifact and never was created?

**Comment by mdoering** [comment]
I cannot reproduce this. I can create children just fine on dev. Just I have to reload the page for them to show in the UI
