### ISSUE TITLE
Add Cache-Control headers

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#774]
The backend should set appropriate Cache-Control headers so clients and [our varnish](https://github.com/CatalogueOfLife/deploy/issues/1) can cache responses appropriately.

All responses from API methods that belong to releases should have be able to be cached.
Setup a response filter that knows about released dataset keys and sets the headers

**Comment by mdoering** [comment]
@MattBlissett which headers should the backend define? Is `Cache-Control` alone good enough or should we also define `Expires` or others?

According to here Cache-Control overrules Expires and seems to be good enough:
https://support.nine.ch/artikel/varnish-cache-cache-mit-http-headern-steuern

But maybe it wont hurt to set both in case of other client software being used by users?

**Comment by mdoering** [comment]
@MattBlissett And what is a reasonable max-age in case the data can be cached basically forever?
Changing API response structures and maybe software related updates taking into account I would think 24h are reasonable?

**Comment by mdoering** [comment]
@MattBlissett any experience with authentication and Varnish?
Some responses depend on the authenticated user, others simply need to make sure the request is properly authenticated.

Should the backend set a `Vary` header or always set `Cache-Control: no-cache` for those requests when auth matters?

**Comment by MattBlissett** [comment]
Just set `Cache-Control`, `Expires` is long obsolete.  24 hours seems reasonable to me too.

Could the authenticated response be cached? If so, we can configure Varnish to allow that, and the Vary header will help: https://varnish-cache.org/docs/trunk/users-guide/increasing-your-hitrate.html#authorization

**Comment by mdoering** [comment]
I would think in many cases the Authorization header is given with every request, even if it is not needed.
I only set 24h cache control for GET requests, all POST, PUT, DELETE will be requesting no-cache anyhow and these are usually the ones that require Auth.

In some few cases the header is truely needed for GET requests though and should be respected by varnish. 
Maybe 24h is not a good idea in such cases as it would mean a changed password or JWToken would not be checked as ti never hits the backend? But a shorter TTL like 1h might still be good. Let me see how many cases there actually are, might just be one or two if it comes to releases.

**Comment by mdoering** [comment]
It doesnt really matter for GET requests against releases. Lets simply ignore the Auth header
