### ISSUE TITLE
Vernacular names are not syncing for most GSDs

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#787]
For most GSDs the [vernacular names are not syncing](https://docs.google.com/spreadsheets/d/1BC0O5-zCJ7Ndl1SNUcZS2lPy1yT-jVAi-XzozzV-nzg/edit#gid=2097276737), but the vernacular names are present in the source databases:

https://data.catalogue.life/dataset/1010/imports
https://data.catalogue.life/catalogue/3/dataset/1010/taxon/23043

I've been looking for errors in the logs, but have not found anything so far and the syncs completed successfully for FishBase. The statistics for the sync show's 0 vernacular names for sector Elasmobranchii which contains taxon 23043 above:

https://api.catalogue.life/dataset/3/sector/3006/sync/6

Previously Elasmobranchii had 24,385 vernacular names:

https://api.catalogue.life/dataset/3/sector/3006/sync/4

**Comment by mdoering** [comment]
Ouch, this is a bug indeed. Every sector can be configured to sync vernacular names, distributions and bibliographic references via the `entities` property. If null is given the default is applied which copies all 3. Most sectors do have an empty list thuugh, not null. Which means the default is not applied and none of the 3 entities are copied!!!

For project 3 this is currently the vast majority:

```
 entities | count 
----------+-------
          |    38
 {}       |   659
```

So 659 sectors would have none of the "extended" information being synced.
I am afraid we will have to repeat the sync for all of them once I fixed this. As there are only 38 without I reckon it's safe to just sync all again.

**Comment by mdoering** [comment]
I am updating all sectors to have entities=[`distribution`, `vernacular`, `reference`], but we better need a UI change soon: https://github.com/CatalogueOfLife/clearinghouse-ui/issues/673

**Comment by mdoering** [comment]
all sectors updated, but I'd like to also deploy a backend adjustment to handle sector defaults via dataset settings so we can change ALL sector entities for a project unless they are specifically configured

**Comment by gdower** [comment]
@mdoering, okay, let me know when you deploy so that I can start the sync all. Ideally if we can sync all today or tomorrow, we might still be able to do a July release.

**Comment by mdoering** [comment]
Deployed to prod and tested the Collembola sector to make sure it's working fine. Distributions did get copied

**Comment by mdoering** [comment]
FishBases Myxini sector also copied vernaculars.
Check the sync history to see how the numbers changed over time (@yroskov @thomasstjerne @gdower we should really show this as a [timeline](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/73) to quickly grasp changes in numbers):

<img width="1637" alt="Screenshot 2020-07-17 at 18 13 47" src="https://user-images.githubusercontent.com/327505/87808005-4bf1be00-c859-11ea-93f6-61ad53858c18.png">

https://data.catalogue.life/catalogue/3/sector/sync?sectorKey=3004
