### ISSUE TITLE
Releases are not generating exports

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#789]
Releases used to generate an export before starting indexing, but now release does not seem to be generating an export. Instead I have been running ac-export on the cloned dataset after it enters the indexing stage, which I think is safe to do?

**Comment by mdoering** [comment]
Yes, thats the change I implemented and reported a while ago.
Releases and exports are decoupled.

**Comment by mdoering** [comment]
And yes, @gdower it's safe to run the export while the indexin is running in the release step!
