### ISSUE TITLE
DownloadException probably from GitHub authentication

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#791]
I think there may be an authentication issue with the CatalogueOfLife private repos, because the import fails with a 404 error:

DownloadException: Download of https://github.com/CatalogueOfLife/data-world-spider-catalog/archive/master.zip failed. life.catalogue.common.io.DownloadException: Download of https://github.com/CatalogueOfLife/data-world-spider-catalog/archive/master.zip failed. http 404 Not Found for URL https://github.com/CatalogueOfLife/data-world-spider-catalog/archive/master.zip

I can just upload the zip archive for now.

**Comment by mdoering** [comment]
Looks like all private repo URL fail currently

**Comment by mdoering** [comment]
Somehow the old github bot user was invalid. I had to create a new bot `col-data` that is used now, but which needs a new personal access token so I also had to redeploy the backen API on both envs

**Comment by mdoering** [comment]
works on dev. I did not try to import on prod and leave that to you, @gdower
