### ISSUE TITLE
Assembly: replace sector Apoidea superfamily; error 400

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#795]
Frontend version: 46d3c9c July 17, 2020 10:52 AMBackend version: 0e593ee July 30, 2020 5:52 AM

Re-assembly of ITIS.

I have deleted family sectors in Apoidea superfamily. Then, drag&drop Apoidea from ITIS, replace. Get notice "Request failed with status code 400":
![image](https://user-images.githubusercontent.com/28574252/89225120-52916c80-d59f-11ea-962d-72f76d61504a.png)

**Comment by mdoering** [comment]
The error says "Sector already exists". You can only create one sector from Apoidea in ITIS in CoL.
@thomasstjerne can increase the visibility of the error reason/message? Not every error is an API problem. Especially the 400 ones need to be read by users. I already improved the messages, but still

**Comment by mdoering** [comment]
the existing sector was created just today:

<img width="1561" alt="Screenshot 2020-08-03 at 22 56 20" src="https://user-images.githubusercontent.com/327505/89226682-a4a4b300-d5dc-11ea-820d-159434c97a37.png">

**Comment by mdoering** [comment]
... and appears to have been symced already
