### ISSUE TITLE
I have broke sync process

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#797]
Frontend version: 73e66a2 August 4, 2020 9:02 AMBackend version: 8aee689 August 6, 2020 2:26 AM

Assembling ITIS, I have broke sync process. Assembly and syncs of Curaliidae (1 spp) & Joppeicoidea (1 spp) were successful. 

**However, syncs in other assembled sectors were reported as failed: Thaumastocoridae, Reduviidae, Velocipedidae**
https://data.catalogue.life/catalogue/3/sector/sync?limit=25&offset=0

![image](https://user-images.githubusercontent.com/28574252/89577140-dd6ba480-d7f5-11ea-9451-5e95340819be.png)
 
@mdoering What's happened?

**Comment by mdoering** [comment]
There is a bug in the code. I will fix that before you wake up:

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.VernacularNameMapper.create (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO vernacular_name_3 ( 
    dataset_key,
     
    taxon_id,
    verbatim_key,
    name,
    latin,
    language,
    country,
    area,
    sex,
    reference_id,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    'b7e8ff06-e635-4bf4-9f9e-e8c013db7a57',
    NULL,
    'Thaumastocorids',
    'Thaumastocorids',
    'eng',
    NULL,
    NULL,
    NULL,
    NULL,
    10,
    102
   , now(), now())
RETURNING * was aborted: ERROR: null value in column "id" violates not-null constraint
  Detail: Failing row contains (null, 3, null, 10, 102, 2020-08-06 19:45:27.091041, 2020-08-06 19:45:27.091041, eng, null, b7e8ff06-e635-4bf4-9f9e-e8c013db7a57, Thaumastocorids, Thaumastocorids, null, null, null).  Call getNextException to see other errors in the batch.
```

**Comment by yroskov** [comment]
Another try on 2020-08-07
Frontend version: 73e66a2 August 4, 2020 9:02 AMBackend version: 8aee689 August 6, 2020 2:26 AM

Search for Thaumastocoridae gives 2 entries: 
![image](https://user-images.githubusercontent.com/28574252/89649019-bb216780-d885-11ea-8746-0a6b9a8c10d2.png)

No one shows final results in the Tree:
![image](https://user-images.githubusercontent.com/28574252/89649155-ef952380-d885-11ea-8cd5-0422163b5a7e.png)

Sync of Thaumastocoridae failed.

**Comment by yroskov** [comment]
Search for Reduviidae also has no results in the Tree:

![image](https://user-images.githubusercontent.com/28574252/89649440-6b8f6b80-d886-11ea-8b6f-2a6e5e0032b6.png)

**Sync failed.**

**Comment by yroskov** [comment]
Operations with two new sectors. Syncs also failed.

Steps:

2020-08-07   drag&drop infraoder Dipsocoromorpha; (before deleted old superfamily)   attached; **Syncs failed**
--
2020-08-07   drag&drop infraoder Enicocephalomorpha; (before deleted old superfamily)   attached; **Syncs failed**

**Comment by mdoering** [comment]
Hi @yroskov, I havent deploye the fix yet to prod. Please wait until this issue is closed I do my best to get it deployed soon

**Comment by mdoering** [comment]
@yroskov the big is fixed and I have synced all the last 5 or 6 failed ITIS sectors again and they succeeded this time:
https://data.catalogue.life/catalogue/3/sector/sync?limit=25&offset=0

**Comment by yroskov** [comment]
Great. Thanks! It works now
