### ISSUE TITLE
Sector sync fails on dev

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#799]
Request failed with status code 500
There was an error processing your request. It has been logged (ID 9557b87d3e5ace2e).

HTTP method: POST

https://api.dev.catalogue.life/dataset/3/sector/sync

Body:
{"sectorKey":5,"key":5,"target":{"id":"95354ae6-31a7-404c-bab4-12d15b32f946","name":"Choanozoa","rank":"phylum"},"subject":{"name":"Ichthyosporea","rank":"class"}}

**Comment by mdoering** [comment]
I'll look into this.
The posted body is suspicous though. It looks more like a full sector object.
Instead the above POST resource expects one of the following:

```
boolean all = false;
Integer sectorKey;
Integer datasetKey;
```

It allows to trigger syncs for an entire project (all=true), all sectors from a given source dataset (datasetKey=1234) or just a single sector (sectorKey=1234)

**Comment by mdoering** [comment]
Ah, that bug was fixed already but only deployed to prod. A minute...

**Comment by mdoering** [comment]
deployed
