### ISSUE TITLE
Sector delete fails on higher ranked synonyms

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#802]
SectorDelete tries to keep higher taxa down to genus level and thus issues deletes of usages and names based on their rank.
Apart from the zoological section rank problem there is also a problem with synonyms which often have a different and higher rank than their accepted name, e.g. the genus `Microchthonius` is a synonym for the currently accepted subgenus `Chthonius subgen. Microchthonius` in ITIS.

@yroskov is it fine to simply delete all synonyms, even if they belong to higher taxa when we delete a sector?

**Comment by yroskov** [comment]
Yes, deletion of all synonyms in the classification is expected behavior.
