### ISSUE TITLE
Disaster in Arachnida ITIS: attachments go to wrong places in the classification

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#803]
Frontend version: 1b442e9 August 12, 2020 4:38 AMBackend version: 9b67c47 August 12, 2020 6:42 AM
@mdoering @gdower 

Doing assembly of ITIS sectors in Arachnida, I have drag&drop orders Amblypygi & Palpigradi from ITIS to assembly tree. 

Expected behavior: both orders will appear in Arachnida - superorder Not assigned - orders Amblypygi & Palpigradi.

However, result was unexpected: Arachnida - superorder Not assigned - **order** Araneae - **order** Amblypygi 
and
Arachnida - superorder Not assigned - **order** Opiliones - **order** Palpigradi 

![image](https://user-images.githubusercontent.com/28574252/90168931-75700d80-dd63-11ea-8892-a2f8834dc5cd.png)

1) Incorrect placement
2) Incorrect hierarchy: order under order

@mdoering After you find and fix a problem, would you please bring Arachnida classification from GSD 2028 in CoL-draft, without sectors & species

**Comment by mdoering** [comment]
@yroskov I cannot see that problem. In my view it is perfectly fine like you expected:

<img width="784" alt="Screenshot 2020-08-14 at 14 25 14" src="https://user-images.githubusercontent.com/327505/90249032-0c0efe00-de3a-11ea-9c1f-af7a51d82453.png">

@thomasstjerne could this be a rare UI tree issue? From the screenshot @yroskov posted all syncs have completed, so it should not be a temporary "move aside" problem by the backend syncs. @yroskov did you try to refresh your view and it remained?

**Comment by yroskov** [comment]
3 h after my report, I have killed these 2 sectors and re-done assembly. Now results are correct.
