### ISSUE TITLE
Ranks bug introduced by series patch

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#807]
Nestor spotted that a lot of the ranks were messed up catalogue-wide by the series patch:

https://api.catalogue.life/dataset/3LR/nameusage/search?facet=rank&facet=decision_mode&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&rank=series&sortBy=relevance&q=Pipistrellus%20nathusii

The rank species got changed to series and a lot of the higher taxa are different as well.

The bug also affects ranks for past releases:

https://api.catalogue.life/dataset/2165/nameusage/search?facet=rank&facet=decision_mode&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&rank=series&sortBy=relevance&q=Pipistrellus%20nathusii

**Comment by mdoering** [comment]
there is no series patch. Only a few new ranks.
But ES index keeps the ranks as int ordinals and therefore that mapping has changed. 
Grrr, that means we need to reindex all data into ES. @ayco-at-naturalis thats your issue too I bet

**Comment by mdoering** [comment]
It will unfortunately take more than a day.
@gdower any datasets that you would like to see updated asap? 2165 and 3 and ???

**Comment by gdower** [comment]
That's not a problem. I'll reply back and say that we need to reindex which will take a day.

I'd prioritize the 2166 which is the [3LR](http://api.catalogue.life/dataset/3/latest) that Nestor is trying to crawl, and then 3.

**Comment by mdoering** [comment]
running

**Comment by ayco-at-naturalis** [comment]
Storing the ordinal of an enum (albeit still as a string) makes you susceptible to this yes, but it also makes the index that much more compact and (marginally) faster. However if the rank enum can be expected to change often, then it's better to store the string value. @mdoering Let me know what you want

**Comment by mdoering** [comment]
storing as ordinal is fine, rank changes should be very rare
