### ISSUE TITLE
The importer fails on dev

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#809]
There was an error processing your request. It has been logged (ID 1bd7406e26912950).

**Comment by mdoering** [comment]
its when the importer is turned off. 
with the running deploy you should get an unavailable response instead. Importer can be turned on in the admin background settings - but it takes some 30s or so

**Comment by mdoering** [comment]
<img width="888" alt="Screenshot 2020-08-18 at 15 56 50" src="https://user-images.githubusercontent.com/327505/90522021-85289100-e16b-11ea-86e8-0411280bc6c2.png">
<img width="383" alt="Screenshot 2020-08-18 at 15 56 38" src="https://user-images.githubusercontent.com/327505/90522027-86f25480-e16b-11ea-9eb6-925140773f48.png">
