### ISSUE TITLE
Facilitate exact matching in name usage search

### ISSUE THREAD

**Issue by ayco-at-naturalis** [CatalogueOfLife/backend#811]
Name usage search now facilitates "prefix" (a.k.a. starts-with) and "fuzzy" matching. There seems to be a need for exact matching.

@mdoering @gdower Would you like me to implement this? And would "exact" matching still at least be case-insensitive? (I would say so)

**Comment by mdoering** [comment]
Thats probably useful. But if we add this we should probably switch from boolean flags to sth like a single `searchtype` parameter  with values `prefix`, `exact`, `fuzzy` or  `null/default`

exact would do a case insensitive match against the scientificName

**Comment by yroskov** [comment]
Exact match should not be case sensitive

**Comment by ayco-at-naturalis** [comment]
ok -all noted

**Comment by ayco-at-naturalis** [comment]
@yroskov Would you mind if I start out with "exact matching" in a case-insensitive manner? Currently only the lower-cased version of the scientific name is indexed. Meaning that if you want to match on the pure, unaltered name, we would have to index that name as well, meaning we would have to re-index everything all over again, which would probably make @mdoering rather unhappy.

@mdoering if you do **not** mind, I'll go for that straight away.

Note that "exact matching" in a case-insensitive means that, when searching for "homo sapiens", you will get "Homo sapiens" and in theoretical cases also "HOMO SAPIENS". But you wouldn't get (for example) "homo-sapiens" or even "homo     sapiens". If you would search for "covid-19", you would find "COVID-19", but not "COVID 19". So it's already pretty restrictive.

**Comment by mdoering** [comment]
go for it!

**Comment by ayco-at-naturalis** [comment]
@mdoering I'm almost done. Do you want me to push? The search functionality would probably start to behave a bit erratically once you deploy until you have also re-indexed ....

@thomasstjerne (and @gdower @yroskov)

Instead of prefix matching (true or false), you now have a **searchType** parameter, which can have these values: EXACT, WHOLE_WORDS, PREFIX.

You still also have the fuzzy parameter, which is honoured for WHOLE_WORDS and PREFIX, but ignored for EXACT matching.

For the suggestion service the searchType parameter is ignored. It is always PREFIX. Exact and whole-word matching defy the purpose of auto-completion. You can still choose between fuzzy and non-fuzzy though.

**Comment by ayco-at-naturalis** [comment]
PS the default is still what it was, i.e. **not** PREFIX, i.e. WHOLE words. Or would you ratther have another default search type?

**Comment by mdoering** [comment]
@ayco-at-naturalis this needs a reindex? If so, can we please add a new parentID field to the ES document?
See https://github.com/CatalogueOfLife/backend/issues/827#issuecomment-685696308

**Comment by mdoering** [comment]
I think WHOLE words is good as the default

**Comment by ayco-at-naturalis** [comment]
> @ayco-at-naturalis this needs a reindex? If so, can we please add a new parentID field to the ES document?
> See [#827 (comment)](https://github.com/CatalogueOfLife/backend/issues/827#issuecomment-685696308)

OK - will do

**Comment by mdoering** [comment]
@ayco-at-naturalis the http params have not changed and still look for boolean flags.
The project doesnt compile right now.

Should we call the new param just `type` or rather `searchtype` ?

**Comment by mdoering** [comment]
Note I also touched on search code today and merged some new suggest features in, see #832

**Comment by mdoering** [comment]
@ayco-at-naturalis Does the index need to be rebuild now or can we continue with the current one?
we wont be able to deploy to prod this week in that case

**Comment by mdoering** [comment]
Or can we use the current index as long as we dont use the new exact search?

**Comment by ayco-at-naturalis** [comment]
Not sure if this is still actual, but (if I am correct with my saturday morning brains), you don't **need** to re-index and you can (and must) use the new searchType parameter. Only: _exact matching won't work until you re-index_

**Comment by ayco-at-naturalis** [comment]
> @ayco-at-naturalis the http params have not changed and still look for boolean flags.
> The project doesnt compile right now.
> 
> Should we call the new param just `type` or rather `searchtype` ?

Huh? I _did_ add the searchType parameter (+ enum): https://github.com/CatalogueOfLife/backend/blob/master/api/src/main/java/life/catalogue/api/search/NameUsageRequest.java

Note that you can independently vary the search type and the fuzzy option (with some restrictions). @thomasstjerne: see here:https://github.com/CatalogueOfLife/backend/blob/master/api/src/main/java/life/catalogue/api/search/NameUsageRequest.java#L18

**Comment by mdoering** [comment]
there are more places where the parameter is exposed, specifically the NameUsageSearchResource:
https://github.com/CatalogueOfLife/backend/commit/91773c3e3a0290e9941bcc64f07ce9bff186503b

**Comment by mdoering** [comment]
all works fine now and prod is reindexed
