### ISSUE TITLE
Problems with the Search (Acanthocephala as an example)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#812]
Frontend version: a882e1f August 19, 2020 4:44 AMBackend version: 15de523 August 17, 2020 3:14 AM
on prod

There are two taxa in CoL:
Acanthocephala Rudolphi, 1802 as a phylum
and 
Acanthocephala Laporte, 1833 as a genus

Mode: Assembly (**CoL, project 3** in the left; **ITIS CoLDP** in the right).

**Comment by yroskov** [comment]
**Search for Acanthocephala in CoL project 3 in a left frame.**

Step 1. Search for **Acanthocephala** in CoL project 3 in a left frame.
**There are 3 Acanthocephala names in context menu.** 
(User does not know, what is what (no rank, no authorstring) - as we designed it, and it might be fine, because we had relatively small number of homonyms in old CoL. If number of homonyms will be higher due to synonyms and various regional resources, an absence of ranks and authorstrings in context search menu may become a big problem).

![image](https://user-images.githubusercontent.com/28574252/90644029-e39c5080-e1f9-11ea-8243-6a83dedf50bd.png)

Step 2. Chose first **Acanthocephala**, go to phylum Acanthocephala Rudolphi, 1802 - expected behaviour
![image](https://user-images.githubusercontent.com/28574252/90644851-d9c71d00-e1fa-11ea-917a-b9217c87419e.png)

Step 3. Chose third **Acanthocephala**, go to phylum Acanthocephala Rudolphi, 1802 again. **Unexpected behaviour.** It supposed to go to genus Acanthocephala Laporte, 1833.

![image](https://user-images.githubusercontent.com/28574252/90645154-3cb8b400-e1fb-11ea-936a-57f1a6736a30.png)

Step 4.  Chose second line **Acanthocephala (synonym of Acanthocephala)**, ah! it refers to genus, but reports an error:  
![image](https://user-images.githubusercontent.com/28574252/90645300-6a9df880-e1fb-11ea-8033-2eb12a81bc4a.png)

**Comment by yroskov** [comment]
**Search for Acanthocephala in ITIS CoLDP  in a right frame.**

Step 1. Search for Acanthocephala in ITIS CoLDP  in a right frame.

Haha, changes appear every moment. Now I have about 30 Acanthocephala in context menu.

![image](https://user-images.githubusercontent.com/28574252/90646185-88b82880-e1fc-11ea-960d-22d78e52dc77.png)

**Comment by mdoering** [comment]
The search index is still rebuilding. Please dont log any search problems until thats over.
Sorry for the inconvenience, I am surprised myself how hard it is this time to get the index updated completely.

**Comment by yroskov** [comment]
Let's do it again:

Step 1. Search for Acanthocephala in ITIS CoLDP in a right frame.
There are 3 Acanthocephala, plus line Acanthocephala (synonym of Acanthocephala):

![image](https://user-images.githubusercontent.com/28574252/90646879-4e9b5680-e1fd-11ea-869f-592c81a6fbd7.png)

Step 2. Chose first Acanthocephala, go to genus Acanthocephala Laporte, 1833:

![image](https://user-images.githubusercontent.com/28574252/90647057-86a29980-e1fd-11ea-990d-d246b8a5dd21.png)
 
Step 3. Chose second Acanthocephala, go to genus Acanthocephala Laporte, 1833:
Step 4. Chose third Acanthocephala, go to genus Acanthocephala Laporte, 1833:

Step 2. Chose **Acanthocephala (synonym of Acanthocephala)**, get error:
![image](https://user-images.githubusercontent.com/28574252/90647479-f7e24c80-e1fd-11ea-9bb5-75f0ff4c3a07.png)

**Comment by yroskov** [comment]
Aaah, still indexing. It explains "vibrant" results.

**Comment by mdoering** [comment]
See also https://github.com/CatalogueOfLife/backend/issues/832
