### ISSUE TITLE
Cannot retrieve imports on dev

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#818]
Request failed with status code 500
There was an error processing your request. It has been logged (ID e53175763c9ebd89).

HTTP method: GET

https://api.dev.catalogue.life/importer?limit=10&offset=0&state=unchanged&state=finished&state=canceled&state=failed

**Comment by thomasstjerne** [comment]
Odd - works again now

**Comment by mdoering** [comment]
I did a redeploy that had a db change, API was done for a few minutes
(prod still is!)
