### ISSUE TITLE
Possible to add parent to the suggest response?

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#819]
I.e.:
```
{
 "match":"Blanidae",
 "acceptedName":"Blanidae",
 "usageId":"020a285f-a5a1-4079-a9e8-25f19c5c8d66",
 "rank":"family",
 "status":"accepted",
 "score":11.312289,
 "suggestion":"Blanidae",
 "parent": {
   "acceptedName":"ParentName",
   "usageId":"xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
}
}

```

This would help to provide some context in the suggests for sector target and subjects and in the tree searchboxes

**Comment by ayco-at-naturalis** [comment]
I will do this if you like Markus

**Comment by mdoering** [comment]
Is the parent usage id needed or should we just add a new `parent` field like we do in the sectors SimpleName class?

Note that `usageID` corresponds to `suggestion` not `acceptedName`.

**Comment by mdoering** [comment]
@ayco-at-naturalis thanks! I will quickly commit the model change for NameUsageSuggestion and then you can go!
Please try hard not to change the index structure, it has been very painful to reindex last week

**Comment by mdoering** [comment]
@thomasstjerne what should the parent be for synonyms? Identical to acceptedName?
Or the parent of the accepted name?
Or do we need acceptedName still if there is a parent?

**Comment by mdoering** [comment]
@thomasstjerne the `suggestion` field is meant to be shown in the UI and contain all information needed for the user.
Maybe we should just extend that with the parent information? Currently it is populated like this:

```
  /**
   * Returns a single-line suggestion string. Could be used to populate a drop-down list. 
   */
  public String getSuggestion() {
    if (vernacularName) {
      return String.format("%s (vernacular name of %s)", match, acceptedName);
    } else if (status == null) {
      return match + " (bare name)";
    } else if (status.isSynonym()) {
      return String.format("%s (%s of %s)", match, status.name().toLowerCase(), acceptedName);
    }
    return match;
  }
```

**Comment by mdoering** [comment]
I would suggest to rename NameUsageSuggestion.acceptedName into NameUsageSuggestion.parent
and populate it with the existing content for vernaculars or synonyms, but add the direct parents scientificName in case of accepted usages:

```
  /**
   * Returns a single-line suggestion string. Could be used to populate a drop-down list. 
   */
  public String getSuggestion() {
    if (vernacularName) {
      return String.format("%s (vernacular name of %s)", match, parent);
    } else if (status == null) {
      return match + " (bare name)";
    } else if (status.isSynonym()) {
      return String.format("%s (%s of %s)", match, status.name().toLowerCase(), parent);
    } else {
      return String.format("%s (%s)", match, parent);
    }
  }
```

**Comment by mdoering** [comment]
@ayco-at-naturalis I did not commit anything, just go ahead!

**Comment by ayco-at-naturalis** [comment]
NB This would never require re-indexation ... The NameSuggestion object is synthesized from existing data (i.e. the EsNameUsage document)

**Comment by ayco-at-naturalis** [comment]
@mdoering  Fixed this but forgot to adapt the unit tests. Will adapt the unit tests tomorrow. Will now push a commit where the failing nameusage suggestion tests are ignored, so you have a working build

**Comment by thomasstjerne** [comment]
> @thomasstjerne Is the parent usage id needed or should we just add a new `parent` field like we do in the sectors SimpleName class?
> 
> Note that `usageID` corresponds to `suggestion` not `acceptedName`.

It should be the parent of the accepted name. 

Is it possible to filter the suggest by using `status=accepted` ?
(When I use the suggest to search for taxa in the trees and for sectors, synonyms are irrelevant and will only confuse the user)

**Comment by ayco-at-naturalis** [comment]
Ah, sorry, yes I can add that filter

**Comment by ayco-at-naturalis** [comment]
@thomasstjerne (and @mdoering) just to make sure I understand you, a synonym has the same classification as the its excepted name, except that (in the ES data model) the classification always ends with the name usage itself. So you don't want the penultimate name but the pen-penultimate name in the list of names constituting the hierarchy.

**Comment by thomasstjerne** [comment]
> @thomasstjerne (and @mdoering) just to make sure I understand you, a synonym has the same classification as the its excepted name, except that (in the ES data model) the classification always ends with the name usage itself. So you don't want the penultimate name but the pen-penultimate name in the list of names constituting the hierarchy.

Yes!

**Comment by mdoering** [comment]
@thomasstjerne do I understand correctly that for synonyms you want 3 names in the suggestion line? the synonym, its accepted and the parent of the accepted? That seems a lot to me and I very much doubt we have cases where the synonyms and the accepted are the same but differ by its parent.

**Comment by thomasstjerne** [comment]
For synonyms it doesn´t matter - the use case is for seraching taxa in the trees
