### ISSUE TITLE
NameUsage importer not interpreting provisionally accepted status?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#820]
Is the importer not interpreting the `provisionally accepted` status for NameUsage.status, or am I doing the status column wrong? Here's an example if you look at the verbatim info:

https://data.catalogue.life/dataset/1164/name/Scorpiones-Scorpionidae-Pandinops-Pandinops%20boschisi

According to the [documentation](https://github.com/catalogueoflife/coldp#nameusage):

```
status: is the taxonomic name usage status which includes Synonym.status and the Taxon.provisional flag.
```

**Comment by mdoering** [comment]
looks like you spotted a bug
