### ISSUE TITLE
Tree Api does not update when a sector target is updated

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#822]
The sector key still sits on the old target

**Comment by mdoering** [comment]
It should be changing on dev already. But the target itself does not change, just its children

**Comment by thomasstjerne** [comment]
But after the sector update of this: https://api.dev.catalogue.life/dataset/2050/sector/10

Sector 10 still sits on 3rd child here
https://api.dev.catalogue.life/dataset/2050/tree/d56d883a-2fd7-4a55-a610-d256c55a466b--incertae-sedis--FAMILY/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=2050&type=CATALOGUE

I would have expected to see it on 2nd child here
https://api.dev.catalogue.life/dataset/2050/tree/fad714f9-7251-4af1-8c34-e316491f0293/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=2050&type=CATALOGUE

**Comment by mdoering** [comment]
Yes, investigating why that is.

**Comment by mdoering** [comment]
works now on dev. But the sector counts seem to misbehave afterwards...

**Comment by mdoering** [comment]
note that the search index has to be udpated for every decendant of the sector, i.e. all sector usages but also any included sector and its usages. This happens in the background, but for large sectors this might take a while. So search can be badly effected for some time
