### ISSUE TITLE
vulpes search yields unexpected results

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#823]
Searching for "Vulpes vulpes" and similar searches yield very unexpected results in various ways:

There is a taxon for `Vulpes vulpes (Linnaeus, 1758)` existing with a synonym `Canis vulpes Linnaeus, 1758`: 
https://data.catalogue.life/dataset/2204/taxon/e7670167-33e4-4c94-aa74-67fcc9a2aa3d

**(1)** "Canis vulpes" search hits nothing:
http://api.catalogue.life/dataset/3/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&q=Canis%20vulpes

**(2)** "vulpes" search limited to Mammalia hits nothing:
http://api.catalogue.life/dataset/3/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&TAXON_ID=a1f62645-d4bd-4948-9764-f163ae5ab1ec&q=vulpes

**(3)** "Vulpes vulpes" sorting by relevance does not yield "Vulpes vulpes" at the top (or anywhere?):
http://api.catalogue.life/dataset/3/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&sortBy=RELEVANCE&q=Vulpes%20vulpes

**(4)** using prefix=true also does not yield Vulpes vulpes.
But instead returns names with a different genus!!!
http://api.catalogue.life/dataset/3/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&sortBy=RELEVANCE&prefix=true&q=Vulpes%20vulpes

**Comment by mdoering** [comment]
Looks like the ES index is broken. Using an older release 2166 this looks better:

(1) http://api.catalogue.life/dataset/2166/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&q=Canis%20vulpes
-> hits Canis vulpes

(2) http://api.catalogue.life/dataset/2166/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&TAXON_ID=014cf0b2-5148-48a0-8e5a-60c55668b157&q=vulpes
-> hits the Vulpes genus first

(3) http://api.catalogue.life/dataset/2166/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&sortBy=RELEVANCE&q=Vulpes%20vulpes
-> by relevance the genus comes first, but then some other binomials. Not sure what Vulpes vulpes does not yield a higher relevance!

(4) http://api.catalogue.life/dataset/2166/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&sortBy=RELEVANCE&prefix=true&q=Vulpes%20vulpes
-> still returns genera with a different prefix!!!

**Comment by ayco-at-naturalis** [comment]
As for (3) my suspicion is that ES sees 2 identical search terms, so ditches one and then sees that there is only 1 exact match (on the genus) , which gets boosted out of reach for the other matches ... This is one more reason to implement exact match (on the **whole** scientific name): see #811 

Can this wait till next week?

**Comment by mdoering** [comment]
yes, that can wait til next week!

**Comment by mdoering** [comment]
exact match is implemented and index rebuilt. Results look much more useful now
