### ISSUE TITLE
Add size property to Sector?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#825]
When looking at [lists of sectors](https://data.catalogue.life/catalogue/3/sector?limit=100&offset=0) I often feel I want to know how large it is, i.e. how many usages are included.
We could add a size property based on the last sector sync metrics, just as we do for [dataset sizes](https://data.catalogue.life/dataset?created&limit=20&offset=0&origin&private&reverse=false&size&sortBy=size). It would then show the number of last synced usages existing in the target project. The size of the source might be different as we can block bits and ignore certain usages.

**Comment by mdoering** [comment]
@gdower @thomasstjerne @yroskov is this useful?

**Comment by yroskov** [comment]
If "usages" refers to number of species (i.e. accepted binomials) in the sector, it will be useful.

**Comment by mdoering** [comment]
No, it refers to taxa + synonyms of any rank.
It reflects the same counts as the search returns. A name usage is either a taxon, synonym or a "bare name", i.e. names that lack any taxon or synonym

**Comment by mdoering** [comment]
if use a different metric than it differs from search results and becomes inconsistent. Also there might be datasets without species. And it correspnds directly to the number of records in the database table.

**Comment by mdoering** [comment]
it is a coarse indicator of how much is in a sector (or dataset). We have detailed metrics for all kinds of specifics if needed. But as a single metric to pick this is the most general and I think also useful one.

**Comment by yroskov** [comment]
Total number of names in the sector is less informative. I never used such stats in my work with CoL.

**Comment by yroskov** [comment]
Only number of accepted species is important measure in taxonomic database. 
How much stats here https://itis.gov/ can tell you about completeness of species checklist?

Total number of synonyms/combinations might be a measure of "elaboration quality" of taxonomic database, or just a reflection of research history of the group. Total number of uninomials without accounting per rank, says nothing at all.

**Comment by mdoering** [comment]
Yuri, you can have all your stats when you look into the sector details. But as the most generic single number number of species does not make much sense. A sector without a species but lots of subspecies or hundreds of genera then becomes size=0.

**Comment by yroskov** [comment]
Sector with size=0 says exactly that it has no accepted species. I am using this in my routine practice.

What can say sector with size=8 names? It might be 1 fam + 1 gen + 6 spp, **or** 1 fam + 4 subfam + 2 gen + 0 spp, **or** 0 fam + 1 tribe + 1 subtribe + 2 gen + 1 sect + 1 sp, etc? How useful this figure of 8 might be, even, if I works with different versions of the same GSD?
