### ISSUE TITLE
As a developer/curator I need IRIs for data concepts to unambigously map my data to CoLDP

### ISSUE THREAD

**Issue by mjy** [CatalogueOfLife/backend#826]
As a developer, and user, I need to unambiguously link my data model to a CoL data concept. 

For example, in TaxonWorks there is no "extinct" field on an OTU.  However, a data curator can extend the OTU data model by creating data predicates.  Those predicates can in turn be cross referenced to an ontology term via IRI/URI, "my predicate has this meaning".  

We need IRIs so that TaxonWorks CoLDP exporter (and others I'm sure) can unambiguously identify that the data predicate attached to the OTU is in fact a field that should be included in a specific field in the CoLDP export.

Providing IRIs for those concepts will essentially pre-adapt the data model for consumption in the OWL/bioportal/obofoundary model as well.

Example:

Taxon#extinct -> URI for concept should look (something) like `http://api.catalogue.life/vocab/extinct` or `http://api.catalogue.life/vocab#extinct`  or `http://api.catalogue.life/vocab/iri/exting`.  Probably completely doable with the documentation/schema approach you are using?

Example in DWC:

`http://rs.tdwg.org/dwc/iri/earliestGeochronologicalEra`.  Let's TW  users create Predicate with this URI, and lets use dump that fact to CSV if provided.

Example in OBO/OWL

`http://bioportal.bioontology.org/ontologies/FISHO#FISHO_0000122` -> extinct!

**Comment by mdoering** [comment]
We have URIs for each ColDP term we are using, very similar to DwC.
They are managed in a [Java enumeration](https://github.com/CatalogueOfLife/backend/blob/master/api/src/main/java/life/catalogue/api/datapackage/ColdpTerm.java#L20) that defines a basic namespace and provides a simple, prefixed and fully qualified name (which is a URI) for the term. It also knows whether a term is a "class" term or a "property". Following DwC and DC conventions the property terms a lowerCamelCase, the class terms UpperCamelCase.

The list of all know terms are exposed in the vocabulary API:
http://api.catalogue.life/vocab/terms

You can filter the terms for a certain prefix, which is an alias for a namespace:
http://api.catalogue.life/vocab/terms?prefix=col

You cannot resolve each term right now, but I will add that today, it's trivial:
http://api.catalogue.life/vocab/terms/col:extinct

The resulting qualified name or URI for the coldp extinct term in any case is:
`http://catalogueoflife.org/terms/extinct`

**Comment by mdoering** [comment]
Do they need to resolve to anything specific?

**Comment by mdoering** [comment]
Btw, the official term IRI for DwC is http://rs.tdwg.org/dwc/terms/xxx, e.g. http://rs.tdwg.org/dwc/terms/earliestEraOrLowestErathem

The `dwc/iri` ones are later RDF additions that take as values also IRIs as you probably know.

**Comment by mjy** [comment]
@mdoering thanks for jumping on this, and clarifying IRI vs values.  Working with @gdower we were looking for `http://api.dev.catalogue.life/vocab/term/col:extinct`, but I think I want the qualified name here.  Will the qualified name resolve to something ultimately.

For the record I don't need think it needs to resolve to anything specific, I just want to use it as a concept identifier.

**Comment by mdoering** [comment]
Yes, http://api.dev.catalogue.life/vocab/term/col:extinct is supposed to be a IRI to be used to refer to coldp:extinct. The qualified name is exactly for that. We might resolve it at some point, probably to the API response for JSON and some RDF we still need to craft. 

Also note that the `catalogue.life` domain in temporary and we will move everything incl the API to catalogueoflife.org at some point this year.
