### ISSUE TITLE
acceptedNameUsageID for synonyms in the suggest response

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#827]
Could we include acceptedNameUsageID for synonyms in the suggest response please?

Also I think bare names should be excluded by default. We could have an `includeBareNames=true`  option, though, but I don´t see where we would use it

**Comment by mdoering** [comment]
I've added acceptedNameUsageID to the suggest response for synonyms. But I wonder if we should not instead add parentID for all usages regardless their status.

The backend currently takes the acceptedNameUsageID from the NameUsageWrapper.usage.parentId which is only accessible in the zipped payload. So we have to unzip the payload to get the id currently which is inefficient. @ayco-at-naturalis can we add  the usage.parentId to a new doc.parentId document field?

**Comment by ayco-at-naturalis** [comment]
@mdoering While I am doing this I am wondering, is acceptedNameUsageID of a synonym not in the classificationIds List? I thought that the synonym simply inherited the classification of the accepted name, with the synonym id itself as the very last item in the list.

So the acceptedNameUsageID would be the last-but-one item in the classificationIds list (synonym id -> accepted name id -> etc).

Anyway, apparently not, soI will continue adding the parentId (and populate it from the NameUsage.parentId) unless I get a signal

**Comment by mdoering** [comment]
Ah, I think you are right! Then there is no need for it really

**Comment by mdoering** [comment]
http://api.catalogue.life/dataset/3/nameusage/search?content=SCIENTIFIC_NAME&vernacular=false&status=SYNONYM&q=Puma

the accepted name usage id is the second last in the list!

**Comment by mdoering** [comment]
changed the code to use the classification instead, thanks for that!

**Comment by thomasstjerne** [comment]
This is deployed? 
I still dont see the acceptedUsageId in the suggest response

**Comment by mdoering** [comment]
indeed not there: http://api.catalogue.life/dataset/3/nameusage/suggest?q=Aa%20brev
http://api.dev.catalogue.life/dataset/2059/nameusage/suggest?q=Abas

Looks like its not working as expected, its deployed to both

**Comment by mdoering** [comment]
doh. True bug with bad comparison. Fixed and added proper test.
Gonna deploy after lunch
