### ISSUE TITLE
Review species estimate types

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#828]
We allow multiple species estimates on taxa, each with a `source` reference and `type` of estimate basis.

We want to capture different species estimates like:

 - estimated living (accepted) species recognized by an expert on a given date
 - estimated extinct species recognized today for fossil groups
 - estimated number of "species hypothesis" as of today for molecular/dark taxa
 - estimated total number of living species incl yet undiscovered by science

The [current vocabulary](http://api.catalogue.life/vocab/estimatetype) consists of 3 entries:

```
[
  {
    "name": "described species living",
    "description": "Estimate number of all extant species described with a linnean name."
  },
  {
    "name": "described species extinct",
    "description": "Estimate number of all extinct species incl fossils described with a linnean name."
  },
  {
    "name": "estimated species",
    "description": "Estimate number of all species including both described and yet to be discovered species."
  }
]
```

Is there a need to update the enumeration and its description/definition?

The [CoL concludes](http://www.catalogueoflife.org/annual-checklist/2019/info/hierarchy) the following:

> What does the species estimate mean?

> The CoL "estimate" is the number of living species in each taxon globally which are known to taxonomists at present time. Estimates do not include fossil species.

> This is not the same number as that for all species "ever described" through the history of taxonomy. There are many cases where the same species was described more than once under different names, and later experts in taxonomy synonymised these names under just one name, the correct one for that species. Taxonomists have described many more species than are currently recognised at present.

> The estimate is also not the same number as that which is predicted by including those species which are awaiting discovery, and thus not yet named.

**Comment by mdoering** [comment]
@dhobern @yroskov @thomasstjerne @olafbanki @gdower please comment if you think this needs an update

**Comment by mdoering** [comment]
Proposal:

 - **species living**: number of living species which are known to taxonomists at present time on a global scale and have been described by a Linnean name. Estimates do not include fossil species.
 - **species extinct**: number of extinct species which are known to taxonomists at present time on a global scale and have been described by a Linnean name. Estimates do not include living species.
 - **undiscovered species**: number of living species which are estimated to exist on a global scale, but have not yet been described by a Linnean name.
 - **OTU**: number of living _molecular_ species which are known to taxonomists at present time on a global scale, but do not have been described by a Linnean name.

**Comment by thomasstjerne** [comment]
I am happy with the existing ENUM. Maybe we could add the word _formally_ to the descriptions, i.e.
"Estimate number of all extant species formally described with a linnean name."

Related to our discussion at the meeting, I do not agree that undescribed species are not species. 

This is the kind of estimate of global fungal species richness I would expect to see in CoL (2.2 -3.8 million species):

https://doi.org/10.1128%2Fmicrobiolspec.FUNK-0052-2016 (Full text available here: https://www.researchgate.net/publication/318757663_Fungal_Diversity_Revisited_22_to_38_Million_Species)

**Comment by dhobern** [comment]
The formality is good. I am not convinced that we can get value out of the OTU one as defined. First, the term OTU does not necessarily refer to OTUs defined by molecular means. The Australian National Insect Collection is full of drawers containing a number of named species with sets of clearly different but unnamed forms separated out. These are probably mostly species and are morphologically determined OTUs. Secondly, and much more importantly, if we go with molecular OTUs, it will be perfectly reasonable to select very different numbers based on different portions of the genome and different algorithms. 

So I would recommend just using the first three terms rather than all four.

Lastly, would it not be better to replace **undiscovered species** with something like **estimated total species**? Almost everyone who make any use of this number will start by adding it to **species living** to get a sense of the current size of the taxon. I would expect that a fair number of those who supply values for this estimate will in any case give the estimated total rather than the difference, since this is a more commonly managed number.

**Comment by mdoering** [comment]
> Lastly, would it not be better to replace undiscovered species with something like estimated total species? Almost everyone who make any use of this number will start by adding it to species living to get a sense of the current size of the taxon. I would expect that a fair number of those who supply values for this estimate will in any case give the estimated total rather than the difference, since this is a more commonly managed number.

Agree. And it is what we currently have with `estimated species`. Then the proposal would be like this, basically just updating the existing values and definitions, but keeping the 3 "concepts":

 - **species living**: number of living species which are recognised by science at present time on a global scale and have been described by a Linnean name. Estimates do not include fossil species.
 - **species extinct**: number of extinct species which are recognised by science at present time on a global scale and have been described by a Linnean name. Estimates do not include living species.
 - **estimated total species**: number of living species which are estimated to exist on a global scale, including both already described and yet to be discovered species.

**Comment by yroskov** [comment]
"Estimated Species" is preoccupied term for your new "Species Living": CoL has been using it through last 5 years and populated it through Wikipedia. Please do not confuse our users with "Estimated Total Species" for a figure, which include undiscovered and undescribed species. New term is needed. Any suggestions?

**Comment by yroskov** [comment]
Species Projected 
Species Extrapolated 
Species Prognostic

**Comment by mdoering** [comment]
As CoL did not differ between the various estimations in the past it might not be too confusing. All of these are "species estimates", just based on a slightly different context. 

"projected species living" was I also had in mind just now.

**Comment by yroskov** [comment]
CoL clearly defined what is its meaning of "Species Estimates": http://www.catalogueoflife.org/annual-checklist/2019/info/hierarchy. 
As I said, term is preoccupied.

**Comment by yroskov** [comment]
Figure, based on speculation rather than on facts, should have distinctive non-confusive name.

**Comment by yroskov** [comment]
species living: number of living species which are recognised by science at present time on a global scale and have been **formally** described with a Linnean name. Estimates do not include fossil species.

**Comment by yroskov** [comment]
"species living speculative"
