### ISSUE TITLE
Do we need to index the names and ranks in the classification

### ISSUE THREAD

**Issue by ayco-at-naturalis** [CatalogueOfLife/backend#830]
@mdoering - before we start another round of indexing:

As far as I'm aware we **do** search on the classificationId (deleteSubTree), but we never search on the ranks and names within the classification.

If we ever want to enable searches like get all species that are descendants of Aves, we would need to index the names (and ranks). But currently, that's a **whole** lot of data (several simple names per taxon / synonym) being indexed for nothing.

Or did I forget something?

**Comment by mdoering** [comment]
thats fine, we dont want to search on them, just return them in the response for the UI

**Comment by ayco-at-naturalis** [comment]
@mdoering I'm not sure whether you're still using gitter, so here: I made one more change: since none of the fields within the EsMonomial object within EsNameUsage are no indexed, we can change the type of the classification field of EsNameUsage from "nested" to "object". This will prevent the creation of subdocuments.

Don't worry if you've already started re-indexing. The big gain was un-indexing the EsMonomial fields themselves. The change from "nested" to "object" will then come about transparently the next time you re-index
