### ISSUE TITLE
Allow filtering of tree API children by extinct flag

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#837]
demand by API users, see https://discourse.gbif.org/t/extinction-status-and-the-species-api-routes/2312/2

**Comment by mdoering** [comment]
done

**Comment by sckott** [comment]
thanks! is that change on the `/species/{id}/children/`  route? And what parameter? `isExtinct` ?

**Comment by mdoering** [comment]
No, there is actually a simpler tree API that returns smaller objects, may include extra infos about the source in case of aggregated datasets like the CoL and is designed to drive tree navigations.

To get the root of the tree:
http://api.catalogue.life/dataset/3/tree?extinct=true

To list children:
http://api.catalogue.life/dataset/3/tree/0/children?extinct=true
http://api.catalogue.life/dataset/3/tree/061950e4-9782-4d1a-9c87-dcf375788e6b/children?extinct=true

**Comment by mdoering** [comment]
you can also get the parents in case you need to open a tree from some known ID:
http://api.catalogue.life/dataset/3/tree/5a45f4b7-3ab5-41f4-bbaf-81be3a0edd35

**Comment by mdoering** [comment]
http://api.catalogue.life/dataset/3/tree/80774660-983d-4b20-aadc-04d068e3a1d2/children
http://api.catalogue.life/dataset/3/tree/80774660-983d-4b20-aadc-04d068e3a1d2/children?extinct=false

**Comment by sckott** [comment]
thanks!
