### ISSUE TITLE
Crash of assembly in the Clearinghouse?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#840]
Re-assembling World Plants sectors.
Order Huerteales (Dipentodontaceae, Gerrardinaceae, Petenaeaceae, Tapisciaceae).

2020-09-04 Steps completed before Clearinghouse stopped responding: 
1) I have deleted all sectors in order Huerteales, 
2) Deleted order Huerteales in the Tree. 
3) Attempted to add order Huerteales as a child in class Magnoliopsida. All attempts failed. Finally, no any messages appear on the screen, no any actions proceeded.

**Comment by yroskov** [comment]
Snapshot of the screen before final silence of the Clearinghouse:

![image](https://user-images.githubusercontent.com/28574252/92273952-f5484e00-eeb1-11ea-85eb-92f1b878a991.png)

**Comment by gdower** [comment]
We think we fixed it.

**Comment by yroskov** [comment]
Well, it is definitely a bug in the system. The same as https://github.com/CatalogueOfLife/backend/issues/839
