### ISSUE TITLE
When asking for facet 'nomstatus' the returned facet is named 'nom status'

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#853]
https://api.catalogue.life/dataset/3LR/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic&status=synonym

Gives a blank dropdown in public search: https://www.dev.catalogue.life/data/search.html

**Comment by mdoering** [comment]
strange. `nomstatus` indeed is the correct, normative name for the vocab:
http://api.catalogue.life/vocab/

**Comment by mdoering** [comment]
Ah, the facet is not the vocabulary name but the [search parameter name](https://github.com/CatalogueOfLife/backend/blob/master/api/src/main/java/life/catalogue/api/search/NameUsageSearchParameter.java#L49).
So that `nom status` is actually expected and correct!

**Comment by thomasstjerne** [comment]
So the client is actually expected to use a param with white space included?
Odd thing is that asking explicitly for facet 'nomstatus' returns facet 'nom status'

**Comment by mdoering** [comment]
the search parameter value gets serialised just any other enumeration value.
E.g. `PROVISIONALLY_ACCEPTED` becomes `provisionally accepted` as a taxons status.
The API is leniently parsing controlled values, allowing underscores in place of whitespace or no whitespace and is also case insensitive.

I would prefer to keep the serialization strategy for all enumerations the same. Passing values in is lenient, but the API will have to respond in one flavor. Currently this is lower case and whitespace instead of underscores.

Is this an issue for the UI?

**Comment by thomasstjerne** [comment]
> Is this an issue for the UI?

It is actually a bit cumbersome, yes. In many cases the UI expects a consistent naming between enums and corresponding search params. Part of the problem is that the enums are injected as variables - which cant have white space in them. So I cant really rename those to correspond to the parameter name

**Comment by mdoering** [comment]
Let's review our options then.

We can modify the search parameter enum to simply have no underscore/whitespace. Maybe I misunderstand, but it sounds like this would only be part of the solution as the enumeration for the values itself is called differently? You expect the facet names to be the same as the vocabularies name that defines its values? That is very likely to break in any case as we could reuse the same vocabulary for several search parameters

**Comment by thomasstjerne** [comment]
I managed to get it to work in the `nom status` case, and I think as long as the facet name is equal to the parameter name it will work out. I was just puzzled that the param `nomstatus` worked and I did not check that `nom status` also worked.

But I must admit that I think it is quite unusual to see white space in parameter names.

**Comment by mdoering** [comment]
for sure it is and I don't like that. I did not think we use enum values as parameter values, but here it is.
Mind if I rename the search parameter enum to not have any underscores/whitespace or will that break the UI in many places?

**Comment by mdoering** [comment]
using lowerCamelCase serialization now for NameUsageSearchParameter to avoid whitespace but keep things readable
