### ISSUE TITLE
Collision of search params

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#854]
The name search in the clearinghouse is currently broken as the `type` param now points to the search type i.e. `PREFIX`, `WHOLE_WORDS`, `EXACT` but the facet named `type` is pointing to the name type e.g `scientific`, `placeholder` etc

**Comment by mdoering** [comment]
ouch. I would suggest to change the facet to "NAME_TYPE" or `name type` then.
But I also realize now that facet **values** get used as http parameter keys. [Having whitespace in there isn't good](https://github.com/CatalogueOfLife/backend/issues/853).

**Comment by mdoering** [comment]
I've rename NameUsageSearchParameter.type to NameUsageSearchParameter.nameType
and use a lowerCamelCase serialization for NameUsageSearchParameter now, including as facet values.
That prevents whitespace
