### ISSUE TITLE
500 error on tree diffs

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#855]
I am getting a 500 error on the tree diffs:

https://api.catalogue.life/dataset/3/sector/27/diff/tree?attempts=7..8
```
{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID 5219c2031841588d)."
}
```
The GBIF log server is down at the moment, so I can't give you the stack trace, but it should be reproducible by just visiting: 

https://data.catalogue.life/catalogue/3/sync/27/diff?attempts=7..8

![image](https://user-images.githubusercontent.com/8573609/94155029-1f9f8280-fe44-11ea-8cad-3612b4e8ac9a.png)

Frontend version: 7816e60 September 23, 2020 12:56 PM
Backend version: 8b37897 September 24, 2020 4:27 AM

**Comment by mdoering** [comment]
The log server is there luckily, but IPs have changed and it needs some time to get it public again. @MattBlissett Its still only accessible via VPN right now.

```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class life.catalogue.api.model.DSID (java.lang.Integer is in module java.base of loader 'bootstrap'; life.catalogue.api.model.DSID is in unnamed module of loader 'app') at life.catalogue.db.tree.SectorDiffService.parseAttempts(SectorDiffService.java:16) at life.catalogue.db.tree.BaseDiffService.treeDiff(BaseDiffService.java:36) at 
```

**Comment by MattBlissett** [comment]
The log server should be public again.
