### ISSUE TITLE
Aberrations marked as "ab." seem to be flagged as an error

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/backend#856]
https://data.catalogue.life/dataset/1199/verbatim?issue=unusual%20name%20characters

This relates to this example. I think the "ab." label for the infraspecific name has caused the problem.

![image](https://user-images.githubusercontent.com/26148454/94327770-6d58ee00-fff0-11ea-9fd3-df0104be56ba.png)

**Comment by mdoering** [comment]
The parser seems to be good:
http://api.catalogue.life/parser/name?name=Alucita%20icterodactyla%20ab.%20noctis&authorship=Caradja,%201920

```
{
  "name": {
    "scientificName": "Alucita icterodactyla ab. noctis",
    "authorship": "Caradja, 1920",
    "rank": "aberration",
    "genus": "Alucita",
    "specificEpithet": "icterodactyla",
    "infraspecificEpithet": "noctis",
    "combinationAuthorship": {
      "authors": [
        "Caradja"
      ],
      "year": "1920"
    },
    "code": "zoological",
    "type": "scientific",
    "parsed": true
  },
  "extinct": false
}
```


This verbatim line is suspicous:

> col:uninomial    Alucita icterodactyla ab. noctis

A uninomial should be just one word and only be given for higher ranks.
That could explain some of the issues.

**Comment by dhobern** [comment]
You probably realise this but I didn't offer a uninomial for this record

**Comment by mdoering** [comment]
It seems you did. The line 2168 of file name.csv contains this:

> "2779","2779","Alucita icterodactyla ab. noctis","Caradja, 1920","aberration","Alucita icterodactyla ab. noctis","Alucita","icterodactyla","noctis","374","83","1920","ICZN","established",,

Headers are:
> "ID","basionymID","scientificName","authorship","rank","uninomial","genus","specificEpithet","infraspecificEpithet","referenceID","publishedInPage","publishedInYear","code","status","remarks","link"

After rank comes uninomial, so that is real.
Did you create the file programmatically?

**Comment by mdoering** [comment]
I am closing the issue, please reopen it if the uninomial really wasn't in your file.

**Comment by dhobern** [comment]
So sorry - you're correct. Changing it now.
