### ISSUE TITLE
Export html catalogues?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#860]
Should we generate a classic catalouge similar to https://alucitoidea.hobern.net/catalogue.php in html as an export for any given root taxon? It is the classic view taxonomists love

It could also be a page in the UI, but I like the idea of being able to download a snapshot in html that renders nicely. If marked up fine it should even be fairly simple to upload the same kind of html to the importer.

**Comment by mdoering** [comment]
@dhobern ?

**Comment by dhobern** [comment]
The model I've been working on is a very simple nested <div> model that can easily be styled in different ways. If we follow a model like that, it should be easily generated from the Clearinghouse data/API.

My current tools (thousands of lines of uncommented Java) is here:

https://github.com/dhobern/COLDPUtils

It's a general toolset I'm creating and that only currently works for my own CSV contents, but I plan to generalise it. It has three modes:

1. Validate the contents of a COLDP file
2. Support various data manipulations of value to editors.
3. Generate HTML outputs.

**Comment by mdoering** [comment]
Simple one with just names here: https://api.catalogue.life/dataset/3/export/e48db8f6-4c8c-4033-b1f8-35083f782d5f
Extended one with references, vernacular names and distributions to be done still:
https://api.catalogue.life/dataset/3/export/e48db8f6-4c8c-4033-b1f8-35083f782d5f?full=true
