### ISSUE TITLE
Dataset search index not getting populated on prod

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#861]
On prod, the dataset search index doesn't seem to be getting populated for newly imported datasets:

http://api.catalogue.life/dataset/1140/nameusage/search

It is working on dev:

http://api.dev.catalogue.life/dataset/1140/nameusage/search

**Comment by mdoering** [comment]
search index, not names index I suppose. Indeed World Ferns, Plants, Alucitoidea and the sept col release did not get indexed.
I have started a reindex job for those. All finished but World Plants

**Comment by mdoering** [comment]
Hm, but it hasnt changed the index...

**Comment by mdoering** [comment]
I have started to built a new search index this morning so we can switch tomorrow morning (CET) to this one. There was a small change in the index structure, maybe that is related. On dev the new index is already in place. But I cant see any errors in the logs and it claims to have indexed the above datasets successfully...

**Comment by mdoering** [comment]
The index is still missing some 20 datasets, but I switched prod to use it already and indexing new datasets seems to work again
