### ISSUE TITLE
Search for author Navas yields nothing

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#864]
World checklist of freshwater Ephemeroptera species contains several names by the author spelled Navas or Navás

E.g. [Eatonica schoutedeni (Navás, 1911)](https://data.catalogue.life/dataset/1120/taxon/9047)

But the search does not yield anything:

https://api.catalogue.life/dataset/1120/nameusage/search?q=Navás&sortBy=taxonomic
Also not with https://api.catalogue.life/dataset/1120/nameusage/search?q=Navás&sortBy=taxonomic&content=AUTHORSHIP

**Comment by mdoering** [comment]
Strangely the verbatim, postgres driven search also does not find him:
https://data.catalogue.life/dataset/1120/verbatim?q=Navas

**Comment by mdoering** [comment]
And also the search in GBIF has troubles with him:
https://www.gbif.org/species/search?q=Navas&constituent_key=7ddf754f-d193-4cc9-b351-99906754a03b&highertaxon_key=1225&qField=SCIENTIFIC&advanced=1

Only if you include non CoL data which uses `Navas` without diacritics:
https://www.gbif.org/species/search?q=Navas&highertaxon_key=1225&qField=SCIENTIFIC&advanced=1

It looks to me as if the ascii folding is not working???

**Comment by mdoering** [comment]
our ascii folding works, need to check lucene

> assertEquals("Navas, 1929", StringUtils.foldToAscii("Navás, 1929"));

**Comment by mdoering** [comment]
@ayco-at-naturalis I have added a [new search test for Navas](https://github.com/CatalogueOfLife/backend/commit/b8b17d4e76b365bc705d3ed7c746e50a4c6b6755#diff-8f53ec583cbaa2e425c073b0b1dfb080) that fails.
Could you take a look to see what might be going on here?

We might treat the authorship search pretty wrongly according to that test.

**Comment by mdoering** [comment]
Search was using the wrong ES authorship field to search on.
You still cannot search by year if its part of the authorship. Thats not curcial, but would be nice to have. 
@ayco-at-naturalis could you please look into why that is? I suspect some analyzer removing numericals...

**Comment by mdoering** [comment]
authorship and vernacular search uses the `ignore_case` analyzer which uses the keyword tokenizer which keeps the entire word as it is. In addition the search does an ngram search on the same field to catch the start of a field which explains why authors get matched at all. 

Changing to use a modified standard analyzer that adds ascii folding

**Comment by ayco-at-naturalis** [comment]
@mdoering Sorry I'm reading this only now. I keep an eye sideways on CoL issues, but don't hesitate to  send me an email or app if you suspect I missed it.
