### ISSUE TITLE
Split Dataset.authorsAndEditors

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#865]
CoL seems to add more information to a Person in authors and contacts than just the name itself.
For example:
 - `Froese R. & Pauly D. (eds).`
 - `Lefkowitz E.J. (ed).`
 - `Roskov Y., Zarucchi J., Novoselova M. & Bisby F. (†) (eds).`

How should we cater for (eds.) (ed.) or  (†) (eds). ?

Propose to add a new _suffix_ property to Person that can hold these things or others like _Jr._ and is more flexible than a role attribute which does not fit the dagger for example.

**Comment by mdoering** [comment]
See also https://github.com/CatalogueOfLife/portal/issues/29
@yroskov does that make sense to you?

**Comment by yroskov** [comment]
Most important for me a role of the person in GSD project: author (default, no attribute) or editor (with attribute "ed." or "eds"). It might be formalized as a flag in additional field. 

Well, interface form for typing and sorting names in this metadata field needs better design. It may require split: surname, given names, role, etc. Output in final product should be standard: surname in full, then initial(s). Delimiters should follow one of bibliographic standards.

I have no strong opinion on use of dagger. It's not clear to me, whether it is needed or not.

**Comment by mdoering** [comment]
@yroskov whats the difference between `ed.` and `eds.`?
So it seems a single _editor_ checkbox would be sufficient to render all author/editor names nicely?
Happy to add that or a more generic suffix property which just takes a string.

The advantage of the boolean flag is that we can render all editors consistently and change that easily for all if we want to

**Comment by yroskov** [comment]
The only difference between ed. and eds. is in combined string:

Minelli A. (**ed**). (2019). ChiloBase: A World Catalogue of Centipedes (Chilopoda) for the web (version 1.01, May 2006). In: 

Ma K., Ji L., Qin H., Liu J.Y., Yao Y., Lin C., Yan H., Wang L., Qiao H. & Li R. (**eds**). (2019). Catalogue of Life China (version 2012). In:

**Comment by mdoering** [comment]
so that means all the people cited are editors? How can you then differ between authors and editors?

**Comment by yroskov** [comment]
_Authors and editors._ How to cite a book with many chapters written by different authors? Often, editor(s) cited for the book, authors for each chapter in the book. The same with GSDs. Each project has own structure, rules and level of expert contribution. It might be a single author, small group of authors, or it might be lot of experts with one/few editors in charge of checklist scrutiny. GSD custodian decides how to cite their GSD in CoL: with list of authors OR with list of editors, as an alternative.

**Comment by mdoering** [comment]
Then the field should have been called _Authors OR editors_ ;)
Until now it was never clear to me that this is exclusive! 

In that case we could even change the entire model and have to Person lists, either authors or editors. Why is this even mixed?
We can visualise them even either authors: xyz or editors: xyz 
It would make things a lot simpler to understand.

And if they are cited in the entire bibliography string, then we can add the (eds.) to highlight these are editors, not authors.

**Comment by mdoering** [comment]
https://libguides.dixie.edu/c.php?g=57887&p=371727

**Comment by mdoering** [comment]
BibTex and other ref standards simply separate authors and editors and 2 fields. Now that I finally understand the problem I would strongly suggest we do the same

**Comment by yroskov** [comment]
All depend on data presentation in final product. I hope, there will be no empty fields like "Authors -" or "Editors -". And combined bibliographic citation should have no stupid view as "Oosterbroek P. (author)".

**Comment by mdoering** [comment]
Surely not! It becomes easier that way for development I think.
If both are present we will just show the editors with an (ed.) or (eds.) suffix if they are more than one in the citation string.

On the metadata page I would show Authors and Editors as separate lines. We can decide not to show them if they are empty like you seem to favour - or always show both which seems slightly cleaner to me as we do the same for all other metadata fields. We can of course also decide to drop all of the empty ones in the visualisation. In the old page you also show a dash `-` for missing infos: http://www.catalogueoflife.org/col/details/database/id/78

**Comment by yroskov** [comment]
Yes, such implementation is fine for me.

**Comment by thomasstjerne** [comment]
> All depend on data presentation in final product. I hope, there will be no empty fields like "Authors -" or "Editors -". And combined bibliographic citation should have no stupid view as "Oosterbroek P. (author)".

Would you prefer that we hide empty fields? Rather than displaying "-" ?
It may look nicer, but on the other hand then the fields will vary from dataset to dataset and it may be overlooked that a license is missing or similar

**Comment by mdoering** [comment]
Personally I prefer to keep them so that the layout is alike and you feel more used to where to find items on the screen.
But I do not have a very strong opinion. @dhobern any opinion when dealing with the portal?

**Comment by mdoering** [comment]
@yroskov I have looked at various special cases

 - Zinetti F. (data managers)
 - Roman Khalikov (Zoological Institute RAS)

the RAS case comes from GBIF DwC archives. But I do wonder if we want some other attributes on a Person, e.g. role or organisation/affiliation? If we can keep it simple and just ignore these thats best. We _can_ place it into the familyName, but I fear this might cause troubles down the line when building citations. Or we could create a generic _suffix_ field that can hold anything and gets shown at the end no matter what

**Comment by mdoering** [comment]
deployed to prod

**Comment by yroskov** [comment]
>Would you prefer that we hide empty fields? Rather than displaying "-" ?

Yes, please hide empty Editors & Authors fields.

**Comment by yroskov** [comment]
I would interpret:
    Zinetti F. (data managers) ->  Zinetti F. (editor)
    Sánchez-Ruiz M. (technical editor) ->  Sánchez-Ruiz M. (editor).
    Govaerts R. (ed). For a full list of reviewers see: http://apps.kew.org/wcsp/compilersReviewers.do ->  Govaerts R. (editor); Phrase "For a full list of reviewers see: http://apps.kew.org/wcsp/compilersReviewers.do" should go to the abstract.  
    Rambold G. (lead editor; for detailed information see http://liaslight.lias.net/About/Impressum.html and http://liasnames.lias.net/About/Impressum.html) ->  Rambold G. (editor); Phrase "for detailed information see..."should go to the abstract.   
    Roman Khalikov (Zoological Institute RAS) ->  Roman Khalikov (author); Organisation: Zoological Institute RAS
