### ISSUE TITLE
Tree API: datasetSectors missing for latest release keys 

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#866]
https://api.catalogue.life/dataset/3LR/tree/0/children?limit=10000&offset=0&insertPlaceholder=true&catalogueKey=3LR&type=CATALOGUE

vs

https://api.catalogue.life/dataset/3/tree/0/children?limit=10000&offset=0&insertPlaceholder=true&catalogueKey=3LR&type=CATALOGUE

**Comment by mdoering** [comment]
the release copy procedure does not copy the column `dataset_sectors`

**Comment by mdoering** [comment]
I am updating the sector counts for the last release manually too
