### ISSUE TITLE
Missing source

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#869]
In the datasetSectors object of kingdom Plantae is a source with key: 1141:
https://api.catalogue.life/dataset/3LR/tree/0/children?limit=10000&offset=0&insertPlaceholder=true&catalogueKey=3LR&type=CATALOGUE

Trying to fetch this source fails: https://api.catalogue.life/dataset/3LR/source/1141

**Comment by mdoering** [comment]
there are 157 source datasets for 3LR, but 163 distinct sources in the sectors. 
Sth not right indeed...
