### ISSUE TITLE
Sync stuck on deleting step?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#874]
Sync seems to be stuck on deleting for World Plants sector Myrtales, which only has around 14,000 species and it's been deleting for 2 hours. The sector subject ID is Myrtales, so I don't think it is caused by an & in the authorship.

http://api.catalogue.life/dataset/3/sector/1131

The [logs](https://logs.gbif.org/app/discover#/context/463d38b0-fe44-11ea-93de-b97c40066ce8/L6RIInUB7hqSFwpZAS79?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,params:(query:undefined),type:phrase),query:(match:(sector:(query:undefined,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,params:(query:col-prod),type:phrase),query:(match:(environment:(query:col-prod,type:phrase))))))&_g=(filters:!())) say:

Deleted 41979 existing taxa with their synonyms and related information from sector Sector{1131, datasetKey=3, mode=ATTACH, subjectDatasetKey=1141, subject=ACCEPTED ORDER Myrtales Juss. ex Bercht. & J. Presl [Myrtales]}

It seems like maybe it finished deleting but didn't go onto the next step?

**Comment by gdower** [comment]
Nevermind, it looks like it finally deleted.

**Comment by mdoering** [comment]
`DELETE FROM reference_3 WHERE sector_key=$1` is running since 3 hours already. Sth not right.
@gdower any chance I can stop all queued syncs and restart the server?

**Comment by gdower** [comment]
@mdoering, go ahead.

**Comment by mdoering** [comment]
ok, restarted and deployed the latest version to prod.
@gdower please use it as you need again

**Comment by gdower** [comment]
@mdoering, I restarted the syncs.

**Comment by mdoering** [comment]
sorry, I had to redeploy once more. There was a bug that needs to get fixed.
We should work on a persistent queue for the sync jobs...

**Comment by gdower** [comment]
No problem
