### ISSUE TITLE
nameusage search doesn´t handle latest release keys like 3LR

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#875]
https://api.catalogue.life/nameusage/search?USAGE_ID=6983e8ff-e0f8-414d-814d-e1bbc2f6f752&DATASET_KEY=3LR

**Comment by mdoering** [comment]
the LR suffix is preprocessed before it hits the actual services and parameter values are swapped out.
That matching is case insensitive, but it did not handle additional underscores, but this works:

https://api.catalogue.life/nameusage/search?USAGE_ID=6983e8ff-e0f8-414d-814d-e1bbc2f6f752&DATASETKEY=3LR

I will allow the use of underscores anywhere too
