### ISSUE TITLE
Disappearance of search content "vernacular name" has disadvantages

### ISSUE THREAD

**Issue by ayco-at-naturalis** [CatalogueOfLife/backend#879]
I saw the discussion about removing vernacular name as a search target flying by, but didn't realize at the time that this would break our own (Naturalis) API, which calls CoL under the hood and uses this feature. I suspect I can achieve the same effect by doing two calls, but being able to find on one shot synonyms and accepted names **via** vernacular names and/or scientific names is quite handy.

**Comment by mdoering** [comment]
I was anticipating that the missing accepted name is annoying. We can easily add that in though. Would that help? Vernaculars are never boumd to synonyms, so thats not an issue.

**Comment by ayco-at-naturalis** [comment]
Hi Markus, I left the day after for vacation, so sorry for the late reply. Yes for our API that would surely help, as its point is to find scientific names "by any means", including via vernacular names.

**Comment by ayco-at-naturalis** [comment]
@mdoering Hello Markus I guess you're totally occupied with the aftermath of the beta release, but if you have time, could you consider this one again. It's now a "known ssue" in our own api, so no hurry, but it'd be nice if we can follow the route via the CoL again

**Comment by mdoering** [comment]
@ayco-at-naturalis just making sure, adding a simple taxon property with id, scientificName, authorship, rank and status would solve it?

**Comment by ayco-at-naturalis** [comment]
Well, the point of our service, which we call the "name resolution service", is to resolve a "name" (or rather just a search string) of whatever type (including vernacular names and bare names) to one or more scientific names, and to then use those scientific to find specimens in our own document store. Useful b/c a lot of specimens have iffy scientific names. So it's a two-step service, under the hood calling CoL as the 1st step.

So: vernacular names are "resolved" to accepted names, accepted names to their associated synonyms, and synonyms to their accepted names. And the whole bunch of accepted names is held against our specimen index.

The original CoL search service was ideal for that because you could do it out-of-the box, setting searchContent simply to scientific and vernacular.

**Comment by mdoering** [comment]
Understood, but there are now 2 different services for scientific and vernacular names.
There is no plan to vert that. We can only improve on the vernacular search service to better match your needs

**Comment by ayco-at-naturalis** [comment]
OK - I'll rework our own service then to combine the 2 services. If there's anything as regards the vn service the would help us, I'll let you knwo
