### ISSUE TITLE
Remove data access URL when uploading data manually?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#881]
We have a data access url in a datasets settings which we use to pull data when an import is triggered.
You can also manually upload an archive though. Should this then remove the access url from the settings? Otherwise hitting import again after the upload has happened will overwrite the manually uploaded data.

For example [reptile db](https://data.catalogue.life/dataset/1008/imports) still has the [old ACEF file](https://raw.githubusercontent.com/Sp2000/colplus-repo/master/ACEF/8.tar.gz) listed in its settings, but the data in CLB is more up to date because of manual uploads.

**Comment by mdoering** [comment]
@gdower would you agree with that?

**Comment by gdower** [comment]
Do you mean just setting the data access URL to empty when an archive is uploaded? That's fine by me, so long as I can still set the data access URL.

**Comment by mdoering** [comment]
yes, set it to NULL.
Otherwise I fear we overwrite the manually uploaded archive easily

**Comment by mdoering** [comment]
or we could change the UI to ask if you also want to reset the access url whenever you upload a file

**Comment by gdower** [comment]
I think setting it to NULL is a good idea for now. Other users probably won't realize that the data access URL is reset when they upload an archive, so at least warning them that the data access URL will be reset would probably be a good idea.

**Comment by mdoering** [comment]
ok, I'll do so then
