### ISSUE TITLE
How is the catalogueKey (project scope) passed to patch endpoints

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#883]
I assume `key` is the source datasetKey:
/dataset/{key}/patch

Something like 
catalogue/{catalogueKey}/dataset/{key}/patch
Maybe?

**Comment by mdoering** [comment]
key is the project key, so `/dataset/{key}/patch` returns the list of all patches for a project.
An individual patch is:
`/dataset/{peojectKey}/patch/{sourceDatasetKey}`

PS: Let's not use catalogueKey in new code but use projectKey instead

**Comment by thomasstjerne** [comment]
So I should also be able to POST to  `/dataset/{peojectKey}/patch/{sourceDatasetKey}`
I.e. include the `sourceDatasetKey` on the first creation of a patch?
From the docs, it doesn´t seem the API allows that.

Or should I always use PUT i.e. assume that a source always has a patch? (which would be empty by default)

**Comment by mdoering** [comment]
I see, a bit unusual.
You should POST to /dataset/{projectKey}/patch a full dataset object with its key being the sourceDatasetKey.

**Comment by mdoering** [comment]
right now you cannot PUT to a non existing patch.
But we could also allow that as its a 1:1 relation and clear

**Comment by thomasstjerne** [comment]
> You should POST to /dataset/{projectKey}/patch a full dataset object with its key being the sourceDatasetKey.

Makes sense
