### ISSUE TITLE
Loosen validation on meta data patches

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#885]
Meta data patches should probably not have the same validation as meta data. 
For now, I have followed the principle that a value left out from the request object, means "no patch for this attr". However, this gives validation errors from the backend.
Also, I have implemented a small `null` switch for explicitly nulling an attribute in the patch - i.e. if theres a value in the meta data, overwrite with `null`

Request failed with status code 422
Validation error

origin must not be null. type must not be null

HTTP method: POST

https://api.dev.catalogue.life/dataset

Body:
`````
{"key":1008,
"title":"The Reptile Database in TSJ TEST Assembly",
"alias":"ReptileDB",
"organisations":null,
"confidence":5}

````

**Comment by mdoering** [comment]
Indeed the validation should be off - we dont even store some of those fields as you should never be able to override the origin for example.

**Comment by thomasstjerne** [comment]
Hmm - maybe it was my bad. Seems it posted to the /dataset endpoint.

**Comment by mdoering** [comment]
from the code it seems POST is fine, but PUT does indeed a validation which I will remove
