### ISSUE TITLE
Move private property to dataset options and disallow PUT on external datasets

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#886]
If we consider metadata on external datasets immutable in our system, a PUT should fail.
However, currently we have the `private` attr in the meta data, and I reckon that this could actually be changed over time.

Problem is I think we show the "private" icon in many places taken from the dataset response.
This would not be possible unless it was included as a readonly attr on the dataset response, but only mutable in the options

**Comment by mdoering** [comment]
external datasets do not have immutable metadata.
In fact external data (uploaded or downloaded) might not have any metadata at all and we & users need a way to manage it.

**Comment by thomasstjerne** [comment]
OK - was just considering (maybe I already did) hiding the edit toggle for external datasets.

**Comment by mdoering** [comment]
The distinction between dataset metadata and settings is not always clear I agree.
We have various things linked to a dataset that are very independent from each other:
 - classic human metadata: (title, alias, description, contact, etc
 - external settings (url, format, delimiter)
 - private flag
 - ACL of allowed editors
 - origin, creator which are immutable
 - key, sourceKey, importAttempt as backend managed keys only
