### ISSUE TITLE
preview.catalogue.life is down

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#896]
It looks like https://preview.catalogue.life/ is down today:

![image](https://user-images.githubusercontent.com/28574252/97709075-c3a1cc80-1a87-11eb-959f-d2685540c6fb.png)

**Comment by mdoering** [comment]
thanks Yuri. Please post these kind of serious problems in our skype chat in the future so we can respond quickly

**Comment by yroskov** [comment]
Search in the Tree does not work.

Searching for Tanacetum aureum

![image](https://user-images.githubusercontent.com/28574252/97719442-13d35b80-1a95-11eb-8c3e-b533c3f78aca.png)

**Comment by mdoering** [comment]
Thomas also had problems. They seem to be gone now. Please reopen if it persists

**Comment by yroskov** [comment]
It works now on my side
