### ISSUE TITLE
Missing Taxonomic coverage in all GSDs at preview.catalogue.life

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#900]
Taxonomic coverage is missing in all GSDs at preview.catalogue.life: 

For example:
http://preview.catalogue.life/data/dataset/1021
http://preview.catalogue.life/data/dataset/1055
http://preview.catalogue.life/data/dataset/1062
http://preview.catalogue.life/data/dataset/1199

**Comment by mdoering** [comment]
With new usage identifiers created during the release we also need to update all target ids in sectors and estimates.
This is currently missing during a release. The idMap tables are also removed from a project after a release, so we cannot easily update the sectors. We can only try to rematch them.

Code should be changed to:
 - update all target ids in sectors and estimate based on the idmap table
 - finally move the idmap tables to the release (but do not keep them in the project) so we can reuse them if needed later on

**Comment by mdoering** [comment]
For the 2230 release I am rematching all sector and estimate targets

**Comment by mdoering** [comment]
if you clear your browsers cache you can see tax coverage now!
