### ISSUE TITLE
Varnish 503 on POST /importer/{key}

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#902]
Perhaps this should go in deploy, but when importing a zip archive, I'm getting a 503 error from varnish:

POST https://api.catalogue.life/importer/2144
```
Error 503 Backend fetch failed

Backend fetch failed
Guru Meditation:

XID: 48103551

Varnish cache server
```

I get the same issue posting to http://api.catalogueoflife.org, so it doesn't seem to be a domain issue.

POST http://api.catalogueoflife.org/importer/2144
```
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 45200929

Varnish cache server
```

**Comment by mdoering** [comment]
This usually did happen after a deploy when varnish wasn't updated and still referred to the old port.
We fixed the deploy script (or better local file permissions) since and it should not reappear. But please reopen if you encounter this again
