### ISSUE TITLE
Misspelled names without a correction relationship

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#908]
More often than not there is no spelling correction relationship provided for misspelled names because most people do not have that in their data models yet and it is just specified that the name is misspelled. The information that the name is misspelled is still useful without having the spelling correction relationship specified. It might be good to allow the below incomplete relationship and flag it with an issue that we need more info on what the correctly spelled name is:
 
# NameRelation.tsv
nameID | relatedNameID | type | referenceID | pageReferenceID | remarks
--|--|--|--|--|--
47838 | | spelling correction

The importer would just mark the name as misspelled with no relationship to the correct name. Alternatively, maybe we should have a misspelled name status? I could mark them as invalid, but then we're losing the more detailed knowledge that it's a misspelling.

**Comment by mdoering** [comment]
That's indeed a problem to solve. I would very much prefer not to losen name relations to become non relations.
Instead a change in the name status seems more appropriate to me. As you can use the Nomen vocabulary for a name status already that might be an option. Would that be [NOMEN status 217](http://bioportal.bioontology.org/ontologies/NOMEN?p=classes&conceptid=http://purl.obolibrary.org/obo/NOMEN_0000217)?

But then again not all misspelled names are invalid names. Very often they are still available as the zoological code allows for various spellings:

- https://code.iczn.org/formation-and-treatment-of-names/article-32-original-spellings/?frame=1
- https://code.iczn.org/formation-and-treatment-of-names/article-33-subsequent-spellings/?frame=1#art-33-2
- https://code.iczn.org/formation-and-treatment-of-names/article-34-mandatory-changes-in-spelling-consequent-upon-changes-in-rank-or-combination/?frame=1

**Comment by mdoering** [comment]
Maybe we should simply adopt all NOMEN subclasses of [NOMEN:scientificName](http://bioportal.bioontology.org/ontologies/NOMEN/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNOMEN_0000036) for our name status vocabulary to be very precise. Especially if we want to integrate names from nomenclators. I have the feeling NOMEN might need some additions for the botanical code, but that should be fine to improve on.

@deepreef have you ever made use of or reviewed [NOMEN](https://github.com/SpeciesFileGroup/nomen)? I'd recommend to  view it either through [bioportal](http://bioportal.bioontology.org/ontologies/NOMEN/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNOMEN_0000036) or locally through Protege.

We can still very easily derive a generic status on the fly while keeping the detailed status for a name.

**Comment by mdoering** [comment]
Hm, does not seem to help to use NOMEN, they have the same problem:
https://github.com/SpeciesFileGroup/nomen/issues/22#issuecomment-726819816

**Comment by mjy** [comment]
I'm not sure it's a problem, it's a reflection of best practices in encoding data, or not over-asserting accuracy in your data.

When you assert it's a misspelling, but not of what, you are creating downstream work for the next person, who has to figure out why, *not cool*.  Rather you should just use weaker assertion.

**Comment by mdoering** [comment]
@gdower @yroskov @mjy so for 3i and any other TaxonWorks sources there should not be any flagged misspellings without having a proper relation? Only unavailable names according to [Art 19.3](https://code.iczn.org/chapter-4-criteria-of-availability/article-19-status-of-emendations-incorrect-spellings-and-mandatory-changes/?frame=1) can be flagged as [incorrect original spellings](https://bioportal.bioontology.org/ontologies/NOMEN/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNOMEN_0000217)?

Then we should not have an issue in ColDP either, or do we?

**Comment by mdoering** [comment]
Let's continue this with the concrete example at hand from 3i here: https://github.com/CatalogueOfLife/data/issues/208#issuecomment-726808585

**Comment by mdoering** [comment]
You can also find the use of '[sic]` in the official ICZN lists: https://www.iczn.org/assets/32eb31b32e/officialists.pdf

> Acanthograptus (emendation of Acanthograpsus) Spencer, 1878, Canadian Naturalist, 8: 461
> (conserved under the plenary power) (gender: masculine) (type species, by monotypy:
> Acanthograpsus [sic] granti Spencer, 1878, Canadian Naturalist, 8: 461) (Graptolithina).
> Op. 650 ................................................................................................................................................. available 


> albinus, Cyphodeirus [sic], Nicolet, [1842], Neue Denkschr. Allgem. schweiz. Ges., 6: 67
> (specific name of the type species of Cyphoderus (emendation of Cyphodeirus) Nicolet, [1842])
> (Insecta, Collembola). Op. 291 ........................................................................................................... available 


> bucklandii, Peltoura [sic], Milne Edwards, 1840, in Roret’s Suites à Buffon, Hist. nat. Crust., 3:
> 345 (Trilobita). Op. 466 ....................................................................................................................... available 
> 

> chalybata, Paradisea [sic], Forster, 1781, Indische Zool.: 40 (specific name of the type species
> of Manucodia Boddaert, 1783) (Aves). Direction 43 .......................................................................... available

> chalybea, Manucodia, Boddaert, 1783, Tabl. Pl. enlum. Hist. nat. Daubenton: 39 (a junior
> objective synonym of chalybata, Paradisea [sic], Forster, 1781). Direction 44 ....................................... index

> chalybeata, Paradisea [sic], Stiles, 1916, Smithson. Publ., 2409: 181 (an incorrect subsequent
> spelling for chalybata, Paradisea [sic], Forster, 1781). Direction 44 ....................................................... index 
> 

But here they seem to be proper emendation relations. Still it would be good to [parse and render [sic] in names correctly](https://github.com/gbif/name-parser/issues/33).

**Comment by mdoering** [comment]
Also from the DSMZ bacterial "code" list:
https://lpsn.dsmz.de/text/glossary#corrigendum

> The abbreviation "corrig." (corrigendum) may be appended to the name if an unintentional typographical or orthographic error has been corrected by a subsequent author. Such a correction does not affect the validity and original date of publication [Rule 61]. Example: Flavobacterium branchiophilum corrig. Wakabayashi et al. 1989 (in place of Flavobacterium branchiophila (sic) Wakabayashi et al. 1989).

**Comment by mdoering** [comment]
Last not least you also find `orth. var.` in botanical names governed by [ICN article 60.1](https://www.iapt-taxon.org/nomen/pages/main/art_60.html) such as:

- Hieronima Allemão, orth. var.

Again these are relations, but we might not know the related name.
Current practise in CLB would be to strip off orth. var. and place it into the nomenclatural remarks of the name and set the status to unavailable

**Comment by mdoering** [comment]
Other examples:

From https://bdj.pensoft.net/article/8080/:
- Inflabilis barati (sic) Prevot 1938
- Hyphomicrobium Stutzer and Hartleb 1899 (sic)
- Streptomyces cinnamomeus forma cinnamomeus (sic) Pridham et al. 1956

**Comment by mjy** [comment]
@mdoering 

> ... no ... flagged misspellings without having a proper relation?"

To my understanding yes, this is the correct assumption that we're targetting.  Whether we need to tweak to get this is I'm less sure. @gdower pinging you to add to our list to check/confirm/fix.

**Comment by mjy** [comment]
@proceps mental note vs. "[sic]" and "(sic)" in bacterial world.  We might need conditional rendering to reflect best practices for Bacterial names?

**Comment by proceps** [comment]
Yes "(sic)" is defined in the Bacterial code, I will do the correction (although, we probably do not have any in TW at the moment). Abbreviation "corrig." in my understanding it is more related to original publications rather than checklists. Similar to "comb.n." in zoology. But I could be wrong, I will wait for an imput from community before making corrections.

**Comment by proceps** [comment]
for misspelled name without a relationship to the correct name, I completely agree with @mjy. Having this in the DB brings more problem for the reade. Status of Invalid or Unavailabe could be much more relevant. Keep in mind, some misspellings are available names in Zoological nomenclature. For example an unjustified emendation is an available name, when the incorrect original spelling is not.

**Comment by gdower** [comment]
Based on the argument made by @proceps and @mjy, I think it's better to just mark them as invalid to not create more work for people trying to figure out why it's misspelled without a correction or citation.

**Comment by mdoering** [comment]
Setting the status as unavailable or available is indeed good. But I'm not sure if [sic] alone tells you that.
In any case I will add support for [sic] to the name parser and probably parsed name in the COL API so we can parse and render those names properly. They will appear in various places just as names so better to be prepared
