### ISSUE TITLE
Tree API childCount doesn´t take extinct flag into account

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#920]
This is not very import for now, the portal frontend has a workaround for it.

This request fetches the three children of _Ginkgoaceae_ , with the `extinct` option set to `false`:
https://api.catalogue.life/dataset/3LR/tree/D2Y/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=3LR&type=CATALOGUE&extinct=false

The first child is the genus `Ginkgo` , having `childCount: 101`. However a subsequent call to fetch the children return only one child:
https://api.catalogue.life/dataset/3LR/tree/5NHCF/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=3LR&type=CATALOGUE&extinct=false

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/backend/commit/6bec50c740a21db123057b26a1da0a68473a2b38
