### ISSUE TITLE
Export download links not working

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#924]
The frontend says the download will be available at:

https://api.catalogue.life/export/6604ef41946f40c5b60371a2a0dd7a88

The logs say it's here: 

/var/www/html/col/exports/66/6604ef41-946f-40c5-b603-71a2a0dd7a88.zip

Can you please send me this file?

**Comment by mdoering** [comment]
Oh, there is some UUID formatting trouble here.
It should be this https://api.catalogue.life/export/6604ef41-946f-40c5-b603-71a2a0dd7a88
which then takes you to https://download.catalogue.life/exports/66/6604ef41-946f-40c5-b603-71a2a0dd7a88.zip

And which gives you a 404 until the export is completed.
This should inform you about progress while the job is still running or queued:
https://api.catalogue.life/admin/job/6604ef41-946f-40c5-b603-71a2a0dd7a88

**Comment by gdower** [comment]
According to the logs, the export completed and I actually tried that location thinking it might have been the dashes.

**Comment by gdower** [comment]
Actually, it failed: https://logs.gbif.org/app/discover?#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/6-WvHnYBU86Couzb1fFG?_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!())&_g=(filters:!())
