### ISSUE TITLE
IDs are wrong in ac-export.zip

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#928]
@mdoering, if you subtract col_new - wrong_id the IDs in ac-export.zip the IDs are pretty consistently off by 6 or 7:

| col\_old | col\_new | wrong\_id | scientificName |
| :--- | :--- | :--- | :--- |
| 27b4b59594d1f335ce612fc42f6273d1 | 32228 | 32222 | Cryptoripersia lii \(Brookes, 1976\) |
| 6153c4091c83f55d1f2b0d4ce4f2a519 | 32229 | 32223 | Cryptoripersia loweri \(Brookes, 1976\) |
| 31161fd296772d2a4ca95c802885fd3d | 3222D | 32227 | Cryptoripersia myrmecophila \(Maskell, 1897\) |
| 13b37f88e089ae4819a7f9f980e4e939 | 3222J | 3222C | Cryptoripersia trichura \(Cockerell, 1901\) |
| 2795132442dbba436a4f0970be86711b | 3222K | 3222D | Cryptoripersia tubulata McKenzie, 1964 |
| c0f4ef1332bbd710f16d2d204e2bc0da | 3222L | 3222E | Cryptorites scotti Jeannel, 1950 |
| e827a25c199789bc793f8570524a4e34 | 3222M | 3222F | Cryptorrhynchidius flavonotatus Voss, 1937 |
| c9e7736126c951fc083a7e0647b034f8 | 3222N | 3222G | Cryptorrhynchidius granocostatus Kolbe, 1910 |
| b9acea3ec8a889c495db739429e63cfe | 3222P | 3222H | Cryptorrhynchidius patruelis Voss, 1937 |
| a3e8fa0a5d4e0cbbb20bb37d9f166b36 | 3222Q | 3222J | Cryptorrhynchus abjectus Champion, 1906 |
| 0071ecaa55dcc213e9be1bb041fc71a4 | 3222S | 3222L | Cryptorrhynchus aequalis Champion, 1906 |
| 53fa8f0a682fec3d198b9e25da3501e8 | 3222T | 3222M | Cryptorrhynchus africanus Hustache, 1924 |
| a06f3ae9ad93470f0898ce57ec05c65d | 3222U | 3222N | Cryptorrhynchus albidulus Fiedler, 1952 |
| e35b6cb5fd205c9144f2464bba6542e3 | 3222V | 3222P | Cryptorrhynchus albitarsus Champion, 1906 |
| d8e411f7f9a1681b6f670fa28bb07286 | 3222W | 3222Q | Cryptorrhynchus albopunctatus Champion, 1906 |
| d0d3e960a10e70ce7d14e6a6850ea635 | 3222X | 3222R | Cryptorrhynchus alboscutellatus Champion, 1906 |
| a0fa2d7e5afb30ead46cd185ed20c7e9 | 3222Y | 3222S | Cryptorrhynchus albosignatus Fiedler, 1952 |
| 21fb32de719dd90823cfcb668f98ea2f | 3222Z | 3222T | Cryptorrhynchus alpinus Fügner, 1891 |
| a0d6f9e51ccaf10b2ff51930da50a7a3 | 32232 | 3222U | Cryptorrhynchus alpinus Stierlin, 1894 |
| c03358dddda6e53958f0b16595c06da6 | 32233 | 3222V | Cryptorrhynchus alutaceus Champion, 1906 |
| 14aa4968c66c146d1fa77b02c22c51a6 | 32234 | 3222W | Cryptorrhynchus angustior Fairmaire, 1897 |
| a41cb91ba6f4b0ed5752f29b62c67367 | 32235 | 3222X | Cryptorrhynchus annulifer Fiedler, 1952 |
| 8dd9344d317e12a32f4e7347a02600a0 | 32236 | 3222Y | Cryptorrhynchus annulipes Roelofs, 1879 |
| 16cfe4cf4b646e811629fe36460f3290 | 32237 | 3222Z | Cryptorrhynchus anthonomoides Champion, 1906 |
| 47e92f3bfdbf7f41037e4d61a23b2806 | 32238 | 32232 | Cryptorrhynchus apicipennis Lea, 1913 |
| 0c49cd03a4df6fda99f1513939571db2 | 32239 | 32233 | Cryptorrhynchus arcuatus Fahraeus, 1871 |
| 7d1dd85638ba984d489d4e6f1ba1529f | 3223A | 32234 | Cryptorrhynchus asper Bohem. in Schoenh., 1837 |
| b70ef02d31c61956a16178f3d331e59e | 3223B | 32235 | Cryptorrhynchus atkinsoni Marshall, 1936 |
| fc0b517bd2a905c0538a90862498b0ad | 3223C | 32236 | Cryptorrhynchus atramentarius Fiedler, 1952 |
| e733780e0a73803502b5041d46e5c186 | 3223D | 32237 | Cryptorrhynchus atricollis Fiedler, 1952 |
| acc4aab9b0a7e28a80d9b4fd5fdae7ba | 3223E | 32238 | Cryptorrhynchus atrocinctus Fiedler, 1954 |
| d3b21d98b2e3d6494c990e15f3213da0 | 3223F | 32239 | Cryptorrhynchus atrolateralis Fiedler, 1952 |
| 1b7614a5bc3b4afab5adfe2c5d6daecf | 3223G | 3223A | Cryptorrhynchus atrosignatus Champion, 1906 |
| 7813c8f1f2bacb74e04436536ca87939 | 3223H | 3223B | Cryptorrhynchus belti Champion, 1906 |
| 46ee7e2de0b2c4951eba0b1aa960d172 | 3223J | 3223C | Cryptorrhynchus bicallosus Boheman, 1859 |
| d84d62edcffed21143e40aa3d550d525 | 3223K | 3223D | Cryptorrhynchus bicruciatus Champion, 1906 |
| 744c716373f053f1f833a0b340a5da2a | 3223L | 3223E | Cryptorrhynchus bifenestratus Champion, 1906 |
| 810f3bfb0f29531aeceaa6494ef24f8e | 3223M | 3223F | Cryptorrhynchus biguttatus Champion, 1906 |
| 6bef0a3c0a0f9b0cfc0bc9bbb504e932 | 3223N | 3223G | Cryptorrhynchus bimaculatus Champion, 1906 |
| da6ce3d748eed8cbbe9b12b88dd0a97d | 3223P | 3223H | Cryptorrhynchus binaevus Kirsch, 1875 |
| 379cdcd16d044d22084dde4a56cb5230 | 3223Q | 3223J | Cryptorrhynchus bioculatus Champion, 1906 |
| 8682a2e7b6b260bd0b076bc30b9839de | 3223R | 3223K | Cryptorrhynchus bipupillatus Champion, 1906 |
| a23847f2123666b08030af52d17def83 | 3223S | 3223L | Cryptorrhynchus bisignatus Suffrian, 1876 |
| f0490c29ae887768c9579e903fb27a6a | 3223T | 3223M | Cryptorrhynchus bisinuatus Champion, 1906 |
| 18d303645c4737812138313c3de4ca0a | 3223U | 3223N | Cryptorrhynchus bistigma Fiedler, 1952 |
| 765736dd6e6b552cd4714ae0ec6d0f1a | 3223V | 3223P | Cryptorrhynchus bistigmatus Fiedler, 1952 |
| 87c764ad8fd465d8ce32039ea8e70cab | 3223W | 3223Q | Cryptorrhynchus bivittatus Champion, 1906 |
| 1de9e3c18c914eda737ea1af26a43ce5 | 3223X | 3223R | Cryptorrhynchus bolivianus Fiedler, 1952 |
| 7c81742608dea29c7e4698e527e30a0c | 3223Y | 3223S | Cryptorrhynchus brachialis LeConte, 1885 |
| 5478739fdec95c1ee50cad9c27a6b7b8 | 3223Z | 3223T | Cryptorrhynchus brandisi Stebbing, 1911 |
| 971bf662f2332b8bd8ca86c41d1731d6 | 32242 | 3223U | Cryptorrhynchus brandti Harold, 1881 |
| 40155db87c42da83f7a382b92898d043 | 32244 | 3223W | Cryptorrhynchus breyeri Brèthes, 1910 |
| caab3f983b03b91282546c506931f5e3 | 32245 | 3223X | Cryptorrhynchus bufonius Jacquelin du Val, 1857 |
| db4bb8ad1f67e955f3924bf50daa14ec | 32246 | 3223Y | Cryptorrhynchus calandroides Suffrian, 1876 |
| 6be93da969cf558a365136fd4ae616ed | 32247 | 3223Z | Cryptorrhynchus caliginosus Champion, 1906 |
| a72023583acc3914f37130ccbed9b287 | 32248 | 32242 | Cryptorrhynchus camelus Dej., 1802 |
| c3221e3bb4888c5ac68a8ae34b5f0400 | 32249 | 32243 | Cryptorrhynchus cancellatus Champion, 1906 |
| 541f5e1daca4af75b1f6efb4505336a1 | 3224A | 32244 | Cryptorrhynchus cancroma Kirsch, 1869 |
| 9dbee30c84bc4900fde486eb0b85f6de | 3224B | 32245 | Cryptorrhynchus carinicollis Fiedler, 1952 |
| b7e13cbaefcff06fd3593fc734c0b2f4 | 3224C | 32246 | Cryptorrhynchus carinifer Champion, 1906 |
| 8977b209b6ccbd692b85cf4f516d177a | 3224D | 32247 | Cryptorrhynchus cinctipes Champion, 1906 |
| 8fbe6fe21d9763d2cd8a6335f98c2ea9 | 3224E | 32248 | Cryptorrhynchus cinereus Champion, 1906 |
| f09fffdaa353a34ab15db22e4950592b | 3224F | 32249 | Cryptorrhynchus collabismoides Champion, 1906 |
| 3703927d9a267db28d139b62b5fba03e | 3224G | 3224A | Cryptorrhynchus collinus Champion, 1906 |
| f7f29bc5a2e5d6c91a885a9421ec1409 | 3224H | 3224B | Cryptorrhynchus commixtus Champion, 1906 |
| c17feb56d06704852262e62086d3f6ce | 3224J | 3224C | Cryptorrhynchus concentricus Champion, 1906 |
| 53d498f24653e7560f7c9999c8451dd5 | 3224K | 3224D | Cryptorrhynchus conspicillatus Champion, 1906 |
| 25d953ac0ffb92090550d46b8a38da73 | 3224L | 3224E | Cryptorrhynchus conspurcatus Champion, 1906 |
| 8375067b2200fa0a79fa62ac4a96eef0 | 3224M | 3224F | Cryptorrhynchus contaminatus Champion, 1906 |
| 13308897ec0fb59af47b88d22661a5d8 | 3224N | 3224G | Cryptorrhynchus convexicollis Champion, 1906 |
| b49612cb983975006fa0a6171781e688 | 3224P | 3224H | Cryptorrhynchus cordubensis Champion, 1906 |
| 90663f779fc1dc872e7bbdf9f85b067f | 3224Q | 3224J | Cryptorrhynchus coriarius Champion, 1906 |
| 183c80fe85dd5e0a5f81a6d1f03ff8c8 | 3224R | 3224K | Cryptorrhynchus crotonis Champion, 1906 |
| c0f590db8e9de26eaf3c9c64c4220895 | 3224S | 3224L | Cryptorrhynchus cruciatus Fiedler, 1952 |
| e39ac8014cfe5f91c9c5de3a8cece614 | 3224T | 3224M | Cryptorrhynchus curticollis Suffrian, 1876 |
| da85662dbcdf7a454095007ef2cc312f | 3224U | 3224N | Cryptorrhynchus curtirostris Champion, 1906 |
| 44aa8bea905a69059248b92bbafbf8d6 | 3224V | 3224P | Cryptorrhynchus cyphorrhynchoides Kirsch, 1875 |
| 077d57c3401e7fe388e3d8df9dcee654 | 3224W | 3224Q | Cryptorrhynchus dahlbergiae Hustache, 1926 |
| 4d544ab6476ff6b3f8c67060919f508c | 3224X | 3224R | Cryptorrhynchus decemguttatus Chevrolat, 1880 |
| fa4326e209ae4c617d96156c2d98bdbf | 3224Y | 3224S | Cryptorrhynchus decipiens Suffrian, 1876 |
| e28146fc3932a3345b5a1d782d631008 | 3224Z | 3224T | Cryptorrhynchus decoratus Champion, 1906 |
| bd65a09bc44cf094cc36142fde28d1d2 | 32252 | 3224U | Cryptorrhynchus decorus Champion, 1906 |
| 745d0b8e5809b55823d1076e8b89c360 | 32253 | 3224V | Cryptorrhynchus degressus Champion, 1906 |
| aaf78a8388396d63d38d882dff605d3d | 32254 | 3224W | Cryptorrhynchus dentatus Chevrolat, 1880 |
| 30db632fcd3e246a6bb075e828fb192a | 32255 | 3224X | Cryptorrhynchus denticollis Germ., 1824 |
| 4ae4abd17d5d6739454f260a8ec56e45 | 32256 | 3224Y | Cryptorrhynchus diophthalmus Champion, 1906 |
| 709160638ca40cdbc6a522ad4a58f654 | 32257 | 3224Z | Cryptorrhynchus discedens Champion, 1906 |
| 6ea0ecac68022aa5607619b5a362cfb7 | 32258 | 32252 | Cryptorrhynchus disciger Champion, 1906 |
| ae397bb95f17a0f2dc314663876e0557 | 32259 | 32253 | Cryptorrhynchus discophorus Suffrian, 1876 |
| 0a75b78420a6a7e978b1d8ee018d38bf | 3225A | 32254 | Cryptorrhynchus disjunctus Champion, 1906 |
| 59159ab69acc4384ba12164c844902e4 | 3225B | 32255 | Cryptorrhynchus distigma Champion, 1906 |
| 661bce598c3aff44c6276e87b79c9dd7 | 3225C | 32256 | Cryptorrhynchus diversus Champion, 1906 |
| 9ca082bb67f0bcab12baa805115bd9eb | 3225D | 32257 | Cryptorrhynchus dorsuarius Champion, 1906 |
| 9231d111fc9412ca47a27ba8c1c774a0 | 3225E | 32258 | Cryptorrhynchus duplaris Champion, 1906 |
| 3a481616622031dc23e8086ed28c9d09 | 3225F | 32259 | Cryptorrhynchus ebeni Bertoloni, 1855 |
| 2ffd73dc7c7b3d0140b0273744df77bc | 3225G | 3225A | Cryptorrhynchus echinatus Champion, 1906 |
| fa367436057385485208ff5529f9807e | 3225H | 3225B | Cryptorrhynchus enodis Champion, 1906 |
| 143b3ed6cf6eddfe879efdb7eaa3890f | 3225J | 3225C | Cryptorrhynchus erraticus Champion, 1906 |
| 92a6dd33384f1e20db9da5d57c7d37f3 | 3225K | 3225D | Cryptorrhynchus erratus Champion, 1914 |
| dc33a89e9bc066fd498a81e2d33eb33c | 3225L | 3225E | Cryptorrhynchus erubescens Champion, 1906 |

I generated this by exporting from text/tsv from http://api.catalogueoflife.org/dataset/2242/nameusage and querying:

```SQL
SELECT hash AS col_old, nu.ID AS col_new, name_code wrong_id, CONCAT_WS(' ', scientificName, authorship) AS scientificName FROM `ac_plus_2020-12-01`._natural_keys nk
    INNER JOIN `ac_plus_2020-12-01`.`nameusage-1607440443678` nu ON nk.name = nu.scientificName AND nk.author = nu.authorship LIMIT 100;
```
`ac_plus_2020-12-01._natural_keys` is the converted ac-export.zip with the wrong name_codes
`ac_plus_2020-12-01.nameusage-1607440443678` is the nameusage export

Re: https://github.com/CatalogueOfLife/data/issues/211

**Comment by mdoering** [comment]
I was wondering about that too. All names are always siblings. That why I guessed it is based on a previous release with only slightly changed content

**Comment by mdoering** [comment]
The AC-export I did today does contain the correct IDs it seems:

```
7:9:1010	32228	\N	Cryptoripersia	\N	lii	\N	\N	\N	(Brookes, 1976)	32228	\N	\N	1	26	753	3346783	\N	F8D	1	\N	\N	0	0	0
```

**Comment by gdower** [comment]
Good point. Let me re-run conversion on a new ac-export.zip from datset 2242.
