### ISSUE TITLE
Some synonym references missing in portal

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#929]
References are not displaying for some synonyms in the public portal and it might be because inconsistent usage of referenceID and publishedInID in the API.

In the following examples look for publishedInID vs referenceID for the synonyms:

https://api.catalogueoflife.org/dataset/2242/taxon/36FMF/info
https://api.catalogueoflife.org/dataset/2242/taxon/58PXH/info

References missing: https://www.catalogueoflife.org/data/taxon/36FMF
References present: https://www.catalogueoflife.org/data/taxon/58PXH

The references are present in the datasets.

**Comment by mdoering** [comment]
There are several things going wrong here indeed.
The info package should always have all references cited in any of the taxon, synonym, vernacular name or distributions.
That is clearly not the case in `36FMF` - a backend (data) issue.

But also in `58PXH` things are not correct. There are 6 references listed in the taxons referenceIds section:
```
    "referenceIds": [
      "dca34dd0-a6b1-4e98-8a1a-5b7bdd54cf93",
      "aff9b2c2-aec8-4bd9-9b7d-0222a5373bc6",
      "fe5f6ae5-bd2a-4ccc-9a8f-1368ae843f11",
      "c714c1a3-2eeb-4713-8ee9-1cca67e61cde",
      "32ce4f76-e20c-46da-936a-15a71f42343a",
      "875c8b80-dd62-4a8f-b707-48d9d4f95152"
    ]
```

But the taxon page shows way more:
```
Krasnoborov,I.M. & al. Opredelitel rasteni Tuvinskoi ASSR. Novosibirsk. (Rus). (1984).
Roskov Yu.R. Editorial scrutiny: Northern Eurasia data Import (unpubl.). (2005).
Ohwi,J. Flora of Japan. Washington: Smithsonian Institution. (1965).
Ulziykhutag, N. Bobovye Mongolskoi Narodnoi Respubliki, Vol.2. Doct.Thes. (1989).
Yakovlev G, Sytin A & Roskov Y. Legumes of Northern Eurasia. Royal Botanic Gardens, Kew. (1996).
Hara,H. Contributs.study var.Japnse.J.Fac.Sci.uni.Tokyo III.6(2):29-. (1952).
Roskov,Yu.R. Revis.of the g.Trifolium in fl.USSR.Cand.thes.Leningrad(Rus). (1990).
Chen,Te-chao & Wu,Te-lin. Typed Script(MO)130pp Enumeration Chinese Papilionoideae. (1986).
Heywood,V.H. & Ball,P.W. Leguminosae.In:Flora Europaea Vol.2.ed.Tutin,T.G.et al. (1968).
Linnaeus,C.von. Sp.Pl. (1753).
Wei,Z. & Huang,Y.Z. Galega &... In: Fl.Reip.Pop.Sinicae, 42(2) (Leguminosae 5). (1998).
Zohary,M. & Heller,D. The Genus Trifolium. Jerusalem. (1984).
Roskov,Yu.R. Pers. com. (2004).
Bobrov, E.G. In:Prezidentu Akadenii Nauk SSSR V.L.Komarovu:130-142. (1939).
```
@thomasstjerne Maybe all references from the taxon info object are shown even if they are used in vernaculars or elsewhere?

**Comment by mdoering** [comment]
indeed a backend bug, just fixed
