### ISSUE TITLE
Error when I tried to apply decision

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#933]
Leave FeedbackFrontend version: 2c59729 December 8, 2020 4:31 AMBackend version: 74a5865 December 10, 2020 3:59 AM

Working with WPlants Tasks in the clearinghouse, I applied decisions to selected synonyms in SYN-SYN species (diff acc, same auth). Some decisions were processed, others reported error:

![image](https://user-images.githubusercontent.com/28574252/101954983-a00f8d00-3bc2-11eb-95e7-25f49fb88c20.png)

52 names on the page left unresolved due to error.

**Comment by yroskov** [comment]
Another example. Task SYN-SYN infra (diff acc, same auth):


![image](https://user-images.githubusercontent.com/28574252/101955628-cda90600-3bc3-11eb-8754-d5d0baea6f91.png)

**Comment by mdoering** [comment]
Logs say database connection timeout - no free connections available. Thats a bit strange unless we did some postgres works at the same time. Which I don't remember we did. 

It's working now and for sure no code bug. But please reopen this ticket if this happens again - maybe we do get more load than expected. Though our connection pool does not record such high load.
