### ISSUE TITLE
Unable to change number of names shown per page - Error 500

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#938]
Leave FeedbackFrontend version: 2c59729 December 8, 2020 4:31 AMBackend version: 74a5865 December 10, 2020 3:59 AM

Working with Tasks for World Plants in the clearinghouse, I open report for Manuscript Names (953 of 1010). Default setting 50/page, and long report on 21 pages. I have tried to change setting as 500/page, and got Error 500: 

![image](https://user-images.githubusercontent.com/28574252/101956129-b3235c80-3bc4-11eb-9661-14fe08897897.png)

**Comment by mdoering** [comment]
Same as other postgres problems at that time:

```
PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.
```

I have changed pg settings since
