### ISSUE TITLE
Release to the preview website failed

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#939]
Geoff kicked off preview release of Friday, 2020-12-18.
It suppose to include updated ITIS, World Ferns, World Plants, Alucitoidea & Pterophoroidea.

I have checked results at https://preview.catalogueoflife.org/ on 2020-12-12. It looks like, new preview release does not appear on the site.

1) Metadata point to previous release:
Version
This is version 2020-12-01 of the COL Checklist.
https://github.com/CatalogueOfLife/portal/issues/106

2) Statistics for ITIS, World Ferns, World Plants, Alucitoidea & Pterophoroidea are identical to 2020-12-01.

3) Geoff said, it seems to be showing 2242 not 2246

For attention @mdoering @thomasstjerne @gdower

**Comment by thomasstjerne** [comment]
duplicate of https://github.com/CatalogueOfLife/portal/issues/106
