### ISSUE TITLE
Cleasinghouse, Tasks: application of decisions does not work

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#942]
Resolving WCSP Tasks, I have applied decision Ambiguous Synonym to synonyms in SYN-SYN species (diff acc, diff auth), and get error reports for every name, like that:

![image](https://user-images.githubusercontent.com/28574252/103775833-37b2a080-4ff4-11eb-91ef-dbf2ba1ab81a.png)

**Comment by mdoering** [comment]
```
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 5000ms.
```

Puzzled why this is. @thomasstjerne maybe a huge amount of parallel request from the UI? How many can that be, 100 in parallel? I doubt this is allowed in a browser for a single domain, or is it?

**Comment by yroskov** [comment]
The same problem with SYN-SYN infra (diff acc, diff auth)

![image](https://user-images.githubusercontent.com/28574252/103776620-49e10e80-4ff5-11eb-8622-18fc4ad7fdbf.png)

**Comment by mdoering** [comment]
How many taxa are these @yroskov ?
I see we have limited the backend to use 32 db connections - that might be a bit too low.
If these requests come in parallel we might get problems as each could be using more than 1 connection, e.g. for authentication

**Comment by yroskov** [comment]
How many records are these? - Interface does not give an answer to the question. It shows "1089 names on this page <1, 2>". When I switch to page 2, it show "1138 names on this page <1,2,3> _there are 3 pages now, before were 2, and number of pages may grows during progress._

**Comment by thomasstjerne** [comment]
I think Chrome only sends 6 parallel requests pr domain. 
I created an issue for the UI to do limit requests, but in principle this should be handled by the browser.
https://github.com/CatalogueOfLife/checklistbank/issues/789

**Comment by mdoering** [comment]
I'll try to debug it locally to see how many connections are opened at the same time

**Comment by yroskov** [comment]
@mdoering @thomasstjerne 

I have the same problem today (2021-01-08). 
TASKS ACC-SYN species (diff acc, diff auth):

![image](https://user-images.githubusercontent.com/28574252/104054506-e0a6fa00-51b2-11eb-932e-bdb7afe6d334.png)

**Comment by mdoering** [comment]
On Safari and Chrome only 6 requests are done in parallel. Also not thousands of requests are send but just the page you are looking at. 50 max by default, but maybe @yroskov increased the page size to more? I can't see from the screenshots.

I have doubled the number of max connections in the backend, please reopen this ticket if it shows up again !!!
