### ISSUE TITLE
Allow sectors without a target & subject?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#945]
As far as I know there's no way to attach a full dataset as a sector to managed datasets. For datasets like [ICTV](https://data.catalogueoflife.org/dataset/1014/classification) with no root taxon, if they add kingdoms or other top level taxa and we don't notice, they won't get assembled and synced. It's very common for datasets to not have a root taxon, and I usually add them when I create dataset converters.

TaxonWorks forces you to attach everything to 1 `root` placeholder taxon in the datasets called `root`, which could be advantageous for our purposes, too, because it would allow us to attach the `root` taxon to the tree in assembly and that would assemble the full dataset. I'm not sure if that would be easy to implement or not, but it would probably help keep CoL more up to date.

**Comment by mdoering** [comment]
So you suggest to always create a root taxon in case its missing on import? That could be done rather easily.
But we could also create a new sector MODE which allows to sync an entire dataset. 

Any preference over these 2 options? The later one would need a change in the UI as you would need to be able to create a new sector without drag n drop. But that should also be rather simple, e.g. just a new entry in the context menu of the project tree or a new button on the source side.

**Comment by yroskov** [comment]
I would not introduce higher classification in GSD export, if these taxa are not present in the original GSD. In some cases it is risky business.

**Comment by mdoering** [comment]
Understood, but this is not considered as one of the 2 options. These rather are:

 - a) add a synthetic root taxon in case there is no single root. Propose to call it "Biota" 
 - b) add a new sector mode that includes all root taxa of the source dataset under the target. Similar to a UNION copies any children

**Comment by mdoering** [comment]
I feel we are better off with b)

**Comment by gdower** [comment]
I think it's better to go with a) actually, because the user will already intuitively know how to assemble the full dataset using the same drag and drop method. You wouldn't need a new sector type, because the dataset is only going to have 1 top level name called "Biota" introduced by the importer, which works with the existing subject-target sector registrations. If we went with b) there's a possibility that the user won't know the option exists, or won't understand how to use it.

It might be good to at least briefly talk about this on the Tuesday stand-up though in case there are any implications that I have not thought of. I don't think adding a top level root would mess up the existing sector registrations. For datasets like ITIS where we need multiple sector registrations, Yuri would just ignore the top level root. The frontend already expands the top level root, so it shouldn't add a tedious extra click.

**Comment by mdoering** [comment]
The main implication of a) is that we alter the source data and the far more users that do not assemble projects might wonder where Biota comes from. But I don't mind any of the two

**Comment by gdower** [comment]
That's a good point.

**Comment by mdoering** [comment]
For merging names into the extended catalogue we will also likely need to declare a sector which matches all root taxa in a source. E.g. when ZooBank or IPNI will have thousands of root taxa.

I was thinking of coding for a special catch all identifier that matches not a single source or target, but any.

**Comment by mdoering** [comment]
Consider to use a magic source taxonID=* or to allow null values instead

**Comment by mdoering** [comment]
we allow null values now for subject and target with merge mode.
