### ISSUE TITLE
Can't make requests against COL API on CI systems

### ISSUE THREAD

**Issue by sckott** [CatalogueOfLife/backend#950]
COL API been working fine locally - but testing real HTTP requests against COL API seem to not work on Github Actions (i don't know about other CI systems). I always get 

```
Empty reply from server
```

E.g., from this `rcol` package example that tries to run on GH Actions  https://github.com/ropensci/rcol/runs/1690374153?check_suite_focus=true#step:10:79  

```r
z <- cp_children(dataset_key=1000, taxon_id='1', verbose=TRUE)
```

```r
*   Trying 130.225.43.9...
* Connected to api.catalogueoflife.org (130.225.43.9) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
* 	 subject: CN=catalogueoflife.org
* 	 start date: Jan  2 23:05:15 2021 GMT
* 	 expire date: Apr  2 23:05:15 2021 GMT
* 	 subjectAltName: api.catalogueoflife.org matched
* 	 issuer: C=US; O=Let's Encrypt; CN=R3
* 	 SSL certificate verify ok.
> GET /dataset/1000/taxon/1/children HTTP/1.1
Host: api.catalogueoflife.org
Accept-Encoding: gzip, deflate
Accept: application/json, text/xml, application/xml, */*
User-Agent: r-curl/4.3 crul/1.0.0 rOpenSci(rcol/0.1.0)
X-USER-AGENT: r-curl/4.3 crul/1.0.0 rOpenSci(rcol/0.1.0)

* Empty reply from server
* Connection #0 to host api.catalogueoflife.org left intact
Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  Empty reply from server
```

One difference I can see is that locally on my machine I see:

```
ALPN, offering h2
# and 
Using HTTP2, ...
```

So it seems that with whatever setup I have locally, HTTP2 is used, whereas on GH Actions HTTP1 is used. Could that be the problem here?

Are you seeing anything in your logs that could help here?

I'd love to ssh into the GH Actions server, but don't think that's allowed

Tested on another linux box and could not replicate the problem on GH Actions

**Comment by sckott** [comment]
@mdoering  Yes, using https (i realize the curl output doesn't show the scheme)

@MattBlissett I've never had problems before on Github actions with any http requests.

Thanks for checking on this. I'll keep digging. I've not encountered this issue before. In case it helps, I'll add a user agent string to http requests for those that come from GitHub Actions.

**Comment by mdoering** [comment]
if you can place a specific user agent to the gh actions that would help, yes!

**Comment by sckott** [comment]
Okay, a few runs have completed on Github Actions with a user agent string that now contains "GitHub Actions"

**Comment by mdoering** [comment]
I don't see any of these requests in the application logs.
Only for user agent `r-curl/4.3, crul/1.0.0, rOpenSci`

It seems to be blocked somewhere before that.
Is there a way that I can trigger the action to monitor our varnish cache live logs?

**Comment by sckott** [comment]
Okay, thanks for letting me know. I just ran a check on GH Actions about 1 minute ago, with same results and passing the header. See anything in logs? Sounds like you're right that the requests are getting blocked earlier on. I'm not even sure where that would be. 

> Is there a way that I can trigger the action to monitor our varnish cache live logs?

Not sure I follow. Can you explain?

**Comment by sckott** [comment]
Okay, should have tried this earlier. If I force the http version I can replicate the problem:

```
curl --http1.1 https://api.catalogueoflife.org/dataset/1000/taxon/1/children
# curl: (52) Empty reply from server

curl --http1.0 https://api.catalogueoflife.org/dataset/1000/taxon/1/children
# curl: (52) Empty reply from server

curl --http2 https://api.catalogueoflife.org/dataset/1000/taxon/1/children
{"offset":0,"limit":10,"total":2,"result":[{"created":"2020-07-02T23:50:52.600532","createdBy":10,"modified":"2020-07-02T23:50:52.600532","modifiedBy":10,"datasetKey":1000,"id":"2","verbatimKey":856,"name":{"created":"2020-07-02T23:50:52.226718","createdBy":10,"modified":"2020-07-13T01:40:01.160395","modifiedBy":10,"datasetKey":1000,"id":"2","verbatimKey":1660,"homotypicNameId":"2","scientificName":"Archaea","rank":"kingdom","uninomial":"Archaea","origin":"source","type":"scientific","parsed":true},"status":"accepted","origin":"source","parentId":"1","label":"Archaea","labelHtml":"Archaea"},{"created":"2020-07-02T23:50:52.600532","createdBy":10,"modified":"2020-07-02T23:50:52.600532","modifiedBy":10,"datasetKey":1000,"id":"41","verbatimKey":319,"name":{"created":"2020-07-02T23:50:52.226718","createdBy":10,"modified":"2020-07-13T01:40:01.160395","modifiedBy":10,"datasetKey":1000,"id":"41","verbatimKey":4830,"homotypicNameId":"41","scientificName":"Bacteria","rank":"kingdom","uninomial":"Bacteria","origin":"source","type":"scientific","parsed":true},"status":"accepted","origin":"source","parentId":"1","label":"Bacteria","labelHtml":"Bacteria"}],"empty":false,"last":true}
```

I'm guessing there's some kind of setting in the openssl or related that I have on my local machine that uses H2 by default, where on Github Actions it uses http 1.1 by default - so GH actions always fails to make requests. 

I'm still trying to figure out how to make sure GH actions uses http 2 rather than http 1.1. 

Anything you can do on your end to allow clients that use http 1.1 to work?

**Comment by mdoering** [comment]
The fun thing is that it works via http 1.0, 1.1 or 2.0 from my machine:

```
curl --http1.1 https://api.catalogueoflife.org/dataset/1000/taxon/1/children
{"offset":0,"limit":10,"total":2,"result":[{"created":"2020-07-02T23:50:52.600532","createdBy":10,"modified":"2020-07-02T23:50:52.600532","modifiedBy":10,"datasetKey":1000,"id":"2","verbatimKey":856,"name":{"created":"2020-07-02T23:50:52.226718","createdBy":10,"modified":"2020-07-13T01:40:01.160395","modifiedBy":10,"datasetKey":1000,"id":"2","verbatimKey":1660,"homotypicNameId":"2","scientificName":"Archaea","rank":"kingdom","uninomial":"Archaea","origin":"source","type":"scientific","parsed":true},"status":"accepted","origin":"source","parentId":"1","label":"Archaea","labelHtml":"Archaea"},{"created":"2020-07-02T23:50:52.600532","createdBy":10,"modified":"2020-07-02T23:50:52.600532","modifiedBy":10,"datasetKey":1000,"id":"41","verbatimKey":319,"name":{"created":"2020-07-02T23:50:52.226718","createdBy":10,"modified":"2020-07-13T01:40:01.160395","modifiedBy":10,"datasetKey":1000,"id":"41","verbatimKey":4830,"homotypicNameId":"41","scientificName":"Bacteria","rank":"kingdom","uninomial":"Bacteria","origin":"source","type":"scientific","parsed":true},"status":"accepted","origin":"source","parentId":"1","label":"Bacteria","labelHtml":"Bacteria"}],"empty":false,"last":true}%  
```

Maybe you can try to use http instead of https?
@MattBlissett any idea why we might see this?

**Comment by fmendezh** [comment]
I get this output:
curl -v --http1.1 https://api.catalogueoflife.org/dataset/1000/taxon/1/children
*   Trying 130.225.43.9...
* TCP_NODELAY set
* Connected to api.catalogueoflife.org (130.225.43.9) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT)
, TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT)
, TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT)
, TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=catalogueoflife.org
*  start date: Jan  2 23:05:15 2021 GMT
*  expire date: Apr  2 23:05:15 2021 GMT
*  subjectAltName: host "api.catalogueoflife.org" matched cert's "*.catalogueoflife.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /dataset/1000/taxon/1/children HTTP/1.1
> Host: api.catalogueoflife.org
> User-Agent: curl/7.64.1
> Accept: /
> 
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Connection #0 to host api.catalogueoflife.org left intact
curl: (52) Empty reply from server
* Closing connection 0

macOs Big Sur 11.0.1

**Comment by sckott** [comment]
perhaps this has to do with curl version or its dependencies. on my mac:

```
curl --version
curl 7.74.0 (x86_64-apple-darwin19.6.0) libcurl/7.74.0 (SecureTransport) OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.42.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Comment by MattBlissett** [comment]
I didn't see it from Linux, Mac or Windows machines I have here, but Fede did see it from his Mac.  Fede also sees it for https://api.gbif.org, but that has the same configuration.

My Mac is on Big Sur 11.1, but for some reason has an older version of Curl:

```
curl --version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

**Comment by fmendezh** [comment]
> I didn't see it from Linux, Mac or Windows machines I have here, but Fede did see it from his Mac. Fede also sees it for https://api.gbif.org, but that has the same configuration.
> 
> My Mac is on Big Sur 11.1, but for some reason has an older version of Curl:
> 
> ```
> curl --version
> curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
> Release-Date: 2019-03-27
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
> Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
> ```

ok, this doesn't make any sense,  I have the same version:
```
curl --version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

**Comment by MattBlissett** [comment]
It turns out to be related to how far you are from our server (like [the 500 mile email](https://www.ibiblio.org/harris/500milemail.html)), specifically https://github.com/varnish/hitch/issues/330 with the fix being as described in the comment.  The updated default hasn't been applied to Varnish 6.0.7, the long-term supported branch.

It should work now.

**Comment by sckott** [comment]
I was just about to say I can just use `http` instead of `https` (Tested on CI and that does work)

But glad we don't need to resort to http only.  Thanks for the fix!

**Comment by mdoering** [comment]
glad you found that @MattBlissett, a rather obscure issue.
And thanks @sckott for sticking with us that long!

**Comment by sckott** [comment]
thanks all
