### ISSUE TITLE
Sync attempt should return error if importer is turned off

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#952]
To test decisions I have created this managed dataset and attached one sector. It was assigned `sectorKey: 1`.
But when I hit sync, it doesn´t copy taxa from the source:
https://data.dev.catalogueoflife.org/catalogue/2049/assembly

**Comment by mdoering** [comment]
Hm, works for me. At least the first  thousands are going through fine:

<img width="650" alt="Screenshot 2021-01-18 at 11 15 55" src="https://user-images.githubusercontent.com/327505/104902130-9aa22100-597e-11eb-881b-12e3f1363fe4.png">

**Comment by mdoering** [comment]
the older syncs failed with "UnavailableException: The names index is currently not available".
Was the importer not started then? Its on now

**Comment by thomasstjerne** [comment]
I turned on the importer - does that operate syncs as well?

**Comment by mdoering** [comment]
yes. also required for the name matching API. Maybe we need to find a better name or split importer, sync and names index into separate settings.

**Comment by thomasstjerne** [comment]
The error wasn´t passed through the API, it just responded status 200.
Then I wanted to import a dataset, and then I got the error that hinted me.

**Comment by mdoering** [comment]
A POST returns a 503 now if the names index is not online
