### ISSUE TITLE
Sector rematch is failing

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#955]
The backend is reporting a bunch of ITIS sectors as broken, when they actually seem to be correctly registered. When I use the frontend [sector management interface to reattach the subject to the target](https://data.catalogueoflife.org/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=2144), it removes the subject's name, authorship, rank, code, status, and parent and adds the subject ID back, which sets subject.broken=false as shown below. Although maybe the drag and drop assembly registers the sector differently than the sector management interface which might only use the ID instead of name, authorship, rank, code, status, and parent?

Before
```JSON
{
	"created": "2021-01-05T19:53:17.741287",
	"createdBy": 102,
	"modified": "2021-01-21T22:35:29.031801",
	"modifiedBy": 102,
	"datasetKey": 3,
	"id": 1136,
	"target": {
	"id": "bdf68402-b69e-4de6-b7ce-15a773517f52",
	"name": "Opiliones",
	"authorship": "Sundevall, 1833",
	"rank": "order",
	"code": "zoological",
	"broken": false
	},
	"subjectDatasetKey": 2144,
	"subject": {
	"name": "Triaenonychoidea",
	"authorship": "Sørensen, 1886",
	"rank": "superfamily",
	"code": "zoological",
	"status": "accepted",
	"parent": "1012395",
	"broken": true
	},
	"originalSubjectId": "1012405",
	"mode": "attach",
	"syncAttempt": 2,
	"size": 636
},
```

After
```JSON
{
  "created": "2021-01-05T19:53:17.741287",
  "createdBy": 102,
  "modified": "2021-01-25T16:22:15.136347",
  "modifiedBy": 103,
  "datasetKey": 3,
  "id": 1136,
  "target": {
    "id": "bdf68402-b69e-4de6-b7ce-15a773517f52",
    "name": "Opiliones",
    "authorship": "Sundevall, 1833",
    "rank": "order",
    "code": "zoological",
    "broken": false
  },
  "subjectDatasetKey": 2144,
  "subject": {
    "id": "1012405",
    "broken": false
  },
  "originalSubjectId": "1012405",
  "mode": "attach",
  "syncAttempt": 2,
  "size": 636
}
```

**Comment by gdower** [comment]
@yroskov tried to do `rematch all` on Thursday which didn't work. My best guess is that when ITIS failed to import because of the [PARENT_SPECIES_MISSING bug](https://github.com/CatalogueOfLife/backend/issues/954), that the subject ID was removed and the sectors were reported as broken. Rematch does not seem to work correctly despite all of the sector registration information being correct.

Doing the following [fixes the broken sector](http://api.catalogueoflife.org/dataset/3/sector/1136) with the only difference being that I added the subject.id back in from the originalSubjectId:

```
PUT /dataset/3/sector/1136
{
	"created": "2021-01-05T19:53:17.741287",
	"createdBy": 102,
	"modified": "2021-01-21T22:35:29.031801",
	"modifiedBy": 102,
	"datasetKey": 3,
	"id": 1136,
	"target": {
	"id": "bdf68402-b69e-4de6-b7ce-15a773517f52",
	"name": "Opiliones",
	"authorship": "Sundevall, 1833",
	"rank": "order",
	"code": "zoological",
	"broken": false
	},
	"subjectDatasetKey": 2144,
	"subject": {
	"id": "1012405",
	"name": "Triaenonychoidea",
	"authorship": "Sørensen, 1886",
	"rank": "superfamily",
	"code": "zoological",
	"status": "accepted",
	"parent": "1012395",
	"broken": true
	},
	"originalSubjectId": "1012405",
	"mode": "attach",
	"syncAttempt": 2,
	"size": 636
}
```

I think the actual bug is that rematch is failing, and if rematch worked, I would assume that you rematch the sectors when re-importing a dataset, which would correct the broken state for the sectors.

**Comment by mdoering** [comment]
As far as I can see the _Rematch Decisions_ option is not turned on for ITIS.
So any ID changes in the dataset will lead to broken sectors. Unless you want to manually manage all decisions and sectors you should keep that turned on!

**Comment by mdoering** [comment]
I would even be happy to remove that option again as I can't see a reason for turning this ever off

**Comment by mdoering** [comment]
No idea why we lost the subjects name and rank though. That's not good.
I saw Matt reported we had some Postgres connection problems at some stage. Maybe that caused some losses somehow? Or did you use the API to update those sectors manually maybe? Without a subjects name and rank we cannot rematch

**Comment by gdower** [comment]
Good point--I'll turn rematch on. It seems unlikely that there were ID changes though and the current ID matches the originalSubjectID.

I think we should keep that feature actually because a lot of datasets don't have persistent IDs.

> No idea why we lost the subjects name and rank though.

It might be a frontend bug. I'll check and open a ticket, if so.

**Comment by gdower** [comment]
You should rest, recover, and not worry about this for now, because it's not a major issue. I can rematch the sectors by adding back the IDs.

**Comment by mdoering** [comment]
you can actually use the manual matching in the UI to fix some

**Comment by gdower** [comment]
Yeah it's a frontend issue where it only registers the ID for the subject when using this interface. I'll open a bug ticket.

![image](https://user-images.githubusercontent.com/8573609/106026482-7dacd280-608f-11eb-86db-8bac3f43f743.png)

```
PUT https://api.catalogueoflife.org/dataset/3/sector/867
{
  "created": "2020-08-25T21:00:51.89555",
  "createdBy": 102,
  "modified": "2021-01-21T22:35:29.046866",
  "modifiedBy": 102,
  "datasetKey": 3,
  "id": 867,
  "target": {
    "id": "57b4cba3-9a7d-493b-b44c-866591658f54",
    "name": "Coleoptera",
    "rank": "order",
    "broken": false
  },
  "subjectDatasetKey": 2144,
  "subject": {
    "id": "109217"
  },
  "originalSubjectId": "109217",
  "mode": "attach",
  "syncAttempt": 8,
  "size": 108,
  "dataset": {
    "created": "2020-06-12T18:18:00.600409",
    "createdBy": 102,
    "modified": "2021-01-27T16:56:17.292906",
    "modifiedBy": 103,
    "key": 2144,
    "importAttempt": 31,
    "type": "taxonomic",
    "origin": "external",
    "title": "The Integrated Taxonomic Information System",
    "alias": "ITIS",
    "description": "The Integrated Taxonomic Information System (ITIS, www.itis.gov) was proposed in 1993 and established through a Memorandum of Understanding in 1996. ITIS partners with U.S. Federal agencies, other government agencies and organizations from the United States, Canada and Mexico, and with data stewards and experts from around the world to maintain an authoritative reference of scientific and common names of all seven Kingdoms of Life (Archaea, Bacteria, Protozoa, Chromista, Fungi, Plantae, and Animalia). For news and information about recent ITIS updates see www.itis.gov/whatsnew.html.",
    "contact": {
      "familyName": "itiswebmaster@itis.gov",
      "name": "itiswebmaster@itis.gov"
    },
    "license": "other",
    "version": "2020-12-21",
    "released": "2020-12-21",
    "geographicScope": "Global & Regional",
    "website": "https://itis.gov",
    "group": "Biota",
    "confidence": 5,
    "completeness": 100,
    "imported": "2021-01-21T22:07:16.428692",
    "size": 848844,
    "private": false
  }
}
```

**Comment by gdower** [comment]
I'll close this for now because maybe it is just the rematch settings that were messing this up.
