### ISSUE TITLE
Logo upload is failed

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#958]
I have tried to upload logo for WCO (dataset 2256), but upload is failed:

Request failed with status code 503
HTTP method: POST
https://api.catalogueoflife.org/importer/2256

**Comment by mdoering** [comment]
Not sure what you exactly did. Which file did you use and how did you upload it?

It works for me. Just the logo does not show for private datasets. 
@thomasstjerne was that expected or did we resolve that?

There is one issue with the backend. At some point I decided to add a default header to all request do not provide any Accept header or which is set to accept all `*/*`. This breaks retrieval of the logo by just the URL. I have reverted this now, but not deployed to prod yet.

**Comment by mdoering** [comment]
closing as I cannot reproduce this. @yroskov if you see this happening again please reopen and explain what exactly happened. If you manually uploaded a log file please also attach the file here
