### ISSUE TITLE
Subgenus uninomials always flagged with  `inconsistent name` and `parsed name differs` issues

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#960]
No matter how subgenus uninomials are provided, they always seem to be flagged with the `inconsistent name` and `parsed name differs` issues. I tried all of the below approaches in this example dataset and every single one is [flagged with those issues](https://data.dev.catalogueoflife.org/dataset/2058/verbatim?issue=inconsistent+name&limit=50):

I think IDs 9 and 18 are the way subgenera are supposed to be provided. People often try to supply them as `Zalmoxis (Papuastus)` in scientificName. The genus - infraspecificEpithet fields, I interpret to be for binomials and trinomials only.

ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | cultivarEpithet | code | status | referenceID | publishedInYear | publishedInPage | publishedInPageLink | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Zalmoxis (Papuastus) | Zalmoxis | Papuastus |   |   |   | zoological |   |   |   |   |   |   |  
2 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Zalmoxis (Papuastus) | Zalmoxis |   |   |   |   | zoological |   |   |   |   |   |   |  
3 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Zalmoxis (Papuastus) |   |   |   |   |   | zoological |   |   |   |   |   |   |  
4 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Papuastus | Zalmoxis | Papuastus |   |   |   | zoological |   |   |   |   |   |   |  
5 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Papuastus | Zalmoxis |   |   |   |   | zoological |   |   |   |   |   |   |  
6 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Papuastus |   |   |   |   |   | zoological |   |   |   |   |   |   |  
7 |   | Papuastus | Roewer, 1949 | subgenus | Papuastus | Zalmoxis | Papuastus |   |   |   | zoological |   |   |   |   |   |   |  
8 |   | Papuastus | Roewer, 1949 | subgenus | Papuastus | Zalmoxis |   |   |   |   | zoological |   |   |   |   |   |   |  
9 |   | Papuastus | Roewer, 1949 | subgenus | Papuastus |   |   |   |   |   | zoological |   |   |   |   |   |   |  
10 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Zalmoxis (Papuastus) | Zalmoxis | Papuastus |   |   |   | botanical |   |   |   |   |   |   |  
11 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Zalmoxis (Papuastus) | Zalmoxis |   |   |   |   | botanical |   |   |   |   |   |   |  
12 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Zalmoxis (Papuastus) |   |   |   |   |   | botanical |   |   |   |   |   |   |  
13 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Papuastus | Zalmoxis | Papuastus |   |   |   | botanical |   |   |   |   |   |   |  
14 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Papuastus | Zalmoxis |   |   |   |   | botanical |   |   |   |   |   |   |  
15 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus | Papuastus |   |   |   |   |   | botanical |   |   |   |   |   |   |  
16 |   | Papuastus | Roewer, 1949 | subgenus | Papuastus | Zalmoxis | Papuastus |   |   |   | botanical |   |   |   |   |   |   |  
17 |   | Papuastus | Roewer, 1949 | subgenus | Papuastus | Zalmoxis |   |   |   |   | botanical |   |   |   |   |   |   |  
18 |   | Papuastus | Roewer, 1949 | subgenus | Papuastus |   |   |   |   |   | botanical |   |   |   |   |   |   |

**Comment by mdoering** [comment]
Oh, there must be sth wrong in the importer then.
The uninominal field is supposed to contain just a single word, a uni-nomial, and only in the case there is nothing else. 
I.e. a genus, family or higher rank name. A subgenus without the genus would also be a fit, but infragenerics are usually cited by their genus placement. So the correct way would be the first, but leaving uninominal blank. I don't see this option anywhere, maybe this is why its flagged. I will try to trace it locally.

**Comment by gdower** [comment]
You mean like below? I added it to that example dataset as records 19, 20. I somewhat dislike that approach because I think it will confuse people with the genus and infragenericEpithet being populated when it's not a species or infraspecies.

ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | cultivarEpithet | code | status | referenceID | publishedInYear | publishedInPage | publishedInPageLink | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
19 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus |   |   |   |   |   |   | zoological |   |   |   |   |   |   |  
20 |   | Zalmoxis (Papuastus) | Roewer, 1949 | subgenus |   | Zalmoxis | Papuastus |   |   |   | zoological |   |   |   |   |   |   |  

It does work though: 

https://data.dev.catalogueoflife.org/dataset/2058/verbatim?offset=9&limit=1
https://data.dev.catalogueoflife.org/dataset/2058/verbatim?offset=14&limit=1

**Comment by mdoering** [comment]
good to know. I designed it that way so there is no bug then. Uninominal is strictly for when the scientific name is a single word. I see your uneasiness with infragenericEpithet. If it would be "subgenus" I suspect it would be more obvious. But we also see all kind of other subgeneric ranks especially in botany.

**Comment by mdoering** [comment]
uninominal and the other parsed name epithet fields are basically mutually exclusive.
A hierarchical diagram would be useful to users to document that.
