### ISSUE TITLE
Inconsistent country string handling

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#964]
The documentation lists AFGHANISTAN as an example for organisations in the PUT /dataset/{key} endpoint:

```
  "organisations": [
    {
      "name": "string",
      "department": "string",
      "city": "string",
      "state": "string",
      "country": "AFGHANISTAN",
      "label": "string"
    }
  ],
```

However, if you try to PUT /dataset/2069 that it won't take AFGHANISTAN as the country, because apparently the backend expects a 2 letter country code. 

```
"title": "Country example",
"type": "taxonomic",
"origin": "external",
"organisations": [
    {
      "name": "Example 1",
      "department": "string",
      "city": "string",
      "state": "string",
      "country": "AFGHANISTAN",
      "label": "string"
    },
    {
      "name": "Example 2",
      "department": "string",
      "city": "string",
      "state": "string",
      "country": "AF",
      "label": "string"
    }
  ]
```
Here's what GET /dataset/2069 returns after putting that:

```
{
  "created": "2021-02-10T17:55:37.356368",
  "createdBy": 103,
  "modified": "2021-02-10T17:56:08.693276",
  "modifiedBy": 103,
  "key": 2069,
  "type": "taxonomic",
  "origin": "external",
  "title": "Country example",
  "organisations": [
    {
      "name": "Example 1",
      "department": "string",
      "city": "string",
      "state": "string",
      "label": "Example 1, string, string, string"
    },
    {
      "name": "Example 2",
      "department": "string",
      "city": "string",
      "state": "string",
      "country": "AF",
      "label": "Example 2, string, string, string, Afghanistan"
    }
  ],
  "size": 0,
  "private": false
}
```

This has messed up some of the CoL metadata patches, because I thought the backend took country strings. Some datasets had 2 letter country codes, but not all so we didn't immediately notice.

Ideally it would be good if the backend can parse a country string into a country code. Otherwise, we need to update the documentation to specify using an ISO code. People will still likely screw this up without noticing because the backend doesn't warn you that it couldn't parse the country code. The YAML validator tool silently parses the country string into a country code, which is probably okay so long as the YAML importer actually processes the YAML correctly.

**Comment by mdoering** [comment]
Which documentation says the country should be a string? It is correct that the API only uses ISO 2 letter codes everywhere we use countries. Just the YAML metadata is allowed to contain a country name.

You can also use the country parser via the API in case you need this for scripts. All available parsers are listed here and normally take a `q` parameter as the input:
http://api.catalogueoflife.org/parser/

To parse countries you can do:
http://api.catalogueoflife.org/parser/country?q=Germany

**Comment by mdoering** [comment]
The only incorrect behaviour I can spot is that the PUT should have thrown an error if do not use [known 2 letter codes](http://api.catalogueoflife.org/vocab/country).

**Comment by mdoering** [comment]
Note that `PUT /dataset/2069` is not changing a metadata patch but modifying the current metadata.

**Comment by mdoering** [comment]
we could also allow the API to accept YAML metadata in addition to JSON - that might be useful

**Comment by mdoering** [comment]
I just added support for PUT/POST of YAML and EML. 
Also the JSON parsing now also accepts country names the same way YAML does.

I am not sure about throwing an exception if the country is not parsable. Sounds good to have in the atomic PUT/POST requests, but if you import a ColDP or DwC archive I don't think this should stop the importer from reading any metadata - or should it?

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/backend/commit/dd48812c8cd7421b91fc0027e722b5c944264b25

**Comment by gdower** [comment]
The API documentation gives the example of providing a country string:

![image](https://user-images.githubusercontent.com/8573609/107647902-47e81c00-6c41-11eb-9fda-c0bc8664586e.png)

I'm re-opening this because the documentation examples are wrong.

Looking at your patch, I think it might be an improvement to throw an exception if a country code isn't given because at least then the user will know something is wrong, but then again it might also be extremely frustrating to users depending on how the frontend handles it. If a user spends an hour entering metadata and then loses all their work in a save because they didn't enter a country code, that's really not going to be good thing.

I don't really want YAML support from the backend. If anything that just complicates things, and will add to confusion for other users because the YAML version allows country strings and the JSON version doesn't.

**Comment by mdoering** [comment]
as said above the JSON version now uses the exact same parser and supports country names, not just ISO codes.

**Comment by gdower** [comment]
Great, thanks!

**Comment by mdoering** [comment]
That example is generated by Swagger - changing that will get us into manually crafting the documentation which I would like to avoid at this stage. We still haven't gone all the way
