### ISSUE TITLE
Immutable originalSubjectId breaking sectors

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#969]
A bunch of sectors broke for World Plants when Yuri did a `rematch all` on the dataset on the [sectors page](https://data.catalogueoflife.org/catalogue/3/sector?broken=true&limit=100&offset=0&subjectDatasetKey=1141). I think it's because the sector `originalSubjectId` is still using the old subject IDs. I fixed the broken sectors, but I cannot update the `originalSubjectId` which means that if anyone hits `rematch all` again it will probably break those sectors again.

How does the dataset option "rematch decisions" affect the `originalSubjectId`, if at all? I had rematch off originally and turned it on after we hit this issue.

```JSON
GET https://api.catalogueoflife.org/dataset/3/sector/1078
{
  "created": "2020-09-17T19:23:58.276078",
  "createdBy": 102,
  "modified": "2021-03-03T22:23:52.703092",
  "modifiedBy": 103,
  "datasetKey": 3,
  "id": 1078,
  "target": {
    "id": "604e7fab-83f7-4f1b-ba59-97d03d7ead26",
    "name": "Magnoliopsida",
    "rank": "class",
    "broken": false
  },
  "subjectDatasetKey": 1141,
  "subject": {
    "id": "Paracryphiales",
    "name": "Paracryphiales",
    "authorship": "Takht. ex Reveal",
    "rank": "order",
    "code": "botanical",
    "status": "accepted",
    "broken": false
  },
  "originalSubjectId": "f077cff0-3246-5260-ba9a-8699d727b15f",
  "mode": "attach",
  "syncAttempt": 9,
  "size": 79
}
```

Here's what I PUT with no success in updating the `originalSubjectId` as seen above:

```JSON
PUT https://api.catalogueoflife.org/dataset/3/sector/1078
{
	"created": "2020-09-17T19:23:58.276078",
	"createdBy": 102,
	"modified": "2021-03-03T21:51:06.364326",
	"modifiedBy": 103,
	"datasetKey": 3,
	"id": 1078,
	"target": {
		"id": "604e7fab-83f7-4f1b-ba59-97d03d7ead26",
		"name": "Magnoliopsida",
		"rank": "class",
		"broken": false
	},
	"subjectDatasetKey": 1141,
	"subject": {
		"id": "Paracryphiales",
		"name": "Paracryphiales",
		"authorship": "Takht. ex Reveal",
		"rank": "order",
		"code": "botanical",
		"status": "accepted",
		"broken": false
	},
	"originalSubjectId": "Paracryphiales",
	"mode": "attach",
	"syncAttempt": 8,
	"size": 79
}
```

**Comment by mdoering** [comment]
rematch=off simply means no automatic rematching is performed after an import of the source. 
rematch=on will auto rematch which is the same as a manual rematch all on a dataset page as Yuri apparently did.

The broken sectors must have a different primary reason
