### ISSUE TITLE
Subterclass: please include missing rank "Subterclass" in the classification

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#970]
@gdower has pointed 8 taxa in WoRMS with the rank "Subterclass".  

@mdoering, pls include missing rank(s) in the checklistbank hierarchy. 

This rank is a member of the class group with following hierarchy:

Superclass
Class 
Subclass
Infraclass 
**Subterclass** 
Parvclass

**Comment by gdower** [comment]
Here's some examples:

http://www.molluscabase.org/aphia.php?p=taxdetails&id=216
http://www.molluscabase.org/aphia.php?p=taxdetails&id=382203
http://www.molluscabase.org/aphia.php?p=taxdetails&id=382253
http://www.molluscabase.org/aphia.php?p=taxdetails&id=1057250

**Comment by mdoering** [comment]
any other ranks we are aware of that need to be added?
What about realm (virus) vs domain (rest) - we consider realm as synonymous to domain

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/backend/commit/9b9008be5030cfaed87e15752788fffb4a425886

**Comment by mdoering** [comment]
deployed
