### ISSUE TITLE
DB Pool error trying to create many decisions

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#993]
For attention of @mdoering @thomasstjerne 

Again the same situation as few months ago: when I tried to apply decisions in the reports with substantial number of names (200+), I have got a list of errors, like that:

(WoRMS Mollusca, id 1130, TASKS)

![image](https://user-images.githubusercontent.com/28574252/113042799-390de800-9161-11eb-868c-6d619ea7d9f7.png)

**Comment by mdoering** [comment]
same as #942

This is again a lack of db connections from the Hikari Pool:
https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-30T18:05:34.765Z',to:'2021-03-30T22:21:00.939Z'))&_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'24993300-fdb1-11ea-93de-b97c40066ce8',key:level,negate:!f,params:(query:ERROR),type:phrase),query:(match_phrase:(level:ERROR)))),index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',interval:auto,query:(language:kuery,query:''),sort:!())

I had changed the pool configs to keep a minimum of 20 idle connections and a maximum of 60.
I am surprised how many concurrent connections seem to be used. Maybe they are not closed/returned properly? The UI should be sending just 8 parallel requests to the API, this could not lead to more than 60 connections. Ganglia also does not show excessive pool use.

**Comment by mdoering** [comment]
@yroskov what exact browser do you use? Could you try (maybe on DEV!) if that also happens with a current version of Chrome?

**Comment by mdoering** [comment]
Seems browser differ considerably: https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser
IE11 apparently has 13. The requests were using http 2.0 which might also behave differently. @MortenHofft so you know more about this?

**Comment by yroskov** [comment]
I am using Firefox 87.0 (64-bit) with Win10.

**Comment by mdoering** [comment]
Thanks both. @MortenHofft I know the UI does not do any active throttling cause it is anticipated that the browser will queue them. And thats my question to you really, is this sth we can expect from http1 or http2 across all common browsers in use? Meging them all into a single batch request might be the best and clearly most efficient way forward though.

**Comment by MortenHofft** [comment]
Yes I believe it is to be expected from http2 that there is effectively no limit and should be throttled somewhere, in client or in an intermediate API layer. With http1 the browser queues the requests. E.g. 6 concurrent for for IE, 10 for chrome. Or so I believe it used to be. But those numbers could have changed.

**Comment by mdoering** [comment]
Creating a new decision takes some time as we need to update the ES index. All the time a connection is kept open, which quickly saturates the db pool. I will close the connection early before we update ES
