### ISSUE TITLE
Copy editors to new releases

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#997]
@yroskov and I discovered that he cannot see the release status in the imports queue because the release dataset is set to private and [editors are not getting copied over to the new release dataset](http://api.catalogueoflife.org/dataset/2296/editor). It's actually important that the editors can see the release status so that they know not to [break the release by using assembly while a release is running](https://github.com/CatalogueOfLife/backend/issues/996). Perhaps the editors are copied, but at a later stage? If so, it would be good to copy the editors right after the new dataset is created.

Probably the frontend should at least warn that there is a release running so that editors don't break the release by editing the draft catalogue while it is being copied. I'll open a frontend ticket on that issue.

**Comment by yroskov** [comment]
When @gdower started release, my list was empty (even after few refreshings) 

![image](https://user-images.githubusercontent.com/28574252/113613070-4a9a3880-9616-11eb-9b4b-0220884ea54e.png)

Later (10+ mins?), the process has appeared in the list on my side as well:

![image](https://user-images.githubusercontent.com/28574252/113613307-a6fd5800-9616-11eb-997a-5453f5b0400b.png)

**Comment by mdoering** [comment]
I think it would be best if the backend enforces no edits on a project while a release is running. But I agree anyone on a project should see the running release, the current situation is unexpected. Please see also https://github.com/CatalogueOfLife/backend/issues/983 where I wonder how we should deal with permissions for releases more generally.

**Comment by mdoering** [comment]
covered by the above 2 issues
